- internal/pkg/composable/controller.go
- internal/pkg/composable/providers/host/host_test.go
- internal/pkg/composable/testing/context.go
Despite [recent fixes](https://github.com/elastic/elastic-agent/pull/2787) of data races in `host/TextContextProvider` found by the go race detector, there were still underlying logical races in the test, causing it to be flaky. Specifically, the test expected that after notification of a change it could always request the current value to get the content of that change, when in fact (when CI is running slow enough) it was possible for the current value to change a second time while still handling the first notification.
This PR passes the changed value along with the notification callback, so the test can always observe the exact sequence. It also adds some comments and clarifies some code in `composable.controller`, since troubleshooting this problem involved working through some of …
> Fix flakiness in host/TestContextProvider

- docs/test-framework-dev-guide.md
- magefile.go
This PR always cleans the OGC cache folder when `mage integration:clean` is run.  The PR also adds a tip in the documentaion to run `mage integration:clean` if OGC-related errors are encountered when running other `mage integration:*` targets.
To help test authors try and get past any OGC-related errors due to stale contents in the OGC cache.
- Fixes #2794
> Make `mage integration clean` remove ogc cache

- magefile.go
Add's support for parsing `SNAPSHOT=true` from the environment when running all `mage integration:*` targets.
This allows use just `SNAPSHOT=true` and it will use the Elastic Agent version from the repository with `-SNAPSHOT` appended. Removes the requirement of defining the whole `AGENT_VERSION` environment variable.
- ~~[ ] I have added an integration …
> Allow SNAPSHOT=true for mage integration:*

- internal/pkg/agent/application/managed_mode.go
- internal/pkg/composable/controller.go
- pkg/component/runtime/manager_test.go
- pkg/component/runtime/service.go
A few places in the Agent code use `Timer.Reset` when the timer isn't known to have expired. The [go docs](https://pkg.go.dev/time#Timer.Reset) say:
If a program has already received a value from t.C, the timer is known to have expired
and the channel drained, so t.Reset can be used directly. If a program has not yet received
a value from t.C, however, the timer must be stopped and—if Stop reports that the timer
expired before being stopped—the channel explicitly drained:
```go
if !t.Stop() {
<-t.C
}
t.Reset(d)
```
This is usually a minor error but it causes races in the timer handling and in rare cases can even cause a panic. (Callers who habitually reset to a consistent interval like this might prefer `time.Ticker` which requires less boilerplate to reset safely.)
This PR fixes all the …
> Fix timer reset patterns in the Agent

- internal/pkg/agent/application/coordinator/coordinator.go
- pkg/component/runtime/command.go
- pkg/component/runtime/failed.go
- pkg/component/runtime/manager.go
- pkg/component/runtime/runtime.go
- pkg/component/runtime/service.go
This is code cleanup only, it does not change any behavior.
A few cleanups around the runtime and coordinator:
- ~~Break `(*Coordinator).compute()` into two pieces, `(*Coordinator).recomputeConfig` and `(*Coordinator).recomputeComponents`~~
* This one ended up breaking the diagnostics tests, because the Coordinator's component generation continues to modify the generated config, and the diagnostics expect the final modified version -- thus the config can't be fully generated without also regenerating the components. This is potentially undesirable behavior, but outside the scope of this PR, so I moved these back into a single function for now.
- Move the main monitoring loop for `componentRuntimeState` from an anonymous goroutine in the initialization into an explicit named helper …
> Runtime + Coordinator cleanups

- internal/pkg/agent/storage/store/action_store.go
- internal/pkg/agent/storage/store/state_store.go
When opening a state store or action store, if the store already exists but there's an error loading it, log the error instead of silently returning an empty store (but then return an empty store anyway, because there's nothing else we can do).
> Log an error when a store exists but we can't load it

- pkg/testing/tools/cmd.go
- pkg/testing/tools/tools.go
- testing/integration/fqdn_test.go
- testing/integration/upgrade_test.go
This PR follows up https://github.com/elastic/elastic-agent/pull/2833 by fixing a couple of [compile errors](https://github.com/elastic/elastic-agent/pull/2833#issuecomment-1584882967) introduced in that PR. 
It also renames a couple of utility functions provided by the testing framework to use `Agent` instead of `ElasticAgent`.
So integration/E2E tests can be run once again and to have consistency (and brevity) in naming.
> Fixing compile errors + more consistent naming

- internal/pkg/agent/application/managed_mode.go
- internal/pkg/composable/controller.go
- pkg/component/runtime/manager_test.go
- pkg/component/runtime/service.go
Following @aleksmaus discovery, I'm reverting elastic/elastic-agent#2818 to unblock the service runtime.
> Revert "[8.8](backport #2817) Fix timer reset patterns in the Agent"

- internal/pkg/agent/application/managed_mode.go
- internal/pkg/composable/controller.go
- pkg/component/runtime/manager_test.go
- pkg/component/runtime/service.go
Following @aleksmaus discovery, I'm reverting https://github.com/elastic/elastic-agent/pull/2817 to unblock the service runtime.
> Revert "Fix timer reset patterns in the Agent"

- Makefile
- magefile.go
- pkg/testing/tools/artifacts_api.go
- pkg/testing/tools/artifacts_api_test.go
- testing/fleetservertest/checkin.go
- testing/fleetservertest/fleetserver.go
- testing/fleetservertest/fleetserver_test.go
- testing/fleetservertest/handlers.go
- testing/fleetservertest/models.go
- testing/fleetservertest/server.go
Apparently we were not running the `mage check` command in CI. This ensures we have the appropriate license headers in all files, among other things.
> Run mage check in CI.

- changelog/fragments/1686770028-spec-timeout-units.yaml
- pkg/component/component_test.go
- specs/endpoint-security.spec.yml
This PR updates the Endpoint spec file to explicitly specify units for `inputs[].service.operations.*.timeout` values.
The `inputs[].service.operations.*.timeout` values are unmarshalled from YAML as [`time.Duration`](https://github.com/elastic/elastic-agent/blob/0c32b31933ba7898d1b753d1dda291372554869b/pkg/component/spec.go#L156).  By default, when no time unit is explicitly specified in these values, [`ms` is assumed](https://go.dev/play/p/U18P6hUQoKQ).  So, for example, `600` (no explicit time unit) will be parsed as `600ms` = `0.6s`.
Looking at https://github.com/elastic/beats/issues/19700, the intention with the timeout values in the Endpoint spec file was for their units to be in seconds.  
Run the `TestSpecDurationsAreValid` defined in this PR.  It should pass.
However, if you …
> [Component spec files] Add units to duration values

- changelog/fragments/1686845318-deployment-kubernetes-add-elements-for-Universal-Profiling.yaml
- changelog/fragments/1686845318-deployment-kubernetes:-add-elements-for-Universal-Profiling.yaml
- deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
- deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
- deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
- deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
Adding additional elements to the manifest so the Universal Profiling integration can be used.
Without these additional elements the Universal Profiling integration will not work.
> deployment/kubernetes: add elements for Universal Profiling

- internal/pkg/agent/cmd/uninstall.go
"can only be uninstall" -> "can only be uninstalled"
> Fix typo in uninstall location error message.

- NOTICE.txt
- go.mod
- go.sum
Continuation of https://github.com/elastic/elastic-agent-autodiscover/pull/51.
Update the  elastic-agent-autodiscover version to 0.6.2 in order to include the kubernetes node discover re-ordering.
> Bump elastic-agent-autodiscover version to 0.6.2

- changelog/fragments/1687251084-Fixed-diagnostics-logging-collection-on-k8s.yaml
- internal/pkg/diagnostics/diagnostics.go
This PR adds a support for unversioned path in diagnostics.
This is important because when running in k8s containers we are using state path so logs are not within a versioned directories. This has a side effect that resulting logs directory in a diagnostics package is empty
Discussed with @pierrehilbert that integration tests targeting k8s diagnostics will be part of future work.
Tested on:
- darwin/linux bare metal
- docker as a regular container 
- k8s deployment with custom state path
Fixes: #2899
> Add support for diagnostics logging collection on k8s

- testing/integration/upgrade_test.go
This PR isolates the `TestStandaloneUpgradeRetryDownload` E2E test.
This test is consistently failing when run along with other E2E/integration tests.  However, it passes when the test is run just by itself.  While we investigate what's going on, we can run this test in an isolated fashion, thus allowing all tests to be run and enabled for PR builds in CI.
> Isolate standalone upgrade retry test

- magefile.go
This PR randomizes the order in which a batch of tests from the same package are run.
It will help ensure that we (test authors) don't inadvertently introduce dependencies between tests.
> [Integration Testing Framework] Randomize test order

- pkg/testing/fetcher_artifact.go
- pkg/testing/fixture.go
- pkg/testing/tools/artifacts_api.go
- testing/integration/upgrade_test.go
This PR  introduces a way to read the hash of the agent version we are upgrading to from the `.build_hash.txt` of the actual artifact instead of relying on the hash provided by artifact API. This is temporary until the hash from artifact API becomes reliable again.
We want to avoid random failures of integration test `TestStandaloneUpgrade` due to artifact API reporting an incorrect hash
- ~~[ ] I have added an integration test …
> Agent hash workaround for upgrade to snapshot integration test

- magefile.go
- testing/integration/upgrade_test.go
This PR disables the timeout for executing the test binary used in integration/E2E tests.
Some integration/E2E tests can take a few minutes to run.  Moreover, the integration test runner will try to run such tests in a group (for all tests in the same package with `Isolate: false`).  As such, the total runtime of such a group of tests may exceed `go test`'s default timeout for the test binary, which is 10 minutes.
> [Integration Test Framework] Disable timeout for test binary execution

- magefile.go
- pkg/testing/runner/archiver.go
- pkg/testing/runner/config.go
- pkg/testing/runner/debian.go
- pkg/testing/runner/runner.go
Another set of small, minor fixes. There's a few things here:
- Change the behavior of archiver.go to make it more intuitive. Right now, it excludes any file outside of git, which excudes newly-created code files. This is a tad unintuitive, as yesterday I spent 40 minutes trying to figure out why none of the tests would build on a remote GCP instance. This still excludes files marked by `.gitignore` and others, so we're not trying to zip up random build artifacts, etc.
- Pass along verbose states to `testOnremote`
This improves logging and makes behavior more intuitive.
~- [ ] I have made corresponding changes to the documentation~
~- [ ] I have made corresponding change to the default configuration files~
> Integration tests: Pass along verbse statements in debian handler, tweak archiver

- specs/cloudbeat.spec.yml
As part of the CSPM for GCP epic, a new integration will trigger Cloudbeat to assess misconfiguration in the client's GCP account. This PR adds support for a new input type named `cloudbeat/cis_gcp`.
- https://github.com/elastic/cloudbeat/issues/769
> [Cloud Security] Support GCP CSPM integration

- docs/upgrades.md
This PR adds developer documentation illustrating the Fleet-managed Agent upgrade process, focussing on the communications amongst the various components involved.
For Agent and Fleet developers to understand how Agent upgrades work.
View the rich diff of the file.
> [Developer Documentation] Illustrate the Agent upgrade process

- changelog/fragments/1687301871-service-command-retries.yaml
- docs/component-specs.md
- pkg/component/runtime/service.go
- pkg/component/runtime/service_command.go
- pkg/component/runtime/service_command_test.go
- pkg/component/spec.go
This PR adds the ability for service operations to be retried.  Service components can optionally specify retries for their operations in their spec files like so:
```yml
version: 2
inputs:
- name: endpoint
service:
operations:
install:
retry:
init_interval: 60s
```
With the above spec definition, the `install` operation of the `endpoint` service will be retried indefinitely, with the duration between retries will start at 60 seconds and grow exponentially (with some random jitter). 
If `retry_sleep_init_duration` is omitted, it will default to **20 seconds**.
The duration between retries will grow exponentially (with some random jitter) but will be capped at approximately **15 minutes**.
In cases where a service operation may be flaky due to transient issues, it makes sense to retry the …
> [Service Runtime] Add ability for service operations to be retried

- testing/integration/upgrade_test.go
This PR updates the `TestStandaloneUpgradeRetryDownload` integration test to downgrade from the current (locally-built) Agent version to _two_ minor versions ago (instead of just _one_ minor version ago).
Every so often, we find ourselves in a situation where the current (local) [version](https://github.com/elastic/elastic-agent/blob/a3403e5ec52b80fccb05b5c165e4f6372702f9ee/version/version.go#L7) of Agent has been bumped up, e.g. `8.10.0` but the previous minor version, e.g. `8.9.0`, has not yet been released.  So, to be safe, the test should downgrade from the current (locally-built) version of Agent to two minor versions ago.
In case you're wondering why the test attempts a _downgrade_ instead of an upgrade, it's because it's a lot simpler to calculate past version numbers from the …
> Downgrade _two_ minors in integration test

- pkg/component/runtime/service_command_test.go
This PR adjusts timeouts in the `TestExecuteServiceCommand` test so it's not flaky on Windows in CI.
The test appears to be flaky on Windows in CI.  For example:
https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp/detail/main/1133/pipeline
I thought I had resolved the flakiness in the [PR that introduced the test](https://github.com/elastic/elastic-agent/pull/2889#issuecomment-1613868864) but apparently not so.  So this PR is another attempt at adjusting the timeouts for this test so it passes consistently on Windows in CI.
FWIW, I ran the test (after the changes in this PR) a 100 times locally on my Mac and it passed every time:
```
$ go test ./pkg/component/runtime/... -test.run TestExecuteServiceCommand/succeed_after_retry -test.count 100
ok …
```
> Adjust timeouts to remove flakiness from test

- internal/pkg/agent/application/upgrade/crash_checker.go
- internal/pkg/agent/application/upgrade/crash_checker_test.go
- internal/pkg/agent/application/upgrade/error_checker.go
- internal/pkg/agent/cmd/watch.go
- internal/pkg/agent/configuration/settings.go
- internal/pkg/agent/configuration/upgrade.go
- pkg/testing/fixture.go
- testing/integration/upgrade_test.go
This PR introduces a new `agent.upgrade` section in the Elastic Agent configuration file.  Initially, this section can be used to override the Upgrade Watcher's settings like so:
```yml
agent.upgrade:
watcher:
grace_period: 1m
error_check:
interval: 15s
crash_check:
interval: 15s
```
The default values of these settings are the same as they were before the changes in this PR.
This PR also introduces a new method on the `testing.Fixture` struct: 
```go
// Configure replaces the default Agent configuration file with the provided
// configuration. This must be called after `Prepare` is called but before `Run`
// or `Install` can be called.
func (f *Fixture) Configure(ctx context.Context, yamlConfig []byte) error {
```
This new method will allow tests to replace the default contents of the …
> Make upgrade watcher configurable

- testing/integration/upgrade_test.go
This PR disables the Upgrade Watcher check at the end of the `TestFleetManagedUpgrade` E2E test.
It will allow the `TestFleetManagedUpgrade` to pass again.  See #2977 for more context.
```
$ SNAPSHOT=true mage integration:single TestFleetManagedUpgrade
>>> Bring down instances through ogc
>>> Pulling latest ogc image
>>> Create SSH keys to use for SSH
>>> Creating zip archive of repo to send to remote hosts
>>> Creating ESS cloud 8.10.0-SNAPSHOT (at-shaunak-agent-testing-8100-SNAPSHOT)
>>> Import layouts into ogc
>>> Bring up instances through ogc
>>> (linux/amd64/ubuntu/22.04[4cht]) Starting SSH connection to 34.27.232.215
>>> (linux/arm64/ubuntu/22.04[4cht]) Starting SSH connection to 34.123.16.214
>>> (linux/arm64/ubuntu/22.04[4cht]) Connected over SSH
>>> …
```
> [Workaround] Disable upgrade watcher check in `TestFleetManagedUpgrade`

- internal/pkg/agent/application/upgrade/step_download.go
- internal/pkg/agent/application/upgrade/step_download_test.go
This PRs adds a fallback to a downloader. When downloadArtifact is called, it appends a fallback key into a passed keys collection.
This key is used as a last resort for signature verification of downloaded packages and is useful when embedded key is no longer used. 
This option is used regardless of mode in which ugprade was triggered let it be standalone CLI trigger or managed action. 
Option to support older agents when keys are rotated.
- temper embedded key
- build agent locally
- install built agent (managed)
- try to upgrade 
- should pass (first verification with embedded key fails, fallback should be fine)
> Added verification fallback to https://artifacts.elastic.co/GPG-KEY-elastic-agent

- internal/pkg/agent/cmd/container.go
- internal/pkg/agent/cmd/setup_config.go
As setup is now called in kibana we don't need to call it at all. 
PR removes these calls and ENV variable altering behavior.
Tested:
- enroll modified agent to normal fleet
- enroll modified agent on k8s to normal fleet
- enroll modified agent to cloud instance running modified agent (using cloud first testing)
All working
Fixes: #2910
> Removed call to fleet setup during container start

- pkg/testing/define/define.go
- testing/integration/diagnostics_test.go
- testing/integration/enroll_test.go
- testing/integration/fake_test.go
- testing/integration/fqdn_test.go
- testing/integration/install_test.go
- testing/integration/upgrade_test.go
Adds a version parameter to `define.NewFixture` which will be passed to `github.com/elastic/elastic-agent/pkg/testing.NewFixture` instead of the current local version.
`define.NewFixture` is a wrapper/sugar syntax for `github.com/elastic/elastic-agent/pkg/testing.NewFixture` but as it does not takes in the version, its usage is rather limited. Besides having two similar methods with such a difference is confusing.
- ~~[ ] I have added tests that prove my fix is effective or that my feature works
Just run the …
> Add a version parameter to define.NewFixture

- pkg/testing/fetcher_local.go
- pkg/testing/fetcher_local_test.go
Enhance local fetcher to accept versions with SNAPSHOT suffix and avoid potentially having it trying to fetch a `-SNAPSHOT-SNAPSHOT` version.
It also changes the tests to a table test
Enhance local fetcher to accept versions with SNAPSHOT suffix and avoid potentially having it trying to fetch a `-SNAPSHOT-SNAPSHOT` version
- Run all the integration tests, they should keep passing …
> Enhance local fetcher to accept versions with SNAPSHOT suffix

- .buildkite/scripts/integration_tests.sh
Follow up from https://github.com/elastic/elastic-agent/pull/2998, enable integration test timestamps when they are run from buildkite.
> Enable timestamps in buildkite integration tests.

- changelog/fragments/1688657261-Don't-trigger-IOC-alert-on-Windows-uninstall.yaml
- internal/pkg/agent/install/uninstall.go
- internal/pkg/agent/install/uninstall_unix.go
- internal/pkg/agent/install/uninstall_windows.go
- internal/pkg/agent/install/uninstall_windows_test.go
Previously the Elastic Agent would spawn a `cmd.exe` that would wait 2 seconds and then delete the `C:\Program Files\Elastic\Agent` directory. This triggers a Cloud IOC alert as that is something that nefarious applications do.
This provides a better way of uninstalling of Elastic Agent on Windows, by using the Windows API to allow removal of a directory even if there is an executable running inside of it.
Two reasons this is important. Uninstall no longer has a 2 second delay for it to be fully removed, something that caused a problem with integration testing on Windows, and a Cloud IOC alert will no longer trigger when Elastic Agent is uninstalled.
- ~~[ ] I have made corresponding change to the default configuration …
> Improve uninstall on Windows to remove directory even when uninstall is being executed from same directory

- testing/integration/upgrade_test.go
This PR removes the `FleetManagedUpgradeTestSuite`,  `StandaloneUpgradeTestSuite`, and `StandaloneUpgradeRetryDownloadTestSuite` test suite structs that are used by the `TestFleetManagedUpgrade`,  `TestStandaloneUpgrade`, and `TestStandaloneUpgradeRetryDownload` functions, respectively.
The `FleetManagedUpgradeTestSuite`,  `StandaloneUpgradeTestSuite`, and `StandaloneUpgradeRetryDownloadTestSuite` test suites only contains a single test method each.  As such, the contents of these test method could simply be inlined into the `TestFleetManagedUpgrade`,  `TestStandaloneUpgrade`, and `TestStandaloneUpgradeRetryDownload` functions, respectively, thereby removing unnecessary complexity of the test suites. 
As an additional benefit, this change will also reduce double counting in test reports …
> Upgrade integration tests: Remove test suite wrappers

- testing/integration/fake_test.go
This PR removes the `FakeComponentIntegrationTestSuite` test suite struct that's used by the `TestFakeComponent` function.
The `FakeComponentIntegrationTestSuite` test suite only contains a single test method.  As such, the contents of this test method could simply be inlined into the `TestFakeComponent` function itself, thereby removing unnecessary complexity of the test suite. 
As an additional benefit, this change will also reduce double counting in test reports ([example](https://buildkiteartifacts.com/e0f3970e-3a75-4621-919f-e6c773e2bb12/0187faac-2a90-4642-bc78-c33cefa167ba/01892a41-e00e-49f9-8c6f-66f133491e86/01892a42-99f5-4d7d-9d50-ce150671e842/build/TEST-report.html?response-content-type=text%2Fhtml&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAQPCP3C7L5WM5OD4T%2F20230706%2 …
> `TestFakeComponent`: Remove test suite struct

- pkg/testing/runner/runner.go
This PR fixes the log message about SSH'ing into the hosts used by the integration test framework for running tests. Specifically, this PR:
* makes the path to the SSH private key (used in the log message) portable across OSes,
* makes the path to the SSH private key absolute so it doesn't matter where the SSH command is executed from, and
* fixes the order of the username and hostname
So the SSH command emitted in the log message works.
Run any integration test and notice the messages about SSH'ing into the hosts used by the integration test framework.  Copy the SSH command mentioned in the log message, paste it into a new window, and try to execute it.
```
$ mage integration:single TestFQDN
...
>>> Bring up instances through ogc
>>> (linux/amd64/ubuntu/22.04[7slm]) Starting SSH; connect …
```
> Integration Test Framework: Fix SSH connection log message

- testing/integration/diagnostics_test.go
This PR removes the `DiagnosticsIntegrationTestSuite` test suite struct that's used by the `TestDiagnosticsCommand` function.
The `DiagnosticsIntegrationTestSuite` test suite only contains a single test method.  As such, the contents of this test method could simply be inlined into the `TestDiagnosticsCommand` function itself, thereby removing unnecessary complexity of the test suite. 
As an additional benefit, this change will also reduce double counting in test reports ([example](https://buildkiteartifacts.com/e0f3970e-3a75-4621-919f-e6c773e2bb12/0187faac-2a90-4642-bc78-c33cefa167ba/01892a41-e00e-49f9-8c6f-66f133491e86/01892a42-99f5-4d7d-9d50-ce150671e842/build/TEST-report.html?response-content-type=text%2Fhtml&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAQPCP3C7L5WM5OD4T%2F2023 …
> `TestDiagnosticsCommand`: Remove test suite struct

- testing/integration/fqdn_test.go
This PR increases the timeout of the check that looks for the expected hostname in `logs-*` and `metrics-*` indices from 1 minute to 2 minutes.
This test seems to _occasionally_ fail in CI ([example](https://buildkite.com/elastic/elastic-agent/builds/1482#01892a42-99f5-4d7d-9d50-ce150671e842)), however it doesn't seem to fail when run locally, even with a dozen+ attempts.
> `TestFQDN`: Increase timeout for data check to 2 minutes

- dev-tools/mage/gotest.go
- dev-tools/mage/gotest_test.go
- magefile.go
Follow up from https://github.com/elastic/elastic-agent/pull/3052
A previous PR re-used the `TestName` parameter as the argument to the `-run` arg of `go test`. The problem is that the original code intended this to only be use for logging purposes, see the comment in:
https://github.com/elastic/elastic-agent/blob/d20b1085a3c8ba92ff3f7401e363b34f21d97f3e/dev-tools/mage/gotest.go#L31
The `mage unitTest` target used by sonarcloud and CI is implemented by:
https://github.com/elastic/elastic-agent/blob/d20b1085a3c8ba92ff3f7401e363b34f21d97f3e/magefile.go#L330-L335
The default Go test args unconditionally set the test name to `Unit`:
https://github.com/elastic/elastic-agent/blob/d20b1085a3c8ba92ff3f7401e363b34f21d97f3e/dev-tools/mage/gotest.go#L90
The `makeGoTestArgs` function called here …
> Fix mage unitTest to actually run tests

- testing/integration/fqdn_test.go
This PR disables a flaky assertion in the `TestFQDN` integration test.
So Ci is not flaky.
Related to https://github.com/elastic/elastic-agent/issues/3078
> [Integration Test][`TestFQDN`] Disable flaky assertion

- pkg/testing/runner/archiver.go
Figured out with @blakerouse the race condition while reading the output of `git ls-files`
Relates: https://github.com/elastic/elastic-agent/issues/3068
> Integration tests: fixed couldn't stat file error

- changelog/fragments/1689328899-Elastic-Agent-container-runs-on-Azure-Container-Instances-.yaml
- dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
This changes owner of agent directories. Tested locally and on azure container instances, seems to work. 
Containers running on Azure Container Instances refuse to read config.
- build docker image
- push to observability-ci container repo
- create Azure (portal.azure.com login using SSO) Container Instance using published repo (you need to specify Other-Private docker registry with login and pass capture from docker-auth.elastic.co)
- see it runs
Closes: https://github.com/elastic/elastic-agent/issues/82
> Agent owns its directories

- docs/test-framework-dev-guide.md
- testing/integration/fqdn_test.go
This PR tries to fix the flaky `TestFQDN` end-to-end test. It also adds documentation on using test namespaces to avoid flaky tests.
So we don't have flaky tests.
> Fix flaky `TestFQDN`

- testing/integration/enroll_test.go
This PR skips the flaky `TestEnrollAndLog` E2E test.
To avoid flaky tests.
-  Related to https://github.com/elastic/elastic-agent/issues/3081
> Skip flaky `TestEnrollAndLog` E2E test

- version/version.go
Updates references to the new release 8.9.1.
Merge after the release 8.9.0.
> [Release] Update version to 8.9.1

- changelog/fragments/1689622778-upgrade-watcher-fix-error-message.yaml
- internal/pkg/agent/cmd/watch.go
This PR fixes a couple of error messages in the Upgrade Watcher.
The error messages were misleading, which makes it confusing when troubleshooting.
> [Upgrade Watcher] Fix error messages

- .ci/bump-golang.yml
- .github/workflows/govulncheck.yml
- Closes https://github.com/elastic/ingest-dev/issues/2258
Enable running govulncheck in PRs to pre-emptively detect security issues.
> Enable running govulncheck in PRs

- dev-tools/mage/gotest.go
- docs/test-framework-dev-guide.md
- magefile.go
- pkg/testing/define/batch.go
- pkg/testing/define/batch_test.go
- pkg/testing/runner/config.go
- pkg/testing/runner/runner.go
It allows to propagate go test flags to the actual go test command allowing for finer control over the test execution.
The `-test.short` is also important for allowing a quicker execution for PRs, for example while maintaining a full integration test run in other contexts.
Try to run integration tests (both locally and remotely) with some custom go test flags. There are some examples listed in the …
> Pass go test flags to integration tests

- changelog/fragments/1689883203-Elastic-Defend-runtime-prevention.yaml
- internal/pkg/agent/application/paths/common.go
- internal/pkg/agent/cmd/install.go
- internal/pkg/agent/cmd/install_test.go
- internal/pkg/agent/cmd/install_windows_test.go
- pkg/component/component.go
- pkg/component/component_test.go
- pkg/testing/tools/cmd.go
- pkg/testing/tools/tools.go
- specs/endpoint-security.spec.yml
- testing/integration/endpoint_security_test.go
- testing/integration/enroll_test.go
- testing/integration/fqdn_test.go
- testing/integration/upgrade_test.go
- adds runtime prevention that prevents Elastic Defend from running if Agent is not installed in the default location
- Shows all prevention messages
- Integration test that installs agent in a non default location and tries to add Elastic Defend to the policy
Elastic Defend require the default installation path.
``` bash
mage integration:single  TestEndpointSecurityNonDefaultBasePath
```
1. Install stack
2. Create policy without Elastic Defend
3. Install Agent, use `--base-path=<not the default>` during install
4. Check Agent is healthy in Fleet and CLI
5. Add Elastic Defend to the policy
6. Check that Agent is Degraded with 1 or more components/units in a failed state
7. Check logs and `elastic-agent status` output to make sure "Elastic Defend requires Elastic Agent be installed at the …
> Elastic Defend install path runtime prevention

- internal/pkg/agent/application/dispatcher/dispatcher_test.go
Disable TestActionDispatcher/Cancel_queued_action
The test is flaky and blocking PRs
N/A
N/A
- Relates #3137
- ...
> Disable flaky assertion on  TestActionDispatcher/Cancel_queued_action

- .buildkite/scripts/common.sh
Fixes the buildkit job to fail when `mage` or `go` functions actual fail.
Without this change CI integration failures will not mark the tests as failed.
- Closes #3148
> Fix mage and go buildkit script exit codes

- testing/integration/upgrade_test.go
This will fix the build on main and avoid wasting time while we investigate the root cause.
See https://github.com/elastic/elastic-agent/issues/3155
This test fails often enough for me that we just need to disable it while we investigate.
> Skip flaky retry upgrade test.

- pkg/component/runtime/manager.go
- pkg/component/runtime/manager_test.go
The runtime manager uses a mysterious lookup table, `waitReady`, that is injected into the TLS authentication callbacks to allow a special list of unregistered components to connect. However this turns out to only ever be used by the unit tests for a single connection, which itself is only used to probe whether the RPC server is listening yet. This can be done more simply by just setting an atomic flag when the server loop starts, so this PR does that and removes the extra synchronization baggage.
Has no functional effect except when using the unit test helper `waitForReady`, and should effectively still be a no-op there (just with fewer redundant network connections).
> Clean up runtime manager test initialization

- testing/integration/proxy_url_test.go
All of the proxy tests are currently flaky and fail regularly, see https://github.com/elastic/elastic-agent/issues/3154
Disabling them while we investigate a fix to unblock CI.
> Disable proxy tests while flakiness is addressed.

- pkg/testing/fixture.go
- pkg/testing/tools/cmd.go
- testing/integration/upgrade_test.go
This PR adds upgrade tests for both standalone and managed agent from some versions of the current and previous major release to the latest snapshot.
The tests will select:
- up to 2 versions with the same major version as the current agent
- up to 1 version from a previous major version
These versions are retrieved using the Artifact API and working backwards through the versions, excluding snapshots.
The _up to_ part is because under certain circumstances (new major release, for example) we may not find enough versions fitting the criteria.
The tests `TestStandaloneUpgrade` and `TestFleetManagedUpgrade` will start a subtest (using `t.Run()`) for each version to be used as a starting point for the upgrade and then upgrade it to the latest version of agent.
Current limitations:
- We are …
> Introduce upgrade tests from released versions

- internal/pkg/agent/application/upgrade/crash_checker.go
- internal/pkg/agent/application/upgrade/install_checker.go
- internal/pkg/agent/cmd/watch.go
- internal/pkg/agent/configuration/upgrade.go
Adds a new `InstallChecker` that watches that the Elastic Agent remains installed why the watcher is running. In the case that the Elastic Agent gets uninstalled the watcher will stop.
If an Elastic Agent is upgraded and then uninstalled during the grace period the watcher will remain running. This change ensures that it stops.
Without this change it is not possible to uninstall the Elastic Agent on Windows after an upgrade has been performed. …
> Add new install checker that stops the watcher when Elastic Agent is uninstalled

- testing/integration/upgrade_test.go
This PR filters out versions that too new from agent upgrade integration tests, allowing backport of those test on release branches.
This PR needs to backported together with #2955 onto 8.9 branch
We want to have working upgrade tests with relevant versions also on release branches
- Relates #2955  …
> Skip versions newer than version under test for upgrade tests

- internal/pkg/agent/application/upgrade/artifact/download/http/verifier.go
Fixes a confusing typo about verification failures.
It should be clear when an artifact verification fails.
- Related https://github.com/elastic/ingest-dev/issues/2264
> Fix typo in artifact verification error log

- changelog/fragments/1690896259-synthetics-default-timezone.yaml
- dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Fixes https://github.com/elastic/beats/issues/36117 on the agent. Add default TZ value to fix synthetic journeys for timezone-triggered errors.
Unspecified timezone values can cause navigation errors on synthetics journeys.
1. Build agent docker image locally.
2. Create a journey that navigates to a Kibana URL and enroll agent on the private location policy.
3. Wait for Kibana login page to load properly.
> [heartbeat] Add default timezone to complete image

- docs/test-framework-dev-guide.md
- magefile.go
- pkg/testing/runner/config.go
- pkg/testing/runner/config_test.go
- pkg/testing/runner/runner.go
- pkg/testing/runner/supported.go
- pkg/testing/runner/supported_test.go
Adds a new environment variable that will adjust the integration test runner to only run tests on the platforms defined in the `TEST_PLATFORM` variable. This is done in a way that allows the runner to use the platforms selected to adjust non-specific tests. Meaning if a test is not specific to the Ubuntu version and the caller has `TEST_PLATFORM=linux/amd64/ubuntu/20.04` it will use Ubuntu 20.04 instead of the default 22.04.
Note: I tried to make it use the `PLATFORM` variable so it could share the same variable as packaging. This does not work because the dev-tools/ parses that environment variable in a `init()` function.
When debugging integration tests is nice to be able to select only a specific instance to run it on without having to modify the test. Before it required the test …
> Add ability to filter runner by TEST_PLATFORM

- docs/upgrades.md
This PR enhances the sequence diagram in https://github.com/elastic/elastic-agent/blob/main/docs/upgrades.md to include more details about the interplay between the Upgrade Watcher, the upgrade marker file, and the Agents (old or new).
To understand exactly the steps taken by the Upgrade Watcher during an ongoing upgrade, either to decide that the new (post-upgrade) Agent is running OK or that it needs to be rolled back to the old (pre-upgrade) Agent.
> [Developer Documentation] Add details of Upgrade Watcher interactions with Agent and upgrade marker file

- testing/integration/fqdn_test.go
Disable the flaky FQDN integration test
CI needs to be green
- ~~[x] I have commented my code, particularly in hard-to-understand areas~~
- Relates #3154 
- ...
> [Flaky test] skip FQDN integration test

- catalog-info.yaml
Since buildkite pipelines were not backported to 8.9, the scheduled DRA job for 8.9 branch is continuously failing. This removes it.
> Remove 8.9 schedule for DRA artifacts

- internal/pkg/agent/application/coordinator/coordinator.go
This fixes a mistake in some log messages that used `%q` for formatting (in `fmt` helpers like `Sprintf` this indicates a quoted value, but this is not supported by our logging helpers).
> Fix Coordinator log formatting strings

- internal/pkg/agent/application/paths/common.go
Fixes the path that should be used to spawn the watcher. Before I believes that the symlink was under the `elastic-agent.app/Contents/MacOS` path, and I did not test the upgrade on macOS. I only tested this change on Linux with the integration testing suite.
Without this its not possible to upgrade Elastic Agent to any other version.
- ~~[ ] I have added an integration test or an E2E test~~ (Sadly we don't support macOS in the …
> Fix spawning upgrade watcher on darwin platform

- changelog/fragments/1691694963-Stop-translating-the-Upgrading-agent-state-to-Degraded.yaml
- internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
- internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
Degraded is interpreted by users as the agent being in an error state. We should not report degraded for situations where the agent is working as expected.
Long term we should probably just send these states directly to Fleet rather than translating them into a less fine grained set of states.
- Closes https://github.com/elastic/elastic-agent/issues/2273
> Fix mapping the upgrading state to degraded.

- internal/pkg/agent/install/uninstall.go
- internal/pkg/agent/install/uninstall_windows_test.go
increases internal/pkg/agent/install.RemovePath arbitraty timeout.
On non-CI machine 2s is enough, as it keeps failing on CI, let's increase it.
run the test, it should be skipped
- Closes #3221 
- …
> increase internal/pkg/agent/install.RemovePath arbitrary timeout

- .buildkite/pipeline.yml
Change the machine type for the unit test integration pipeline. It was reported that the pipeline was failing with exit 255 which is indicative of OOM event.
> Change BK machine type in integration pipeline

- pkg/testing/tools/artifacts_api.go
- testing/integration/upgrade_test.go
Commit message:
>**Tile:** 
skip downgrade test when only one snapshot version is available (#3293)
**Message:**
TestStandaloneUpgradeToSpecificSnapshotBuild actually test a downgrade to a previous SNAPSHOT. This fix renames it to TestStandaloneDowngradeToPreviousSnapshotBuild. It also skips the test if there is only one SNAPSHOT available as, in that case, there is no 'previous' SNAPSHOT to downgrade to.
It fixes TestStandaloneUpgradeToSpecificSnapshotBuild to work is there is only one snapshot build available.
When there is only one snapshot version for the current version the test fails.
- ~~[ ] I have made corresponding change to the default …
> skip downgrade test when only one snapshot version is available

- .github/CODEOWNERS
Add cloud-native group as codeowner for the k8s provider.
Related to https://github.com/elastic/elastic-agent/pull/3107#issuecomment-1686568690.
> Add cnative team as codeowner for k8s provider

- changelog/fragments/1692141038-upgrade-watcher-logging.yaml
- internal/pkg/agent/application/upgrade/rollback.go
- internal/pkg/agent/cmd/run.go
- internal/pkg/agent/cmd/watch.go
- version/version.go
This PR adds logging to the restart step of the Agent upgrade rollback process.
To better understand the progress of the upgrade rollback process.
1. Build an install Agent from `main` (currently at version `8.11.0`).
```
EXTERNAL=true SNAPSHOT=true  DEV=true PLATFORMS=linux/arm64 PACKAGES=tar.gz mage package
```
3. Build Agent package from this PR (currently at version `8.12.0`).  Make sure NOT to use `SNAPSHOT=true` or `EXTERNAL=true`.
```
DEV=true PLATFORMS=linux/arm64 PACKAGES=tar.gz mage package
```
4. Upgrade the installed `8.11.0` Agent to the `8.12.0` Agent built with this PR.
```
sudo elastic-agent upgrade 8.12.0 --source-uri file://$(pwd)/build/distributions/ --skip-verify
```
6. Tail the Upgrade Watcher logs and ensure that the log messages in this PR show up.
```
tail -F …
```
> [Upgrade Watcher] Add logging to rollback restart step

- .buildkite/hooks/pre-command
- .buildkite/hooks/pre-exit
- .buildkite/misc/gce-cleanup.yml
- .buildkite/pipeline.elastic-agent-gce-cleanup.yml
- .buildkite/scripts/steps/gce-cleanup.sh
- .buildkite/scripts/unset-secrets.sh
- catalog-info.yaml
- Enhancement
Daily buildkite job that cleans up stale GCE instances left after integration tests
Removes stale GCE instances having matching labels, name prefixes and older than 24 hours
Integration tests are being interrupted without a proper cleanup when we add new commits to pull requests.
It's a temporary solution. Normally we should make the CI system manage build agents.
> Daily BK job deleting stale GCE instances

- internal/pkg/agent/application/upgrade/upgrade.go
- testing/integration/upgrade_test.go
**Commit title:** skip test while snapshot downloader cannot handle downgrades
**Commit message:** The snapshot downloader cannot handle downgrades what brakes this test between releases. An issue to fix the snapshot dowloader is filed: https://github.com/elastic/elastic-agent/issues/3313
Rename `TestStandaloneUpgradeWithGPGFallback` to `TestStandaloneDowngradeWithGPGFallback` and skip it
The snapshot downloader cannot handle downgrades what brakes this test between releases.
- ~~[ ] I …
>  Skip test while snapshot downloader cannot handle downgrades

- pkg/testing/tools/check/check.go
- testing/integration/monitoring_logs_test.go
- testing/integration/proxy_url_test.go
Fix flakiness on enrollment integration test and rename it so it better reflects what is tested by it.
I continually run the test for 20h and it did not fail.
The test was flaky and the name was misleading. It could lead one to believe the test was just the enrollement, when it actually tests the enrollment and the monitoring is shipping logs.
- ~~[ ] I …
> Fix flakiness on enrollment integration test and rename it

- changelog/fragments/1693319952-Change-error-handling-o-Windows-when-uninstalling-the-Elastic-Agent.yaml
- internal/pkg/agent/install/uninstall.go
- internal/pkg/agent/install/uninstall_unix.go
- internal/pkg/agent/install/uninstall_windows.go
Properly check if and error matches a windows/syscall error
RemovePath is failing as it considers the error not retriable when it actually is.
- Closes #3316 
- What …
> Properly check if and error matches a windows/syscall error

- docs/component-specs.md
- internal/pkg/agent/install/install_windows.go
- internal/pkg/agent/install/installed.go
- internal/pkg/agent/install/pkgmgr/pkgmgr_unix.go
- internal/pkg/agent/install/pkgmgr/pkgmgr_windows.go
- pkg/component/component.go
changes how the `install.in_default` runtime protection variable is calculated on systems where elastic-agent is installed via deb or rpm package.  Previously this would have returned false be cause the install path is not the same as the `tar.gz` install.  However, endpoint knows how to operate when elastic-agent is installed as a deb or rpm, so now it will return true.
This is required because the runtime prevention was blocking the install of endpoint on systems installed via deb/rpm.
example:
```
sudo elastic-agent status
┌─ fleet
│  └─ status: (HEALTHY) Connected
└─ elastic-agent
├─ status: (DEGRADED) 1 or more components/units in a failed state
└─ endpoint-default
├─ status: (FAILED) Elastic Defend requires Elastic Agent be installed at the default installation path
├─ …
```
> modify runtime variable 'install.in_default' with rpm/deb

- dev-tools/packaging/packages.yml
- version/helper.go
Move elastic package version file outside of `elastic-agent.app` directory to fix the package signing for Mac
- Closes #3285 
- What are the metrics I should take care …
> move the package version file outside of app directory for MacOS

- changelog/fragments/1693544911-Diagnostics-command-creates-necessary-folders-for--f-flag.yaml
- internal/pkg/agent/cmd/diagnostics.go
- internal/pkg/agent/cmd/diagnostics_test.go
- internal/pkg/agent/cmd/logs_test.go
Fixes how the diagnostics command handles the custom path to save the diagnostics. Right now if the custom file path to save the diagnostics on contains folders that do not exist, the diagnostics fail to create the file, consequently failing to save the diagnostics.
It not clear on the diagnostics help the path to the file must exist, it'd be much easier for our users if the diagnostics is capable of creating the necessary folders. …
> Diagnostics creates the necessary folder for -f argument

- pkg/testing/tools/testcontext/testcontext.go
- pkg/testing/tools/tools.go
- testing/integration/endpoint_security_test.go
- testing/integration/install_test.go
- testing/integration/upgrade_test.go
- remove missing verb on printf-like call
- remove folder as it might be left over from another test
Fixes a possible cause of flakiness on tests and the missing verb on a printf-like call.
To avoid test flakiness
- N/A …
> Small improvements on integration tests

- dev-tools/mage/crossbuild.go
This PR fixes the path separators in the `crossBuild` target, so if this target is invoked on a Windows host, it creates the correct build command to be run inside a Linux-based Docker container.
So we can build Elastic Agent on Windows hosts.
Without this PR, e.g. from `main`, we get the following error while building an Elastic Agent package on a Windows host:
```
$ EXTERNAL=true SNAPSHOT=true DEV=true PLATFORMS=windows/amd64 mage package 
...
sh: 1: buildmage-linux-amd64: not found
...
```
> [crossbuild] Fix path separators

- sonar-project.properties
Exclude fake components used in elastic-agent tests from sonarqube analysis
To avoid false positives in sonarqube quality gate results
- 
- …
> exclude fake components from sonar analysis

- pkg/testing/define/batch.go
- pkg/testing/define/batch_test.go
- pkg/testing/ogc/provisioner.go
- pkg/testing/runner/debian.go
- pkg/testing/runner/runner.go
When running `mage integration:single TestFakeComponent` the integration testing runner would create a stack even though the test did not require a stack. 
This is because the `pkg/testing/define` merged batches of tests that didn't require a stack and those that didn't as they can be ran in the same batch. This is fine until then only a single test is selected out of that batch and the test doesn't need a stack.
Makes it faster to run the integration tests for a single test in the case that it doesn't need a stack.
- ~~[ ] I have added an entry in …
> Don't create a stack on a single run that doesn't require a stack

- NOTICE.txt
- changelog/fragments/1693427183-install-progress.yaml
- go.mod
- internal/pkg/agent/cmd/install.go
- internal/pkg/agent/install/install.go
- internal/pkg/agent/install/progress.go
- internal/pkg/agent/install/progress_test.go
This PR enhances `elastic-agent install` to show users the progress of the installation.
https://github.com/elastic/elastic-agent/assets/51061/6f47764d-971f-4222-be20-c3bf8f3325ca
https://github.com/elastic/elastic-agent/assets/51061/8eb08be5-d664-4d7e-b1fd-2857af5c6151
So users know installation is proceeding and not stalled.
> Show installation progress

- docs/test-framework-dev-guide.md
- pkg/testing/fixture_install.go
Ignore AGENT_KEEP_INSTALLED if test succeeds
If the agent is kept installed after a successful test, other tests installing the agent might fail.
Ignore AGENT_KEEP_INSTALLED if test succeeds
If the agent is kept installed after a successful test, other tests installing the agent might fail.
- N/A …
> Ignore AGENT_KEEP_INSTALLED if test succeeds

- testing/integration/upgrade_test.go
This is a work around while we implement a fix for https://github.com/elastic/elastic-agent/issues/3371.
If the watcher is still running at the end of a test, it will observe the normal uninstall+reinstall as a crash and roll back the agent at the start of the next generally causing chaos and failing tests.
> Fix integration tests by waiting for the watcher to finish during upgrade tests

- pkg/testing/fixture_install.go
- testing/integration/upgrade_test.go
This PR adds an integration test that ensures that an unhealthy Agent is rolled back.
To ensure upgrade rollbacks work as expected.
Check out this PR's branch and then:
```
DEV=true PLATFORMS=linux/arm64,linux/amd64 PACKAGES=tar.gz mage package
mage integration:single TestStandaloneUpgradeFailsStatus
```
- Relates https://github.com/elastic/elastic-agent/issues/2176
> Adding upgrade test for unhealthy upgraded Agent

- pkg/testing/fixture_install.go
Avoid the Fixture.Install method logging _ignoring AGENT_KEEP_INSTALLED=true as test succeeded, keeping the agent installed will jeperdise other tests_ when AGENT_KEEP_INSTALLED isn't set. It also fixes the typo.
- How are we going to measure its …
> Fix when fixture.Install logs  'ignoring AGENT_KEEP_INSTALLED...'

- NOTICE.txt
- changelog/fragments/1693813219-log-command-colors.yaml
- go.mod
- internal/pkg/agent/cmd/logs.go
- internal/pkg/agent/cmd/logs_test.go
`elastic-agent logs` command now has colors. To disable colors use the `--no-colors` flag.
Also, fixed a few bugs in printing logs related to buffering.
Easier to follow the logs.
Run the stack snapshot using:
```sh
elastic-package stack up --version=8.11.0-SNAPSHOT -v
```
Build the agent:
```sh
DEV=true SNAPSHOT=true PLATFORMS=darwin/arm64 mage package
```
Enroll the built agent into the stack's Fleet:
Note: you need to put your platform in the environment variable.
```sh
cd build/distributions
tar xvfz elastic-agent-8.11.0-SNAPSHOT-*.tar.gz
cd elastic-agent-8.11.0-SNAPSHOT-*
sudo ./elastic-agent install -i --url=https://localhost:8220 …
```
> Add colors for log messages based on their level

- internal/pkg/agent/application/coordinator/coordinator.go
- pkg/core/logger/logger.go
Improves the coordinator logging correctness.
Before this change the logger reported lines for each use of the ```logBasedOnState``` wrapper function as the lines within that function, where one would expect the line where the logging was called.
```
{"log.level":"info","@timestamp":"2023-08-22T21:34:18.707-0400","log.origin":{"file.name":"coordinator/coordinator.go","file.line":1249},"message":"Unit state changed system/metrics-default-system/metrics-system-58826646-b1bc-45c9-a0dc-1d5e1ccb2414 (STARTING->HEALTHY): Healthy","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"HEALTHY"},"unit":{"id":"system/metrics-default-system/metrics-system-58826646-b1bc-45c9-a0dc-1d5e1ccb2414","type":"input","state":"HEALTHY","old_state":"STARTING"},"ecs.version":"1.6.0" …
```
> Improve the coordinator logging correctness

- changelog/fragments/1693920861-netinfo-manifests.yaml
- deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
- deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
- deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
- deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml
- deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
- deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml
- deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
- deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
- deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
- deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
- Enhancement
This PR add the the NETINFO variable in the kubernetes manifests
```yaml
```
- Relates to https://github.com/elastic/beats/pull/36506
```bash
cd elastic-agent
cd deploy/kubernetes
GENERATEKUSTOMIZE=true make ci-create-kustomize
make generate-k8s
```
- Relates #https://github.com/elastic/beats/pull/36506
- Relates #https://github.com/elastic/integrations/issues/6674
> Updating Elastic Manifests with NETINFO variable

- magefile.go
- pkg/testing/ess/deployment.go
This PR updates the Integration Test Framework code to allow the creation of test stack deployments in the Azure region (`azure-eastus2`) instead of the GCP region (`gcp-us-central1`) in the ESS QA environment. 
Deployments in the GCP QA region appear to be taking indefinitely long to create today.  Meanwhile, deployments in the Azure QA region are being created normally. When such incidents occur, the changes in this PR will allow us to quickly switch the QA ESS region where we want deployments to be created by setting the value of the `TEST_INTEG_AUTH_ESS_REGION` environment variable.
> [Integration Test Framework] Allow creation of deployments in ESS QA Azure region

- .mockery.yaml
- internal/pkg/agent/application/coordinator/coordinator.go
- internal/pkg/agent/application/coordinator/coordinator_test.go
- internal/pkg/agent/application/coordinator/gateway.go
- internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
- internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
- internal/pkg/agent/application/managed_mode.go
- internal/pkg/fleetapi/checkin_cmd.go
- internal/pkg/fleetapi/client/client.go
- internal/pkg/fleetapi/client/client_test.go
- internal/pkg/fleetapi/client/round_trippers.go
- internal/pkg/remote/client.go
We add an `Elastic-Api-Version` header to all requests to Fleet. 
We already have support for detecting and logging warnings and downgrade requests (those are not yet implemented though)
The `Warning` header coming from Fleet is logged at fleet client level and propagated to coordinator via the specific error type `WarningError`. When the coordinator receives a `WarningError` will set fleet status to `Degraded` (as opposed to `Failed` that was used for any error up to this point) and set fleet status message to the warning it received.
We aim for Elastic Agent to support connecting to multiple versions of Fleet server supporting multiple api versions.
- ~~[ ] I have made corresponding change to the default configuration …
>  Implement basic version negotiation with Fleet Server

- changelog/fragments/1694190260-improve-upgrade-logging.yaml
- internal/pkg/agent/application/upgrade/cleanup.go
- internal/pkg/agent/application/upgrade/crash_checker.go
- internal/pkg/agent/application/upgrade/error_checker.go
- internal/pkg/agent/application/upgrade/rollback.go
- internal/pkg/agent/application/upgrade/step_download.go
- internal/pkg/agent/application/upgrade/step_mark.go
- internal/pkg/agent/application/upgrade/step_unpack.go
- internal/pkg/agent/application/upgrade/upgrade.go
- internal/pkg/agent/cmd/run.go
- internal/pkg/agent/cmd/watch.go
This PR makes several improvements to logs emitted by the Agent upgrade process:
* Changes all DEBUG level messages to INFO level in the upgrade process, whether that's the steps that happen in the Agent or in the Upgrade Watcher.
* The only exception to this is log messages where files/directories from the Agent artifact are being unpacked, as logging those at `INFO` level is unhelpefully verbose.
* Logs the Agent's version (including hash) and PID as early as possible after start up.
* Logs the Upgrade Watcher's version (including hash) and PID as early as possible after start up.
* Logs the Upgrade Watcher's PID when that process is spawned from the "main" Agent process.
To increase visibility into the Agent upgrade process, so we can tell from logs exactly where and how upgrades might …
> Improve Upgrade-related logging

- internal/pkg/agent/install/testblocking/main.go
- internal/pkg/agent/install/uninstall_windows_test.go
- magefile.go
My suspicion is this test gets flagged as malware because it writes code to disk and then compiles it by executing `go build` itself. This does seem like something malware could do, so I changed this to use the same build strategy the fake component uses. The `mage build:testBinary` target must be used to build the binaries before the test can run, which is a dependency of `mage unitTest`.
> Fix TestRemovePath being flagged as a possible virus

- changelog/fragments/1695050880-Improve-retry-strategy-when-uninstalling-agent.yaml
- internal/pkg/agent/install/uninstall.go
- internal/pkg/agent/install/uninstall_windows_test.go
Slightly modified the `RemovePath` retry loop on windows adding another iteration after deleting a blocking executable.
We want to make sure that we can uninstall elastic-agent even if a binary is still executing within the directory but we want to avoid false positives
Just run the test on windows (multiple times would be ideal) like:
```shell
gotestsum -- -count 1000 -v …
```
> Fix TestRemovePath flakiness on windows

- .buildkite/scripts/steps/integration_tests.sh
> Switch ESS region to azure-eastus2 for integ tests

- changelog/fragments/1695035111-Resilient-handling-of-air-gapped-PGP-checks.yaml
- internal/pkg/agent/application/upgrade/artifact/download/fs/verifier.go
- internal/pkg/agent/application/upgrade/artifact/download/fs/verifier_test.go
- internal/pkg/agent/application/upgrade/artifact/download/http/verifier.go
- internal/pkg/agent/application/upgrade/artifact/download/verifier.go
- internal/pkg/agent/install/uninstall_windows_test.go
- testing/integration/upgrade_test.go
This PR adds filtering capabilities for incorrect location or download failure when trying to fetch PGP keys before verification. 
When this error is encountered warning is logged and key not considered. This will not prevent from verifying in air gapped environments where default elastic artifact api is not available
Fixes #3368
> [Bug] Do not fail when remote PGPs are not available

- specs/endpoint-security.spec.yml
This PR  modifies the elastic security spec file by treating the container platforms as separate inputs without the restriction of requiring the default install location. 
This fixes an issue where the beta deployment of Endpoint in K8s would throw an error on deployment.
> [BUG] Treat elastic-security container platforms as separate inputs

- pkg/testing/fixture_install.go
This PR contains two changes to help with debugging test failures:
1. It fixes the naming of the diagnostics files in the case where a sub-test is executing. Sub test names contain `/` characters which are illegal in file names on Linux. Replace the `/` with a `-`.
2. If diagnostics collection fails for any reason, create a zip archive the agent installation directory on the test VM and upload that as a test artifact instead. This was useful when debugging the upgrade watcher test failures because I sometimes got logs and could see that the install directory was being manipulated very clearly.
> Fix test diagnostics collection, zip the install directory when diagnostics collection fails

- internal/pkg/agent/cmd/install.go
- internal/pkg/agent/install/install.go
This PR improves the `elastic-agent install` experience by only trying to uninstall the existing Elastic Agent installation if Elastic Agent is currently installed.
So the progress messages shown to the user during `elastic-agent install` are not misleading by suggesting that the existing Elastic Agent installation is being uninstalled, even when there is no Elastic Agent currently installed.
1. Start with a host where Elastic Agent is NOT currently installed.
2. Build Elastic Agent from this PR and install it.
```
sudo ./elastic-agent install
```
3. Verify that the progress messages shown do NOT include a message about Elastic Agent being uninstalled.
4. Verify that the installation succeeds.
```
sudo elastic-agent status
```
5. Try to install Elastic Agent again.
```
sudo …
```
> `elastic-agent install`: Only uninstall when Agent is installed

- .buildkite/scripts/common.sh
Fix the GCP credentials variable name according to the doc: https://cloud.google.com/docs/authentication/application-default-credentials#GAC
The credentials aren't working properly in some cases, for example, when the pipeline has multiple GCP credentials. 
It was tested in the other elastic repo.
> fix the GCP credentials variable name

- .buildkite/scripts/steps/integration_tests.sh
Remove override on agent and stack version
- 
- ...
> Refactor agent version pinning in integration test script

- changelog/fragments/1695780865-Enable-tamper-protection-feature-flag-by-default-for-Agent-8.11.0.yaml
- pkg/features/features.go
Enables tamper protection feature flag by default for Agent 8.11.0. 
In the 8.10.0 the default tamper protection feature flag disabled by default.
ATTN!!!: It is important to use the Agent with corresponding Endpoint build for 8.11.0 that has the feature flags default set to the same value for the feature to work correctly.
(omitting the link to Endpoint PR here since the Endpoint repository is private)
The combination of agent feature flag value in the policy
```
"agent": {
"features": {
"tamper_protection": {
"enabled": false
}
},
```
and the agent protection flag
```
agent:
....
protection:
enabled: true
````
define if the tamper protection is enabled or not.
Here are the tables that help to understand how this change of the tamper protection feature flag value affects 8.11 settings. …
> Enable tamper protection feature flag by default for Agent 8.11.0

- sonar-project.properties
- testing/integration/upgrade_test.go
Relates https://github.com/elastic/elastic-agent/issues/2176
This PR adds an integration test that ensures an Agent upgrade is rolled back because the new Agent (after upgrade) fails to start.
The test creates a fake Agent package containing a fake Agent binary that immediately exits with a non-zero status code.  The test installs the locally-built Agent and then attempts to upgrade to the fake Agent package. The upgrade is expected to fail due to the new (fake) Agent binary failing to start successfully, and therefore the upgrade should be rolled back to the previous Agent version.
To ensure the upgrade/rollback behavior is working as expected.
1. Build Agent locally.
```
DEV=true EXTERNAL=true SNAPSHOT=true PLATFORMS=linux/amd64,linux/arm64 PACKAGES=tar.gz mage package
```
2. Run the …
> [Integration Test] New Agent after upgrade fails to start

- docs/tracing.md
- internal/pkg/agent/application/apm_config_modifier.go
- internal/pkg/agent/application/apm_config_modifier_test.go
- internal/pkg/agent/application/application.go
- internal/pkg/agent/application/coordinator/config_patcher.go
- internal/pkg/agent/application/coordinator/diagnostics_test.go
- internal/pkg/agent/cmd/run.go
- internal/pkg/core/monitoring/config/config.go
- pkg/component/component.go
- pkg/component/config.go
- pkg/component/fake/component/README.md
- pkg/component/fake/component/comp/actions.go
- pkg/component/fake/component/comp/apm.go
- pkg/component/fake/component/comp/component.go
- pkg/component/fake/component/main.go
- pkg/component/runtime/apm_config_mapper.go
- pkg/component/runtime/apm_config_mapper_test.go
- pkg/component/runtime/command.go
- pkg/component/runtime/manager_test.go
- pkg/component/runtime/state.go
- pkg/utils/maps.go
- testing/integration/apm_propagation_test.go
- testing/integration/fake_test.go
- testing/integration/fakes.go
This change propagates the APM configuration set up for agent to the components that are managed.
We only support Elastic APM at the moment and at the time of this change this can only be configured in `elastic-agent.yml` configuration file.
For fleet-managed agents we include a workaround that will inject this configuration from the config file; this workaround inject the configuration from the config file in all the config changes received from Fleet, however it does not support hot reloading in this configuration: any changes to the apm configuration will take effect after a restart. 
Here's what an example of APM configuration looks like:
```yaml
agent.monitoring:
...
traces: true
apm:
hosts:
- https://12519f377f2449228f5095a5b549fe49.apm.us-central1.gcp.qa.cld.elstc.co:443 …
```
> Propagate apm config

- changelog/fragments/1696361138-es-default-compression.yaml
Changelog-only PR. Adds an entry for enabling compression by default in Elasticsearch outputs, which is an update that is propagating to Agent now that https://github.com/elastic/beats/pull/36681 changed the default for all beats.
> Add changelog for default ES compression

- internal/pkg/agent/cmd/install.go
- testing/integration/install_test.go
This PR un-hides the `--base-path` flag defined on the `elastic-agent install` sub-command.
To allow users to install Elastic Agent in custom locations.
> Un-hide `--base-path` install flag

- .golangci.yml
- NOTICE.txt
- changelog/fragments/1693592658-concurrent-install.yaml
- go.mod
- go.sum
- internal/pkg/agent/application/upgrade/upgrade.go
- internal/pkg/agent/install/install.go
- internal/pkg/agent/install/install_test.go
This PR makes `elastic-agent install` run slightly faster by concurrently copying files when the Agent is being installed on a host with SSDs.  The same is done with Elastic Agent upgrades.
For all tests, the first installation result was discarded and the worse of the next two installation results (the result with the higher installation time) was used.
| OS | Disk type | Before this PR (s) | After this PR (s) | Time savings (s) | Time savings (%) |
| --- | --------- | ----------------------------- | --------------------------- | ----------------- | ----------------- |
| MacOS | SSD | 15.3s | 13.9s | 1.4s | 9.2% |
| MacOS | HDD | | | | |
| Linux | SSD | 12.2s | 9.2s | 3s | 24.6% |
| Linux | HDD | 45.7s | 46s | -0.3s | -0.7% |
| Windows | SSD | 9.6s | 6.3s | 3.3s | 34.4% |
| Windows | HDD …
> Improve `elastic-agent install` performance

- changelog/fragments/1693403216-Surface-errors-during-Agent's-enroll.yaml
- internal/pkg/agent/cmd/enroll.go
- internal/pkg/agent/cmd/enroll_cmd.go
- internal/pkg/agent/cmd/enroll_cmd_test.go
- internal/pkg/agent/cmd/install.go
- internal/pkg/agent/install/perms_unix.go
For the agent to be actually enrolled it needs to restart after the enroll process is completed, so it'll pickup the new config and "connect" to fleet-server.
This change makes the enroll command to fail if it cannot restart the agent after enrolling on fleet
This change makes the enroll command to fail if it cannot restart the agent after enrolling on fleet
For the agent to be actually enrolled it needs to restart after the enroll process is completed, so it'll pickup the new config and "connect" to fleet-server.
- ~~[ ] I have added tests that prove my fix is effective …
> install fails if enroll fails and surface errors

- changelog/fragments/1694692246-hintspercontainer.yaml
- internal/pkg/composable/providers/kubernetes/hints.go
- internal/pkg/composable/providers/kubernetes/hints_test.go
Enhancement
This PR is introrduces the functionality described in https://github.com/elastic/elastic-agent/issues/3161!
In more details users provide the container name in the hint and this functionality is applied only to a specific container of the pod. When a pod has multiple containers, the settings are shared unless you put the container name in the hint. 
For eg. `co.elastic.hints.nginx/stream: stderr` is an annotation (aka. hints) that will be applied to a container wtih name nginx
It introduces a missing functionality that exists in Hints autodiscovry for beats as described in the [Multiple Containers Section](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html#_multiple_containers)
1. Follow the same steps as desceibed in "How to test this …
> Support Hints per container input

- internal/pkg/agent/application/coordinator/coordinator_test.go
adjust timeouts on the Coordinator tests so they have a better chance of succeeding in CI
Flaky tests in CI
- #3538
- ...
> adjust timeouts so tests have better chance of succeeding

- changelog/fragments/1696530758-bugfix-upgrade-progress-reporter.yaml
- internal/pkg/agent/application/upgrade/artifact/download/http/downloader.go
- internal/pkg/agent/application/upgrade/artifact/download/http/downloader_test.go
This PR fixes a bug in the progress logger being used while downloading the Agent artifact during the upgrade process.  Prior to this PR the progress logger used a `time.Timer` to log progress of the download.  With this PR, the progress logger uses a `time.Ticker` instead.
The progress logger should _periodically_ log progress of the download, not just once (after a delay).
- Found while writing tests for https://github.com/elastic/elastic-agent/pull/3542
> Replace timer with ticker in download progress reporter

- internal/pkg/agent/application/upgrade/artifact/download/fs/verifier.go
Replace succfailed by failed.
- 
- ...
> Fix typo in the GPG FS verifier warn message

- changelog/fragments/1696955150-Slow-down-agent-monitoring-metrics-interval-to-60s.yaml
- internal/pkg/agent/application/monitoring/v1_monitor.go
- internal/pkg/agent/application/monitoring/v1_monitor_test.go
Increase metricset execution interval for monitoring inputs created by agent.
To reduce the amount of data and the load related to collecting agent metrics
- 
- ...
> Increase metrics interval to 60s

- NOTICE.txt
- changelog/fragments/1697103197-updating_agentautodiscovery_811.yaml
- go.mod
- go.sum
- Breaking change
WHAT: Update the Elastic-agent-autodiscover to v0.6.4. This disables by default metadata enrichment for deployment and cronjobs
WHY: The metadata enrichemnt for replicasets (which are produced from deployments) and cronjobs is proved a feature with heavy memory usage especially in big kubernetes clusters. The outcome was to enhance pods that were created from deployments and cronjobs with the relevant deployment/cronjob name. Decision 
We want to avoid the memory impact of keeping the feature enabled in big k8s clusters
- Relates #https://github.com/elastic/sdh-beats/issues/3863
>  [backport 8.11]Elastic-agent-autodiscover to v0.6.4

- internal/pkg/agent/application/upgrade/artifact/download/http/downloader.go
- internal/pkg/agent/application/upgrade/artifact/download/http/downloader_test.go
- internal/pkg/agent/application/upgrade/artifact/download/http/progress_observer.go
- internal/pkg/agent/application/upgrade/artifact/download/http/progress_reporter.go
- internal/pkg/agent/application/upgrade/artifact/download/http/verifier.go
Prior to this PR, the HTTP downloader's `progressReporter` would report download progress in Agent logs. This functionality was implemented entirely within the `progressReporter` code.
This PR refactors the `progressReporter` code to accept multiple observers and introduces a new observer, `loggingProgressObserver`, that logs the observed progress in Agent logs, preserving the behavior prior to this PR. 
This PR is purely a refactoring PR; it does not change any functionality.  Functionally, the HTTP downloader's progress will continue to be reported in Agent logs. 
However, in https://github.com/elastic/elastic-agent/pull/3527, we will need the `progressReporter` to also report progress to another observer.  This PR makes it easy to accomplish that in a clean manner.  More context here: …
> Refactoring HTTP downloader progress reporter to accept multiple observers

- NOTICE.txt
- changelog/fragments/1697102363-updating_agentautodiscovery_810.yaml
- go.mod
- go.sum
- Breaking change
WHAT: Update the Elastic-agent-autodiscover to v0.6.4. This disables by default metadata enrichment for deployment and cronjobs
WHY: The metadata enrichemnt for replicasets (which are produced from deployments) and cronjobs is proved a feature with heavy memory usage especially in big kubernetes clusters. The outcome was to enhance pods that were created from deployments and cronjobs with the relevant deployment/cronjob name. Decision 
We want to avoid the memory impact of keeping the feature enabled in big k8s clusters
- Relates #https://github.com/elastic/sdh-beats/issues/3863
> [backport 8.10] Elastic-agent-autodiscover to v0.6.4

- magefile.go
- pkg/testing/ess/create_deployment_csp_configuration.yaml
- pkg/testing/ess/create_deployment_request.tmpl.json
- pkg/testing/ess/deployment.go
- pkg/testing/ess/provisioner.go
- refactor deployment creation and support aws templates
- support tags to be assigned to integration tests stack deployments
Support all 3 major CSP and tag stack deployments appropriately
- 
- How are …
> ESS Staging integ test improvements

- .buildkite/scripts/steps/integration_tests.sh
- internal/pkg/agent/application/upgrade/artifact/download/snapshot/downloader.go
- internal/pkg/agent/application/upgrade/artifact/download/snapshot/downloader_test.go
- pkg/testing/tools/artifacts_api.go
- testing/integration/upgrade_rollback_test.go
- testing/upgradetest/versions.go
- testing/upgradetest/versions_test.go
We now have working 8.12.0, 8.11.0, and 8.10.3 snapshots.
> Remove the agent version override in tests.

- NOTICE.txt
- changelog/fragments/1697662109-upgrade-elastic-agent-libs-to-v0.6.0.yaml
- go.mod
- go.sum
upgrade elastic-agent-libs to v0.6.0
allows elastic-agent running as a windows service to receive more than one
change request. Without this elastic-agent can become unresponsive to
Windows Service Manager requests (Interrogate/Shutdown/Restart).
Without this change Restart and Uninstall may hang, and shutdowns take significantly longer.
1. Install elastic-agent as a Windows Service, stand alone or Fleet managed
2. Start PowerShell
3. Interrogate service with 3 calls to Get-WmiObject -Class Win32_Service -Filter "name='Elastic Agent'"
4. Try to Restart 'Elastic Agent' with Services control panel
Without this PR Restart should fail, with PR it should succeed
- Closes #3557
- Closes #3372
- Closes #3307
- Closes #3061 …
> upgrade elastic-agent-libs to v0.6.0

- changelog/fragments/1696935756-add-default-host.yaml
- internal/pkg/composable/providers/kubernetes/hints.go
- internal/pkg/composable/providers/kubernetes/hints_test.go
- internal/pkg/composable/providers/kubernetes/pod.go
Given a pod with containers, it adds `co.elastic.hints.<container-name>/host: '${kubernetes.pod.ip}:<container-port>'` to the annotations for each container.
The user no longer needs to specify the host for the hints, which until now was a mandatory step.
1. Clone this branch.
2. Follow the steps in the [README](https://github.com/elastic/elastic-agent/blob/main/README.md#testing-elastic-agent-on-kubernetes) file to create the EA and add it to Kubernetes.
3. Deploy a pod with at least one container and the required annotation `co.elastic.hints/package` and check if the results can be seen in ES.
- Closes https://github.com/elastic/elastic-agent/issues/1453
- Relates to https://github.com/elastic/elastic-agent/issues/3063
**Context**: We have a nginx container with two pods: one in port …
> [Hints Support] Add default host

- changelog/fragments/1695920792-Prevent-multiple-stops-of-services.yaml
- pkg/component/runtime/manager.go
- pkg/component/runtime/runtime.go
- pkg/component/runtime/service.go
This PR prevents agent from stopping already stopped components.
Calling stop on an already stopped component may have unforeseen effects especially if uninstall is involved
- 
- ...
> Fix double stop components

- dev-tools/packaging/templates/ironbank/hardening_manifest.yaml.tmpl
> Update Ironbank contacts

- changelog/fragments/1698259940-Increase-wait-period-between-service-restarts-on-failure-to-15s-on-Windows.yaml
- internal/pkg/agent/install/svc.go
Increase the Windows `OnFailureDelayDuration` delay to 15s. This is the delay before the service is restarted when it exits unexpectedly. This is the same value used by endpoint-security by default.
Note that this change only applies to new agent installations. We would need to add code to migrate existing agent installations to the new value.
It was originally suggested that we increase this to 30s+ in https://github.com/elastic/elastic-agent/issues/3307#issuecomment-1696423487 but I am confident the root cause for that problem was addressed by https://github.com/elastic/elastic-agent-libs/pull/155.
Regardless I don't think our current default for this value was chosen for any particular reason and we can at least have agent behave consistently with endpoint. Speaking with @bjmcnic a 15s …
> Increase the Windows OnFailureDelayDuration delay to 15s

- internal/pkg/agent/application/monitoring/server.go
- internal/pkg/core/monitoring/config/config.go
- internal/pkg/core/monitoring/config/config_test.go
This PR disables option to configure agent in a way that it will expose monitoring agent on all interfaces. 
Empty value for `agent.monitoring.http.host` is now disabled and is replaced by localhost
Agents upgraded from <8.5 do have empty host due to change in defaults in 8.5. These agents are exposing metrics endpoint on all interfaces not on purpose.
Guard is implemented at the time of configuration unpacking and at the time of server creation to minimize future misbehavior with possible code changes 
Fixes: https://github.com/elastic/elastic-agent/issues/2509
> Disable exposing metrics server on all interfaces

- changelog/fragments/1698247934-hb-bump-node.yaml
- dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Bump NodeJS version bundled with Heartbeat to 18.18.2.
1. Build mage package locally.
2. Run a container with the generated image.
3. Execute the following command and test version matches `18.18.2`:
```
docker run --rm --entrypoint /bin/bash docker.elastic.co/beats/elastic-agent-complete:<version> -c "node --version"
v18.17.1
```
> [Heartbeat] Bump Node to 18.18

- .buildkite/hooks/pre-exit
- .buildkite/pipeline.yml
- magefile.go
- pkg/testing/ess/deployment.go
This PR changes the ESS region used by integration tests, when run in Buildkite, to `aws-eu-central-1`. 
This is the only region that's working at the moment.  In other regions, we're experiencing a Kibana failure, which is not only causing integration tests to fail because the deployment cannot come up but it's also leaving these broken deployments orphaned which costs money!
> [Buildkite][Integration tests] Change ESS region to `aws-eu-central-1`

- pkg/testing/fetcher_artifact.go
Switch from `uint64` to an `atomic.Uint64` to prevent data race in testing artifact fetcher
In CI we can see the data race:
```
==================
WARNING: DATA RACE
Read at 0x00c0002dbc18 by goroutine 11:
github.com/elastic/elastic-agent/pkg/testing.(*writeProgress).printProgress()
/var/lib/jenkins/workspace/tic-agent_elastic-agent-mbp_8.11/src/github.com/elastic/elastic-agent/pkg/testing/fetcher_artifact.go:285 +0x158
github.com/elastic/elastic-agent/pkg/testing.newWriteProgress.func1()
/var/lib/jenkins/workspace/tic-agent_elastic-agent-mbp_8.11/src/github.com/elastic/elastic-agent/pkg/testing/fetcher_artifact.go:267 +0x4c
Previous write at 0x00c0002dbc18 by goroutine 9:
github.com/elastic/elastic-agent/pkg/testing.(*writeProgress).Write() …
```
> prevent data race in testing artifact fetcher

- .ci/Jenkinsfile
Remove 1.25 version compatibility and add 1.28.
Relates to https://github.com/elastic/observability-dev/issues/2802.
> [Tests] Update K8s version for 1.28 compatibility

- testing/integration/endpoint_security_test.go
- testing/integration/upgrade_fleet_test.go
Update the endpoint package version for integration tests, some tests were failing because the old version was not found.
Fixes: https://github.com/elastic/elastic-agent/issues/3524, at least until newer versions are released.
Run the integration tests: `mage …
> Update endpoint package version on tests

- internal/pkg/remote/client.go
Fix a log message when fleet returns an error due to a wrong api version
This avoids a noisy formatting error in logs
- 
- …
> Fix wrong logging for wrong fleet api version response

- changelog/fragments/1697735373-Add-component-fields-to-metrics.yaml
- internal/pkg/agent/application/monitoring/v1_monitor.go
- internal/pkg/agent/application/monitoring/v1_monitor_test.go
This PR adds `component.id` and `component.binary` to the monitoring metrics, those fields are necessary to create unique TSDB entries.
It fixes metrics collection.
See the "How to test this PR locally" section from the integrations PR: https://github.com/elastic/integrations/pull/8238
- Relates https://github.com/elastic/integrations/pull/8238
- Closes https://github.com/elastic/integrations/issues/7977
~~## …
> Add component.{id, binary} to monitoring metrics

- .ci/Jenkinsfile
- dev-tools/dependencies-report
- dev-tools/packaging/packages.yml
- dev-tools/packaging/templates/ironbank/Dockerfile.tmpl
- dev-tools/packaging/templates/ironbank/hardening_manifest.yaml.tmpl
https://github.com/elastic/elastic-agent/pull/3567 partially changed the `ubi` version to `ubi9` but there were some other changes required in the packaging itself and the base docker images.
`ubi9` is not available yet.
It ran in the CI
```bash
$ docker pull docker.elastic.co/observability-ci/elastic-agent-ubi9:52773d50b4496e1e2d5ba82736c69aa7862161e8
$ docker inspect docker.elastic.co/observability-ci/elastic-agent-ubi9:52773d50b4496e1e2d5ba82736c69aa7862161e8 | jq -r '.[0].Config.Labels' | grep ubi
"com.redhat.component": "ubi9-minimal-container",
```
In addition
```
$ wget https://storage.googleapis.com/fleet-ci-artifacts/elastic-agent/commits/52773d50b4496e1e2d5ba82736c69aa7862161e8/elastic-agent-ironbank-8.12.0-SNAPSHOT-docker-build-context.tar.gz
$ tar xvzf …
```
> ironbank: move to ubi9

- sonar-project.properties
This PR configures Sonar to exclude the code files generated by from code coverage analysis.
Generated code does not come with corresponding generated tests — that would be silly! As such, if Sonar sees _only_ changes to generated code, it will flag it as a decrease in code coverage which, while technically correct, is practically useless.
> Add generated protobuf code files to sonar exclusions list

- internal/pkg/agent/application/coordinator/coordinator.go
- internal/pkg/agent/application/coordinator/coordinator_test.go
Clean up `Coordinator` shutdown handling and fix the no-op retry loop described in https://github.com/elastic/elastic-agent/issues/2789.
The previous retry logic in `(*Coordinator).Run` never took effect: the only possible error return was considered fatal, and so there was never an actual retry. This returned error (`ErrFatalCoordinator`) was a placeholder returned in part out of caution, since accidentally retrying a fatal error could deadlock the Agent.
Following discussion in https://github.com/elastic/elastic-agent/issues/2789, the new model is:
- All errors that cause a Manager's Run routine to terminate are considered fatal
- Managers should send non-fatal errors to the manager's existing error channel instead of returning
(This is already how managers work in practice.)
This PR:
- …
> Clean up Agent Coordinator and manager shutdown logic

- internal/pkg/agent/application/upgrade/details/details.go
- internal/pkg/agent/application/upgrade/details/details_test.go
This PR fixes the Upgrade Details struct such that setting its `State` field to anything other than `StateFailed` clears associated fields, `Metadata.FailedState` and `Metadata.ErrorMsg`.
The `Metadata.FailedState` and `Metadata.ErrorMsg` should only be set when `State` is set to `StateFailed`.
> [Upgrade Details] When state is set to something other than `StateFailed`, clear related metadata fields

- changelog/fragments/1697662209-duplicate-tags.yaml
- internal/pkg/agent/cmd/enroll_cmd.go
- internal/pkg/agent/cmd/enroll_cmd_test.go
When duplicate tags are specified, only take them once into account.
Enroll Agent by specifying "--tag=mac,test,mac" and verify that you only have "mac" tag once.
- Closes https://github.com/elastic/elastic-agent/issues/858
- ...
> Remove duplicate tags

- .buildkite/pipeline.yml
Makes MacOS 13 ARM unit tests to be executed only on push to the `main` branch
The Orka cluster on ARM MacOS VMs is being exhausted by pull requests. As it was discussed before we can run it only on `main` because there's no ARM-specific code for darwin.
> [CI] run MacOS 13 ARM unit tests only on main branch

- deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset-configmap.yaml
- deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-ksm-daemonset-configmap.yaml
- deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-ksm-statefulset-configmap.yaml
- deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-ksm-daemonset-configmap.yaml
- deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-ksm-statefulset-configmap.yaml
- deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
- deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml
- deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-ksm-daemonset-configmap.yaml
- deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-ksm-statefulset-configmap.yaml
Add the `state_namespace` data stream by default to the EA manifest files.
This data stream was introduced in version 8.11.0.
The package version was also updated to 1.52.0 as the data stream was [introduced there](https://github.com/elastic/integrations/blob/af38b975375ce4504b2589ea9df4aa45c77dc205/packages/kubernetes/changelog.yml#L12).
1. Clone this branch.
2. Deploy EA standalone in version 8.11.0.
3. Check `state_namespace` metrics are there.
Relates to https://github.com/elastic/elastic-agent/issues/3100.
> [EA standalone] Add state_namespace data stream by default to the manifests

- pkg/testing/multipass/provisioner.go
- testing/integration/logs_ingestion_test.go
It deletes and purges the multipass instance if it already exists.
The multipass provisioner tries to launch a nre instance, if it already exists the test setup fails.
- ~~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool]~~(https://github.com/elastic/elastic-agent#changelog)
Run a integration test with the multipass provider twice, the multipass setup will succeeded in the second attempt.
- Relates …
> multipass: ensure instance does not exist

- internal/pkg/agent/application/dispatcher/dispatcher.go
- internal/pkg/agent/application/dispatcher/dispatcher_test.go
- internal/pkg/agent/application/managed_mode.go
- internal/pkg/agent/application/managed_mode_test.go
- internal/pkg/agent/application/upgrade/details/details.go
This PR enhances Elastic Agent to track the `UPG_SCHEDULED` state.  It tracks this state for the first (next) scheduled upgrade.
Users can know if an upgrade has been scheduled and when it has been scheduled for.
- Relates to https://github.com/elastic/elastic-agent/issues/3119#issuecomment-1743638526
> [Upgrade Details] Implement tracking of `UPG_SCHEDULED` state

- magefile.go
- pkg/testing/ess/serverless_provisioner.go
- pkg/testing/ess/serverless_test.go
- pkg/testing/ess/statful_provisioner.go
- pkg/testing/multipass/provisioner.go
- pkg/testing/ogc/provisioner.go
- pkg/testing/runner/provisioner.go
- pkg/testing/runner/runner.go
- pkg/testing/runner/runner_test.go
It adds the provisioner name to Stack and Instance so the test framework can differentiate stack and instances from different providers
The runner was not taking into account the provisioner when checking is there was already an instance or stack to be reused
see https://github.com/elastic/elastic-agent/issues/3756
- Closes …
> Fix runner/provisioners to account for the provision r when comparing instances and stacks

- NOTICE.txt
- go.mod
- go.sum
- internal/pkg/agent/application/upgrade/details/details.go
- internal/pkg/agent/application/upgrade/details/details_test.go
This is a refactoring PR. It moves the `details.DownloadRate` type from the `github.com/elastic/elastic-agent` module to the `github.com/elastic/elastic-agent-libs` module.
So packages within the `github.com/elastic/elastic-agent-libs` module can reuse the `details.DownloadRate` type; see https://github.com/elastic/elastic-agent-libs/pull/166.
* Closes https://github.com/elastic/elastic-agent/issues/3792
> [Upgrade Details] Use `details.DownloadRate` type from elastic-agent-libs

- internal/pkg/agent/application/application.go
- pkg/component/runtime/manager.go
Adding some log messages I wish had been present while troubleshooting my most recent support case.
> Log some useful details during startup

- pkg/testing/runner/runner.go
If the BatchID is longer than 63 characters, OGC will fail to instantiate a GCP VM, this commit fixes this by using a MD5 hash of the whole ID and ensuring the final ID is at most 63 characters long.
It fixes the integration tests
Run the integration tests, they should not fail.
OGC error …
> Limit batchID length.

- deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
- deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
- deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
- deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml
- deploy/kubernetes/elastic-agent-managed-kubernetes.yaml
- deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
This changes the default FLEET_INSECURE value to false in the Kubernetes templates. This will change to match the [documentation](https://www.elastic.co/guide/en/fleet/8.11/agent-environment-variables.html#env-enroll-agent), which states `false` is the default, and using `true` is not recommended.
This will improve security for users of the Kubernetes daemonset who don't change the default value.
~~- [ ] My code follows the style guidelines of this project~~
~~- [ ] I have added an entry in `./changelog/fragments` using the [changelog …
> Change the default FLEET_INSECURE values in Kubernetes templates to false

- internal/pkg/agent/cmd/install.go
HIde's the `--unprivileged` installation flag until it is fully supported. Includes a message during installation explaining that when used it is experimental and unsupported.
Make it clear that its not to be used until the feature is complete.
> [Non-Root] Hide --unprivileged installation flag until supported

- internal/pkg/agent/application/upgrade/marker_watcher.go
- internal/pkg/agent/application/upgrade/marker_watcher_test.go
Change rollback detection based on version check to include commit hash. 
For improving related integration tests changes from #3827 and #3837 are needed
This allows correct version detection in case of upgrade between different builds of the same SNAPSHOT version
-  Relates #3827 
- Relates #3837 
- What are the metrics I …
> Add agent hash to check for detecting upgrade rollbacks

- internal/pkg/agent/application/upgrade/marker_watcher.go
- internal/pkg/agent/application/upgrade/marker_watcher_test.go
- internal/pkg/agent/application/upgrade/upgrade.go
This PR allows the part of the upgrade process performed by the old (pre-upgrade) Agent to inform the Upgrade Marker Watcher when an upgrade starts.
The Upgrade Marker Watcher's job is to watch for changes to the Upgrade Marker file and process said changes.  As part of this processing, it implements fallback logic to determine if the upgrade has been rolled back.  For this, it checks whether the running Agent's version is the same as the `prev_version` noted in the Upgrade Marker. 
However, this version check alone is not sufficient to say that the Agent has rolled back, as the check will also succeed in the period right after the old (pre-upgrade) Agent creates the Upgrade Marker but before it re-execs and starts up the new (post-upgrade) Agent.  If the old (pre-upgrade) Agent can …
> [Upgrade Details] Inform the Upgrade Marker Watcher when an upgrade starts

- internal/pkg/agent/application/upgrade/marker_access_common.go
- internal/pkg/agent/application/upgrade/marker_access_common_test.go
- internal/pkg/agent/application/upgrade/marker_access_other.go
- internal/pkg/agent/application/upgrade/marker_access_test.go
- internal/pkg/agent/application/upgrade/marker_access_windows.go
- internal/pkg/agent/application/upgrade/step_mark.go
- internal/pkg/agent/application/upgrade/upgrade.go
- internal/pkg/agent/cmd/watch.go
This PR calls https://pkg.go.dev/os#File.Sync on the Upgrade Marker file when critical upgrade transitions happen.
In case the Agent immediately crashes (e.g. host loses power) after critical upgrade transitions, these transitions will be persisted to disk in the Upgrade Marker file.
- Relates https://github.com/elastic/elastic-agent/pull/3827#discussion_r1408453784
> [Upgrade Details] For critical state transitions, fsync upgrade marker file

- internal/pkg/agent/application/paths/common.go
`--path.install` has no effect since v8.6.0, removing it is a breaking change because it would prevent the Elastic-Agent from running if `--path.install` is passed.
Instead of removing it, this commit updates its documentation to inform it is deprecated and has no effect.
It updates our CLI documentation to correctly reflect the Elastic-Agent behaviour. …
> Update CLI documentation for `--path.install`

- .mergify.yml
Merge as soon as 8.12 branch was created. Auto-merge is not yet supported, see https://github.com/Mergifyio/mergify-engine/discussions/2821
> backport: Add 8.12 branch

- testing/integration/upgrade_fleet_test.go
Fixes the `TestFleetAirGappedUpgrade` which was using the latest snapshot, but during minor releases the stack isn't available on the same version. Therefore it should use the "current" version which is adjusted so the tests wont fail during minor releases.
The failing test prevent PRs from being merged
- ~~[ ] I have added an integration test or an E2E …
> download current agent version to upgrade to

- pkg/testing/tools/testcontext/testcontext.go
- testing/integration/fqdn_test.go
This PR re-enables the `TestFQDN` integration test as the flaky test issue referenced in the skip directive (https://github.com/elastic/elastic-agent/issues/3154) has been resolved.
> Re-enable TestFQDN

- changelog/fragments/1701091034-add-cache-for-secrets.yaml
- internal/pkg/composable/providers/kubernetessecrets/config.go
- internal/pkg/composable/providers/kubernetessecrets/kubernetes_secrets.go
- internal/pkg/composable/providers/kubernetessecrets/kubernetes_secrets_test.go
Currently, we make a request to the API Server every time we need to get the value of a secret. This issue is better explained [here](https://github.com/elastic/elastic-agent/issues/3594). Discussion also present in the issue.
With this PR, we use a map to store the secrets like this:
1. Once the kubernetes secret provider starts running, we launch a go routine that will update the cache every TTL minutes. [TTL](https://github.com/constanca-m/elastic-agent/blob/dadc79b3d338bd2f4b37e3488c453d145450e436/internal/pkg/composable/providers/kubernetessecrets/config.go#L14) is a new option in the configuration of the provider. By default it is set to 10 minutes.
2. To update the cache, we range over every secret stored there, and make a new request to the API Server to obtain the current value. …
> [Kubernetes secret provider] Add cache for the secrets

- magefile.go
- pkg/testing/ess/serverless.go
- pkg/testing/ess/serverless_provisioner.go
- pkg/testing/ess/serverless_test.go
- pkg/testing/fixture.go
- pkg/testing/machine.go
- pkg/testing/machine_test.go
- pkg/testing/tools/check/check.go
- pkg/testing/tools/estools/elasticsearch.go
- pkg/testing/tools/fleettools/fleet.go
- pkg/testing/tools/tools.go
- testing/integration/apm_propagation_test.go
- testing/integration/diagnostics_test.go
- testing/integration/endpoint_security_test.go
- testing/integration/fqdn_test.go
- testing/integration/logs_ingestion_test.go
- testing/integration/package_version_test.go
- testing/integration/proxy_url_test.go
- testing/integration/upgrade_fleet_test.go
We are still seeing integration tests time out after 2+ hours. This appears to be because we are making network requests without timeouts in several instances, with the root cause being that we do not propagate contexts through the calls even though we are using the `WithContext` variant of the network call.
For example https://buildkite.com/elastic/elastic-agent/builds/5302#018c2582-6e37-488c-a13f-4964c8fc51ea got stuck in a new place. It timed out in https://github.com/elastic/elastic-agent/blob/33ad31eae14026fa1151c7b42ee3cf44ead00b9b/pkg/testing/tools/tools.go#L126-L132
That eventually ends up in https://github.com/elastic/elastic-agent/blob/33ad31eae14026fa1151c7b42ee3cf44ead00b9b/pkg/testing/tools/fleettools/fleet.go#L18-L22
Which hard codes context.Background. 
I searched for …
> Add missing contexts (and therefore timeouts) to integration test code

- testing/integration/apm_propagation_test.go
This test causes the Windows tests to hang for 2 hours until they time out. While we investigate the root cause skip the test. The test will still run on Linux.
> Skip APM propagation test on Windows.

- specs/endpoint-security.spec.yml
- Closes https://github.com/elastic/elastic-agent/issues/3936
Endpoint wasn't using the anchored outputs section from its Linux definition for Windows and Mac, so it wasn't allowing use of Kafka when it should be.
> Endpoint outputs should be the same on Windows, Mac, and Linux

- internal/pkg/agent/application/upgrade/marker_access_common.go
- internal/pkg/agent/application/upgrade/marker_access_common_test.go
This PR fixes the corruption that could take place when writing the Upgrade Marker file.
Agent tries to reads the Upgrade Marker file at startup to determine if the Agent is in the midst of an upgrade.  If it cannot read the Upgrade Marker file because it's corrupted, an error is returned, and Agent fails to start up.
The bug that's being fixed in this PR was caught via an E2E test that was failing consistently: `TestFleetManagedUpgrade `.  Unfortunately, though this PR fixes the bug, this test will not pass on the PR.  That's to be expected because the non-truncating write that was causing the bug is happening from the Upgrade Watcher, which is run as part of the new (i.e. upgraded) Agent. And the Agent that's upgraded to in the test is one pulled down from the artifacts API, not the one …
> [Upgrade Details] Fix corruption when writing upgrade marker file

- NOTICE.txt
- changelog/fragments/1703157372-a-changeset-filename.yaml
- go.mod
- go.sum
To include fix introduced in elastic-agent-autodiscover by this PR - https://github.com/elastic/elastic-agent-autodiscover/pull/72
- 
- ...
> Bump elastic-agent-autodiscover version

- internal/pkg/agent/application/upgrade/upgrade.go
- internal/pkg/agent/application/upgrade/upgrade_test.go
Add a test to the `UpgraderReloader` to ensure it reloads all the configuration present on the `agent.download` configuration key.
A followup issue, https://github.com/elastic/elastic-agent/issues/3940, will cover making sure new options added to `agent.download` are also covered by test.
Ensuring all configuration received from fleet-server is indeed applied.
Run the tests, ensure they pass, check their coverage.
- Closes #3820 …
> Add test ensuring all the agent.download settings are reloaded

- pkg/control/v2/server/listener_windows.go
- pkg/utils/root_windows.go
replaces custom `isWindowsAdmin` in listener_windows.go with call to `HasRoot` implementation in `utils`.  Also fix memory leak in `HasRoot` function.
In some localized Windows installs calls to `GroupIds` for the user of the process fail, this was causing the `isWindowsAdmin` check to fail, which causes problems with the control socket for `elastic-agent`.
The `HasRoot` implementation doesn't depend on `GroupIds`
1. Run agent install command on Windows 10 French/German VM.
2. Observe agent service is not restarted itself on installation.
3. Navigate to services and manually restart the Elastic Agent service.
4. Observe agent gets Healthy under Agents tab.
1. Run agent install command on Windows 10 French/German VM.
2. Observe agent service is restarted on installation.
3. `elastic-agent …
> switch to consistent HasRoot method on windows and fix memory leak

- testing/integration/container_cmd_test.go
Increases PrepareAgentCommand ctx deadline for TestContainerCMD
The tests is flaky failing due to `error running container cmd: context deadline exceeded`
- N/A
- What …
> Increase PrepareAgentCommand ctx deadline for TestContainerCMD

- .github/dependabot.yml
- .github/workflows/post-dependabot.yml
post dependabot is failing on make notice.
`make notice` proxies to `mage notice` ( since #3772 ) which is not present at the time
In addition this PR adds commit steps for otel readme introduced in #3992
> Setup mage for post dependabot action

- testing/upgradetest/upgrader.go
- Relates https://github.com/elastic/elastic-agent/pull/3901
In https://github.com/elastic/elastic-agent/pull/3901 when we switched the agent package version from 8.12.0 to 8.13.0 it had the side effect of enabling the upgrade details checks for watching state:
https://github.com/elastic/elastic-agent/blob/602a2b4587a8050b38881ad9e5811be79b4562c1/testing/upgradetest/upgrader.go#L178-L188
There are two problems with this:
1. That check should be against 8.12.0 and not 8.13.0, since we backported the code involved.
2. Versions older than 8.10.0 start their version of the watcher, and not the version of the watcher from the new agent. This means this check was enabled for 7.17 and causing the tests that upgrade from 7.17 to fail. This is expected, we need to consider the version we are …
> Use correct 8.12 version for watcher details checks.

- internal/pkg/agent/cmd/run.go
- pkg/testing/fixture_install.go
- pkg/testing/tools/tools.go
- testing/integration/delay_enroll_test.go
This PR skips trying to restart the `elastic-agent` process during a delayed enroll.  Instead the process exits and is restarted by the service manager.
This is necessary because the code to restart the `elastic-agent` process requires that the control server be up, and it isn't at this point.  This restores previous behavior, where the attempt to restart the `elastic-agent` process was non-fatal.
bug that prevents `elastic-agent` from starting when `--delay-enroll` is used
1. On Windows, install elastic-agent with `--delay-enroll` option
2. attempt to start service with Services control panel
3. notice in logs that restart fails 4 times and `elastic-agent status` will fail
1. On Windows, install elastic-agent with `--delay-enroll` option
2. attempt to start service with Services control …
> set SkipDaemonRestart in tryDelayEnroll

- testing/upgradetest/upgrader.go
So, we know that we upgrade from and to different builds/snapshots, not the same.
Related to https://github.com/elastic/elastic-agent/issues/4089
> Add commit hashes to logged versions in upgrader

- pkg/testing/fixture.go
- testing/integration/fake_test.go
- Closes https://github.com/elastic/elastic-agent/issues/4076
The TestFakeComponent test had a short 10 second context timeout, which is shorter than the retry interval of when waiting for the control socket. This is causing the test to continue to be flaky because it isn't allowing the control socket and agent enough time to start on Windows.
Fixes the failure below, where we start polling for the control socket at `2024-01-18T16:30:05.0297061` but the first agent logs have timestamp `2024-01-18T16:30:13.362Z` 8 seconds later.
```
=== RUN   TestFakeComponent
fixture.go:262: Extracting artifact elastic-agent-8.13.0-SNAPSHOT-windows-x86_64.zip to C:\Users\windows\AppData\Local\Temp\TestFakeComponent2648583623\001
fixture.go:275: Completed extraction of artifact …
```
> Increase short 10 second timeout in TestFakeComponent

- changelog/fragments/1705605734-fix-creation-of-directories-when-unpacking-tar.gz-packages.yaml
- internal/pkg/agent/application/upgrade/step_unpack.go
- internal/pkg/agent/application/upgrade/step_unpack_test.go
- internal/pkg/agent/application/upgrade/upgrade.go
This change fixes the creation of destination directories for file contained in a tar package.
If a file needs to be extracted to a destination directory that does not yet exist we create the necessary directories on the fly with permission `0750`.
If we encounter the same directories after the file, we fix the permissions according to what is specified in the tar archive
When running without superuser privileges we need to create a directory structure that has permissions that do not block access to the current user
- ~~[x] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in …
> Fix creation of containing directories for files in tar packages

- .github/ISSUE_TEMPLATE/flaky-test.yml
* There were wrong indentations
* A wrong `about` key was used instead of `description`
* I added the Platform Ingest Project too
Reported errors (interestingly enough the Github editor didn't catch them):
Now I tested this YAML in my personal private repository and it looks like this:
> Fix YAML formatting in the flaky-test form

- pkg/testing/fixture.go
Observed another failure attempting to connect to the gRPC pipe with marginal timing. It shouldn't take us 15 seconds to connect, I suspect we might be starting too connect to early. 
This PR doesn't start the state watch until after we actually launch the agent process.
Here is the failure from https://buildkite.com/elastic/elastic-agent/builds/6393 for reference:
```
=== RUN   TestFakeComponent
fixture.go:261: Extracting artifact elastic-agent-8.13.0-SNAPSHOT-windows-x86_64.zip to C:\Users\windows\AppData\Local\Temp\TestFakeComponent3737372147\001
fixture.go:274: Completed extraction of artifact elastic-agent-8.13.0-SNAPSHOT-windows-x86_64.zip to C:\Users\windows\AppData\Local\Temp\TestFakeComponent3737372147\001
fixture.go:880: All component specifications where removed
fixture.go:921: …
```
> Start state watch after starting process.

- pkg/testing/ess/statful_provisioner.go
These new tags will help when deployments are left lingering to trace back the build that left them like that and identify how we can implement better clean-up strategies for them.
This is going to help us trace lingering ess deployments to builds and see why we did not clean them up.
This is similar to the tagging we did for [fleet-server](https://github.com/elastic/fleet-server/blob/main/dev-tools/cloud/terraform/main.tf) 
This change should not have any impact on the elastic-agent codebase.
> Add some deployment tags for helping with tracing

- .buildkite/pipeline.yml
Temporarily disables windows 10 tests
Previous images caused failures for unit tests on windows 10
> [CI] Disables win 10 unit tests

- testing/integration/upgrade_uninstall_test.go
In TestStandaloneUpgradeUninstallKillWatcher,  we need to wait for watcher process to start before starting the uninstall.  If watcher hasn't started before the uninstall begins, the uninstall won't find it's pid, so won't kill it, but the watcher can start before the directory gets deleted.
Fixes flaky test.
```
mage integration:single TestStandaloneUpgradeUninstallKillWatcher
```
- ...
> flaky TestStandaloneUpgradeUninstallKillWatcher

- dev-tools/mage/common.go
- dev-tools/mage/settings.go
- dev-tools/packaging/package_test.go
- dev-tools/packaging/packages.yml
- pkg/api/v1/api.go
- pkg/api/v1/manifest.go
- pkg/api/v1/manifest_test.go
This PR adds a manifest to .zip, tar.gz, .deb and .rpm packages according to the outcome of #3639
In this PR the manifest is only generated and included in the packages but not yet used by install or upgrade processes.
This is a prerequisite for #3950 where the manifest included in the package will be used for remapping package directories during install and upgrade
It can be interesting having a look at .tar.gz or .zip packages and see how the manifest …
> Add manifest to package

- internal/pkg/agent/application/upgrade/rollback.go
- internal/pkg/agent/application/upgrade/step_mark.go
- internal/pkg/agent/application/upgrade/step_relink.go
- internal/pkg/agent/application/upgrade/step_unpack.go
- internal/pkg/agent/application/upgrade/step_unpack_test.go
- internal/pkg/agent/application/upgrade/upgrade.go
- internal/pkg/agent/cmd/watch.go
This is a subset of a bigger PR #3950, so CI is not expected to be green, especially regarding the integration tests.
This PR uses the package manifest included in elastic-agent packages to map the package contents onto disk when upgrading . In the context of #2579 the path mapping is used to install the agent we are upgrading to in a directory like `data/elastic-agent-<package version>-<hash>`.
The upgrade process now looks for the package manifest file and copies the files in the archive after mapping the name using the path mappings in the manifest. This means that also the new agent will end up in `data/elastic-agent-<package version>-<hash>`
This PR is needed to ensure that new versions of agents get installed to a new path containing the version from a package …
> Use package manifests for upgrade

- internal/pkg/agent/application/paths/common.go
- internal/pkg/agent/application/upgrade/rollback.go
- internal/pkg/agent/application/upgrade/rollback_test.go
- internal/pkg/agent/application/upgrade/step_mark.go
- internal/pkg/agent/application/upgrade/step_relink.go
- internal/pkg/agent/application/upgrade/step_unpack.go
- internal/pkg/agent/application/upgrade/step_unpack_test.go
- internal/pkg/agent/application/upgrade/upgrade.go
- internal/pkg/agent/cmd/run.go
- internal/pkg/agent/cmd/watch.go
This is a subset of a bigger PR #3950, so CI is not expected to be green, especially regarding the integration tests.
This PR adds new fields in the update marker so that the upgrade watcher Cleanup and Rollback processes can operate correctly with the new `elastic-agent-<version>-<hash>`.
There is some refactoring to make Cleanup() and Rollback() testable that involves injecting paths rather than obtaining through `paths.*` functions: this is needed to be able to write unit tests without calling `paths.SetTop()` which already created flakiness and introduced race conditions in our tests in the past
Now the agent installation is correctly cleaned up leaving only the new or old version of agent installed, since the watcher is reading the correct paths from the new update marker
- ~~[ ] I …
> Support version in watcher cleanup rollback

- changelog/fragments/1706703918-Add-the-full-version-number-to-the-installation-directory-name.yaml
- dev-tools/mage/settings.go
- dev-tools/packaging/package_test.go
- dev-tools/packaging/templates/darwin/elastic-agent.tmpl
- docs/upgrades.md
- internal/pkg/agent/application/upgrade/rollback.go
- internal/pkg/agent/application/upgrade/rollback_darwin.go
- internal/pkg/agent/application/upgrade/rollback_linux.go
- internal/pkg/agent/application/upgrade/rollback_test.go
- internal/pkg/agent/application/upgrade/rollback_windows.go
- internal/pkg/agent/application/upgrade/step_download.go
- internal/pkg/agent/application/upgrade/step_download_test.go
- internal/pkg/agent/application/upgrade/step_mark.go
- internal/pkg/agent/application/upgrade/step_relink.go
- internal/pkg/agent/application/upgrade/step_unpack.go
- internal/pkg/agent/application/upgrade/step_unpack_test.go
- internal/pkg/agent/application/upgrade/upgrade.go
- internal/pkg/agent/application/upgrade/upgrade_test.go
- internal/pkg/agent/cmd/run.go
- internal/pkg/agent/cmd/watch.go
- internal/pkg/agent/install/install.go
- internal/pkg/agent/install/install_test.go
- pkg/api/v1/manifest.go
This is the last subset of a bigger PR #3950, so CI should be green.
This change checks if the target version of the upgrade is at least 8.13.0 to decide which upgrade watcher to launch. This is needed to ensure that the watcher performs correct cleanup and rollbacks by reading paths in the update marker.
In this PR it's also included a necessary fix to the shutdownCallback since we do some path manipulation to support the legacy structure of component run directory where we replace versions from old to new.
This PR includes also a set of minor fixes to fix the elastic-agent upgrade on MacOS and Windows.
This is the final block of code necessary to implement #2579 on Linux, MacOS and Windows. It will make use of the mapping described in the package manifest to correctly place agent files …
> Use watcher that supports paths in update marker

- NOTICE.txt
- go.mod
- internal/pkg/agent/cmd/common.go
- internal/pkg/agent/cmd/otel.go
- internal/pkg/agent/cmd/otel_flags.go
- internal/pkg/agent/cmd/otel_flags_test.go
- internal/pkg/agent/cmd/validate.go
- testing/integration/otel_test.go
Added support for [feature gates](https://github.com/open-telemetry/opentelemetry-collector/blob/main/featuregate/README.md) for `otel` and `validate` commands
- Build/Package agent
- run `./elastic-agent otel --feature-gates "-telemetry.useOtelForInternalMetrics"`
- as this is `stable` feature gate, you should see error returned saying `useOtelForInternalMetrics` is stable and cannot be disabled
- running `./elastic-agent otel --feature-gates telemetry.useOtelForInternalMetrics` (difference is `-` in front of a gate name) should result in a warning message in output saying it's stable and collector running normally 
- running `./elastic-agent otel -h` needs to include flag in help message
Fixes: #3873
> Enable feature-gates for otel subcommands

- testing/integration/package_version_test.go
Skip flaky integration test TestComponentBuildHashInDiagnostics
The test is flaky
<!-- Recommended
Link related issues below. Insert the issue link or reference after the word "Closes" if merging this should automatically close it.
- Relates https://github.com/elastic/elastic-agent/issues/4215
- …
> Skip flaky integration test TestComponentBuildHashInDiagnostics

- pkg/testing/ess/serverless.go
The previous _reset-credentials endpoint will soon return a less privileged user. The internal variant returns one with operator privileges to allow inspecting cluster health for testing purposes.
> Serverless: switch to _reset-internal-credentials.

- changelog/fragments/1707481157-etw-filebeat-spec.yaml
- specs/filebeat.spec.yml
ETW is a new Filebeat input added at https://github.com/elastic/beats/pull/36915. This PR adds it to the Filebeat spec so it can be run by the elastic-agent.
**Note:** Don't merge it before the input at PR mentioned above.
This makes that input available to be used by integrations.
- Relates https://github.com/elastic/beats/pull/36915
> specs/filebeat.spec.yml - make ETW input available

- internal/pkg/agent/application/upgrade/rollback.go
- internal/pkg/agent/application/upgrade/upgrade.go
- internal/pkg/agent/application/upgrade/upgrade_test.go
- internal/pkg/agent/cmd/run.go
This PR adds a wait after launching the upgrade watcher to make sure that the process is up and running before restarting agent.
We want to avoid race conditions that may happen in case of downgrade where after restart an older watcher that does not understand the new update marker format may break the whole agent installation.
- Closes #4204
- Closes #4228
- …
> Add wait for watcher

- changelog/fragments/1707754331-websocket-filebeat-spec.yaml
- specs/filebeat.spec.yml
Please label this PR with one of the following labels, depending on the scope of your change:
- Configuration
Websocket is a new Filebeat input added with the PR https://github.com/elastic/beats/pull/37774. This PR adds it to the Filebeat spec so it can be run by the elastic-agent.
This makes that input available to be used by integrations.
- 
- ...
> [elastic-agent][new spec] - Added websocket to agent spec sheet

- pkg/testing/fixture_install.go
This commit adds assertions at the beginning and at the end of Fixture.Install() checking that no agent processes are running before installing or after uninstalling.
If any elastic-agent processes are detected, the test is marked as failed but it still runs to completion.
This PR adds assertions for `elastic-agent` processes not running before installing or after uninstalling elastic agent in our integration tests. 
This is needed to highlight any test that leaves agent processes running (usually watchers) which may influence other tests runs and cause flakyness. …
> Check for agent rogue processes in integration tests

- changelog/fragments/1707999059-Fixes-an-issue-where-the-Elastic-Agent-did-not-utilize-the-download-settings-when-downloading-the-artifact-signature-file..yaml
- internal/pkg/agent/application/upgrade/artifact/download/http/verifier.go
- internal/pkg/agent/application/upgrade/artifact/download/http/verifier_test.go
Changes the http.Verifier to use its http.Client and extend the tests to also test it uses the proxy.
The http.Verifier was using the default http client, which does not have the user defined settings.
follow the **_Steps to Reproduce_** from https://github.com/elastic/elastic-agent/issues/4237
- Closes https://github.com/elastic/elastic-agent/issues/4237
- What are the metrics I should …
> Fixes http.Verifier so it uses its http client

- changelog/fragments/1707935415-Add-mTLS-env-var-settings-for-containers.yaml
- internal/pkg/agent/cmd/container.go
- internal/pkg/agent/cmd/container_test.go
- internal/pkg/agent/cmd/setup_config.go
Add env var bindings so fleet-server/elastic-agents started in container mode can specify mTLS variables.
Missed adding container env vars in #4007, this will allow users to start fleet-server instances with mTLS support.
> Add mTLS env vars for container mode

- pkg/testing/tools/artifacts_api.go
Using the default HTTP client was incorrect.
So, we can correctly configure this request.
- Relates https://github.com/elastic/elastic-agent/pull/4276
> Use the right HTTP client

- internal/pkg/agent/install/install.go
- internal/pkg/agent/install/install_test.go
Extract the copyConcurrency parameter out of copyFiles() function allows for a simpler function signature and removes a dependency on cli.IOStreams that was used only to output an error log. The functions copyFiles() and calculateCopyConcurrency() implement a better separation of concerns.
General cleanliness of code and testability
- Closes #4284 …
> Refactor out copyConcurrency calculation in install.copyFiles()

- changelog/fragments/1708594284-Increase-timeout-for-file-removal-during-uninstall.yaml
- internal/pkg/agent/install/uninstall.go
This PR increases the timeout for removing files during `elastic-agent uninstall` and slows down retries to give time to the OS (especially windows) to release locks on the agent files.
This comes after checking the results of #4304  where we verified that no lingering agent processes were present when we still had some `access denied`  errors on executable files
This should prevent failures in our integration tests where we install/uninstall agent in quick succession.
It's also something that should make the uninstall process more reliable on a slower (especially windows) machine by giving more time to the OS to release files.
On a machine that already managed to deal with the quicker timeout (linux/darwin) there could be a negligible slowdown (most likely none) due to the slower …
> Increase waiting time and timeout for removal of agent files

- pkg/component/runtime/manager_test.go
Makes `drainErrChan` to return if the channel is closed.
As it's possible to read from a closed channel, if the channel passed to `drainErrChan` is closed it'd never exit.
`drainErrChan` would never return if received a closed channel and therefore would hang the test until it times out.
check the behaviour here: https://go.dev/play/p/WVM-P8RwJaM
- N/A …
> Avoid drainErrChan hanging forever if the channel is closed

- .buildkite/scripts/steps/integration_tests.sh
- testing/integration/upgrade_broken_package_test.go
Reverts 8.13.0 version bump related changes in https://github.com/elastic/elastic-agent/pull/4257/
> Stop pinning tests on main to 8.13.0 now that 8.14.0-SNAPSHOT exists

- dev-tools/mage/settings.go
- pkg/testing/fetcher_local.go
- pkg/testing/fixture.go
- testing/integration/upgrade_standalone_same_commit_test.go
- testing/upgradetest/upgrader.go
- testing/upgradetest/versions.go
This PR will add integration tests checking that:
- we cannot upgrade an agent with the exact same version
- we can modify the version of the agent package and the upgrade using this modified version with an agent built from the same commit
The new integration tests prove that #4193 makes it possible to have 2 agent installs from the same hash at the same time on disk (we have this situation when performing an upgrade before the end of the grace period).
It also proves that we can use the same package built from the commit to test certain upgrade flows in CI.
- ~~[ …
> Add integration test to update an agent with another built from the same commit

- pkg/testing/fixture_install.go
This PR adds a dump of the processes running on the system when an integration test fails and saves it in a JSON file available as artifact
We are often encountering strange behavior in integration tests which can be attributed to extra processes running on the system and investigation benefits from having a picture of what was running on the system close to the time of failure.
- ~~[ ] I have added an integration test or an E2E …
> Add process dump for failed integration tests

- testing/integration/proxy_url_test.go
These tests have been disabled for some time now, but the issue they are linked to was closed: https://github.com/elastic/elastic-agent/issues/3154
Let's re-enable these tests and see if they pass now.
> Re-enable the ProxyURL tests.

- pkg/testing/tools/artifacts_api.go
- pkg/testing/tools/artifacts_api_test.go
- testing/integration/upgrade_broken_package_test.go
- testing/integration/upgrade_downgrade_test.go
- testing/integration/upgrade_gpg_test.go
- testing/integration/upgrade_rollback_test.go
- testing/integration/upgrade_standalone_inprogress_test.go
- testing/integration/upgrade_standalone_retry_test.go
- testing/integration/upgrade_standalone_test.go
- testing/integration/upgrade_uninstall_test.go
- testing/upgradetest/versions.go
This PR adds retries to the Artifacts API call in the integration testing framework, as recommended by @DaveSys911.
The Artifacts API can sometimes be flaky. 
- Resolves #4345
> Integration Testing Framework: Add retries for artifacts API call

- internal/pkg/agent/application/coordinator/coordinator_unit_test.go
Adds a timeout to TestCoordinatorReportsInvalidPolicy when trying to receive from the state channel.
Even thought the `coordinator.runLoopIteration` is synchronous, the actual state update, which is sent on `stateChan`, happens on a goroutine. Therefore there is the possibility when the test tries to read the channel, the stat isn't there yet. Whereas unlikely, it has been observed and made the test flaky.
I tried running it …
> Add timeouts to TestCoordinatorReportsInvalidPolicy

- pkg/testing/runner/windows.go
This reverts commit 4509b55fd795ce241fb648e8a3d1b753aa5c3ec5.
The solution is not stable and sometimes fails. We need an alternative.
> Revert "Add Windows Defender exception for integration tests (#4357)"

- internal/pkg/agent/application/monitoring/v1_monitor.go
https://github.com/elastic/elastic-agent/pull/4150 added some debug lines that I put in while I was tinkering with the monitoring code. This removes them.
The lines shouldn't be there.
> Remove accidental debug lines

- internal/pkg/agent/application/actions/handlers/handler_action_unenroll.go
- internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
- internal/pkg/agent/application/managed_mode.go
- internal/pkg/agent/cmd/run.go
- internal/pkg/agent/storage/store/action_store.go
- internal/pkg/agent/storage/store/state_store.go
- internal/pkg/agent/storage/store/state_store_test.go
- internal/pkg/config/operations/inspector.go
- internal/pkg/fleetapi/action.go
- internal/pkg/queue/actionqueue.go
- internal/pkg/queue/actionqueue_test.go
It refactors the state store to:
- Have an interface that better reflects what it actually does
- methods do not return a slice of action when only 1 action is involved
- action queue only accepts ScheduledAction
- Add a `Version` field to the state store state
- Test for saving 2 actions in the queue uses 2 upgrade actions as it's the only scheduled action so far.
So the state store API reflects its actual usage and purpose.
- Relates #3912 
- How are we …
> Refactor state store

- .buildkite/scripts/steps/integration_tests.sh
8.12.3-SNAPSHOT now exists, stop pinning to 8.12.2.
> [8.12] Remove integration test package version override

- specs/endpoint-security.spec.yml
`go-sysinfo` cannot read the underlaying native architecture on older Windows OS, before `IsWow64Process2` API was introduced. https://github.com/elastic/go-sysinfo/pull/201
We treat this as an unknown architecture, rather that an error. Code depending on the native architecture has to account for the unknown.
Due to the bug Elastic Defend cannot be installed on Windows 2016, AMD64.
Install Agent on Windows Server 2016, AMD64. Enroll Agent to a policy with Elastic Defend.
- Closes https://github.com/elastic/elastic-agent/issues/4395
- ...
> update prevention condition to allow install if runtime cannot discover the native architecture

- .buildkite/scripts/steps/integration_tests.sh
- dev-tools/mage/pkg.go
- pkg/testing/define/define.go
- pkg/testing/fetch_test.go
- pkg/testing/fetcher.go
- pkg/testing/fetcher_artifact.go
- pkg/testing/fetcher_artifact_test.go
- pkg/testing/fetcher_http.go
- pkg/testing/fetcher_http_test.go
- pkg/testing/fetcher_local.go
- pkg/testing/fetcher_local_test.go
- pkg/testing/fixture.go
- pkg/testing/fixture_install.go
- pkg/testing/runner/debian.go
- pkg/testing/runner/runner.go
- pkg/testing/runner/windows.go
- testing/integration/groups_test.go
- testing/integration/logs_ingestion_test.go
- testing/integration/upgrade_fleet_test.go
Add an integration test that installs elastic-agent via the DEB package and makes sure that logs are sent to Elasticsearch.
Need to test that DEB packages work.
```
mage integration:single TestDebLogIngestFleetManaged
```
- Relates #4086
- ...
> add a DEB integration test

- pkg/component/runtime/manager.go
While working on the agent I noticed that the gRPC server shutdown sequence is not working as expected, the 
```m.serverLoop``` is executed as a go routine within go routine. Thus the ```defer wgServer.Done()``` is called right away without waiting for the server loop to exit. 
So when the shutdown sequence is called at:
https://github.com/elastic/elastic-agent/blame/main/pkg/component/runtime/manager.go#L244
the ```wgServer.Wait()``` doesn't wait because it is already ```wgServer.Done()```.
This change seems only went in into 8.12. 
https://github.com/elastic/elastic-agent/commit/112f61896951f738c98f0a46c6df4160d31b718f#diff-ca07503cdc90a78b407b2bbf402f63604226ce4b1ec042a58ceb5f79bd325012R226
Fixed grpc server shutdown sequence.
Regression testing.
> Fix GRPC server shutdown sequence

- changelog/fragments/1710153529-Add-CPU-profile-collection-to-diagnostics-action-handler.yaml
- internal/pkg/agent/application/actions/handlers/handler_action_diagnostics.go
- internal/pkg/agent/application/actions/handlers/handler_action_diagnostics_test.go
- internal/pkg/diagnostics/diagnostics.go
- internal/pkg/fleetapi/action.go
- internal/pkg/fleetapi/action_test.go
- pkg/control/v2/server/server.go
Add the optional CPU profile collection to the diagnostic action handler.
CPU profiles will be collected if the REQUEST_DIAGNOSTICS action has the
optional additional_metrics parameter list contains "CPU".
Will make diagnostics requested through fleet feature-complete (compared to cli options)
Changes have been tested with an e2e workflow, see https://github.com/elastic/fleet-server/pull/3333#issuecomment-1988924338
- Closes #3491
> Add CPU profile collection to diagnostics handler

- internal/pkg/agent/cmd/install.go
- internal/pkg/agent/cmd/uninstall.go
- pkg/testing/fixture_install.go
Fixes a typo and adjust a comment
This pull request serves to rectify a minor typographical error and adjust a comment within the codebase. By fixing this typo, we are enhancing the overall readability and professionalism of our code. 
Maintaining high standards of code quality is essential, even in seemingly minor matters, as it reflects our commitment to excellence. 
Additionally, accurate comments facilitate better collaboration among team members and ensure that our documentation remains precise and reliable. By promptly addressing small issues like typos, we streamline the code review process, allowing reviewers to focus on more substantial aspects of the changes. 
This proactive approach demonstrates our dedication to continuous improvement and upholding the integrity of our …
> Fix typo and adjust comment

- internal/pkg/agent/application/upgrade/upgrade.go
- internal/pkg/agent/application/upgrade/upgrade_test.go
This PR changes the way that timeouts are triggered on unit test `TestWaitForWatcher`: instead of relying on a simple `context.WithTimeout` as we do in production code, we intercept the context creation, we assert that it's called with the correct arguments but we return a context that we cancel manually from the test.
This should make the unit tests more reliable in case we run on slow agents during CI (a slow Mac OS agent has been the cause for most of the false positives we had from these tests)
- ~~[ ] I have added an entry in `./changelog/fragments` using the …
> Fix  timing on WaitForWatcher unit tests by making context expire manually

- .github/workflows/bump-agent-versions.yml
Due to permissions of the GITHUB_TOKEN the list of teams is not available to the workflow. So, it cannot assign a team for review.
Failure sample https://github.com/elastic/elastic-agent/actions/runs/8257409021/job/22587904612
> Remove reviewers from the update agent versions automation

- changelog/fragments/1709824109-k8s-secret-provider-trigger-signal.yaml
- internal/pkg/composable/providers/kubernetessecrets/kubernetes_secrets.go
- internal/pkg/composable/providers/kubernetessecrets/kubernetes_secrets_test.go
If the secrets in the cache get updated, then we notify the agent.
See issue https://github.com/elastic/elastic-agent/issues/4168 and the comments there.
Check the README file in the root directory to see how to build your own custom image and loaded to kind cluster.
<details>
<summary>Example secret.</summary>
```yaml
apiVersion: v1
kind: Secret
metadata:
name: my-secret
data:
extra: bXktc2VjcmV0LW1lc3NhZ2UK
```
</details>
<details>
<summary>Example input that you can add to EA standalone using the secret.</summary>
```yaml
- id: kubernetes-node-metrics
type: kubernetes/metrics
meta:
package:
name: kubernetes
version: 1.52.0
data_stream:
namespace: default
streams:
- data_stream:
dataset: kubernetes.proxy
type: metrics
metricsets:
- proxy
hosts:
- 'localhost:10249' …
```
> [Kubernetes secret provider] Send signal to agent if cache is updated

- .buildkite/scripts/steps/dra-publish.sh
- dev-tools/mage/manifest/manifest.go
It fixes a bug that was made in this PR: https://github.com/elastic/elastic-agent/pull/4222
The bug is that I didn't account for the `-SNAPSHOT` prerelease suffix in parsing the versions in the manifests.
For the Independent Agent Release, we want to leave off the `+buildYYYYMMDDHHMM` suffix when pulling previously-release artifacts that don't have that suffix.
The fix is to use the `Version.VersionWithPrerelease()` value, which will include any prerelease value, which starts with `-`.  The `+buildYYYYMMDDHHMM` is a `metadata` value in semver, so it should never be part of the `VersionWithPrerelease()` value.
It fixes a bug where SNAPSHOT versions were not downloading the proper artifacts since the versions were `8.14.0-SNAPSHOT` and not just `8.14.0`.
- 
- How are we going to support …
> [main] Bugfix for Independent Agent version parsing

- changelog/fragments/1710179479-Enable---unprivileged-on-Mac-OS.yaml
- internal/pkg/agent/application/application.go
- internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
- internal/pkg/agent/application/info/agent_id.go
- internal/pkg/agent/application/secret/secret.go
- internal/pkg/agent/cmd/enroll_cmd.go
- internal/pkg/agent/cmd/enroll_cmd_test.go
- internal/pkg/agent/cmd/inspect.go
- internal/pkg/agent/cmd/install.go
- internal/pkg/agent/cmd/run.go
- internal/pkg/agent/cmd/uninstall.go
- internal/pkg/agent/install/install.go
- internal/pkg/agent/install/uninstall.go
- internal/pkg/agent/install/uninstall_test.go
- internal/pkg/agent/migration/migrate_config.go
- internal/pkg/agent/migration/migrate_config_test.go
- internal/pkg/agent/storage/disk_store.go
- internal/pkg/agent/storage/encrypted_disk_storage_windows_linux_test.go
- internal/pkg/agent/storage/encrypted_disk_store.go
- internal/pkg/agent/storage/encrypted_disk_store_test.go
- internal/pkg/agent/storage/storage_test.go
- internal/pkg/agent/storage/store/action_store_test.go
- internal/pkg/agent/storage/store/state_store.go
- internal/pkg/agent/storage/store/state_store_test.go
- internal/pkg/config/operations/inspector.go
This PR allows running elastic-agent (either installed or just extracted from the package) as an unprivileged user, using a file-based vault as fallback instead of the keychain-based one.
When creating an EncryptedDiskStore, we can specify an `unprivileged` flag which will instantiate the file-based vault on Mac OS (the default value of such flag is defined as whether elastic-agent is running with administrative rights).
In most cases, such default value is enough to choose the correct vault implementation: the exception is `elastic-agent uninstall` command where a specific check for a file vault containing the agent secret has been added.
The additional check during uninstall is necessary since the command needs to run with administrative rights for both privileged and unprivileged …
> Enable unprivileged on macos

- .github/workflows/bump-agent-versions.yml
So, we don't have to set them manually.
> Add more labels to the bump-agent-versions.yml automation

- testing/integration/container_cmd_test.go
- testing/integration/delay_enroll_test.go
- testing/integration/logs_ingestion_test.go
Otherwise we have name collisions and errors from the Fleet server.
- Fixes https://github.com/elastic/elastic-agent/issues/4393
> Make policy names unique in integration tests

- internal/pkg/core/backoff/backoff_test.go
If the initial wait is short it's possible that `time.After` unblocks faster than the channel gets closed. Which makes this test to fail.
- Fixes https://github.com/elastic/elastic-agent/issues/4415
> Give TestCloseChannel more time to close the channel

- internal/pkg/agent/application/upgrade/upgrade_test.go
Refactor TestWaitForWatcher removing timeouts altogether. 
Context canceling is now done with an explicit call to a `context.CancelFunc`. This should help with timing issue when the test is running on a very slow machine.
TestWaitForWatcher should no longer be flaky
- Closes #4385
- How are we going to measure its …
> Optionally cancel context in TestWaitForWatcher to test timeouts

- .buildkite/scripts/steps/integration_tests.sh
- dev-tools/mage/pkg.go
- pkg/testing/define/define.go
- pkg/testing/fetch_test.go
- pkg/testing/fetcher.go
- pkg/testing/fetcher_artifact.go
- pkg/testing/fetcher_artifact_test.go
- pkg/testing/fetcher_http.go
- pkg/testing/fetcher_http_test.go
- pkg/testing/fetcher_local.go
- pkg/testing/fetcher_local_test.go
- pkg/testing/fixture.go
- pkg/testing/fixture_install.go
- pkg/testing/runner/debian.go
- pkg/testing/runner/runner.go
- pkg/testing/runner/windows.go
- testing/integration/groups_test.go
- testing/integration/logs_ingestion_test.go
- testing/integration/upgrade_fleet_test.go
Add an integration test that installs elastic-agent via the DEB package and makes sure that logs are sent to Elasticsearch.
This is a retry of #4301 with what should be a fix for the serverless builds.
Need to test that DEB packages work.
```
mage integration:single TestDebLogIngestFleetManaged
```
- Relates #4086
- Relates #4301
- ...
> integration deb rpm

- .buildkite/pipeline.yml
The tests started failing. Disabling the tests while the failures are being investigated.
Related to https://github.com/elastic/elastic-agent/issues/4447
> Temporary skip `Extended runtime leak tests`

- dev-tools/packaging/templates/darwin/elastic-agent.tmpl
Fix syntax in compatibility script for MacOS originally introduced in #1392 and modified for #4193. Modification introduced in #4193 contains a syntax error that this PR fixes
Upgrade from elastic-agent < 8.5.0 needs this script to correct the target for link `/Library/Elastic/Agent/elastic-agent` to the actual elastic-agent binary
- ~~[ ] I have added …
> Fix MacOS compatibility script syntax

- internal/pkg/agent/application/coordinator/coordinator_unit_test.go
Fixes flakyness of `TestCoordinatorReportsInvalidPolicy` by increasing the state change timeout, failing fast and having better error messages and printing the coordinator logs if the test fails.
The test is flaky
- N/A
- Closes #4117 
- How are …
> Fix flaky TestCoordinatorReportsInvalidPolicy

- pkg/testing/fixture.go
- pkg/testing/fixture_install.go
- pkg/testing/ogc/supported.go
- pkg/testing/runner/debian.go
- pkg/testing/runner/linux.go
- pkg/testing/runner/sles.go
- pkg/testing/runner/supported.go
- pkg/testing/runner/supported_test.go
- testing/integration/groups_test.go
- testing/integration/logs_ingestion_test.go
Adds Integration test that uses SLES 15 AMD to test fleet managed elastic-agent installed via RPM.
Only AMD was added because at the moment ogc doesn't support SLES ARM on GCP.  Also looked at implementing https://github.com/elastic/elastic-agent/pull/4301#discussion_r1516304403 This was skipped because adding a slice of strings (for supported package formats) to the OS struct broke comparison of OS structs.  I think this is still worth doing, just in a separate PR because it is likely to change a fair number of things.
Need to test our RPM builds
```
mage integration:single TestRpmLogIngestFleetManaged
```
- Relates #4086
- What are the metrics I should take …
> add integration test for install via RPM on SLES

- magefile.go
The top level context for integration tests comes from mage, which doesn't set a default timeout unless you give it one on the command line, which we don't do.
Detect when the timeout wasn't set, and force a reasonable default. Hopefully this prevents the tests from running indefinitely when the failure is in the setup and provisioning stage.
- Relates https://github.com/elastic/elastic-agent/issues/4475
> Ensure integration test setup has a timeout.

- magefile.go
- pkg/testing/runner/config.go
- pkg/testing/runner/runner.go
add TEST_PACKAGES environment variable for integration tests
It allows to select which packages the integration test will copy to the test runner
Run an integration tests with on;y the selected agent package built. The test should run
```
AGENT_KEEP_INSTALLED=true INSTANCE_PROVISIONER="multipass" SNAPSHOT=true TEST_PLATFORMS="linux/amd64" TEST_PACKAGES="tar.gz" mage …
```
> Add TEST_PACKAGES environment variable for integration tests

- NOTICE.txt
- changelog/fragments/1710868294-ucfg-parser-fix.yaml
- go.mod
- go.sum
- internal/pkg/config/config.go
- internal/pkg/config/config_test.go
This is the final round of fixes for https://github.com/elastic/go-ucfg/issues/196. This imports the `IgnoreCommas` option added to go-ucfg and places it as a default option.
I'm a little paranoid about this, and open to alternate suggestions as for how to fix this. I'm fairly sure that the only legitimate use case for the "original" behavior is for parsing command line args (probably like `-E list,of,things`), and I don't see anywhere in agent where this is being used. The alternative fix for this would be to make the `IgnoreCommas` option opt-in, but then we have to play whack-a-mole with the dozens of instances of `NewConfigFrom()` and `ToMapStr()` instead.
Right now, the config setup process is breaking under certain conditions where a user passes a config that looks like `'a', 'b'`.
> Use IgnoreCommas in default config options

- internal/pkg/agent/cmd/install.go
- internal/pkg/agent/cmd/uninstall.go
- pkg/core/logger/logger.go
- pkg/core/logger/logger_test.go
It adds an in memory logger to the `pkg/core/logger` package and replaces the observer used during install and uninstall by the new in memory logger
The zap observer isn't intended to be logged, it's an feature designed for tests and when printed without any processing it is just raw Go structs, making it hard to read and understand the logs.
Those logs are printed on install or uninstall failures, where the clarity of the logs are rather important for us or the user trying to understand what went wrong.
- ~~[ ] I have added an entry in `./changelog/fragments` …
> Add in-memory logger and use it on install and uninstall

- .buildkite/scripts/steps/integration_tests.sh
- testing/integration/upgrade_broken_package_test.go
Undoes the changes from https://github.com/elastic/elastic-agent/pull/4504/. Can be merged once the first 8.13.2 snapshot is produced.
> Remove 8.13.1 version pinning.

- .github/workflows/bump-agent-versions.sh
- .github/workflows/bump-agent-versions.yml
When the script is in the multiline YAML it breaks the desired formatting of the commit message.
Also editing this script separately is a better developer experience.
> Extract the bump-agent-versions workflow into a script

- .github/workflows/bump-agent-versions.sh
- .github/workflows/bump-agent-versions.yml
This should solve permission issues with triggering buildkite builds and will notify our team about failed and successful attempts to update the version file.
> Use pre-defined Github actions, enable Slack notifications

- pkg/testing/fixture_install.go
Cannot use the `file` variable if we failed to create/open the file.
Appeared in https://buildkite.com/elastic/elastic-agent/builds/8127#018eae91-5ab5-4b08-94a3-8bcde2881e0c
> Fix panic when handling error in process dumping

- changelog/fragments/1712305270-fix-upgrade-cmd-fail-when-disconnected.yaml
- internal/pkg/agent/cmd/upgrade.go
- internal/pkg/agent/cmd/upgrade_test.go
- testing/upgradetest/upgrader.go
The upgrade CLI command creates a client, connects to the Elastic Agent server and triggers the upgrade process which is supposed to shut down the agent and start the upgrade. Sometimes, this happens before the client gets a successful response and the upgrade command returns an error code although the upgrade succeeded.
This change checks if the connection was interrupted and treats it as a successful result instead of error.
This race condition occasionally fails our integration tests.
- Fixes https://github.com/elastic/elastic-agent/issues/3890
> Fix failing upgrade command when gRPC server interrupts connection

- changelog/fragments/1711474205-Reduce-false-positives-in-logging-an-API-switch-request-from-Fleet-server.yaml
- internal/pkg/fleetapi/client/client_test.go
- internal/pkg/remote/client.go
This PR adds a check before logging a `400 - Bad request` status code in Fleet response as a request to change `Elastic-Api-Version`.
Before this change any response indicating a bad request, containing an Elastic-Api-Version would be considered (and logged) as a switch version request.
With this change we log only if Fleet answered with an api version that is *different* from what was sent in the request.
This part of the code did not influence the response processing even before this change and the error message extraction is left to the command layer (CheckinCmd, EnrollCmd, AckCmd).
This should reduce the noise in the logs and avoid misleading during investigation of issues by indicating a request to switch version when in reality there was none.
- ~~[ ] I have made corresponding …
> Check if the Fleet API version is different between request and response to detect an api version switch request

- .github/workflows/bump-agent-versions.sh
- .github/workflows/bump-agent-versions.yml
Currently, the Slack message is sent on every successful job run which is incorrect. The message should be sent only when a new PR is created.
> Send Slack notifications only when versions file PR is created

- testing/upgradetest/upgrader.go
Older agent versions don't properly handle an interrupted connection during the upgrade. So, we need to handle it in tests.
The check was introduced in 4ad7824108ef29ec911efddb7f5f847a8c186ae2 however it checked a wrong string, it was supposed to check the output of the command not the actual error string.
Closes https://github.com/elastic/elastic-agent/issues/3890
> Do not fail tests when interrupted connection during upgrade

- internal/pkg/agent/application/upgrade/step_download_test.go
The number of attempts cannot be calculated as
`testCaseSettings.Timeout / testCaseSettings.RetrySleepInitDuration` since the exponential backoff is using
`testCaseSettings.RetrySleepInitDuration` only as an `InitialInterval` and then increases the next delay using multipliers and randomized values.
However, we can tell approximately how many attempts should fit in the timeout.
I validated this by running the test 1000 times and it never failed.
Closes https://github.com/elastic/elastic-agent/issues/4336
> Make the logs test assertion in upgrade retries deterministic

- changelog/fragments/1712324173-improve-enroll-stability.yaml
- internal/pkg/agent/cmd/enroll_cmd.go
- internal/pkg/agent/cmd/enroll_cmd_test.go
- internal/pkg/fleetapi/enroll_cmd.go
- internal/pkg/fleetapi/enroll_cmd_test.go
* Fixed incorrect backoff configuration that could cause every retry iteration to last 10 minutes
* Add support for temporary/recoverable server errors when doing requests to Fleet
We have our integration tests failing without these improvements that means our customers are likely experiencing this too.
- Closes https://github.com/elastic/elastic-agent/issues/4513
> Make enroll command more stable

- catalog-info.yaml
The `branch_configuration` property needs to be under the `spec` block, otherwise terrazzo refuses to parse the config because it's invalid.
Related: https://github.com/elastic/elastic-agent/pull/4550
> fix branch_configuration location in catalog-info

- internal/pkg/agent/application/actions/handlers/handler_action_policy_change.go
- internal/pkg/agent/application/actions/handlers/handler_action_policy_change_test.go
Refactor action policy handler splitting validation, persistence and runtime update of the new configuration
This is a prerequisite for implementing #2851
- 
- ...
> Refactor action policy change handler

- .github/workflows/bump-agent-versions.yml
When an update for the versions file is created, the automation should send a Slack notification with the link to the PR. Due to the typo in the variable name, no PR link was rendered.
> Fix typo in the variable name when sending a Slack message

- .buildkite/scripts/steps/integration_tests.sh
- testing/integration/upgrade_broken_package_test.go
Revert the 8.13.2 version pinning done as part of https://github.com/elastic/elastic-agent/pull/4546.
> Revert version pinning in CI from 8.13.2 release

- .buildkite/hooks/pre-exit
Hopefully this works and makes it so we can't forget if we add another serverless step.
- Relates https://github.com/elastic/ingest-dev/issues/3164
> Unconditionally cleanup severless projects in buildkite pre-exit hook

- _meta/config/common.p2.yml.tmpl
- _meta/config/common.reference.p2.yml.tmpl
- _meta/config/elastic-agent.docker.yml.tmpl
- _meta/elastic-agent.yml
- changelog/fragments/1711653910-add-liveness-endpoint.yaml
- elastic-agent.docker.yml
- elastic-agent.reference.yml
- elastic-agent.yml
- internal/pkg/agent/application/coordinator/coordinator.go
- internal/pkg/agent/application/coordinator/coordinator_unit_test.go
- internal/pkg/agent/application/monitoring/handler.go
- internal/pkg/agent/application/monitoring/liveness.go
- internal/pkg/agent/application/monitoring/liveness_test.go
- internal/pkg/agent/application/monitoring/process.go
- internal/pkg/agent/application/monitoring/processes.go
- internal/pkg/agent/application/monitoring/reload/reload.go
- internal/pkg/agent/application/monitoring/reload/reload_test.go
- internal/pkg/agent/application/monitoring/server.go
- internal/pkg/agent/application/monitoring/server_test.go
- internal/pkg/agent/cmd/run.go
- internal/pkg/core/monitoring/config/config.go
- internal/pkg/core/monitoring/config/config_test.go
- testing/integration/monitoring_probe_preserve_text_cfg_test.go
- testing/integration/monitoring_probe_reload_test.go
Closes https://github.com/elastic/elastic-agent/issues/4582
This reverts the revert in https://github.com/elastic/elastic-agent/pull/4583 and adds some extra logic so that if the HTTP monitoring server is enabled, and we get a config reload that _does not explicitly set it to disabled_ we keep it enabled.
This also adds a ton of tests, because now I'm paranoid.
> Fix liveness reload config handling

- changelog/fragments/1713946896-remove-mandatory-ns-node-permissions.yaml
- internal/pkg/composable/providers/kubernetes/pod.go
- internal/pkg/composable/providers/kubernetes/pod_test.go
- internal/pkg/composable/providers/kubernetes/service.go
- internal/pkg/composable/providers/kubernetes/service_test.go
Check AddResourceMetadata and hints before starting namespace and node watchers.
This PR is to sync beats with the agent. Change in beats was done in this [PR](https://github.com/elastic/beats/pull/38762), and issue is[ this one](https://github.com/elastic/beats/issues/37179).
See [issue](https://github.com/elastic/beats/issues/37179).
Closes https://github.com/elastic/beats/issues/37179.
> [Kubernetes] Check AddResourceMetadata and hints before starting namespace and node watchers

- testing/integration/logs_ingestion_test.go
Add add_cloud_metadata processor error to exclusion list
It fixes a flaky test: https://github.com/elastic/elastic-agent/issues/3741
- Closes https://github.com/elastic/elastic-agent/issues/3741
~~## Logs~~
> Add add_cloud_metadata processor error to exclusion list

- internal/pkg/agent/application/upgrade/step_download_test.go
Seems like on very slow machines this test still fails, this new timeout should make sure it does not happen.
Closes https://github.com/elastic/elastic-agent/issues/4336
> Increase the download timeout to make the test more stable

- .agent-versions.json
This file is used for picking agent versions in integration tests.
The file's content is based on responses from https://www.elastic.co/api/product_versions and https://snapshots.elastic.co
The current update is generated based on the following requirements:
```json
{
"UpgradeToVersion": "8.15.0",
"CurrentMajors": 1,
"PreviousMajors": 1,
"PreviousMinors": 2,
"SnapshotBranches": [
"8.14",
"8.13",
"7.17"
]
}
```
> [main][Automation] Update .agent-versions.json

- .github/PULL_REQUEST_TEMPLATE.md
Looking through the past couple of dozen PRs created by humans (as opposed to bots) in this repository, it's clear that certain sections in the PR template are never used.  This PR updates the PR template to remove those sections and reduce noise.
> Remove unused sections in PR template

- internal/pkg/agent/install/user_windows.go
Adds the `SeCreateSymbolicLinkPrivilege` to the created `elastic-agent-user` when installing in unprivileged mode.
This privilege is required on the `elastic-agent-user. With out the privilege upgrade fails to update symlinks between the current and previous versions of Elastic Agent.
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~ **integration tests**
- Closes #4646
> Fix ability for unprivileged Windows to upgrade

- .agent-versions.json
Removes `8.12.3-SNAPSHOT` from `.agent-version.json`.
`8.12.3-SNAPSHOT`  has expired and no longer exists.
> [8.14] Remove `8.12.3-SNAPSHOT` from `.agent-version.json`

- .ci/bump-golang.yml
This PR updates the `toolchain` version, if specified, in the `go.mod` file with the contents of `.go-version`.
To keep all Go version references in this repository the same.
See also: https://github.com/elastic/elastic-agent/pull/4623#discussion_r1582668435
> Keep `go.mod` toolchain version in sync with `.go-version` contents

- internal/pkg/composable/providers/agent/agent.go
- internal/pkg/composable/providers/agent/agent_test.go
Adds the `unprivileged` state to the `agent` context provider.
Allows inputs to use `${agent.unprivileged} == true` or `${agent.unprivileged} == false` to determine if an input or metricset should be ran on that specific Elastic Agent.
- ~~[ ] I have added an integration test or an E2E test~~ **(covered in unit tests)**
> Add unprivileged state to agent provider

- pkg/testing/define/define.go
- testing/integration/agent_long_running_leak_test.go
- testing/integration/apm_propagation_test.go
- testing/integration/container_cmd_test.go
- testing/integration/delay_enroll_test.go
- testing/integration/diagnostics_test.go
- testing/integration/endpoint_security_test.go
- testing/integration/fake_test.go
- testing/integration/fqdn_test.go
- testing/integration/install_privileged_test.go
- testing/integration/install_test.go
- testing/integration/logs_ingestion_test.go
- testing/integration/metrics_monitoring_test.go
- testing/integration/otel_test.go
- testing/integration/package_version_test.go
- testing/integration/proxy_url_test.go
- testing/integration/upgrade_broken_package_test.go
- testing/integration/upgrade_downgrade_test.go
- testing/integration/upgrade_fleet_test.go
- testing/integration/upgrade_gpg_test.go
- testing/integration/upgrade_rollback_test.go
- testing/integration/upgrade_standalone_inprogress_test.go
- testing/integration/upgrade_standalone_retry_test.go
- testing/integration/upgrade_standalone_same_commit_test.go
- testing/integration/upgrade_standalone_test.go
- testing/integration/upgrade_uninstall_test.go
Rename define.NewFixture to define.NewFixtureFromLocalBuild
There were two `NewFixture` functions returning the same fixture: `testing.NewFixture` and `define.NewFixture`. They basically differ on where the agent package comes from. This is rather confusing and easily lead to mistakes.
`testing.NewFixture` is the one which actually creates the fixture, whereas `define.NewFixture` is a wrapper around `testing.NewFixture` so it'll use the locally built agent artifact. Therefore `define.NewFixture` was renamed to `define.NewFixtureFromLocalBuild`, better reflecting what it does.
- ~~[ ] I have made corresponding change to the default configuration …
> Rename define.NewFixture to define.NewFixtureFromLocalBuild

- changelog/fragments/1713257367-Remove-beat-state-metricset-from-elastic-agent-monitoring.yaml
This PR patches changelog fragment for already merged PR #4579 specifying the savings coming from removal of beat state metricset
- Closes #4153
- How are we going to measure its …
> Patched changelog for PR 4579

- changelog/fragments/1714717717-Reduce-agent-logs-by-default.yaml
- docs/scripts/es/elastic-agent-logs-comparison
- docs/scripts/es/elastic-agent-logs-comparison.http
- internal/pkg/agent/application/monitoring/v1_monitor.go
- internal/pkg/agent/application/upgrade/artifact/download/composed/verifier.go
This PR drops the `Non-zero metrics after 30s...` logs before they get sent to Elasticsearch.
The goal is to reduce the amount of elastic-agent monitoring events ingested in Elasticsearch in order to reduce index disk size.
Run an elastic agent with and without this change on a deployment making a note of the start times and elastic-agent id of both.
Using the included ES script we then extract the documents ingested during those runs and store them in dedicated indices.
In my tests I ran 2 elastic agents …
> Reduce agent logs by default

- testing/integration/diagnostics_test.go
- testing/integration/fake_test.go
- testing/integration/monitoring_probe_preserve_text_cfg_test.go
- testing/integration/monitoring_probe_reload_test.go
Rename from #4562 skipped few places now tests are failing on:
```
Error: failed to determine batches: error running go test: (exit status 1), got:
testing/integration/diagnostics_test.go:161:25: undefined: define.NewFixture
testing/integration/diagnostics_test.go:210:19: undefined: define.NewFixture
testing/integration/fake_test.go:141:19: undefined: define.NewFixture
testing/integration/monitoring_probe_preserve_text_cfg_test.go:94:25: undefined: define.NewFixture
testing/integration/monitoring_probe_reload_test.go:59:25: undefined: define.NewFixture
FAIL	github.com/elastic/elastic-agent/testing/integration [build failed]
```
cc @belimawr @ycombinator
> Finish rename started in #4562

- .github/PULL_REQUEST_TEMPLATE.md
This PR adds a new section to the PR template for describing any steps users could take to mitigate disruptive changes, when a PR introduces such changes.
> Add disruptive change mitigations section to PR template

- .github/workflows/bump-agent-versions.sh
The changes made by this PR ensure that "Update .agent-versions.json" PRs ([example](https://github.com/elastic/elastic-agent/pull/4663)) created going forward will be labeled with the `Team:Elastic-Agent-Control-Plane` label.
To ensure the correct team gets pinged on the update version PRs and these PRs show up in relevant triage lists.
> [Automation] Add the `Team:Elastic-Agent-Control-Plane` label to "Update .agent-versions.json" PRs

- internal/pkg/agent/storage/store/state_store.go
- internal/pkg/config/operations/inspector.go
Pass the unprivileged flag from the uninstall command down to to the state store migration so that we select the correct encryption key in case of unprivileged install.
To make `elastic-agent uninstall` work for an elastic-agent installed as unprivileged even if an old key from a previous privileged install is present in the system keychain
Test this on MacOS only (other …
> pass unprivileged flag to store migration

- NOTICE.txt
- go.mod
- go.sum
This PR bumps up the version of the `elastic/e2e-testing` library dependency.
Elastic Agent uses the `elastic/e2e-testing` library for downloading artifacts during the packaging process. The previous version of the library only considered `404` HTTP response codes as erroneous when downloading artifacts.  This turned out to be too strict.  The new version of the library considers any HTTP response codes > 399 as errorneous.
> Bumping up `elastic/e2e-testing dependency` version

- NOTICE.txt
- changelog/fragments/1715178161-otel-mode-add-elasticsearch-exporter.yaml
- go.mod
- go.sum
- internal/pkg/otel/README.md
- internal/pkg/otel/components.go
This PR makes the [`elasticsearch` exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/elasticsearchexporter) available to users running Elastic Agent in `otel` mode.
To allow users of Elastic Agent running as as OpenTelemetry Collector to configure pipelines containing the `elasticsearchexporter`.
> Make `elasticsearchexporter` available in Agent running in OTel mode

- NOTICE.txt
- changelog/fragments/1715178093-otel-mode-add-filter-processor.yaml
- go.mod
- go.sum
- internal/pkg/otel/README.md
- internal/pkg/otel/components.go
This PR makes the [`filter` processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor) available to users running Elastic Agent in `otel` mode.
To allow users of Elastic Agent running as as OpenTelemetry Collector to configure pipelines containing the `filterprocessor`.
> Make `filterprocessor` available in Agent running in OTel mode

- magefile.go
Calling `go get` was causing `mage check` to fail with:
```
go: modules disabled by GO111MODULE=off; see 'go help modules'
Error: running "go get github.com/elastic/go-licenser@latest" failed with exit code 1
```
This commit fixes it by using `go install` instead.
It makes `mage check` work again
Run `mage check` it should succeed
- ...
> Use `go install` instead of `go get`

- README.md
Add documentation to README.md about how to package Elastic-Agent for different architectures.
It documents how to package the Elastic-Agent for different architectures.
- ...
> Document how to build for different architectures

- Makefile
The .github/workflows/golangci-lint.yml spec uses v1.55.2 for the
golangci-lint version. This commit updates the make target to use
the same version for consistency as the current version causes a
panic when running on a darwin arm64 system.
Provide a consistent local experience to CI.
> Use same version of golangci-lint in makefile as github actions

- pkg/testing/ogc/provisioner.go
It should bring stability improvements, especially for firewall object errors our CI experiences.
See https://github.com/adam-stokes/ogc/issues/28#issuecomment-2108723332
> Pin OGC to a newer release version

- internal/pkg/agent/cmd/enroll_windows.go
- internal/pkg/agent/perms/windows.go
Fixes an installation issue on Windows in privileged mode where the wrong permissions are given to the Elastic Agent installation directory.
Otherwise it would allow any non-Administrator to read/modify/delete a file in the Elastic Agent installation directory.
Fixes a disruptive user issue of invalid permissions.
1. Install without `--unprivileged` and with enrollment.
2. …
> Fix wrong permissions when installation with enrollment on Windows in privileged mode

- pkg/testing/tools/estools/elasticsearch.go
- testing/integration/logs_ingestion_test.go
This check should not use exact matching but rather "contains" for accounting for know errors since details might change.
> Make error checks in TestLogIngestionFleetManaged more resilient

- internal/pkg/agent/application/upgrade/artifact/download/http/verifier_test.go
- testing/proxytest/proxytest.go
- testing/proxytest/proxytest_test.go
This PR introduces TLS configuration for `testing/proxytest` in order to be able to configure mTLS.
No TLS, basic TLS (certificate server-side, no client auth) and mTLS (certificates for both client and server, common trusted CA) are tested via unit tests
`testing/proxytest` is going to be used to test (m)TLS proxy settings for `elastic-agent`
- Closes #4497 
- …
> Add TLS support for proxytest

- .buildkite/integration.pipeline.yml
So, we spread the load.
Also, removed the redundant `BEAT_NAME` variable.
Relates to https://github.com/elastic/elastic-agent/issues/4704
> Run integration test steps in different data centers

- changelog/fragments/1716227441-Fix-delay-enrollment-to-work-in-unprivileged-mode-on-Windows.yaml
- internal/pkg/agent/cmd/enroll_cmd.go
- testing/integration/delay_enroll_test.go
Fixes an issue where `--delay-enroll` with `--unprivileged` on Windows didn't allow the Elastic Agent to start. This is because the `FixPermissions` work was being skipped with delayed enrollment.
This also adjusts the integration tests for delay enrollment to work both on Linux and on Windows. Adds specific tests for delay enrollment with privileged and unprivileged mode.
To allow `--delay-enroll` to work with `--unprivileged` on Windows.
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~ (integration tests added)
- Closes #4678
> Fix issue with `--delay-enroll` and `--unprivileged` on Windows

- go.mod
Removes an outdated code comment on not updating OTel Collector components beyond v0.97.0. The original blocking issue has been resolved and the components have already been updated to v0.100.0 before.
Keep the code tidy!
None.
No functional changes.
> Remove outdated comment on OTel v0.97.0

- .buildkite/integration.pipeline.yml
Prefix the names of the sub-pipelines from the extended tests so that they show the relationship to the parent job in the Github checks status.
Discussed in: https://elastic.slack.com/archives/C0522G6FBNE/p1716315124665009?thread_ts=1716313001.444009&cid=C0522G6FBNE
> Elaborate on Github check names to show parent relationship

- .buildkite/scripts/steps/integration_tests.sh
- testing/integration/upgrade_broken_package_test.go
Reverts the stack version pinning done in https://github.com/elastic/elastic-agent/pull/4640/files now that 8.13.5-SNAPSHOT exists.
> [8.13] Remove pin to 8.13.4 stack version.

- changelog/fragments/1716543533-add-cloudbeat-asset-inventory-aws.yaml
- specs/cloudbeat.spec.yml
Adds AWS Asset Inventory input to cloudbeat
Cloud Security Posture team is focusing on the CDR Vision, which means we need to build an Asset Inventory. 
The Asset Inventory fetching will reside inside cloudbeat (this decision can be changed in the future). We decided to build an isolated integration for beta testing and avoid unintended side effects to existing cloudbeat inputs. Therefore we are adding a new input.
No disruptions expected.
--
- Part of https://github.com/elastic/security-team/issues/9067
> Add asset inventory as input to cloudbeat

- internal/pkg/otel/run_test.go
Fixes https://github.com/elastic/elastic-agent/issues/4814 (hopefully!)
> Increase timeout for TestStartCollector

- pkg/testing/ess/deployment.go
Improves the logic in `DeploymentIsReady` to not return `false` and the error when it gets an error back from the API. Instead it will keep retrying until the timeout.
Improve reliability of integration tests, when the cloud API returns an HTTP error or disconnects without a response (just the nature of HTTP protocol).
- Relates #4794
> Improve integration testing cloud client DeploymentIsReady.

- .buildkite/pull-requests.json
- .github/PULL_REQUEST_TEMPLATE.md
Draft PRs will not run integration tests. If you need to run them use `/test extended` trigger comment.
Introducing `skip-ci` and `skip-it` labels. 
Makes buildkite pull request builds to ignore `.ci` and `.github` directories. 
Also all `*.md` files
Made file patterns more strict by adding `^` 
Added CI cheatsheet to pull request template
Integration tests were executed 
- Closes https://github.com/elastic/elastic-agent/issues/3674
- ...
> [CI] Trigger improvements

- pkg/testing/ogc/supported.go
ARM cores are lower performance, to make it equal to our AMD64 VMs we should use higher tier instances.
> Use higher tier ARM VM for integration testing

- pkg/testing/ogc/supported.go
The current ARM hardware is experimental and very unstable, we should wait until a new stable instance type is introduced.
> Disable integration tests on ARM due to instability

- .github/workflows/bump-agent-versions.sh
- .github/workflows/bump-agent-versions.yml
The mage target now requires to be run on a release branch.
> Create a version update branch after the mage target is run

- changelog/fragments/1717185708-Stop-creating-a-zombie-process-on-each-restart.yaml
- internal/pkg/agent/application/upgrade/rollback.go
- Relates https://github.com/elastic/elastic-agent/issues/2190
Today every time the agent starts the watcher it results in a zombie process on Linux. This is because we never wait on it. There are two places where this happens:
1. As part of the upgrade process: https://github.com/elastic/elastic-agent/blob/7b81fea37ed79b26a641f9d2c28cfcd913cdb645/internal/pkg/agent/application/upgrade/upgrade.go#L302-L308
2. At startup in case we are starting as a result of an upgrade: https://github.com/elastic/elastic-agent/blob/7b81fea37ed79b26a641f9d2c28cfcd913cdb645/internal/pkg/agent/cmd/run.go#L243-L247
I don't believe the first case is addressed by this change. This is because the agent process re-execs itself before the `Wait` can complete. I still have to do some experimenting to see exactly …
> Wait on the watcher at startup instead of just releasing resources associated with it

- pkg/testing/multipass/provisioner.go
- pkg/testing/ogc/supported.go
- pkg/testing/runner/supported.go
- pkg/testing/runner/supported_test.go
Adds the latest Ubuntu LTS release `24.04` to the integration testing framework.
Ensures that the Elastic Agent stays working on the latest release of Ubuntu.
None.
`mage integration:test` will now use Ubuntu 24.04 as the default
- Closes #4830
> Add Ubuntu 24.04 to integration testing.

- changelog/fragments/1716490302-Load-fleet.ssl.certificate_authorities-from-agent-policy.yaml
- changelog/fragments/1716490372-Load-fleet.ssl.certificate-and-fleet.ssl.key-from-agent-policy.yaml
- internal/pkg/agent/application/actions/handlers/handler_action_policy_change.go
- internal/pkg/agent/application/actions/handlers/handler_action_policy_change_test.go
- internal/pkg/agent/application/dispatcher/dispatcher.go
- internal/pkg/remote/config.go
- pkg/testing/fixture_install.go
- testing/fleetservertest/checkin.go
- testing/fleetservertest/fleetserver_test.go
- testing/integration/proxy_url_test.go
- testing/proxytest/proxytest.go
This PR implements reading and applying TLS configuration for Fleet client  using CA, certificate and key included in Fleet policy.
This PR:
- includes unit tests ported from #4398, 
- reimplements the solution of #4398 to adapt it to the new structure of internal/pkg/agent/application/actions/handlers/handler_action_policy_change.go
- modifies mock fleet server to support SSL configuration
- Add integration tests for both TLS and mTLS usecases using custom CAs
~~Note to reviewers: refactor of ProxyURL integration tests has been moved to PR #4813 , so for initial review you can have a look at [this set of commits](https://github.com/elastic/elastic-agent/pull/4770/files/cae577b7aa3ff22a4d9fbaeaff57ba5b71c088e1..bd9fe64bd86252f39f7b07f2354164fe85fbf860) or wait till PR #4813 is merged and …
> Apply mTLS config from policy

- internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
- internal/pkg/agent/application/info/agent_metadata_test.go
- pkg/testing/fixture.go
- testing/integration/log_level_test.go
This PR fixes the log level reported by Agent when checking in with Fleet. 
Since merging #3090, a managed elastic-agent has now 2 sources of configuration for log level:
1. agent-specific log level setting saved in `fleet.enc`
2. log level setting in the Fleet policy itself (with lower priority than option 1.)
Before this change, the agent was sending only the information coming from 1. (with a default value equal to `info`), now we send back to Fleet the actual log level specified in coordinator state (which is the end result of evaluating the multiple settings with the correct priority)
There has also been a modification of the integration test related to the feature with additional assertions on log level received by Fleet.
The log level is now correctly displayed in Fleet UI …
> Fix log level value reported by Agent to Fleet

- changelog/fragments/1718268915-increase-remove-timeout.yaml
- internal/pkg/agent/install/uninstall.go
On particularly slow machines 30 seconds might be still not enough to release the agent binary, so we're able to remove it on uninstall. This change doubles the timeout to 60 seconds.
- Closes https://github.com/elastic/elastic-agent/issues/4164
> Increase removal timeout when uninstall

- NOTICE.txt
- go.mod
- go.sum
- internal/pkg/agent/application/upgrade/service_update_linux.go
- internal/pkg/agent/install/install.go
- internal/pkg/agent/install/installed.go
- internal/pkg/agent/install/svc.go
- internal/pkg/agent/install/switch.go
- internal/pkg/agent/install/uninstall.go
- pkg/component/runtime/service.go
- testing/integration/upgrade_rollback_test.go
Reverts elastic/elastic-agent#4859
See https://github.com/elastic/elastic-agent/pull/4859#issuecomment-2165526867
> Revert "Repoint kardianos/service to fork elastic/kardianos-service"

- internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
- internal/pkg/agent/application/info/agent_metadata_test.go
- testing/integration/log_level_test.go
This reverts commit 2b2e8d0672b24e84753f434223f0a61c0fe56300.
This PR reverts the revert of PR #4838.
The only difference compared to the original PR is the removal of agent client initialization in `(f *Fixture) PrepareAgentCommand` which was no longer needed once integration test `TestSetLogLevelFleetManaged` used `install` instead of `run` subcommand to run and enroll the agent
We still want to send the correct log level in use by elastic agent to Fleet during check-in
- ~~[ ] I have added tests that prove …
> Revert "Revert "Fix log level value reported by Agent to Fleet (#4838)" (#4938)"

- pkg/testing/ess/statful_provisioner.go
- pkg/testing/ogc/provisioner.go
This PR fixes the `org` and `team` tag values for integration tests cloud resources
It is important in order to link a cloud resource to a team owning such resource
- …
> Set correct org and team tags to integration tests resources

- _meta/config/common.p2.yml.tmpl
- _meta/config/common.reference.p2.yml.tmpl
- _meta/config/elastic-agent.docker.yml.tmpl
- changelog/fragments/1718818524-support-monitoring-metrics-interval.yaml
- elastic-agent.docker.yml
- elastic-agent.reference.yml
- elastic-agent.yml
- internal/pkg/agent/application/coordinator/diagnostics_test.go
- internal/pkg/agent/application/monitoring/v1_monitor.go
- internal/pkg/agent/application/monitoring/v1_monitor_test.go
- internal/pkg/core/monitoring/config/config.go
This PR introduces `agent.monitoring.metrics_period` field
I consider this PR important as it allows each user to control the sampling period of monitoring metrics according to them needs
None
Spawn an agent with setting the config `agent.monitoring.metrics_period` 
- Closes https://github.com/elastic/ingest-dev/issues/2680
> Introduce agent.monitoring.metrics_period

- dev-tools/packaging/templates/ironbank/Dockerfile.tmpl
Update Elastic Agent docker image to use ubi 9.4 within the Ironbank context
> Update Elastic Agent Ironbank Docker image to use ubi 9.4

- NOTICE.txt
- go.mod
- go.sum
- internal/pkg/otel/README.md
- internal/pkg/otel/components.go
- internal/pkg/otel/templates/README.md.tmpl
- internal/pkg/otel/testdata/all-components.yml
- magefile.go
Added 
- `httpcheckreceiver`
- `otlphttpexporter` 
- `spanmetricsconnector`
Modified README file generation to include connectors as well
> Added `httpcheckreceiver`, `otlphttpexporter` and `spanmetricsconnector`

- catalog-info.yaml
Creates a buildkite resource for integration testing matrix pipeline that will run integration tests for all supported platforms.
The pipeline will be triggered every Thursday at 00:00. Or manually from buildkite. The pipeline won't be triggered by any github events.
We need to test elastic-agent on all supported platforms
-
- ...
> [CI] Integration tests matrix pipeline resource

- pkg/component/runtime/runtime_comm.go
closes https://github.com/elastic/elastic-agent/issues/4974
Once again forgot to remove one of me debug lines before I merged something. This removes a superfluous `Infof()` call.
> Remove unneeded `Infof` line in runtime

- changelog/fragments/1718953844-fix-namespace-filter-on-watchers.yaml
- internal/pkg/composable/providers/kubernetes/pod.go
- internal/pkg/composable/providers/kubernetes/service.go
The watchers now take into account the `namespace` specified by the user.
1. Create setup:
```bash
> kind create cluster
> elastic-package stack up -d -v --version=8.15.0-SNAPSHOT
> docker network connect elastic-package-stack_default kind-control-plane
```
2. Build elastic-agent:
```bash
> EXTERNAL=true DEV=true PLATFORMS=linux/amd64 SNAPSHOT=TRUE PACKAGES=docker mage package
```
3. Build docker image:
```bash
> cd build/package/elastic-agent/elastic-agent-linux-amd64.docker/docker-build
> docker build -t custom-agent-image .
```
4. Load this image in your kind cluster:
```bash
> kind load docker-image custom-agent-image:latest
```
5. Deploy elastic agent managed with that image, associate it to a policy with Kubernetes integration with pod data stream enabled. Filter by namespace. …
> [Kubernetes Provider] Fix namespace filter on pod and service watchers

- .buildkite/pipeline.yml
Updates the K8s version being used by elastic package.
Relates to https://github.com/elastic/observability-dev/issues/3068
> Update K8s version to 1.30

- pkg/testing/fetcher_artifact.go
Adds retry logic to the `DownloadPackage` function that is used in the integration testing framework.
Reduce test failures due to failure to download an artifact.
- Closes #5009
> Add retry to DownloadPackage

- changelog/fragments/1719934992-Fix-indefinite-memory-and-CPU-consumption-when-waiting-fleet-to-be-ready.yaml
- internal/pkg/agent/cmd/enroll_cmd.go
- internal/pkg/agent/cmd/enroll_cmd_test.go
- internal/pkg/core/backoff/exponential.go
Fixes the wait for Fleet Server to be ready 
When waiting for Fleet Server to start, the Elastic Agent does not account for the timeout when waiting for Fleet Server to be ready.
Currently, when the timeout is reached, the operation isn't interrupted and the goroutine waiting for Fleet Server to be ready gets stuck in an infinite loop without any delay between iterations. It continually prints a log like:
`{"log.level":"info","@timestamp":"2024-07-02T13:18:59.354Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":812},"message":"Waiting for Elastic Agent to start: rpc error: code = Canceled desc = context canceled","ecs.version":"1.6.0"}
`.
This causes a spike in memory and CPU consumption until the agent is killed by the OS, potentially jeopardising the normal operation of the …
> Fix indefinite memory and CPU consumption when waiting fleet to be ready

- changelog/fragments/1720195309-add-agentbeat-capabilities.yaml
- dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Since we transitioned to `agentbeat` we now need to use `setcap` on a different binary.
The capabilities were not set correctly before this change.
```sh
PLATFORMS=linux/amd64 PACKAGES=docker mage package
PLATFORMS=linux/arm64 PACKAGES=docker mage package
```
> Fix wrong binary for setting capabilities

- changelog/fragments/1720209553-reduce-docker-size.yaml
- dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
This significantly reduces the size of the image.
```sh
PLATFORMS=linux/arm64 PACKAGES=docker mage package
```
Before this change:
```
REPOSITORY                                       TAG          IMAGE ID       CREATED         SIZE
docker.elastic.co/beats/elastic-agent-complete   8.15.0       1452af5ad002   4 minutes ago   2.36GB
docker.elastic.co/beats-ci/elastic-agent-cloud   8.15.0       fa0bc74c04ce   6 minutes ago   1.2GB
docker.elastic.co/beats/elastic-agent            8.15.0       cb118fa60f56   6 minutes ago   852MB
docker.elastic.co/beats/elastic-agent-ubi        8.15.0       0f3615fb5329   6 minutes ago   916MB
docker.elastic.co/beats-dev/golang-crossbuild    1.22.5-arm   0805c9714ddf   27 hours ago    752MB
```
After this change:
```
REPOSITORY …
```
> Set capabilities in the builder Docker image instead of the final

- deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
- deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
- deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
- deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml
- deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
- deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml
- Bug
Fixing wrong values of elastic-agent image in the backport brach of 8.14.3
The [backport-PR](https://github.com/elastic/elastic-agent/commit/dba6a861f4bd1691a1bc1785d5c554c9bd446513) had wrong values for the image
The users that use kubectl kustomize https://github.com/elastic/elastic-agent/deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone\?ref\=v8.14.3 will still install image 8.15.0
> kubectl kustomize https://github.com/elastic/elastic-agent/deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone\?ref\=v8.14.3 > manifest.yaml
The manifest.yaml should have the correct values
> Updating elastic-agent image to version 8.14.3

- internal/pkg/otel/README.md
- internal/pkg/otel/templates/README.md.tmpl
Fixes formatting of the OTel README file by removing redundant whitespace.
Not that important really :stuck_out_tongue: but makes the formatter happy and makes the Markdown code cleaner.
> [otel] docs: fix spaces in README

- deploy/kubernetes/creator_k8s_manifest.sh
- deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset-configmap.yaml
- deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-ksm-daemonset-configmap.yaml
- deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-ksm-daemonset-configmap.yaml
- deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
- deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml
- deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-ksm-daemonset-configmap.yaml
- Bug
WHAT: Fixes the path that is being used in hints autodiscovery of elastic-agent
WHY: The path for hint configuration was not correct when users where extracting the manifest from Kibana page
Note: We have added `hints.default_container_logs: true` also in the standalone configmap
Improves the UX for elastic agent users that want to use kibana to create their manifests
1. Download this nranch
2. Navigate to `deploy/kubernetes`
3. Run: 
```bash
WITHOUTCONFIG=true make generate-k8s
./creator_k8s_manifest.sh .
``
4. Check the new `elastic_agent_manifest.ts` that is being created should include `elastic-agent-standalone/templates.d` line
```yaml
```
> Fixing the hints autodiscovery configuration path in Elastic Agent Manifests

- .buildkite/scripts/install-gh.sh
- .buildkite/scripts/steps/merge.sh
This PR removes the `set -x` options from two scripts run as part of ["K8s tests" group](https://github.com/elastic/elastic-agent/blob/ca726a219e7289ca1278653003c8dc299d302093/.buildkite/pipeline.yml#L180C13-L180C22) in the Elastic Agent buildkite pipeline.
To avoid printing out secrets.
> Remove `set -x` from Buildkite scripts

- testing/integration/event_logging_test.go
The test is flaky https://github.com/elastic/elastic-agent/issues/5159
> Temporary skip TestEventLogOutputConfiguredViaFleet

- changelog/fragments/1720208209-add-docker-wolfi.yaml
- dev-tools/packaging/packages.yml
- dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
- dev-tools/packaging/templates/docker/docker-entrypoint.elastic-agent.tmpl
* New images with `-wolfi` suffix are created
* The `-cloud` image is now based on Wolfi
* Refactored the packaging spec for better readability
* Fixed ignored architecture flags when building Docker images. Building ARM64 on AMD64 and AMD64 or ARM64 is now possible
Wolfi is a security-focused Linux image for containers, see more here https://github.com/wolfi-dev/
```sh
SNAPSHOT=true PLATFORMS=linux/amd64 PACKAGES=docker mage package
```
Before this change:
```
REPOSITORY …
```
> Make Wolfi a part of Docker packaging

- .buildkite/pipeline.integration-test-matrix.yml
Adds a separate packaging step to the matrix pipeline
-
- ...
> [CI] Add packaging step to integration matrix pipeline

- internal/pkg/agent/application/coordinator/coordinator.go
What the summary says, this log line at the debug level can be quite large, let's remove it.
> Remove verbose debug log line.

- pkg/testing/runner/runner.go
- testing/integration/kubernetes_agent_standalone_test.go
This PR skips the failing `TestKubernetesAgentStandalone/drop_ALL_add_CHOWN,_SETPCAP_capabilities_-_rootless_agent` integration test while it's being [fixed](https://github.com/elastic/elastic-agent/issues/5275).
To unblock Agent PRs that are failing CI _only_ due to this test's failure.
> Skip failing k8s capabilities test

- dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
- testing/integration/kubernetes_agent_standalone_test.go
This PR addresses the failures of k8s integrations tests:
1. Fix degraded agent status for rootless agent running with elastic-agent uid (1000). The main reason behind this was the setcap on the `agentbeat` binary in conjunction with it getting copied from a "builder" image during the building of the elastic-agent container image. I am not sure why this is the case, but I have observed in the past that copying files with capabilities across different docker layers results in an Effective set with no capabilities of the file at hand, ignoring completely the Ambient set of the parent which is elastic-agent in our case. This quirk got highlighted when metricbeat implemented status reporting. Now fun fact, we weren't bumping into this scenario for rootless agent with random uid:gid as in this …
> fix: rootless k8s integration tests

- testing/integration/agent_long_running_leak_test.go
- Relates https://github.com/elastic/elastic-agent/issues/5300
Instead of disabling the test because Metricbeat is reporting as degraded due to permission and other errors, relax the state check temporarily to allow the Degraded state while we fix the source of the permissions errors.
> Relax leak test condition from Healthy to not Failed.

- changelog/fragments/1723477450-use-monotonic-clock-for-check-in.yaml
- pkg/component/runtime/command.go
- pkg/component/runtime/service.go
Switch to montonic clocks for component check-in calculation.
Previously the wall clock was used and this caused components to
appear degraded if they "missed" check-ins because the time change
made it appear they hadn't checked in within the necessary time
window.
Necessary to prevent unnecessary restarting of components when the
wall time of the host changes significantly.
1. Install `elastic-agent` on a machine
2. continuously advance the clock
3. without patch observe that components go into degraded state due to failed check-in, and eventually are restarted
4. with patch observer that components stay healthy and are not restarted.  No missed check-ins are reported
- Closes #5277
- How are we …
> switch to monotonic clocks for component check-in

- testing/integration/linux_rpm_test.go
https://github.com/elastic/elastic-agent/issues/5311
> Temporary skip TestRpmLogIngestFleetManaged due to instability

- changelog/fragments/1724103107-Check-windows-permissions-for-false-positive-return.yaml
- internal/pkg/agent/perms/windows.go
Return a nil error instead of syscall.Errno(0) which indicates a successful operation on windows.
Installation may fail with the error: `Error: failed to fix permissions: The operation completed successfully.`. This is caused by `golang.org/x/sys/windows` [using Errno(0)](https://cs.opensource.google/go/x/sys/+/master:windows/zerrors_windows.go;drc=134d130e1a049f4194ae9920ac9f96455cde360d;l=151) to indicate a success in some cases as described by the [Windows API](https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-)
- ~~I have added an integration …
> Return nil error instead of syscall.Errno(0) on windows

- testing/integration/event_logging_test.go
This PR skips the `TestEventLogFile` flaky test to unblock builds while we figure out and fix the root cause for the failure.
This PR should be reverted once https://github.com/elastic/elastic-agent/issues/5337 is resolved.
> Skip flaky test: `TestEventLogFile`

- testing/integration/container_cmd_test.go
- testing/integration/event_logging_test.go
Fix TestEventLogFile, TestContainerCMDEventToStderr and TestEventLogOutputConfiguredViaFleet by updating the string that needs to be searched in the logs.
It fixes some test that were breaking CI
There is no disruptive user impact because this PR is fixing a broken test
Package the Elastic-Agent from this PR:
```
DEV=true SNAPSHOT=true EXTERNAL=true PACKAGES="deb,rpm,tar.gz" PLATFORMS=linux/amd64 mage -v package
```
Then run one of the  integration test that were failing: `TestEventLogFile`, `TestContainerCMDEventToStderr` or `TestEventLogOutputConfiguredViaFleet`
```
SNAPSHOT=true TEST_PLATFORMS="linux/amd64" mage -v integration:single  TestEventLogFile
```
- Closes https://github.com/elastic/elastic-agent/issues/5337 …
> Fix TestEventLogFile, TestContainerCMDEventToStderr and TestEventLogOutputConfiguredViaFleet

- testing/integration/agent_long_running_leak_test.go
Reverts elastic/elastic-agent#5301
With https://github.com/elastic/beats/issues/40542 being merged, we don't mark agent as degraded when metrics are partially collected.
> Revert "Relax leak test condition from Healthy to not Failed."

- internal/pkg/agent/application/upgrade/watcher.go
- internal/pkg/agent/application/upgrade/watcher_test.go
It improves the watcher logs and prints the logs if TestWatcher_AgentErrorQuick fails.
If the test would fail, the logs would be like the following:
```
❯ go test -run TestWatcher_AgentErrorQuick ./internal/pkg/agent/application/upgrade/
--- FAIL: TestWatcher_AgentErrorQuick (1.00s)
watcher_test.go:287: [info] Agent watcher started
watcher_test.go:287: [info] Trying to connect to agent
watcher_test.go:287: [info] Connected to agent
watcher_test.go:287: [debug] received state: FAILED:force failure
watcher_test.go:287: [info] Communicating with PID 0
watcher_test.go:287: [debug] received state: HEALTHY:healthy
watcher_test.go:287: [error] Agent reported failure (starting failed timer): agent reported failed state: force failure
watcher_test.go:287: [info] Agent reported healthy (failed …
```
> Improve watcher and TestWatcher_AgentErrorQuick logs

- internal/pkg/agent/application/actions/handlers/handler_action_upgrade_test.go
- testing/integration/agent_long_running_leak_test.go
This PR fixes following test cases:
- `TestLongRunningAgentForLeaks`
- `TestUpgradeHandlerNewVersion`
- `TestUpgradeHandlerNewVersion` fails due to a potential race condition. We rely on `time.Sleep(..)` to wait, which produces undesirable result if the goroutine sleeps for more than desired time.
Instead of sleeping, make use of channels to indicate the sucess.
- `TestLongRunningAgentForLeaks` failure is explained in https://github.com/elastic/elastic-agent/issues/5279
- Closes https://github.com/elastic/elastic-agent/issues/5279
- Closes https://github.com/elastic/elastic-agent/issues/4289
- ...
> [testing/integration] Fix flaky test cases

- dev-tools/mage/crossbuild.go
- dev-tools/mage/dockerbuilder.go
- dev-tools/mage/dockervariants.go
- dev-tools/mage/pkg.go
- dev-tools/mage/pkgspecs.go
- dev-tools/mage/pkgtypes.go
- dev-tools/packaging/packages.yml
- dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Adds ability to adjust package building to build only a subset of docker image variants.
Helps with developer velocity, where iterating on an image is quicker because you can select only a specific variant to build.
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~ (**dev-tools/ only**)
- ~~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~~ (**dev-tools/ only**)
- ~~[ ] I have added an integration test or an E2E test~~  (**dev-tools/ only**)
None
Build a specific image variant:
```
PLATFORMS="linux/arm64" PACKAGES="docker" …
```
> Add ability to build specific docker variants

- deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
- deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
- deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml
- deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml
- deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml
- deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml
- Bug
WHAT: Update image versions for kustomize templates
WHY: Was a leftover and trying to align with main manifests
To have the same image version to all our manifests
> Updating also kustomize templates for 8.15.1

- internal/pkg/agent/application/upgrade/upgrade.go
- pkg/testing/define/define.go
- pkg/testing/fixture.go
- pkg/testing/fixture_install.go
- pkg/testing/tools/estools/elasticsearch.go
- testing/integration/logs_ingestion_test.go
- testing/integration/upgrade_rollback_test.go
[Integration Tests] Generate namespace based on UUIDv4
TestLogIngestionFleetManaged was failing because the namespace generated by the integration tests framework was not unique among different tests and test runs, so sometimes collisions would occurs causing some tests to be flaky.
TestDebLogIngestFleetManaged was failing because it also has got Beats logging connection errors before receiving the configuration from Elastic-Agent, now this message is also in the allow list.
When testing .deb the AGENT_KEEP_INSTALLED environment variable is respected.
When an integration test fails, the work directory created by the framework is now kept and its path is printed.
It fixes flakiness in our tests
Run an integration test: `mage -v integration:single …
> Fix TestLogIngestionFleetManaged, TestDebLogIngestFleetManaged

- testing/integration/package_version_test.go
The state diagnostics hook now re-fetches once the state when necessary, improving the accuracy of component status reporting.
Given a design choice, the coordinator's reported state might be stale, leading to healthy components lacking version_info immediately after they start.
- ~~[ ] I have added an entry in `./changelog/fragments` using th~~e [changelog tool](https://github.com/elastic/elastic-agent#changelog)
Run the [`TestDiagnosticState`](https://github.com/AndersonQ/elastic-agent/blob/db1be7588b892df7d2ca902d5edd49727ae766d8/internal/pkg/agent/application/coordinator/diagnostics_test. …
> Avoid reporting empty version_info for components that just started

- pkg/testing/fixture_install.go
- testing/integration/package_version_test.go
Saves diagnostic used on TestComponentBuildHashInDiagnostics and prints the agent status output if the test fails
The test is flaky, it'll provide more data to investigate why it's failing
- ~~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool]~~(https://github.com/elastic/elastic-agent#changelog)~~
-N/A
- N/A
- Relates #5333
- What are the metrics I …
> [Flaky Test] TestComponentBuildHashInDiagnostics: save diagnostic and agent status on failure 

- changelog/fragments/1724804905-otel-health-check.yaml
- otel.yml
This PR adds the `health_check` extension to the `otel.yml` file that's bundled with the Elastic Agent package.
Without this addition, if a user tries to install the `open-telemetry/opentelemetry-collector` Helm chart with Elastic's distribution of the OTel Collector (i.e. Elastic Agent), the installation eventually fails.  Specifically, as noted by @andrzej-stencel in https://github.com/elastic/elastic-agent/issues/5092#issuecomment-2309613481:
> One problem I'm seeing when running the chart with this configuration is that the Health Check extension is not used in the `otel.yml` file, which results in Kubernetes restarting the collector container and eventually resulting in a `CrashLoopBackOff`. We should add the `health_check` extension to `service::extensions` in the `otel.yml` file …
> Add `health_check` extension to bundled `otel.yml` file

- testing/integration/agent_long_running_leak_test.go
- Enhancement
>  I opted for a 60s interval to be cautious and ensure the system has enough time to stabilize. But I think `30s` wait would be sufficient. Let me know what do you think
> 
> If we need for the status to stabilize I would have extended the period where we wait for everything to be healthy during the setup but after that I would have kept the check every few seconds instead of waiting a full minute for the status checks (basically checking that once we get the HEALTHY state we keep being healthy for the duration of the test).
> 
> As a first fix I guess we can leave 60s interval between ticks, maybe we can improve this in following iterations...
> 
_Originally posted by @pchila in https://github.com/elastic/elastic-agent/issues/5359#issuecomment-2310453791_
In long running …
> [testing/integration] make sure all unit are healthy for `agent_long_running_leak_test`

- testing/integration/package_version_test.go
Improves the agent status check on TestComponentBuildHashInDiagnostics to ensure the agent is healthy and has components.
The test is flaky because the test did not account for the absence of components 
- N/A
- run the test with `TEST_RUN_UNTIL_FAILURE` until you're satisfied or it fails again
- Closes #5333
- How are we …
> [Flaky Test] TestComponentBuildHashInDiagnostics improve agent state check

- .buildkite/scripts/common.sh
- Makefile
Updates the [Mage](https://github.com/magefile/mage) version used from 1.14.0 to 1.15.0 (currently latest version).
We should be using latest version to be on top of any bug/security fixes.
```
make mage
```
Note that with the way mage …
> Upgrade mage from 1.14.0 to 1.15.0

- internal/pkg/agent/application/managed_mode_test.go
Fixes flaky test `Test_runDispatcher/gateway_actions_passed` by increasing the timeout from 100ms to 200ms.
The flakiness is a result of a 100 miliseconds not always being enough time to  dispatch the action in the test environment.
The correct way to fix this issue is to run the assertions in an `assert.Eventually` with a longer timeout. Unfortunately, a deficiency in the `testify` testing framework makes it impossible to put the `AssertExpectations` methods in an `assert.Eventually` or `assert.EventuallyWithT` function: https://github.com/stretchr/testify/issues/1414.
The workaround is to increase the context timeout for the `gateway actions passed` test case. I'm increasing it from 100ms to 200ms.
Flaky tests are evil!
- …
> Fix flaky test Test_runDispatcher/gateway_actions_passed

- internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
This PR simplifies getting string values for Unit type variants by using the fmt.Stringer impl provided by the elastic-agent-client.
Looking at the implementation in elastic-agent-client, it maps the exact same keys to the same strings, except for the 'unknown' variant, which we currently return as an empty string.
https://github.com/elastic/elastic-agent-client/blob/v7.15.0/pkg/client/unit.go#L91-L110
https://github.com/elastic/elastic-agent-client/blob/v7.15.0/pkg/client/unit.go#L27-L36
Just a cleanup. I'm not sure if it is better to map the values ourselves.
> use Stringer to get string values for eaclient Unit types

- .github/workflows/bump-golang.yml
Use the scm values file to be able to know what's the GH repository where those changes should be applied.
Keep the automation doing what it was aimed to do :)
https://github.com/elastic/elastic-agent/pull/5367 introduced a regression when replaced the hardcoded values for the values in a file. It's required to pass the new values file to the updatecli apply command, that's something I missed to do it.
I ran the below command
```bash
$ GITHUB_TOKEN=$(gh auth token) \
GITHUB_ACTOR=updatecli \
updatecli apply --config .ci/updatecli/updatecli-bump-golang.yml --values .ci/updatecli/values.d/scm.yml --push=false
+++++++++++
+ PREPARE +
+++++++++++
Loading Pipeline ".ci/updatecli/updatecli-bump-golang.yml"
...
Run Summary
===========
Pipeline(s) run:
* Changed:	0
* Failed:	0
* Skipped:	0
* …
```
> fix(updatecli): use values file

- .buildkite/pipeline.yml
Updates the coverage report step to use the proper Golang version
I am not sure if this is related, but recent builds show that the `golang.org/x/tools/cover` suddenly fails when pulling.
We should ensure the version is pulled from the right place `.go-version` or similar.  This is not in scope in this PR, this is to help unblock main.
> [CI] Correct Go version when running the coverage report

- docs/test-framework-dev-guide.md
In the integration test framework guide, mention that authenticating with Elastic's docker registry is necessary to run integration tests. Change `integration:listStacks` to `integration:stacks`.
- https://github.com/elastic/ingest-dev/issues/3759
> Fix minor issues with the test framework guide

- .mergify.yml
Automate the backport from main to `8.x` using GitHub labels
This should help with keeping `main` and `8.x` in sync.
-
- ...
> mergify: automate the backport to 8.x when PRs targeting main

- .buildkite/pipeline.elastic-agent-binary-dra.yml
This PR updates the DRA buildkite pipeline to run steps for _n_.x branches, e.g. `8.x`, in addition to the existing _n.m_ branches (where _n_ and _m_ are digits).
> Run DRA steps for *.x branches as well

- .agent-versions.json
There doesn't exist an `8.14.4-SNAPSHOT` any more.  Consequently, upgrade integration tests have been failing like so:
```
Failed
=== RUN   TestStandaloneUpgrade/Upgrade_8.14.4-SNAPSHOT_to_8.16.0-SNAPSHOT_(unprivileged)
upgrade_standalone_test.go:68: 
Error Trace:	C:/Users/windows/agent/testing/integration/upgrade_standalone_test.go:68
C:/Users/windows/agent/testing/integration/upgrade_standalone_test.go:47
Error:      	Received unexpected error:
failed to prepare before exec: failed to find artifact URI for version 8.14.4-SNAPSHOT: failed to find snapshot information for version "8.14.4-SNAPSHOT": snapshot for version "8.14.4" not found
Test:       	TestStandaloneUpgrade/Upgrade_8.14.4-SNAPSHOT_to_8.16.0-SNAPSHOT_(unprivileged)
--- FAIL: …
```
> Removed aged out snapshot version

- pkg/testing/tools/git/git.go
Update the regex used to identify release branches
Now we have `8.x` which isn't matched by the current regex
None
- run the unit tests
```sh
go test -v -run TestGetReleaseBranches ./pkg/testing/tools/git
```
- N/A
- What are the metrics I should take …
> Update the regex used to identify release branches to include 8.x

- .mergify.yml
Allow mergify to exclude `backport-8.x` if `backport-skip` is added.
Avoid labelling constantly `backport-8.x` for `main`.
-
- ...
> mergify: avoid label automation always

- docs/test-framework-dev-guide.md
It improves the integration tests framework documentation on how to debug test from the remove VMs.
It improves the integration tests framework documentation on how to debug test from the remove VMs.
- How are we …
> Improve the integration tests framework documentation

- dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
There was a missed rename in https://github.com/elastic/elastic-agent/pull/5557
Testing:
```
PLATFORMS=linux/arm64 PACKAGES=docker mage package
```
Then get shell and check the dependencies for Synthetics are there:
```
docker run -it --rm --entrypoint bash docker.elastic.co/beats/elastic-agent-complete-wolfi:9.0.0
ls -lah ~/.npm/bin
```
> Fix the complete image for Wolfi

- changelog/fragments/1726040648-Add-support-for-passphrase-protected-mTLS-client-certificate-key.yaml
- internal/pkg/agent/application/actions/handlers/handler_action_policy_change_test.go
- internal/pkg/agent/cmd/enroll.go
- internal/pkg/agent/cmd/enroll_cmd.go
- internal/pkg/agent/cmd/enroll_cmd_test.go
It adds support for encrypted client certificate key during install/enroll, which done by the cli flag `--elastic-agent-cert-key-passphrase`.
It enables Elastic Agent to be configured with passphrase-protected private keys for client mTLS certificates.
**Tests**
- None
- Build Elastic Agent with the changes from this PR.
- Enroll/Install the Elastic Agent using passphrase-protected private key for the client mTLS certificate.
- Start Elastic Agent and observe successful enrollment/installation with mTLS enabled.
- Closes #5489
- …
> Add support for CLI flag for mTLS client certificate key passphrase

- changelog/fragments/1726238750-change-deprecated-maintainer-label-in-Dockerfile-to-org.opencontainers.image.authors.yaml
- dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
The old way of specifying maintainers in a Dockerfile was to use the MAINTAINER instruction. This is now deprecated and the maintainer label was used instead.
Nowadays the recommended way to set a maintainer is through the `org.opencontainers.image.authors` label.
See https://docs.docker.com/reference/build-checks/maintainer-deprecated/.
> Change maintainer label to opencontainers in Dockerfile

- changelog/fragments/1726740792-pprof-endpoint.yaml
- internal/pkg/agent/application/monitoring/server.go
- internal/pkg/agent/application/monitoring/server_test.go
Adds pprof endpoints to the monitoring server if they're enabled in the config.
The [documentation](https://www.elastic.co/guide/en/fleet/current/elastic-agent-monitoring-configuration.html) claims this should work, and it not working is a bug. And in general, these endpoints are quite useful and provide functionality diagnostics don't.
I added a simple unit test. You can also just start the agent with pprof enabled and verify the endpoints exist at `/debug/pprof/`.
> Add pprof endpoints to the monitoring server if enabled

- dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Fix ownership of components' spec files in `<agent install dir>/data/elastic-agent-<commit>/components/*.yml` from `root:root` to `<user>:<user>` where `user` is the default user the agent process will be started with
To prevent permissions mismatches between component binaries and their spec yaml files under `../components` …
> Fix ownership of component specs in elastic-agent docker image

- .buildkite/integration.pipeline.yml
- .buildkite/pipeline.yml
- docs/test-framework-dev-guide.md
- pkg/testing/kubernetes/supported.go
Adds test coverage for kubernetes v1.31.0, released Aug 13 2024.
- Relates https://github.com/elastic/observability-dev/issues/3718
> add kubernetes v1.31 to test matrix

- .buildkite/hooks/pre-command.ps1
Description of problem:
Windows unit test pre-command steps were failing in CI when the BUILDKITE_MESSAGE param was too long, which would occur when commits had very long descriptions. This sometimes happens from automated processes, such as dependency updates. The BUILDKITE_MESSAGE would be very long, which would fill the Windows env var buffer, preventing further pre-command steps from adding directories to the PATH.
Problem report: https://elastic.slack.com/archives/C0522G6FBNE/p1727193548224399
Fix:
Trim the BUILDKITE_MESSAGE param to the INTERNET_MAX_URL_LENGTH of 2048. 
This was tested in draft PR https://github.com/elastic/elastic-agent/pull/5609 with very long and short commit messages. I confirmed that the Windows unit test steps got past the pre-command phase.
References:
- …
> Handle BUILDKITE_MESSAGE length in pre-command.ps1

- .buildkite/pipeline.yml
- .buildkite/scripts/steps/merge.sh
This PR makes it so that if the "Merge coverage reports" step (`key: merge-coverage`) in CI fails, we don't fail the build.  Since the SonarQube step depends on the `merge-coverage` step, we similarly don't fail the build if that step fails too, which is expected to happen if the `merge-coverage` step doesn't succeed.
We've observed that in some Agent PRs ([example](https://github.com/elastic/elastic-agent/pull/5547/)), if the "Merge coverage reports" step is retried, it fails like so:
```
$  .buildkite/scripts/steps/merge.sh unit-tests-2204 unit-tests-2204-arm64 unit-tests-win2016 unit-tests-win2022 unit-tests-macos-13 unit-tests-win10 unit-tests-win11
--
  | go: downloading github.com/wadey/gocovmerge v0.0.0-20160331181800-b5bfa59ec0ad
  | go: finding module for package …
```
> [CI] Soft fail merge coverage reports step

- _meta/config/elastic-agent.docker.yml.tmpl
- changelog/fragments/1726144746-container-default-credentials.yaml
- changelog/fragments/1726145045-container-api-key.yaml
- elastic-agent.docker.yml
Remove defaults for username and password when running in container mode, and also allow api_key to be set in that mode via the `ELASTICSEARCH_API_KEY` environment variable.
Note that the first of these changes is breaking. I've added two separate changelog entries to make this clear.
It's very useful for users to be able to use an ES api key for authentication without needing to override the whole config file.
This is a breaking change for users who rely on the default username and password in container mode. These users will need to explicitly set these values after this change is rolled out. After the upgrade, the agent will simply fail to start, and will complain about lack of authentication credentials.
```bash
DEV=true SNAPSHOT=true EXTERNAL=true PACKAGES=docker mage package
docker …
```
> Allow setting ES api key via env variable in container mode

- magefile.go
This commit modifies movePackagesToArchive() function to include python wheel packages introduced with commit 701f8b9 .
This solves an issue when packaging docker images using a DROP_PATH env var: prior to this change, the python wheel archives present in DROP_PATH were not moved to `<DROP PATH>/archive/<platform>` failing to create an image for which the Dockerfile expects to install the python wheel package
To have a successful docker image creation during unified build processes.
Package the docker image "service" for elastic agent using a DROP_PATH (and optionally a manifest), for example:
```shell
AGENT_DROP_PATH=./build/agentdrop MANIFEST_URL=https://snapshots.elastic.co/9.0.0-3ca48ed8/agent-package/agent-artifacts-9.0.0-SNAPSHOT.json SNAPSHOT=true PLATFORMS="linux/amd64" …
```
> Include python wheel packages when moving downloaded dependencies archives

- pkg/component/runtime/manager.go
- pkg/component/runtime/manager_fake_input_test.go
- pkg/component/runtime/manager_test.go
Add some output to make it easier to see wheree the flakey `TestManager_StartStopComponent` test is getting stuck.
Use a chan instead of an atomic bool to signal when the manager is ready for tests as it is more idiomatic.
- Relates #4502
> TestManager_StartStopComponent add test logs, alternate manager ready signal

- docs/test-framework-dev-guide.md
> Clarify that Agent package used by integration tests relies on Beats unified release

- dev-tools/mage/dockerbuilder.go
- magefile.go
This PR extends the behaviour introduced in #5647 by copying platform-independent components into <drop path>/archive/<platform-specific directory> instead of moving them.
This fixes the build of docker image `service` when multiple platforms are specified for the build: without this fix the platform-independent component would be moved exactly once, in the directory of the first platform considered during the build.
**Note:**
It seems that `EXTERNAL=true SNAPSHOT=true mage package` still suffers from some inconsistencies when downloading `connectors` dependency for multiple platforms but this is unrelated to this fix and will be tracked by a separate issue.
To correctly build elastic-agent-service docker image for multiple platforms during the Unified Release.
- …
> Fix docker image build when multiple platforms are specified

- testing/integration/apm_propagation_test.go
Now that the APM server issue on Integration server is resolved we can revert this change.
Reverts elastic/elastic-agent#5625
> Revert "Skip flaky integration test - TestAPMConfig"

- .buildkite/integration.pipeline.yml
- catalog-info.yaml
Adds the [daily cron that was manually configured](https://buildkite.com/elastic/elastic-agent/settings/schedules/621c1260-ba0a-4ab1-874e-0fe8b2a2797b) to the yml config.
> Add daily cron for elastic-agent

- .buildkite/integration.pipeline.yml
- .buildkite/pipeline.yml
Upgrades the version of [kind](https://kind.sigs.k8s.io/) to the [latest](https://github.com/kubernetes-sigs/kind/releases) (v0.24.0)
- Related to https://github.com/elastic/observability-dev/issues/3718
> chore: update kind version to v0.24.0

- internal/pkg/agent/application/monitoring/handler.go
- internal/pkg/agent/vault/aesgcm/aesgcm_test.go
- internal/pkg/cli/confirm.go
- internal/pkg/cli/input.go
- pkg/control/v1/client/client.go
- pkg/control/v2/client/client.go
- pkg/testing/multipass/provisioner.go
The cmd/vet in Go 1.24 reports printf calls with non-const format and no args, causing failures.
```
$ go install golang.org/dl/gotip@latest
$ gotip download
$ gotip vet ./...
```
- Related to https://github.com/elastic/elastic-agent-libs/pull/233
> fix go vet errors with Go 1.24

- .golangci.yml
This PR cleans up the list for allowed dependencies in the `go.mod` `replace` directive.  It removes dependencies from the allowlist that are no longer being `replace`d in `go.mod`.
To help minimize the number of dependencies we `replace` with forks.
> Shorten allowlist for `replace`able dependencies

- changelog/fragments/1728039144-k8s-replicaset-onlymeta.yaml
- internal/pkg/composable/providers/kubernetes/pod.go
Use a metadata watcher for ReplicaSets in the K8s provider. The only data we need from ReplicaSets are their name and OwnerReferences, which are used to connect Pods to Deployments and DaemonSets.
This significantly reduces both memory used to store ReplicaSet data, and temporary allocations to process update events from the API Server. See the linked issue for more detailed information.
Showing that the change doesn't cause a regression requires starting agent in K8s and enabling deployment metadata in the K8s provider, and then using it in a templated input definition - this is simplest with filebeat.
Demonstrating the memory consumption improvement is more involved - you need to create a significant amount of ReplicaSets in the cluster. I saw a noticable difference at ~7500, see #5623 …
> Only watch metadata for ReplicaSets in K8s provider

- README.md
Add more details about the different Docker image variants and their specificities.
> Add more details about Docker image variants

- .github/CODEOWNERS
Update CODEOWNERS so the Eng Prod team is automatically added to reviews where CI is getting updated.
> Update CODEOWNERS for Eng Prod ownership

- pkg/testing/windows/windows.go
Retrying the choco install step to reduce the flakiness of integration test runs.
> Retrying choco install

- .buildkite/pipeline.yml
- dev-tools/mage/gotest.go
We noticed that the JUnit annotate step needed to take more time. This PR addresses that issue by not requiring it to parse the coverage files.
The generated coverage XML file was meant to be used in Jenkins to show the coverage report stats. The generated XML files were large, resulting in a problem with BK's JUnit annotate plugin. 
Given that we don't operate any Jenkins instance, this PR removes the code that generated the XML coverage reports.
Now, coverage is reported only to Sonar.
Reduce the time of CI step
> Exclude the coverage files from the annotate step

- pkg/testing/windows/windows.go
Add retries to a few more Windows setup steps in the agent CI to try to reduce flakiness.
Rel: https://github.com/elastic/ingest-dev/issues/4245
> Add retries to choco install steps

- internal/pkg/agent/application/application.go
- internal/pkg/agent/application/application_test.go
- internal/pkg/agent/application/coordinator/coordinator_test.go
- internal/pkg/agent/cmd/otel.go
- internal/pkg/agent/cmd/run.go
- pkg/component/runtime/manager.go
- pkg/component/runtime/manager_fake_input_test.go
- pkg/component/runtime/manager_test.go
- pkg/testing/fixture.go
- testing/integration/kubernetes_agent_service_test.go
- testing/integration/kubernetes_agent_standalone_test.go
- testing/integration/otel_test.go
Previously the control protocol was started when the subcommand `otel` was ran. This should not be done as the subcommand `otel` should operate it in a pure OTel mode.
This is a cleanup that comes out of working on Hybrid mode.
Cleanup to make the code cleaner and less messy as the control protocol should not really be running when running the otel subcommand.
Can no longer call `elastic-agent status` when a `elastic-agent otel` is running.
Run `elastic-agent otel`, then try to run `elastic-agent status` and see …
> Don't run any agent service when running `otel` subcommand

- testing/integration/kubernetes_agent_standalone_test.go
So, we validate all produced images.
Test runtime:
* before this PR – [~57 minutes](https://buildkite.com/elastic/elastic-agent-extended-testing/builds/3760#019290b0-a3b7-4600-b3a3-673bc796005b)
* after this PR – [~1h 37 minutes](https://buildkite.com/elastic/elastic-agent-extended-testing/builds/3756#0192908e-d36e-4588-ba19-262921ad51ca)
Let me know if the runtime increase is sensible.
> Add all Docker images to K8s integration tests

- .buildkite/pipeline.yml
- .buildkite/scripts/steps/merge.sh
Restore the file location of the coverage report file back to `/build` folder.
A recent commit change the generate coverage report file location and moved it from the `/build` to the root of the repo. This had a side effect on the Sonar scanning step that expected the file to be on the `/build` folder
Closes: https://github.com/elastic/ingest-dev/issues/4258
> Move back merged coverage report to build folder

- .github/CODEOWNERS
Adjust CODEOWNERS to list in `ls` order and adjust to account for precedence based on order in the list.
> CODEOWNERS refactor

- catalog-info.yaml
This PR adds a notification for the packaging pipeline when it fails.
The notification is for all the branches this pipeline runs and only on failures.
The notification is sent to the team on their Slack channel.
Yes, this is related to https://github.com/elastic/ingest-dev/issues/3625
> Add notification for when the packaging pipeline fails

- changelog/fragments/1729750939-crossbuild-debian11.yaml
- dev-tools/mage/crossbuild.go
We're dropping support for Debian 10,
so no need to crossbuild using the outdated image anymore.
This also updates the statically linked glibc from 2.19 to 2.31.
```sh
PLATFORMS=linux/arm64 PACKAGES=docker mage package
```
- Relates https://github.com/elastic/beats/pull/41402
> Switch crossbuilding to Debian 11

- .buildkite/scripts/steps/integration-package.sh
- .buildkite/scripts/steps/k8s-extended-tests.sh
In CI we see failures like elastic/beats#41270
Removing `DEV=true` from CI builds should fix.
> remove DEV=true from CI build steps

- docs/test-framework-dev-guide.md
- Docs
Replaces the staging link with the production one to create api keys to be used in the integration test setup
Following the current documentation, a developer won't be able to setup the integration tests
- Relates to #5320
> use production api key link instead of staging

- deploy/helm/elastic-agent/README.md
- deploy/helm/elastic-agent/examples/kubernetes-default/README.md
- deploy/helm/elastic-agent/templates/agent/eck/_pod_template.tpl
- deploy/helm/elastic-agent/templates/agent/k8s/_pod_template.tpl
- deploy/helm/elastic-agent/values.schema.json
- deploy/helm/elastic-agent/values.yaml
This PR that adds support for defining `pullImageSecrets` support in the chart
Users mights need to deploy an agent image from a private repository
N/A
```
```
> [helm]: implement support for defining image pull secrets

- deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/kubernetes-default/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/kubernetes-only-logs/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_controller_manager.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_logs_containers.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_scheduler.tpl
- deploy/helm/elastic-agent/values.schema.json
I was testing k8s standalone elastic-agent using the plain k8s manifest under `deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml` but I also tried to get the same results with the elastic-agent helm chart and I tried to replicate the produced data with the elastic-agent helm chart. This effort uncovered some yaml format issues and some inconsistencies for container logs which this PR handles
Because it fixes bugs 🙂 
N/A
```
```
-
> [helm]: integration config for scheduler and controller-manager conditions and containers logs

- deploy/helm/elastic-agent/README.md
- deploy/helm/elastic-agent/examples/README.md
- deploy/helm/elastic-agent/examples/system-custom-auth-paths/README.md
- deploy/helm/elastic-agent/examples/system-custom-auth-paths/agent-system-values.yaml
- deploy/helm/elastic-agent/examples/system-custom-auth-paths/rendered/manifest.yaml
- deploy/helm/elastic-agent/templates/NOTES.txt
- deploy/helm/elastic-agent/templates/agent/_helpers.tpl
- deploy/helm/elastic-agent/templates/integrations/_system/_system.tpl
- deploy/helm/elastic-agent/templates/integrations/_system/_system_logs.tpl
- deploy/helm/elastic-agent/templates/integrations/_system/_system_metrics.tpl
- deploy/helm/elastic-agent/values.schema.json
- deploy/helm/elastic-agent/values.yaml
This PR introduces support for the system integration 
system integration is usually used in the context of k8s, thus having it as a built-in integration improves the user configuration experience
```
```
> [helm]: implement system integration as chart built-in

- testing/integration/apm_propagation_test.go
This PR skips the `TestAPMConfig` test until we figure out root cause and fix it (see https://github.com/elastic/elastic-agent/issues/5890).
To get CI on `main` to green again.
> Skip TestAPMConfig 

- dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
- testing/integration/kubernetes_agent_service_test.go
The `elastic-agent-service` container followed the template for the `elastic-agent-cloud` container. This isn't quite correct, because while the service container will run exclusively in cloud it is otherwise meant to be used as a standard Elastic Agent docker container with the standard entrypoint.
- Closes https://github.com/elastic/ingest-dev/issues/4363#issuecomment-2447236159
> Fix elastic-agent-service Docker container entrypoint

- pkg/testing/ess/create_deployment_csp_configuration.yaml
This PR updates the deployment template IDs and instance configuration IDs used to spin up deployments in ESS for integration testing.  
The deployments template IDs and instance configuration IDs being used have been [deprecated](https://www.elastic.co/guide/en/cloud/current/ec-regions-templates-instances.html).  Continuing to use them causes errors like so when the integration testing framework attempts to create deployments in ESS:
```
failed to create ESS cloud for version 8.17.0-SNAPSHOT: failed to create: (deployments.elasticsearch_using_legacy_dt) The referenced deployment template in elasticsearch plan [gcp-storage-optimized-v5] is no longer available.
```
```
failed to create ESS cloud for version 9.0.0-SNAPSHOT: failed to create: (deployments.topology_element_using_legacy_ic) …
```
> [Integration Testing Framework][ESS] Stop using deprecated ESS resource IDs

- changelog/fragments/1730418510-confirm-test.yaml
- internal/pkg/cli/confirm.go
- internal/pkg/cli/confirm_test.go
This PR trims spaces in the user input accepted by the `cli.confirm` function.  It also adds unit tests for this function.
To ensure that yes-no confirmation prompts offered by Agent on the CLI work against user input as expected.
> Trim spaces and add unit tests for `cli.confirm` function

- deploy/helm/elastic-agent/examples/fleet-managed/README.md
- deploy/helm/elastic-agent/examples/fleet-managed/fleet-values.yaml
- deploy/helm/elastic-agent/examples/fleet-managed/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/kubernetes-default/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/kubernetes-only-logs/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/nginx-custom-integration/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/system-custom-auth-paths/rendered/manifest.yaml
- deploy/helm/elastic-agent/templates/agent/k8s/_pod_template.yaml
- deploy/helm/elastic-agent/templates/agent/k8s/_secret.tpl
- deploy/helm/elastic-agent/templates/agent/k8s/secret.yaml
This PR forwards providers configuration for managed agents (fleet mode)
Because users need to be able to disable/enabled leader election or/and kubernetes providers for managed agents
N/A
```
mage helm:renderExamples
```
- Relates https://github.com/elastic/elastic-agent/issues/5558
> [helm]: forward agent providers configuration for fleet mode

- deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/fleet-managed/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/kubernetes-default/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/kubernetes-only-logs/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/nginx-custom-integration/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/system-custom-auth-paths/rendered/manifest.yaml
- deploy/helm/elastic-agent/templates/agent/_helpers.tpl
- deploy/helm/elastic-agent/values.yaml
This PR disables by default the kubernetes leader election unless a user explicitly marks it as enabled. More importantly this PR sets the lease name from the Helm release and the agent preset names and thus different agent deployments won't utilise the same lease now.
Because it guarantees correct lease isolation across different agent deployments in the same namespace
N/A
follow [the kubernetes example](https://github.com/elastic/elastic-agent/tree/main/deploy/helm/elastic-agent/examples/kubernetes-default) and do two installations of the Helm chart with a different release name and under the same namespace (leases are namespace-scoped). With this PR you will see that two leases are created for the `clusterWide` preset where before there would be only one
- Relates …
> [helm] derive the lease name from the release and preset names

- pkg/testing/define/define.go
- pkg/testing/define/define_flags.go
- pkg/testing/define/parser.go
- testing/integration/main_test.go
This PR adds a `TestMain()` to the `testing/integration` package to allow passing some command-line arguments when running integration tests using `go test`:
- `-integration.groups` allows to specify a comma-separated list of groups to filter on
- `-integration.dry-run` will validate define constraints but will skip the real tests that contain `define` directives and add a placeholder `<Test name>/dry-run` which will pass if all the `define` checks pass
The `groups` flag allows for a simple way of selecting a subset of tests (for either real running or dry-runs)
The `sudo` flag allows to filter tests based on their sudo requirements (if those need to run as root/administrator or not)
The `dry-run` argument allows for quick execution when experimenting with group filtering (making sure …
> Introduce filter by group and dry-run for integration tests

- pkg/testing/tools/git/git.go
- pkg/testing/tools/git/git_test.go
So, we can support the new 9.0 release, 8.x branch and the rest of the release branches.
It's fixing wrong automation behavior, for example like here https://github.com/elastic/elastic-agent/pull/5953 and here https://github.com/elastic/elastic-agent/pull/5948
~- [ ] I have made corresponding changes to the documentation~
~- [ ] I have made corresponding change to the default configuration files~
~- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~
~- [ ] I have added an integration test or an E2E test~
> Add support of the new branch setup to the version update automation

- testing/proxytest/proxytest.go
Makes the proxytest to wait all requests to finish before closing the underlying HTTP server
The request log sometimes happens after the tests has finished, what causes the test to panic
```
go test -count 15000 -timeout 0 -run TestHTTPSProxy ./testing/proxytest/
```
- Closes https://github.com/elastic/elastic-agent/issues/5869
- How are we going to support this in …
> [proxytest] Wait all requests to finish before closing the server

- deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/fleet-managed/fleet-values.yaml
- deploy/helm/elastic-agent/examples/user-cluster-role/README.md
- deploy/helm/elastic-agent/examples/user-cluster-role/agent-nginx-values.yaml
- deploy/helm/elastic-agent/examples/user-cluster-role/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/user-service-account/README.md
- deploy/helm/elastic-agent/examples/user-service-account/agent-kubernetes-values.yaml
- deploy/helm/elastic-agent/examples/user-service-account/rendered/manifest.yaml
- deploy/helm/elastic-agent/templates/agent/_helpers.tpl
- deploy/helm/elastic-agent/templates/agent/cluster-role-binding.yaml
- deploy/helm/elastic-agent/templates/agent/cluster-role.yaml
- deploy/helm/elastic-agent/templates/agent/eck/_pod_template.yaml
- deploy/helm/elastic-agent/templates/agent/k8s/_pod_template.yaml
- deploy/helm/elastic-agent/templates/agent/service-account.yaml
- deploy/helm/elastic-agent/values.schema.json
- deploy/helm/elastic-agent/values.yaml
This PR introduces the capability for users to bind agent presets with custom service accounts and cluster roles, rather than relying solely on auto-generated or default configurations. This allows greater control over security and permissions for agent interactions. Additionally, it provides support for adding annotations to these bindings, allowing for custom metadata that can be leveraged by observability and monitoring tools to enhance tracking, auditing, and configuration management.
This added flexibility ensures that the Helm chart can be better aligned with organizational policies and infrastructure requirements of users.
N/A
```
mage helm:renderExamples
```
- Relates https://github.com/elastic/elastic-agent/issues/5558 as this PR exposes …
> [helm] support using user-created serviceAccount and clusterRole

- .ci/updatecli/updatecli-bump-golang.yml
- go.mod
So, we have the Go version in `go.mod` synced to the rest of the values.
I used a simplified updatecli configuration that includes these changes:
```yaml
---
name: Bump golang-version to latest version
sources:
latestGoVersion:
name: Get minor version in .go-version
kind: shell
transformers:
- findsubmatch:
pattern: '^(\d+.\d+.\d+)$'
captureindex: 1
spec:
command: cat test-version
conditions:
goDefaultVersion-check:
name: Check if defined golang version differs
kind: shell
sourceid: latestGoVersion
spec:
command: 'grep -v -q {{ source "latestGoVersion" }} .go-version #'
targets:
update-go-version:
name: 'Update .go-version'
sourceid: latestGoVersion
kind: file
spec:
content: '{{ source "latestGoVersion" }}'
file: .go-version
matchpattern: '\d+.\d+.\d+'
update-golang.ci:
name: 'Update …
```
> Add go.mod full version support to updatecli

- deploy/helm/elastic-agent/examples/README.md
- deploy/helm/elastic-agent/examples/kubernetes-default/README.md
- deploy/helm/elastic-agent/templates/agent/eck/deployment.yaml
- deploy/helm/elastic-agent/templates/agent/eck/statefulset.yaml
- deploy/helm/elastic-agent/templates/agent/k8s/deployment.yaml
- deploy/helm/elastic-agent/templates/agent/k8s/statefulset.yaml
This PR sets correctly the replicas of agent presets (including the value of `0`) and fixes some markdown issues in the chart examples
Because users should be able scale presets according to their needs
N/A
Follow [kubernetes example](https://github.com/elastic/elastic-agent/blob/main/deploy/helm/elastic-agent/examples/kubernetes-default/README.md) and in the install command add this `--set agent.presets.clusterWide.replicaCount=2` or `--set agent.presets.clusterWide.replicaCount=0`
N/A
> [helm] agent preset replicas

- .buildkite/bk.integration.pipeline.yml
- .buildkite/scripts/steps/ess_start.sh
- .buildkite/scripts/steps/integration_tests_tf_sudo.sh
- .buildkite/scripts/sudo-integration-tests.sh
- test_infra/ess/deployment.tf
Enhances the buildkite tests pipeline by ARM tests. It uses the prebuilt Ubuntu 24.04 ARM image
Runs integration test groups separately. Allows independent reruns.
Tested here: [Example build](https://buildkite.com/elastic/elastic-agent-extended-testing-bk/builds/33#_). 
Note: It doesn't replace current integration tests. The new buildkite pipeline is not triggered by GitHub events
We have to test elastic agent on ARM architecture
- Closes https://github.com/elastic/ingest-dev/issues/4217
- Relates #123
- Requires #123
- Superseds #123
- ...
> [CI] Buildkite integration tests: Run integration tests on ARM

- deploy/helm/elastic-agent/templates/agent/eck/_pod_template.yaml
- deploy/helm/elastic-agent/templates/agent/k8s/_pod_template.yaml
- deploy/helm/elastic-agent/values.schema.json
This PR adds support for specifying `envFrom` in the pod template of the Helm chart. By introducing this feature, users can configure environment variables from ConfigMaps or Secrets more flexibly and efficiently. The change modifies the pod template to include a new section that allows injecting `envFrom` values, providing an enhanced way to handle environment settings.
This enhancement is useful for users who need to manage environment variables dynamically through ConfigMaps or Secrets e.g. through ExternalSecrets.
N/A
1. create a k8s secret with the name `$secretName`
2. follow the [kubernetes example](https://github.com/elastic/elastic-agent/blob/main/deploy/helm/elastic-agent/examples/kubernetes-default/README.md) and add this param `--set …
> [helm] add envFrom in agent preset

- deploy/helm/elastic-agent/examples/nginx-custom-integration/README.md
- deploy/helm/elastic-agent/examples/nginx-custom-integration/agent-nginx-values.yaml
- deploy/helm/elastic-agent/examples/nginx-custom-integration/rendered/manifest.yaml
- deploy/helm/elastic-agent/templates/agent/cluster-role-binding.yaml
- deploy/helm/elastic-agent/templates/agent/eck/_pod_template.yaml
- deploy/helm/elastic-agent/templates/agent/k8s/_pod_template.yaml
- deploy/helm/elastic-agent/values.schema.json
This PR resolves two key issues:  
1. It enables disabling cluster role creation without needing to specify an existing role name.  
2. It allows falling back to the `default` service account by disabling service account creation without specifying an existing one.
Additionally, it updates the nginx custom integration example to demonstrate how to deploy an elastic agent with Kubernetes providers, leader election, cluster role, and service account creation all disabled.
These changes are essential for improving the configuration flexibility of the deployment process. By allowing cluster role creation to be disabled without requiring the specification of an existing role name, users gain the ability to simplify permissions management. This is particularly useful in environments where …
> [helm] fix disabling cluster role and service account

- go.mod
- go.sum
- testing/integration/otel_test.go
Adds an integration test that:
1. creates a file with newline separated entries
2. creates an otel configuration to read the file using the filebeat receiver, and write to elasticsearch
3. searches elasticsearch to make sure the entries were written
Also updates to latest beat code to get otelconsumer error checking.
End to End test of the otel filebeat receiver
None
```shell
PLATFORMS="linux/arm64,linux/amd64,windows/amd64" PACKAGES="rpm,deb,tar.gz" mage -v clean package
mage integration:auth
mage integration:single TestOtelFBReceiverE2E
```
- Closes elastic/ingest-dev#3489
- ...
> Add filebeat receiver end to end test

- testing/integration/logs_ingestion_test.go
- Enhancement
Updates exlcudeded error strings in the logs_ingestion_test
Error messages generated by the "add_cloud_metadata" processor have been updated as shown [here](https://github.com/elastic/beats/pull/41477/files#diff-54e31882d706ede511023836a842dd7c1e570ce1eab2c7208601afacee49a995L190). These changes break the test case that is the subject of this PR. …
> fix: updated excluded error strings

- changelog/fragments/1731517501-removed-endpoint-security-from-linux-containers.yaml
- dev-tools/mage/manifest/manifest.go
- dev-tools/mage/pkgcommon/pkgcommon-types.go
- dev-tools/mage/pkgtypes.go
- magefile.go
- Enhancement
The goal of this implementation is to remove endpoint security from linux containers. Since we currently do not distribute any container other than linux containers ([source](https://www.elastic.co/guide/en/fleet/current/elastic-agent-container.html)), this PR does not consider selected platforms when excluding the endpoint security from container images.
Endpoint security cannot run in containers since it has a systemd dependency. …
> Remove endpoint security from linux containers

- changelog/fragments/1731500837-pod-status-updates.yaml
- internal/pkg/composable/providers/kubernetes/pod.go
- internal/pkg/composable/providers/kubernetes/pod_test.go
The kubernetes provider emits data each time a Pod gets updated, even if the Pod is not yet running. As a result, every time a new Pod is spawned, we get multiple updates as it is created, scheduled, containers are created, and so on. Instead, emit the data only if the Pod is actually running.
Configuration reloading can be quite expensive when there are a lot of Pods on the Node. We should avoid doing so unnecessarily. This change should help #5835 and #5991.
Note that in principle this exposes us to a new failure mode. It's possible for the Pod to successfully finish running and be removed before we push the new configuration to beats. This was much less likely when we included the Pod when it was scheduled, but still possible with our 100ms debounce timer in the coordinator. I think …
> Emit Pod data only for running Pods in the Kubernetes provider

- testing/integration/otel_test.go
current `TestOtelFileProcessing` integration test reads from /var/log/syslog.  This creates permission issues and won't work on Windows.
This change makes a new input file for each run in the test temporary directory and reads from that.  This makes the test self contained and it should work on Windows when that is available.
None.  Integration test
```shell
mage integration:auth
mage integration:single TestOtelFileProcessing
```
-
- ...
> Improve TestOtelFileProcessing integration test

- changelog/fragments/1731951823-Skip-notify-Fleet-on-Windows-uninstall.yaml
- internal/pkg/agent/install/uninstall.go
- testing/integration/install_test.go
Skips calling `notifyFleetAuditUninstall` on Windows.
When enabled it makes it much more likely that a panic will occur, but this doesn't actually seem like the culprit it just makes it more likely to happen.
**NOTE**: This doesn't actually fix the issue on Windows, it just makes it less likely to occur. Even with this disabled I am still seeing uninstall failing on like the 68th retry, but with this enabled it more likely happens on the 6-8th try. This is just reducing the likely that this issue occurs, it is not actually fixing the issue. (Just want to make that clear).
Reduces changes that uninstall happens on Windows.
- ~~[ ] I have made …
> Skip notifyFleetAuditUninstall on Windows

- .buildkite/pipeline.yml
Adds MacOS 15 ARM tests unit tests for PRs and merge to release branches.
Makes MacOS 13 x86 tests run only on main and release branches
MacOS 14 is expected in a follow-up PR
- Relates https://github.com/elastic/ingest-dev/issues/4038
-
- ...
> [CI] MacOS 15 testing

- internal/pkg/agent/application/coordinator/diagnostics_test.go
- internal/pkg/agent/application/monitoring/v1_monitor.go
- internal/pkg/agent/application/monitoring/v1_monitor_test.go
- internal/pkg/core/monitoring/config/config.go
Use `failure_threshold` introduced in https://github.com/elastic/beats/pull/41570 in self-monitoring configuration to avoid elastic-agent reporting DEGRADED if it fails to fetch metrics due to a component starting/stopping.
The default value for the failure threshold is set to 2 but it can be configured via config file or fleet policy.
It is important to avoid a misrepresentation of agent status due to a single metrics fetch erroring out once.
See https://github.com/elastic/elastic-agent/issues/5332
- ~~[ ] I …
> Add failureThreshold to elastic-agent self-monitoring config

- deploy/helm/elastic-agent/templates/agent/cluster-role-binding.yaml
- deploy/helm/elastic-agent/templates/agent/cluster-role.yaml
- deploy/helm/elastic-agent/templates/agent/eck/daemonset.yaml
- deploy/helm/elastic-agent/templates/agent/eck/secret.yaml
- deploy/helm/elastic-agent/templates/agent/k8s/_secret.tpl
- deploy/helm/elastic-agent/templates/agent/k8s/secret.yaml
- deploy/helm/elastic-agent/templates/agent/service-account.yaml
- magefile.go
This PR extends the Helm lint checks in our CI pipeline to validate all examples in the Helm chart. Previously, the `helm template` command passed successfully but was insufficient because `helm lint` could still fail. By ensuring comprehensive linting, we address inconsistencies and prevent errors during deployment.
Key changes include:
- Adding additional lint checks to cover example configurations in the Helm chart.
This change is important to ensure consistency across our Helm chart configurations. By extending the lint checks to include all examples, we can catch issues ( such as the ones seen in this [Buildkite job](https://buildkite.com/elastic/elastic-agent/builds/14137#01933fce-e319-497b-af4e-91162d5a3371/105-1152)) early in the CI pipeline, reducing the risk of deployment …
> [helm] add lint checks for renderExamples

- internal/pkg/agent/transpiler/ast.go
- internal/pkg/agent/transpiler/ast_test.go
- internal/pkg/agent/transpiler/vars.go
- internal/pkg/composable/controller.go
We generate vars from mappings from both context providers and dynamic providers. Dynamic providers can produce multiple var entries - the Kubernetes provider will do so for each Pod, for example. When that happens, we currently make a deep copy of the context provider mapping, and add the dynamic provider mapping as a key.
As we don't modify the mappings, this deep copy can be replaced by a shallow copy. This PR introduces shallow copying to the AST and uses it when generating vars, leading to a major performance improvement.
All these deep copies can be quite expensive when there's a lot of mappings from the dynamic provider. See the benchstat report below:
```
goos: linux
goarch: amd64
pkg: github.com/elastic/elastic-agent/internal/pkg/composable
cpu: 13th Gen Intel(R) Core(TM) …
```
> Don't deepcopy AST when generating vars

- testing/integration/escaping_secrets_in_policy_test.go
- Bug
Skips test that was added in #5987 
The test is flaky, will skip until it is fixed
- Relates #6107
> fix(6107): skipping escaping secrets in policy test because it is flaky

- internal/pkg/otel/manager/manager_test.go
Flaky test issue https://github.com/elastic/elastic-agent/issues/6119
> mark and skip flaky TestOTelManager_Run

- internal/pkg/agent/transpiler/ast.go
- internal/pkg/composable/benchmark_test.go
- internal/pkg/composable/controller.go
For all variable provider types, we store mappings as untyped dictionaries and only convert them to AST when we're about to generate actual vars. This means we have to recompute all of it every time there's a change to any of the provider data, even if all the other data is unaffected. For example, if a Kubernetes Pod gains a new label, we need to regenerate vars for all Pods.
Instead, we can store mappings as AST to begin with. Then the only cost of emitting new vars after a change is updating a bunch of references.
This unnecessary recomputation can be quite expensive when there's a lot of mappings from the dynamic provider. See the benchstat report below:
```
goos: linux
goarch: amd64
pkg: github.com/elastic/elastic-agent/internal/pkg/composable
cpu: 13th Gen Intel(R) Core(TM) …
```
> Store AST directly in provider mappings

- changelog/fragments/1732840106-Only-run-providers-referenced-in-the-policy.yaml
- internal/pkg/agent/application/coordinator/coordinator.go
- internal/pkg/agent/application/coordinator/coordinator_test.go
- internal/pkg/agent/cmd/run.go
- internal/pkg/agent/transpiler/ast.go
- internal/pkg/agent/transpiler/ast_test.go
- internal/pkg/agent/transpiler/vars.go
- internal/pkg/agent/vars/vars.go
- internal/pkg/composable/benchmark_test.go
- internal/pkg/composable/config.go
- internal/pkg/composable/controller.go
- internal/pkg/composable/controller_test.go
This updates the Elastic Agent to only run composable providers if they are referenced in the policy.
This change provides the following benefits:
- Reduces the memory and load of the Elastic Agent, by only running the providers it references.
- No longer requires access to the kubernetes API or resources just to run an Elastic Agent (as long as its not using any ${kubernetes*` references in the policy).
- Fixes an issue where if no providers are running that a set of empty variables is passed to the coordinator.
- ~~[ ] I have added an integration test or an E2E test~~ (covered by unit tests)
None. As it still runs all those that are referenced …
> Only run providers that are referenced in the policy

- CONTRIBUTING.md
@ycombinator: Let's wait till at least 2/3 of the reviewers tagged on this PR have approved it.  It's an unusually high bar but I'd rather we clear that first than have pushback later.
Add indications about expected size of PRs in CONTRIBUTING.md
To improve code review experience.
- ~~[ ] I …
> Add an indicative limit for judging if a PR is too big in PR guidelines

- internal/pkg/agent/application/actions/handlers/handler_action_upgrade_test.go
What it says on the tin.
This skip should be reverted when the flaky test failure is investigated and fixed, as part of https://github.com/elastic/elastic-agent/issues/5938.
> Skipping flaky unit test: `TestUpgradeHandlerSameVersion`

- README.md
This PR removes the currently-broken SonarQube badge from the Elastic Agent README file.  
Elastic's SonarQube instance is private (hosted at sonar.elastic.dev instead of the public sonarcloud.io).  As such a security token is needed as part of the badge image URL.  Since the elastic-agent repository is public, it would not be a good idea to expose this token.  So we remove the badge instead of trying to replace it.
> Remove SonarQube badge from README

- .buildkite/bk.integration.pipeline.yml
Adds `build/diagnostics` to Builkite artifacts. Diagnostics are generated in the case of a test failure. 
[Example build](https://buildkite.com/elastic/elastic-agent-extended-testing-bk/builds/291#0193ab20-66d7-41eb-837e-3905c2a6e2df) (fleet-upgrade-to-pr-build). Tested it by setting `AGENT_COLLECT_DIAG=true`
Diagnostics are essential for tests troubleshooting
- Closes https://github.com/elastic/ingest-dev/issues/4671#issuecomment-2521221563
- ...
> [CI] Add build/diagnostics dir to artifacts

- changelog/fragments/1733158776-avoid-copies-config-gen.yaml
- internal/pkg/agent/application/coordinator/coordinator.go
- internal/pkg/agent/transpiler/ast.go
- internal/pkg/agent/transpiler/ast_test.go
- internal/pkg/agent/transpiler/utils.go
Remove some unnecessary copies when generating component configuration.
The first copy avoided is done because we want to replace the `inputs` key with the rendered inputs. A shallow copy is sufficient for this. I did find and fix a bug in Dict shallow copies while at it.
The rest of the copies have to do with applying vars to each AST node. We currently make a copy of each Node we do this for, but that's not necessary, as `Apply` creates a new Node with all the data recursively copied anyway. I've added a test to verify that `Apply` actually works this way.
Benchstat result vs `main`, using the benchmark from #6180:
```
goos: linux
goarch: amd64
pkg: github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator
cpu: 13th Gen Intel(R) Core(TM) i7-13700H
│ bench_main.txt │ …
```
> Avoid unnecessary copies during config generation

- changelog/fragments/1733238171-use-xxhash-for-ast-hashing.yaml
- go.mod
- internal/pkg/agent/transpiler/ast.go
- internal/pkg/agent/transpiler/utils.go
We currently use sha256 for hashing AST nodes when generating configuration. This is used both for checking equality between AST instances and for avoiding recomputing inputs unnecessarily. This PR changes this to xxHash, which is much faster. It also changes the interface, letting the caller supply their own hasher instance, and avoiding needing to allocate one for each Node in the tree.
Of note is that I'm using the `xxhash.Digest` struct as an argument instead of the generic `hash.Hash64` interface from the standard library. The reason is that the former has an optimized `WriteString` method, which avoid needing to cast the string to a byte slice. I also don't expect to need to actually supply different hash implementations to this method.
Note also that there's already fairly …
> Use xxhash instead of sha256 for hashing AST nodes

- changelog/fragments/1733131399-vars-for-platform.yaml
- pkg/component/component.go
- pkg/component/platforms.go
We were doing the check for external package manager use when validating vars for the platform, which happens on every configuration reload. I've made this an attribute of the platform instead, and it's now only checked on startup.
Reading a bunch of files every time configuration is reloaded is an unnecessary expense.
- Relates #5835 #5991
> Do external package manager check only at startup

- go.mod
- testing/integration/kubernetes_agent_service_test.go
- testing/integration/kubernetes_agent_standalone_test.go
- testing/integration/otel_helm_test.go
This PR lays the groundwork for Kubernetes hints integration tests. The related commits of the former will be included in a follow-up PR (https://github.com/elastic/elastic-agent/commit/6fa8ffb27756ed1dacb4543045aed4c6e7749e02, https://github.com/elastic/elastic-agent/commit/9a48d023c3e4feae03dfd5fb62cee99bbed4abc3) as I want to keep this PR around [500 lines](https://github.com/elastic/elastic-agent/blob/main/CONTRIBUTING.md?plain=1#L47) (excluding go.mod and NOTICE files). These changes address the need to avoid duplicating code logic, as hints tests require deploying plain Kubernetes YAML files and checking the agent status independently. Key updates include:
- **Centralized Context**: Introduced `k8sContext` to standardize Kubernetes test setup.
- **Refactored Helpers**: Streamlined …
> [k8s]: restructure kubernetes integration tests

- .buildkite/bk.integration.pipeline.yml
- .buildkite/integration.pipeline.yml
- .buildkite/pipeline.yml
- docs/test-framework-dev-guide.md
Runs the new integration testing infrastructure provisioned by buildkite and terraform (ESS)
Integration tests take 1 h 10 minutes instead of ~1:30. 
Independent test groups execution allows to retry tests independently with a dedicated ESS stack:
[Build example 1](https://buildkite.com/elastic/elastic-agent-extended-testing/builds/4907#01936da4-9be4-446b-a01c-d1721b3c21c6)
[Build example 2](https://buildkite.com/elastic/elastic-agent-extended-testing/builds/4908)
[Build example 3](https://buildkite.com/elastic/elastic-agent-extended-testing/builds/4920)
[Build example 4](https://buildkite.com/elastic/elastic-agent-extended-testing/builds/4939)
By comparing test reports, I verified that we run the same test sets for groups. Placed the tests in groups in this …
> Run BK integration tests on PRs and release branches

- changelog/fragments/1733411331-cache-conditions-in-config.yaml
- internal/pkg/agent/transpiler/ast.go
- internal/pkg/agent/transpiler/ast_test.go
Our configurations can have conditional sections. The conditions are expressed in an EQL-like syntax, and we parse the expressions lazily on evaluation. However, we don't cache the parsed expression, and parse it every time it's evaluated. This change instead only parses the condition expression once, and it's then cached in the AST node.
When there are a lot of variables from dynamic providers - notably in Kubernetes, on a Node with a lot of Pods - we end up spending significant resources on re-parsing the condition expressions for every var entry.
See benchstat showing the effect of this change on the benchmark from #6180 (not that this includes #6184, as otherwise we just make a copy before applying and never actually use the cache):
```
goos: linux
goarch: amd64
pkg: …
```
> Cache conditions when applying variables to config

- go.mod
- go.sum
What it says on the tin.  Replaces https://github.com/elastic/elastic-agent/pull/6258 as there were too many conflicts on that PR.
> Bump github.com/elastic/elastic-agent-libs from 0.17.3 to 0.17.4

- .github/workflows/bump-agent-versions.sh
Now the script can be run on a matrix for multiple release branches.
- Superseds https://github.com/elastic/elastic-agent/pull/6309
> Add support for running version updates on multiple branches

- .github/workflows/bump-agent-versions.yml
Before we had to manually trigger the update version automation for all branches other than `main`.
Was tested by triggering the job manually, see https://github.com/elastic/elastic-agent/actions/runs/12303810957/
- Closes https://github.com/elastic/elastic-agent/issues/5897
> Run agent test version bump on all active branches

- .github/workflows/bump-agent-versions.sh
Rename the branch name created for the automation
Avoid matching branches enrolled to the branch protection.
For instance, https://github.com/elastic/elastic-agent/pull/6318 was created using `8.x-update-agent-versions-12303810957`, and there is a branch protection for `8.*`; therefore, it has some constraints about PR development.
-
- ...
> fix: use a different branch name for the auto-updates

- testing/integration/kubernetes_agent_service_test.go
- testing/integration/kubernetes_agent_standalone_test.go
This PR continues the groundwork for Kubernetes hints integration tests. The next and last episode of this PR-series can be seen here https://github.com/elastic/elastic-agent/commit/2ea1f2ff2cdf57442ea29c1e5c269b907971c312. Again these were split up because I want to keep each PR around [500 lines](https://github.com/elastic/elastic-agent/blob/main/CONTRIBUTING.md?plain=1#L47). 
Key changes in this PR:
1. **Transition Kubernetes integration tests to an "adapter" pattern**:
- Refactors Kubernetes integration tests to follow a more modular and reusable adapter pattern.
- Introduces `k8sTestStep` functions that encapsulate individual test steps for clarity and flexibility.
- Simplifies the test flow by eliminating repetitive code and leveraging reusable functions like …
> [k8s]: transition integration tests to adapter pattern

- changelog/fragments/1734098868-prevent-leaking-secrets-when-logging-component-model.yaml
- internal/pkg/agent/application/coordinator/coordinator.go
- pkg/component/component.go
- pkg/component/component_test.go
Implements `MarshalJSON` method on the `component.Component` struct, so that when the component model is logged, the output does not contain any secrets that might be part of the component model (e.g. API keys to HTTP endpoints etc.).
This change also restores the debug log dumping the component model that was removed in https://github.com/elastic/elastic-agent/pull/5201/.
This is part of the effort to prevent leaking secrets in logs as much as possible.
- ~~[ ] I have added an integration …
> Prevent leaking secrets when logging component model

- changelog/fragments/1734512365-embed-hints-inputs-in-agent-container-image.yaml
- deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_hints.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_preset_pernode.tpl
- dev-tools/packaging/package_test.go
- dev-tools/packaging/packages.yml
- internal/pkg/agent/application/application.go
- internal/pkg/composable/providers/kubernetes/config.go
- internal/pkg/composable/providers/kubernetes/config_test.go
- internal/pkg/config/loader.go
This PR embeds the hints-based autodiscovery templates directly into the Elastic Agent container image. These templates, previously fetched by an init container, are now included in the image under `/usr/share/elastic-agent/hints.inputs.d`. The Elastic Agent has been updated to optionally use these embedded templates based on the Kubernetes hints configuration in the user's settings. If hints-based autodiscovery is enabled, the Elastic Agent dynamically reads from the embedded templates directory, ensuring seamless integration without external dependencies.
Additionally:
- Introduced a new mechanism for discovering hints-based inputs dynamically from the embedded directory.
- Updated CI to package the templates into the container image during the build process.
- Modified the Helm chart …
> [k8s] embed hints inputs in agent container image

- deploy/helm/elastic-agent/README.md
- deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/fleet-managed/README.md
- deploy/helm/elastic-agent/examples/fleet-managed/fleet-values.yaml
- deploy/helm/elastic-agent/examples/fleet-managed/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/kubernetes-default/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/kubernetes-only-logs/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/system-custom-auth-paths/agent-system-values.yaml
- deploy/helm/elastic-agent/examples/system-custom-auth-paths/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/user-service-account/rendered/manifest.yaml
- deploy/helm/elastic-agent/templates/agent/_helpers.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_preset_pernode.tpl
- deploy/helm/elastic-agent/values.yaml
This PR introduces several fixes to the Elastic Agent Helm chart regarding Fleet Mode deployments:
- Fleet mode now includes the necessary Kubernetes changes (e.g., volume mounts, resource requests) for enabled integrations.
- Leader election is enabled by default for Fleet mode unless explicitly disabled by the user in the agent preset.
- Kubernetes integration is now enabled by default.
- Sets `hostNetwork=true` for `perNode` (`Daemonset`) agent preset, used by kubernetes and system integrations
These changes are critical as they address bugs 🙂 
N/A
- You can see in the …
> [helm] fleet mode fixes

- testing/integration/beats_serverless_test.go
Relates https://github.com/elastic/elastic-agent/issues/6431
temporarily skip TestBeatsServerless to unblock other PRs on main. I'm currently working on a permanent fix.
> [flaky] temporarily skip TestBeatsServerless

- internal/pkg/config/config.go
- internal/pkg/config/test/tls_version_test.go
- internal/pkg/config/testdata/tls.yml
- internal/pkg/config/testdata/tls10.yml
Call `tlscommon.SetInsecureDefaults` from within an init func in the config package.
Avoid a planned breaking change for tlscommon versions
- ~~My code follows the style guidelines of this project~~
- ~~I have commented my code, particularly in hard-to-understand areas~~
- ~~I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~~
N/A
- Relates https://github.com/elastic/elastic-agent/issues/5996
> Call tlscommon.SetInsecureDefaults

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
This PR:
* adds a statement to the [pull request guidelines](https://github.com/elastic/elastic-agent/blob/main/CONTRIBUTING.md#pull-request-guidelines), asking PR reviewers to provide a rationale for any suggestions.   This was a suggestion made by @pkoutsovasilis in today's Agent Control Plane team meeting.
* links to the PR guidelines from the PR template.
> Update pull request guidelines

- _meta/config/common.p2.yml.tmpl
- _meta/config/common.reference.p2.yml.tmpl
- elastic-agent.reference.yml
- elastic-agent.yml
Add Journald to the examples and default configuration
Linux distributions like Debian 12 are migrating away from traditional log files in favour of journald to system logs, we need good examples of how to ingest those logs.
- It's part of https://github.com/elastic/beats/issues/37877
- ...
> Add Journald to the examples and default configuration

- magefile.go
Before this change we were building all possible Docker images to produce the cloud image. Which is unnecessary and takes a long time.
Now only the `cloud` variant is built. 
**On my machine this reduces this build time from 27 to 20 minutes.**
For testing:
```sh
mage cloud:image
```
Or follow this guide https://github.com/elastic/elastic-agent?tab=readme-ov-file#testing-on-elastic-cloud
> Build only cloud image variant when it's requested

- changelog/fragments/1735137195-remove-deprecated-list-in-favor-of-items.yaml
- internal/pkg/agent/cmd/container.go
- internal/pkg/agent/cmd/container_test.go
- testing/integration/validate_items_deprecated_list_test.go
- Bug
Replaces `list` with `items` from from `kibanaFetchToken` as the `list` is deprecated in the api response and will be removed.
The `list` in the api response is going to be removed in favor of `item`
There shouldn't be any user impact
- Deploy ESS
- Build the agent by running the following command
```
SNAPSHOT=true PLATFORMS="linux/arm64" PACKAGES="docker" EXTERNAL=true mage -v package
```
- Then get the image id for any of the created elastic-agent images and run the following command
```
docker run \
--env FLEET_ENROLL=1 \
--env KIBANA_HOST=<KIBANA HOST> \
--env …
```
> fix(6023): replace list with items

- deploy/helm/elastic-agent/examples/netflow-service/README.md
- deploy/helm/elastic-agent/examples/netflow-service/agent-netflow-values.yaml
- deploy/helm/elastic-agent/examples/netflow-service/rendered/manifest.yaml
- deploy/helm/elastic-agent/templates/agent/eck/_pod_template.yaml
- deploy/helm/elastic-agent/templates/agent/eck/deployment.yaml
- deploy/helm/elastic-agent/templates/agent/eck/statefulset.yaml
- deploy/helm/elastic-agent/templates/agent/k8s/_pod_template.yaml
- deploy/helm/elastic-agent/templates/agent/k8s/daemonset.yaml
- deploy/helm/elastic-agent/templates/agent/k8s/deployment.yaml
- deploy/helm/elastic-agent/templates/agent/k8s/statefulset.yaml
- deploy/helm/elastic-agent/templates/agent/service.yaml
- deploy/helm/elastic-agent/values.schema.json
This PR introduces support for automatically creating Kubernetes services for specific Elastic Agent presets through the Helm chart. It adds a structured and scalable mechanism for managing and exposing agent instances within the Kubernetes cluster. This enhancement allows users to define service configurations (e.g., type, ports) for push-based integrations like NetFlow. 
Key changes:
1. Added logic in the Helm chart to generate services for agent presets when specified in `values.yaml`.
2. Introduced configuration examples for creating a `NodePort` service linked to a NetFlow agent preset.
3. Updated schema definitions in `values.schema.json` to support new service and port configuration options.
This enhancement simplifies the deployment and operational management of push-based …
> [helm] add support for creating services for agent presets

- changelog/fragments/1735664420-remove-deprecated-path-install-cli-flag.yaml
- internal/pkg/agent/application/paths/common.go
- internal/pkg/agent/cmd/common.go
- internal/pkg/agent/cmd/container.go
- internal/pkg/agent/cmd/enroll_cmd.go
- Breaking change
Removes `--path.install` flag declaration from the paths command and removes its use from container and enroll commands
This command is currently ignored and deprecated
Any client using `--path.install` flag will fail
- Deploy ess
- Prepare necessary packages for testing
- tar.gz
- docker
- Try to install tar.gz with `path.install` and verify that the installation fails
- Install tar.gz without the flag and …
> cleanup(2489): removed path.install option from the paths command, removed any usage of this command

- changelog/fragments/1735833843-Restore-cloud-defend..yaml
- dev-tools/mage/manifest/manifest.go
The cloud-defend binary was accidentally removed from 8.x starting with 8.17.0 in the backport for https://github.com/elastic/elastic-agent/pull/6042/files, likely as part of merge conflict resolution.
Includes the cloud-defend binary in the agent docker container again.
Defend for containers which is implemented by cloud-defend is still a supported product in 8.x.
```sh
DOCKER_VARIANTS=basic EXTERNAL=true SNAPSHOT=true PACKAGES=docker PLATFORMS=linux/arm64 mage package
docker run -it --entrypoint /bin/bash docker.elastic.co/beats/elastic-agent:8.18.0-SNAPSHOT
elastic-agent@240c9b878938:~$ ls data/elastic-agent-1f89c7/
components  elastic-agent  logs  otelcol  package.version
elastic-agent@240c9b878938:~$ ls data/elastic-agent-1f89c7/components/
LICENSE.txt …
```
> [8.x] restore cloud defend as an expected binary

- magefile.go
This PR fixes an issue with the Helm chart examples rendering. Specifically, the Helm chart is now reloaded for each example folder. Previously, the chart was loaded once and reused, which leads to stale data when different examples enable or disable subchart dependencies (spoiler alert for the upcoming kube-state-metrics subchart dependency PR I am working on).
Reloading the Helm chart for each example folder ensures correctness in the rendered k8s manifests.
```
mage helm:renderExamples
```
N/A
> [helm] reload chart for each example folder

- internal/pkg/agent/application/actions/handlers/handler_action_upgrade_test.go
Fix flaky test TestUpgradeHandlerSameVersion by increasing the maximum timeout to a generous 1 second. This does not extend the normal test execution time, so no reason to make this timeout too restrictive.
We don't want flaky tests.
- Closes https://github.com/elastic/elastic-agent/issues/5938
> Fix flaky test TestUpgradeHandlerSameVersion

- .buildkite/pipeline.yml
Run integration tests on changes to K8s packaging. Ideally we'd only run the k8s integration tests here, but all of them will do for now.
We shouldn't merge changes to K8s packaging without integration tests passing.
> Run integration tests on changes to K8s packaging

- changelog/fragments/1736520682-restore-maintainer-label.yaml
- dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Restore maintainer label to container images. It's deprecated, and was removed in #5527.
If we don't set this label, it's inherited from the base image. For UBI images, the value is "Red Hat Inc", and Red Hat's preflight validation complains about it.
I'm submitting this directly to the 8.16 branch in the name of speed, as this is blocking the 8.16 build candidate.
- Relates #5527 
- ...
> [8.16] Restore maintainer label to container images

- changelog/fragments/1736520682-restore-maintainer-label.yaml
- dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
If we don't set this label, it's inherited from the base image. For UBI images, the value is "Red Hat Inc", and Red Hat's preflight validation complains about it.
Manual backport of https://github.com/elastic/elastic-agent/pull/6512.
> [8.17] Restore maintainer label to container images

- internal/pkg/otel/samples/darwin/logs_metrics_traces.yml
- internal/pkg/otel/samples/linux/logs_metrics_traces.yml
Adds batch processor before lsm interval processor. This reduces the merge operation that lsm interval processor needs to perform and improves performance.
To improve performance of lsm interval processor. For more details checkout https://github.com/elastic/opentelemetry-collector-components/issues/211
- Relates https://github.com/elastic/opentelemetry-collector-components/issues/211
- ...
> Add batch aggregator before lsm interval processor

- dev-tools/mage/settings.go
In PR #4403 a new environment variable has been introduced to use a commit hash consistent with the hash of the elastic-agent-core DRA binary used. The env var name was not initialized and ended up using "MANIFEST_URL" which is obviously incorrect.
This commit sets the correct name AGENT_COMMIT_OVERRIDE to avoid using the manifest url as a commit hash
It allows for testing elastic-agent packaging with commands like
```
MANIFEST_URL="<some 8.17.1 manifest URL>" AGENT_DROP_PATH=build/elastic-agent-drop AGENT_PACKAGE_VERSION="9.0.0-alpha1" BEAT_VERSION="8.17.1" EXTERNAL=true  mage -v clean downloadManifest package
```
- ~~[ ] I have read and understood the [pull request guidelines](https://github.com/elastic/elastic-agent/blob/main/CONTRIBUTING.md#pull-request-guidelines) of this project.~~ …
> Fix AGENT_COMMIT_OVERRIDE environment variable name

- internal/pkg/agent/cmd/validate.go
- Enhancement
Adds help message explaining what exactly the otel validation command validates
Otel validation fails for otel-elastic hybrid config files. This is the intended behaviour. This PR adds command help message that explains this.
None
Run `elastic-agent validate --help`
- Closes #6235
> fix(6235): added long description for the validate command

- .buildkite/pipeline.elastic-agent-binary-dra.yml
- .buildkite/scripts/steps/build-agent-core.sh
- .buildkite/scripts/steps/dra-publish.sh
This commit adds support for the optional VERSION_QUALIFIER for the elastic-agent-core staging DRA builds.
Allow building prerelease artifacts
staging alpha1 artifact built from this PR -> https://buildkite.com/elastic/elastic-agent-binary-dra/builds/2013
snapshot build using `RUN_SNAPSHOT="true"` and `DRA_BRANCH="main"` -> https://buildkite.com/elastic/elastic-agent-binary-dra/builds/2014
- Closes https://github.com/elastic/elastic-agent/issues/6543
> Support VERSION_QUALIFIER for elastic-agent-core DRA

- changelog/fragments/1737462864-add_k8s_otel_comps.yaml
- go.mod
- go.sum
- internal/pkg/otel/README.md
- internal/pkg/otel/components.go
This PR adds `receivercreator` and `k8sobserver` components to EDOT collector.
By inlcuding `receivercreator` along with its dependency `k8sobserver` we can cover autodiscovery scenarios on K8s.
-
- ...
> Add receivercreator and k8sobserver otel components

- .buildkite/pull-requests.json
Skip files that are not used in Buildkite
Run faster builds and avoid waste of CI cycles.
I decided to support the whole `.github` folder since there are some other files such as CODEOWNERS or .dependaot.yml and the rest are not actually used by Buidlkite
-
- ...
> ci(buildkite): exclude .github folder and updatecli-compose.yaml

- .buildkite/scripts/steps/dra-publish.sh
This commit ensures that the DRA publish BK steps fails fast when there is an error.
Ensures that failing DRA builds are silently failing: https://buildkite.com/elastic/elastic-agent-package/builds/3861#019483f1-cb95-4515-aa84-a67de114bf16/281-355
- Relates: #6523
> Fail fast dra publish on errors

- changelog/fragments/1737657890-Use-a-random-free-port-for-sub-process-communication-in-containers.yaml
- internal/pkg/agent/application/application.go
- internal/pkg/agent/application/application_test.go
- internal/pkg/agent/cmd/container.go
- internal/pkg/agent/cmd/run.go
- internal/pkg/agent/configuration/grpc.go
- internal/pkg/agent/configuration/grpc_test.go
- testing/integration/kubernetes_agent_standalone_test.go
Changes the default port used when agent runs in a container to port 0. There is at least one user whose rollout of Elastic Agent is experiencing collisions with another application on the same port (nobody else could ever pick 6789 as a default port surely...) and I thought this would be straight forward to fix quickly. I was wrong. I expected ~2 hours and spent 3 days:
1. It looked like we already have a separate default config file for Docker containers I could just update: https://github.com/elastic/elastic-agent/blob/9b8a25f8feb5919965f1e5480d26e0324dd88736/_meta/config/elastic-agent.docker.yml.tmpl#L88-L89
2. This didn't work because the Helm chart defines its own configuration separately. I also didn't want to define this more than once because we'll probably change it again later …
> Change the default gRPC port to 0 when in a container

- changelog/fragments/1737717648-add-kafkaexporter-otel-collector.yaml
- go.mod
- go.sum
- internal/pkg/otel/README.md
- internal/pkg/otel/components.go
Add kafkaexporter and kafkareceiver to the list of components in the EDOT collector. Beats/Agent has a Kafka output, and this is the first step towards offering parity of outputs in the EDOT collector.
- Closes https://github.com/elastic/elastic-agent/issues/6562
- Closes https://github.com/elastic/opentelemetry-dev/issues/613
> otel: add kafkaexporter and kafkareceiver to EDOT collector

- changelog/fragments/1737735780-fix-empty-provider-data.yaml
- internal/pkg/composable/controller.go
- internal/pkg/composable/controller_test.go
We only signal from providers if the emitted data is different from the current state. This caused a bug where the data wasn't ever emitted if it was empty. The provider controller now distinguishes between no data (yet) and empty data. As a result, it's again possible to effectively disable all providers by using a local provider with no data.
This is a regression caused by https://github.com/elastic/elastic-agent/pull/6114. It doesn't apply to the main and 8.x branches due to https://github.com/elastic/elastic-agent/pull/6169 refactoring provider initialization in those.
Fixes a regression where agent wouldn't generate any configuration if the only enabled context providers only emitted empty data. This is something users do if they want to effectively disable providers.
> Emit vars even if provider data is empty from the start

- changelog/fragments/1737750331-add-nopreceiver-otel-collector.yaml
- go.mod
- go.sum
- internal/pkg/otel/README.md
- internal/pkg/otel/components.go
This PR adds the nopreceiver to EDOT. It is in our best interest to ensure this receiver is included in the next Elastic Agent release before the ff.
- Depends on https://github.com/elastic/elastic-agent/pull/6591
> otel: add nopreceiver to EDOT collector

- changelog/fragments/1737749181-add-jmxreceiver-otel-collector.yaml
- go.mod
- go.sum
- internal/pkg/otel/README.md
- internal/pkg/otel/components.go
This PR adds the jmxreceiver to EDOT. It is in our best interest to ensure this receiver is included in the next Elastic Agent release before the ff.
- Depends on https://github.com/elastic/elastic-agent/pull/6591.
> otel: add jmxreceiver to EDOT collector

- changelog/fragments/1737666699-Add-filesource-provider.yaml
- internal/pkg/agent/cmd/include.go
- internal/pkg/composable/providers/filesource/filesource.go
- internal/pkg/composable/providers/filesource/filesource_test.go
Adds the `filesource` provide to composable.
The provider watches for changes of the files and updates the values of the variables when the content of the file changes.
This allows information from the filesystem to be used as variables in the Elastic Agent configuration. This information is only allowed by explicitly configuring the provider to read this information from the disk. The policy cannot just read any file, it has to be explicitly configured to allow it.
- ~~[ ] I have added an integration test or an E2E test~~ (covered by unit tests well)
None
Create a configuration:
`elastic-agent.yml`
```
provides:
filesource:
sources:
file1:
path: …
```
> Add filesource provider

- internal/pkg/otel/README.md
- magefile.go
Modifies the `mage otel:readme` command to sort the OTel components by name in the OTel README.
It is much easier to find the component you're looking for in the list of supported EDOT Collector components when they are sorted by name.
> docs(otel): sort OTel components

- changelog/fragments/1738160406-add_redis_nginx_otel_comps.yaml
- go.mod
- go.sum
- internal/pkg/otel/README.md
- internal/pkg/otel/components.go
This PR adds the redis and nginx opentelemetry receiver components to EDOT.
These 2 receivers will provide support for metrics collection from NGINX and Redis workloads.
-
- ...
> Add redis and nginx otel receivers

- catalog-info.yaml
For testing purposes, we created a scheduled pipeline that was running every 6 hours. Now, it's not needed because its stability has been proven 
-
- ...
> [CI] Disable scheduled BK integration tests 

- .golangci.yml
We had previous PRs at https://github.com/elastic/elastic-agent/issues/5335 and https://github.com/elastic/beats/pull/42025 moving away from math/rand to the newer math/rand/v2 package. Currently there is nothing preventing contributors to commiting code using math/rand and regressing these changes.
Introduce a linter that catches math/rand imports in Go files.
- https://github.com/elastic/elastic-agent/issues/5335
> chore: add linter that denies importing math/rand

- .ci/updatecli/updatecli-bump-golang.yml
Set `force` to `false`, it won't try to update the base branch
See https://github.com/updatecli/updatecli/issues/2211#issuecomment-2147430601
We have seen some commits were wiped out, even though they were there originally:
- https://github.com/elastic/elastic-agent/pull/6663
Hence a follow-up was created partially:
- https://github.com/elastic/elastic-agent/pull/6700
Taht should not happen but I see in the [logs](https://github.com/elastic/elastic-agent/actions/runs/13060289796/job/36441381611#step:4:72)
```
WARNING: branch "refs/heads/updatecli_main_901223529a6beca5c9cb3180f1dae9731c8da4e9c40169d7042cc0163a6d7e24" diverged from "refs/heads/main", resetting it to "refs/heads/main"
".go-version" updated with content "1.22.11"
--- .go-version
+++ .go-version
@@ -1 +1 @@
-1.22.10
+1.22.11 …
```
> updatecli:  set force to false, it won't try to update the base branch

- changelog/fragments/1738874791-Fix-secret_paths-redaction-along-complex-paths.yaml
- internal/pkg/diagnostics/diagnostics.go
- internal/pkg/diagnostics/diagnostics_test.go
Redact secrets within complex nested paths.
some secrets are getting skipped within diagnostics bundles
None
> Redacted nested secrets path value

- .mergify.yml
Update mergify rules to use the Buildkite checks and remove the automation labels and update some other bits and pieces
This should help with:
- auto-merge some PRs related to the FF
- delete branches for closed or merged PRs.
- 
-
- ...
> mergify: update rules

- testing/integration/upgrade_standalone_flavors_test.go
- testing/upgradetest/upgrader.go
- testing/upgradetest/versions.go
Followup to #6542 
Adding 3 integration tests:
- upgrading from `basic` flavor
- upgrading from `servers` flavor
- upgrading from version not supporting flavors
Related: #6631
> Update tests for flavors

- .github/dependabot.yml
Removes the Dependabot config for OTel component updates.
The pull requests to update OTel components created by Dependabot have been unreliable and unfit for merging. Examples:
- https://github.com/elastic/elastic-agent/pull/6709/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R46
- https://github.com/elastic/elastic-agent/pull/6377/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R50
They also don't include a changelog entry, which we want to be included with OTel updates.
We have been relying on manual updates of OTel components for the last couple versions, with the intention to move to a different automation in the future that satisfies all requirements (see https://github.com/elastic/elastic-agent/issues/6132).
At this point, the …
> ci: remove Dependabot config for OTel components

- internal/pkg/otel/manager/manager.go
- internal/pkg/otel/manager/manager_test.go
Fixes a bug where the Otel manager wouldn't report runtime errors to the coordinator.
The coordinator needs to know about errors encountered by the otel manager.
- Discovered while testing #6697
> Fix runtime error reporting in Otel manager

- changelog/fragments/1738199968-update-scheduler-when-received-too-many-unathorized-responses.yaml
- internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
- internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
- internal/pkg/scheduler/scheduler.go
- Enhancement
Removes the forced unenroll from fleet gateway. Adds logic in the fleet gateway to switch out the scheduler used for checkins. If the unauthorized response limit is exceeded, a the scheduler is replaced with one that has a long wait duration. When the gateway receives a successful response, it switches back to using the regular scheduler with the shorter wait duration.
Currently the agent unenrolls after 7 unauthorized error responses. This can causes problems in disaster recovery scenarios where users may have to manually intervene. 
None
- Create ESS deployment
- Build the …
> enhancement(5423): added logic to replaces scheduler with long-wait scheduler in case of exceeded unauth response limit

- .buildkite/bk.integration.pipeline.yml
- testing/integration/groups_test.go
- testing/integration/upgrade_standalone_flavors_test.go
Reduces Integration tests time to **49 minutes**
Moves `upgrade_standalone_flavors_test.go` test to the new `upgrade-flavor` test group. 
Added `upgrade-flavor` group to 
* Windows
* Ubuntu x86
* Ubuntu ARM
`upgrade_standalone_flavors_test.go` tests take 30 minutes to complete and increase the overall test execution to 1 hour. 
- A follow up for https://github.com/elastic/elastic-agent/pull/6542
- ...
> [CI] New upgrade-flavor test group for TestStandaloneUpgrade_Flavor tests

- magefile.go
From the looks of it, none of the update steps interact with each other, so I don't see a reason to run them serially.
As an example, making a single line change in the otel components file results in the following timings:
parallel mage update  9.19s user 1.92s system 366% cpu 3.027 total
serial mage update  20.20s user 2.93s system 181% cpu 12.748 total
```bash
mage update
```
> mage: run mage update steps in parallel

- _meta/config/common.p2.yml.tmpl
- _meta/config/common.reference.p2.yml.tmpl
- _meta/elastic-agent.yml
- elastic-agent.reference.yml
- elastic-agent.yml
https://github.com/elastic/beats/pull/42160 added the ability to mark metricset as degraded when partial metrics are encountered. As per [this discussion](https://github.com/elastic/beats/pull/42160#discussion_r1918772579), it didn't really make sense to document this behaviour on beats repo, as this option is only usable while running elastic-agent.
Until now, we weren't marking metricsets as degraded due to various hidden bugs encountered and CI failures on agent. 
The plan is to enable this in agent integration test cases in elastic-agent. Once we're confident enough, we will enable this feature by default in beats and eventually, remove the flag.
This PR updates the reference file with the necessary information about the config.
Simultaneously, I've opened a [PR to update system …
> Update config to reflect `degrade_on_partial` 

- internal/pkg/composable/controller_test.go
Adds a test verifying that the composable provider will correctly emit variables if only an empty local provider is present. https://github.com/elastic/elastic-agent/pull/6598 fixed a bug related to this in 8.17 and 8.16. The bug doesn't exist in newer versions due to https://github.com/elastic/elastic-agent/pull/6169.
Before https://github.com/elastic/elastic-agent/pull/6169 allowed providers to not run if there weren't any references to them in the policy, adding an empty local provider was how users would intentionally disable providers. This test case verifies that newer versions of agent don't break this setup.
> Add a test for empty local provider

- deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/netflow-service/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/nginx-custom-integration/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/user-cluster-role/rendered/manifest.yaml
- deploy/helm/elastic-agent/templates/agent/_helpers.tpl
- deploy/helm/elastic-agent/templates/agent/eck/_pod_template.yaml
- deploy/helm/elastic-agent/templates/agent/k8s/_pod_template.yaml
- deploy/helm/elastic-agent/values.schema.json
- deploy/helm/elastic-agent/values.yaml
This PR adds a `statePersistence` value in Elastic Agent helm chart to allow configuring which type of volume is defined for Agent pods.
The new value `statePersistence` simplify the process of defining storage for Elastic Agent state by providing sensible defaults while allowing flexibility for custom configurations.
- Closes #6026 
- ...
> Add statePersistence value to helm chart presets

- dev-tools/mage/target/common/notice.go
The `NOTICE.txt` contains mixed line endings, as produced by `mage notice` command. This PR adds equivalent of `dos2unix NOTICE.txt` to the generator to fix this.
1. The file is inconsistent to view, whether on unix or windows.
2. The command `mage notice` produces incompatible NOTICE.txt changes on windows, which cannot then be fixed by `dos2unix`, etc, because the CI keeps producing file with mixed line endings.
-
- ...
> Fix NOTICE.txt line endings

- go.mod
- go.sum
- specs/endpoint-security.spec.yml
`go-sysinfo` determines native architecture based on `/proc` filesystem which could be disabled, therefore the prevention should err on allowing installation when native architecture is unknown.
The fixed prevention was not included in any released version yet.
Agent prevents adding Elastic Defend when it cannot determine if it's being emulated. However it's fine to install Elastic Defend in such case, as it does emulation check on it's own upon installation returning installation error when appropriate.
- Relates https://github.com/elastic/go-sysinfo/pull/252
> fix install prevention on Linux

- .buildkite/pipeline.elastic-agent-package.yml
- switch to ubuntu 22.04 ARM for the ARM part of the DRA packaging
- enable multi arch builds avoid the exec format errors when attempting to build arm64 inside arm64 workers
After the [recent upgrade to go 1.23.6](https://github.com/elastic/elastic-agent/pull/5309) we are noticing failures like
```
>> buildGoDaemon: Building for linux/arm64
Unable to find image 'docker.elastic.co/beats-dev/golang-crossbuild:1.23.6-arm' locally
1.23.6-arm: Pulling from beats-dev/golang-crossbuild
d8ccec8a513f: Pull complete
Digest: sha256:4e859ff74164fe8ebc675f93691083aecf7cd13b6fb4f78723a9e8ddad8b4692
Status: Downloaded newer image for docker.elastic.co/beats-dev/golang-crossbuild:1.23.6-arm
exec /crossbuild: exec format error
```
in the packaging ARM step
Tested via …
> Use newer multiarch support for DRA packaging in ARM

- changelog/fragments/1739981369-Fix-deadlock-in-OTelManager.yaml
- internal/pkg/otel/manager/manager.go
- internal/pkg/otel/manager/manager_test.go
Fixes an issue where a deadlock would cause the the OTelManager to get stuck.
This also seems to be the cause of the flaky test `TestOTelManager_Run`. I have ran this over 100 times and hit no more errors with this PR.
Deadlock causes the running internal OTel collector from getting any more updates or actions.
None
`go test -race -v -count=100 github.com/elastic/elastic-agent/internal/pkg/otel/manager`
- Closes #6119
> Fix deadlock in error handling in OTelManager

- catalog-info.yaml
This comment enables the native PR comment functionality from the Buildkite build bot which will allow comments in the PR about steps that failed even when they are flaky. It is enabled on the parent `elastic-agent` pipeline.
Improves visibility for PR authors and the team about test failures and flakiness.
Because the parent job triggers other pipelines e.g. [extended-testing](https://github.com/elastic/elastic-agent/blob/c1d42aef0869d194484d9113dcbac2a4d8fec0bf/.buildkite/pipeline.yml#L296) if any steps failed in the triggered pipeline, the comment will only mention the triggered pipeline. In a [follow up PR](https://github.com/elastic/elastic-agent/pull/6978/files), we are exploring whether it's possible to collapse triggered steps under the same pipeline.
PR will now have an …
> Allow PR comments for failures from the elastic-agent pipeline

- internal/pkg/otel/manager/manager_test.go
Otel collector exposes metrics on port 8888 by default, which can cause conflicts with other applications in tests. Disable this.
Use the debugexporter and nopreceiver in the test instead of the otlpexporter and otlpreceiver. This is faster and doesn't require binding to any ports as well.
Tests should not be flaky.
- Closes https://github.com/elastic/elastic-agent/issues/6965
> Fix config used in Otel manager test

- changelog/fragments/1740485771-ast-null-checks.yaml
- internal/pkg/agent/transpiler/ast.go
- internal/pkg/agent/transpiler/ast_test.go
AST collection nodes can contain nil values, and we currently don't check for them everywhere we should. Add the missing checks.
I'd like to solve this more comprehensively in a follow-up by adding a Node type specifically for null values, this is just a quick fix for the bug.
Right now, agent will panic if the configuration contains a null value in a list.
A unit test is included. You can also build agent and run it with the following configuration file:
```yaml
outputs:
default:
type: elasticsearch
hosts:
- http://localhost:9200
inputs:
- id: filestream
type: filestream
data_stream:
namespace: default
streams:
- id: filestream-Filebeat-input-id
data_stream:
dataset: filestream.generic
paths:
- /tmp/flog.log
processors:
- null
```
- Closes …
> Add missing null checks to AST methods

- internal/pkg/diagnostics/diagnostics.go
- internal/pkg/diagnostics/diagnostics_test.go
If an Otel hybrid mode configuration doesn't exist, we emit a plain text message into the config file generated by diagnostics. When we try to redact secrets from it, we fail to unmarshal it into a map and log a warning about it.
Instead, only run the redaction after confirming the value is actually a map.
We shouldn't emit spurious warnings.
Build the agent locally, start it, and get diagnostics. You shouldn't see a warning message mentioned in https://github.com/elastic/elastic-agent/issues/6783.
- Closes https://github.com/elastic/elastic-agent/issues/6783
> Fix warning on emitting diagnostics for otel hybrid mode

- pkg/testing/tools/fleettools/fleet.go
This PR re-works how we extract an Agent status from the fleet api and fixes the current issue we have we paginated results. 
It fixes frequent flaky issues that make our CI red
N/A
- Relates https://github.com/elastic/elastic-agent/issues/6968
- Relates https://github.com/elastic/elastic-agent/issues/6924
> [flakiness]: List agents by hostname and policy id

- .golangci.yml
- internal/pkg/agent/application/monitoring/processes_cloud_test.go
- internal/pkg/eql/eql_test.go
- internal/pkg/otel/configtranslate/otelconfig.go
- testing/fleetservertest/server.go
Removes unnecessary loop variable copies. These are not necessary anymore as of Go 1.22. It also replaces the deprecated `exportloopref` linter which would find places where these copies are necessary, with the `copyloopvar` linter which instead flags the copies as unnecessary.
We shouldn't unnecessarily copy loop variables, it's confusing and was only necessary due to older Go behaviour.
> Remove unnecessary loop variable copies

- deploy/helm/edot-collector/kube-stack/values.yaml
Remove a deprecated attribute from the routing connector configuration for otel-kube-stack. This removal has no effect on the connector behaviour. See: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/37708.
We can't upgrade to Otel 0.120.x without this change.
```
SNAPSHOT=true mage integration:single TestOtelKubeStackHelm
SNAPSHOT=true EXTERNAL=true PACKAGES=docker PLATFORMS="linux/amd64" mage -v  package
```
> [otel/kube-stack] Drop deprecated parameter from routing connector

- changelog/fragments/1741035554-Elastic-Agent-docker-container-no-longer-availble-from-docker.elastic.co-beats-elastic-agent.yaml
What the summary says.
We haven't documented this anywhere else and it's a breaking change.
> Add a changelog note that the agent Docker container is not longer available from docker.elastic.co/beats/elastic-agent

- internal/pkg/composable/providers/kubernetessecrets/kubernetes_secrets.go
- internal/pkg/composable/providers/kubernetessecrets/kubernetes_secrets_test.go
This PR introduces the following fixes and improvements:  
- **Loosens Time Constraints in Unit Tests** (needed for certain type of CI runners):  
- The `TTLDelete` value in test configurations was increased from `2s` to `10s`, ensuring tests have more leeway in processing cache expiration.  
- The `waitForSignal` value was adjusted from `1s` to `2s` to reduce test flakiness.  
- **Adds Debug Logging for Fetch When Cache is Disabled**:  [relevant comment](https://github.com/elastic/elastic-agent/pull/6841#discussion_r1970166713)
- When the cache is disabled, fetching secrets from the API now logs the retrieved secret’s resource version for better visibility into API interactions.  
- **Fixes a Typo in a Unit Test Name**:   [relevant …
> [flakiness] kubernetes_secrets provider unit tests

- changelog/fragments/1740399399-fleet-backoff.yaml
- internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
- internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
- internal/pkg/agent/cmd/enroll.go
- internal/pkg/agent/cmd/enroll_cmd.go
- internal/pkg/agent/cmd/enroll_cmd_test.go
- internal/pkg/agent/cmd/run.go
We make two changes to the backoff behaviour of the enroll command:
* Plain enroll now has an initial delay of 5s, a max delay of 10m, and uses jitter.
* Delayed enroll now has the same backoff behaviour as other requests to Fleet. This means an initial delay of 1m, a max delay of 10m, and jitter equal to half the delay time.
We've had a report where a lot of agents trying to enroll before Fleet was ready resulted in a DDOS with the previous backoff settings. Any situation where we can retry forever should use very conservative settings to avoid these kinds of situations.
There's a unit test for this behaviour. Testing the actual binary e2e is annoying, because we need to induce fleet server to return 503s.
- Closes https://github.com/elastic/elastic-agent/issues/6761
> Make enroll command backoff more conservative

- pkg/component/runtime/conn_info_server_test.go
This PR fixes a failing test case, `TestConnInfoConnCloseThenAnotherConn`, which was caused by the generation of overly long Unix socket paths. On macOS, UNIX-domain addresses are limited to 104 characters, while Linux imposes a 108-character limit. The previous implementation in `getAddress` did not validate or handle excessive path lengths, causing the test to fail on macOS and occasionally on Linux.
To resolve this, the PR updates `getAddress` to utilize the existing `SocketURLWithFallback` helper function from `pkg/utils/socket_unix.go`, which ensures that socket paths remain within system limits.
This change is essential to prevent flakiness in the test suite and ensure that the test runs reliably across different platforms. By leveraging the existing socket utility functions, we …
> [flakiness]: utilise socket helper funcs in unit-tests

- dev-tools/mage/dockerbuilder.go
- dev-tools/mage/pkg_test.go
- dev-tools/mage/pkgtypes.go
- dev-tools/mage/settings.go
- dev-tools/packaging/packages.yml
This pr will add additional tag to docker image `elastic-agent-service` in form of `elastic-agent-service:git-{SHORT_COMMIT}` 
Elastic-Agent is used in Agentless in both ECH and ES3.
While in ECH we must a version that will match the ELK stack, in ES3 we dont have that restriction.
Two reasons why this is important for ES3:
1. Automatic release flow 
2. Continuous feature release
I do not want to elaborate on the details in a public repo, please check the [RFC](https://docs.google.com/document/d/1U0LMCTA1c3eV4O5ADtH5Th-dRRk30zz6b6VJ2avjDoI/edit?tab=t.0#heading=h.w8zo9ze00qw8) and https://github.com/elastic/security-team/issues/9273 with full context 
- https://github.com/elastic/security-team/issues/9273
-
- How are we going to measure its …
> feat(elastic-agent-services): add another tag to docker image for agentless use

- testing/integration/log_level_test.go
Fleet checkins may take up to 5 minutes so we need to increase timeouts for assertions in TestSetLogLevelFleetManaged to account for it as the agent may apply log level settings while there's already a Fleet check-in in progress.
Settings timeouts for retrieving the correct log level in Fleet to 6 minutes should give enough time to agent to set the log level and communicate it to Fleet in a new check-in request.
This PR should remove flakiness coming from elastic-agent check-in timing in TestSetLogLevelFleetManaged.
- ~~[ ] I have added tests that prove my fix is effective …
> Increase timeout for assertions in TestSetLogLevelFleetManaged

- testing/integration/monitoring_endpoint_test.go
This PR relocates TestEndpointAgentServiceMonitoring to the FleetEndpointSecurity execution group to prevent test failures caused by concurrent installation attempts of the Endpoint package when tests run in different groups.
Reduces flakiness of Endpoint related tests that run in our CI
- Relates https://github.com/elastic/elastic-agent/issues/6969
- Relates https://github.com/elastic/elastic-agent/issues/4883
- Relates https://github.com/elastic/elastic-agent/issues/7221
> [flakiness] Correct group for TestEndpointAgentServiceMonitoring

- .buildkite/pipeline.yml
Validate that definitions in `catalog-info.yaml` are correct.
To ensure well-formed data ingested into EngProd's tooling.
-
- ...
> chore(ci): Validate catalog-info.yaml

- .buildkite/bk.integration.pipeline.yml
- .buildkite/integration.pipeline.yml
- .buildkite/scripts/buildkite-k8s-integration-tests.sh
- .buildkite/scripts/steps/integration_tests_tf.sh
- pkg/testing/define/define.go
- pkg/testing/define/requirements.go
This PR modifies the execution of Kubernetes integration tests by running them on separate runners per Kubernetes version. This change helps mitigate resource contention issues caused by running multiple `kind` clusters on a single host, which has been identified as a potential source of flaky test failures. 
The PR introduces the following:
- Creates a new integration test group `integration-tests-kubernetes` in Buildkite.
- Runs Kubernetes integration tests in parallel for different Kubernetes versions (`v1.27.16`, `v1.28.9`, `v1.29.8`, `v1.30.8`, `v1.31.0`).
- Ensures each Kubernetes version runs on a dedicated Buildkite runner with separate resource allocation.
- Implements a new script `.buildkite/scripts/buildkite-k8s-integration-tests.sh` to manage cluster creation, Docker image …
> [flakiness] improve reliability of kubernetes integration tests

- deploy/helm/elastic-agent/examples/priority-class/README.md
- deploy/helm/elastic-agent/examples/priority-class/priority-class-values.yaml
- deploy/helm/elastic-agent/examples/priority-class/rendered/manifest.yaml
- deploy/helm/elastic-agent/templates/agent/eck/_pod_template.yaml
- deploy/helm/elastic-agent/templates/agent/eck/daemonset.yaml
- deploy/helm/elastic-agent/templates/agent/eck/deployment.yaml
- deploy/helm/elastic-agent/templates/agent/eck/statefulset.yaml
- deploy/helm/elastic-agent/templates/agent/k8s/_pod_template.yaml
- deploy/helm/elastic-agent/templates/agent/k8s/daemonset.yaml
- deploy/helm/elastic-agent/templates/agent/k8s/deployment.yaml
- deploy/helm/elastic-agent/templates/agent/k8s/statefulset.yaml
- deploy/helm/elastic-agent/templates/agent/priority-class.yaml
- deploy/helm/elastic-agent/values.schema.json
This PR extends the Elastic Agent Helm chart to support defining and managing Kubernetes PriorityClasses for agent presets. With this change, users can specify custom priority classes within the Helm values, ensuring that critical workloads receive appropriate scheduling precedence in resource-constrained environments.
PS: The actual logic changes of this PR are captured in [this commit ](https://github.com/elastic/elastic-agent/commit/e7d381c45205c2e5fd246268d913a28f5c3bd7bf) (+139 -7 lines changed). However there is another [extra commit](https://github.com/elastic/elastic-agent/pull/7274/commits/72e675a4ff225912ce3f4f5f11dded1e7f88cc07) that introduces an example of using this that bumps the changes of this PR.
In multi-tenant Kubernetes environments, ensuring that critical Elastic …
> [Helm] support creating priority class

- .buildkite/scripts/buildkite-k8s-integration-tests.sh
This change updates the way the `AGENT_VERSION` is determined in the buildkite Kubernetes integration tests script. Instead of relying on the existence of a `.package-version` file (which is not correct), the version is now extracted directly from the `version/version.go` file using a regular expression (which is correct).
There is no disruptive user impact expected from this change. 
Open a draft PR
N/A
> [ci]: parse agent version from version/version.go for k8s integration tests

- pkg/api/v1/manifest.go
- Enhancement
Adds fips vield to the package manifest
The fips value will be used for fips-to-fips upgrades and this is preliminary PR to get things ready
- Relates https://github.com/elastic/ingest-dev/issues/4811
> enhancement(4811): added fips in the package manifest

- testing/integration/kubernetes_agent_service_test.go
- testing/integration/kubernetes_agent_standalone_test.go
This PR fixes intermittent failures in Kubernetes Kustomize integration tests (`TestKubernetesAgentStandaloneKustomize`) by removing the previously hardcoded container memory limit of `800Mi` at the test-code level. This memory limit apparently has become too restrictive following probably recent changes in Beats components, causing test instability and timeouts during agent health checks. Instead now the tests fallback to the memory limit of `1Gi` that exists in the kustomize manifests. 
The only PR that seems to align with the `800Mi` starting to be restrictive is this one https://github.com/elastic/beats/pull/43105. As soon as this landed on `main` and on `8.x` and it was picked by elastic-agent CI, k8s integration tests started failing. As of now `9:11 PM UTC` this is not yet merged …
> [flaky] fix kustomize integration tests

- changelog/fragments/1741865161-fix-otel-kube-stack-config.yaml
- deploy/helm/edot-collector/kube-stack/values.yaml
Fixes the Elasticsearch exporter configuration in opentelemetry-kube-stack values. This was accidentally removed in https://github.com/elastic/elastic-agent/pull/6444.
I'm going to file an issue to add tests that would've caught this as a follow-up. This is an urgent fix to get in before 9.0.0 RC2, which is why I'm not doing it in this PR.
Currently, this configuration sends traces to the wrong index.
> Fix exporter configuration in kube-stack values

- changelog/fragments/1741622468-Do-not-fail-Windows-permission-updates-on-missing-files-paths..yaml
- internal/pkg/acl/acl_windows.go
- internal/pkg/acl/acl_windows_test.go
- internal/pkg/agent/perms/windows.go
- internal/pkg/agent/perms/windows_test.go
This PR fixes a bug in the Windows permissions handling where the process would fail if a file or directory was missing. The changes include:
- **Improved Error Reporting:**  
Enhanced error messages by wrapping errors (using `%w`) to provide better context for failures in Windows API calls (e.g., `SetEntriesInAclW`, `GetNamedSecurityInfoW`, and `SetNamedSecurityInfoW`).
- **Graceful Handling of Missing Files/Paths:**  
Introduced a helper function, `filterNotFoundErrno`, that explicitly ignores `ERROR_FILE_NOT_FOUND` and `ERROR_PATH_NOT_FOUND` errors. This allows the permission update process to continue even when certain files or directories are not present.
- **Code Restructuring for Testability:**  
Refactored the permission application logic into a new function (`applyPermissions`) …
> [bug]: fix permissions for windows on not found paths and files errors

- internal/pkg/agent/install/switch.go
This PR captures and reports errors encountered during the uninstallation of the Elastic Agent service instead of silently ignoring them. Previously, the error returned by `UninstallService` was ignored, potentially hiding valuable information during troubleshooting. Now, any errors encountered during service uninstallation will be logged through the existing `pt.Describe()` method, providing better context for debugging.
Ignoring errors during service uninstallation can lead to ambiguous failures in subsequent service installation attempts, such as the "service already exists" error observed in integration tests (`TestSwitchPrivilegedWithBasePath`). Reporting these errors helps to identify and diagnose issues related to permissions or service management, particularly on Windows, …
> Capture in progress the error of uninstalling elastic-agent service

- testing/integration/beat_receivers_test.go
Adds Integration test that:
1. Creates and install policy with just monitoring
2. Download the policy, add the API key
3. Installs elastic-agent without enrolling in fleet
4. Make sure logs and metrics for agent monitoring are being received
This is a baseline test that will be expanded to compare agent
monitoring when using beats vs beat receivers.
Provide a baseline to compare Beats receivers vs Beats for agent monitoring
None.  Integration test only
``` shell
mage integration:single TestAgentMonitoring
```
- Closes elastic/ingest-dev#4874
> Add AgentMonitoring Test for Beat Receivers work

- internal/pkg/config/config.go
- internal/pkg/config/config_test.go
- internal/pkg/config/loader_test.go
Fixes an issue where the `ucfg.PathSeperator(".")` was not being applied to `VarSkipKeys` option in the configuration loading code. `outputs` where added to the configuration loader in https://github.com/elastic/elastic-agent/pull/6602 which caused the issue to appear. Before when `outputs` was present in `VarSkipKeys` the paths where expanded when `ToMapStr` was called causing entries like `ssl.certificate_authorities` to be expanded correctly.
Without this change components can get invalid YAML as they do not all understand dot notation inside of YAML configuration. …
> Fix issue with ToMapStr not expanding path separator when reading configuration

- testing/integration/diagnostics_test.go
Fixes a flaky diagnostics redaction test. The test expects to see a particular input from a fleet policy in diagnostic output, but doesn't wait until the policy is actually applied.
- Closes https://github.com/elastic/elastic-agent/issues/7405
> Fix flaky diagnostics redaction integration test

- deploy/helm/elastic-agent/README.md
- deploy/helm/elastic-agent/examples/fleet-managed-certificates/README.md
- deploy/helm/elastic-agent/examples/fleet-managed-certificates/fleet-values.yaml
- deploy/helm/elastic-agent/examples/fleet-managed-certificates/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/fleet-managed-ksm-sharding/rendered/manifest.yaml
- deploy/helm/elastic-agent/examples/kubernetes-ksm-sharding/rendered/manifest.yaml
- deploy/helm/elastic-agent/templates/agent/_helpers.tpl
- deploy/helm/elastic-agent/templates/agent/k8s/_secret.tpl
- deploy/helm/elastic-agent/templates/integrations/_presets/_ksm_sidecar.tpl
- deploy/helm/elastic-agent/values.schema.json
- deploy/helm/elastic-agent/values.yaml
This PR introduces support for configuring Fleet-related certificates (CA certificates and client certificates for mutual TLS authentication) in the Elastic Agent Helm chart. It allows users to specify these certificates directly via Helm CLI arguments (using `--set-file`), define them in `values.yaml`, or reference Kubernetes secrets. The necessary certificates can be provided through chart values such as:
- `agent.fleet.ca`
- `agent.fleet.agentCert`
- `agent.fleet.agentCertKey`
- `agent.fleet.kibanaCA`
Additionally, it exposes more options of the fleet config that a user may want to tune accordingly, such as:
- `agent.fleet.force`
- `agent.fleet.kibanaServiceToken`
- `agent.fleet.tokenName`
- `agent.fleet.policyName`
As usual with this Helm chart related PRs I introduce multiple …
> [Helm] Allow providing CA certificate of the Fleet Server when running the agent in fleet mode

- dev-tools/mage/checksums.go
ChecksumsWithManifest function assumes that all (actually only one) packages matching a component binary name prefix and the target platform are downloaded and available but since -fips packages are available in manifests this is no longer true (see endpoint-security-fips-9.1.0-SNAPSHOT-linux-x86_64.tar.gz and endpoint-security-9.1.0-SNAPSHOT-linux-x86_64.tar.gz which are both present in recent manifest versions).
This is a short term hack to avoid breaking elastic-agent packaging now that -fips package variants are available by skipping them.
To be able to generate elastic-agent packages again
- ~~[ ] I have read and understood the [pull request guidelines](https://github.com/elastic/elastic-agent/blob/main/CONTRIBUTING.md#pull-request-guidelines) of this project.~~
- ~~[ ] My code …
> Skip FIPS components when packaging elastic-agent from a Manifest

- .buildkite/pipeline.elastic-agent-binary-dra.yml
- .buildkite/pipeline.elastic-agent-package.yml
Split darwin/arm64 from amd64 using the aarch64 host and golang crossbuild. 
Uses https://github.com/elastic/golang-crossbuild/pull/533 and https://github.com/elastic/golang-crossbuild/pull/559 (1.24.0)
We can merge this as soon as:
1) This [build](https://buildkite.com/elastic/golang-crossbuild/builds/955) has successfully been build.
2) the CI for https://github.com/elastic/elastic-agent/pull/7304 worked fine!
Avoid using qemu for creating arm64 on amd64.
In the CI see https://github.com/elastic/elastic-agent/pull/7304
-
- ...
> bk(packaging): split arm64 from amd64 workers

- .buildkite/bk.integration.pipeline.yml
- .buildkite/scripts/buildkite-k8s-integration-tests.sh
- testing/integration/kubernetes_agent_service_test.go
- testing/integration/kubernetes_agent_standalone_test.go
This PR enhances Kubernetes integration test logging with the following improvements:
- Logs from **all pods** within both the test namespace and the `kube-system` namespace are now captured and archived.
- A **UUID-based namespace** is used instead of a test-name-derived one, ensuring uniqueness and preventing namespace conflicts.
- The path for dumping pod logs is adjusted, organizing logs into a structured archive that is easier to retrieve and analyze.
- Improves the `ExecInPod` calls by applying **timeouts** to prevent indefinite hangs in test runs.
- Captures **container restarts** explicitly in `k8sCheckAgentStatus`, making test failures more informative.
- Introduces structured logging for test artifacts, ensuring all relevant data is collected in Buildkite.
I did "force" the k8s …
> [ci] capture logs of pods in the test namespace and kube-system

- internal/pkg/agent/cmd/cmd_test.go
- internal/pkg/agent/cmd/common.go
None of the subcommand construction functions return a nil *cobra.Command, althought this was apparently the case in the past. So remove the wrapper func and its tests.
Reduce complexity and bugspace.
-
- ...
> internal/pkg/agent/cmd: remove redundant addCommandIfNotNil func

- dev-tools/mage/downloads/testdata/some-file.txt
- dev-tools/mage/downloads/utils_test.go
Use a local httptest.Server instead of downloading robots.txt from Elastic's website on every test run.
This makes removes the internet connection and the state of Elastic's website as source of flakiness for the test.
```
cd dev-tools/mage/downloads
go test -run=TestDownloadFile
```
- ...
> Use local HTTP server instead of downloading file on test

- dev-tools/mage/otel/deps.go
- dev-tools/mage/otel/deps_test.go
- go.mod
- magefile.go
Makes the `otel:readme` mage command support replace directives. It now also supports pseudo-versions that Go uses for commit hashes in go.mod.
The implementation now actually parses the go.mod file using x/mod.
In order to resolve a dependency conflict between beats and otel 0.120.x, we're going to use our own fork of prometheusreceiver. See https://github.com/elastic/elastic-agent/pull/7443 for this change made in the 8.18 branch.
> Support replace directives in otel readme mage command

- .mergify.yml
Removes `8.16` as a targeted branch for the `backport-active-all` and `backport-active-8` labels used by Mergify.
> [mergify] Remove 8.16 as an active branch

- changelog/fragments/1743421027-Fix-panic-during-shutdown-in-fleetgateway.yaml
- internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
This PR fixes a bug in the `FleetGateway.execute` method where a call to `info.Metadata` could return an error that was not being propagated. If this error occurred during shutdown (e.g. due to context is done/cancelled), the subsequent logic would attempt to use `nil` values, resulting in a panic.
The fix ensures that the `execute` function returns early if `info.Metadata` fails, avoiding a `nil` dereference and the resulting crash.
This bug was causing panics during agent shutdown, as reported in [issue #7309](https://github.com/elastic/elastic-agent/issues/7309). The error originated from the failure to load agent metadata, which led to a `SIGSEGV` (segmentation fault) because the error was logged but not returned. This led to `nil` being used downstream, triggering a crash.
Fixing …
> [bug] do not panic when info.Metadata errors in FleetGateway execute

- deploy/helm/elastic-agent/README.md
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_logs_containers.tpl
- deploy/helm/elastic-agent/values.schema.json
- deploy/helm/elastic-agent/values.yaml
This PR introduces support for configuring additional processors for the `container-logs` stream in the Helm chart. Specifically, it allows users to define a list of processors under the `kubernetes.containers.logs.vars.processors` key in `values.yaml`.
It also introduces the ability to toggle the built-in default processors via the `enabledDefaultProcessors` flag, and groups all log stream customization variables under a new `vars` section for consistency with the other stream configurations.
This enhancement addresses a gap where `container-logs` did not support user-defined processors.
The default behavior remains unchanged unless users opt in by defining custom processors or disabling built-in ones. Existing configurations using `additionalParsersConfig` outside the new `vars` block …
> [Helm] allow additional processors for container logs to be defined 

- dev-tools/mage/checksums.go
- dev-tools/mage/manifest/manifest.go
- dev-tools/mage/manifest/manifest_test.go
- dev-tools/mage/pkg.go
- dev-tools/packaging/packages.yml
- dev-tools/packaging/settings.go
- dev-tools/packaging/testing/package_test.go
- magefile.go
- pkg/version/version_parser.go
This PR allows declarative definitions of elastic-agent components in `dev-tools/packaging/packages.yml`.
In the declaration of such components it's now possible to specify a `packageName` template that will be rendered using platform and version during packaging.
This is a prerequisite for selecting different component packages for specific packaging specs.
No disruptive …
> Make components in packages configurable

- testing/integration/testdata/preinstalled_packages.json
This PR ensures that package installation in the CI is **forced** after provisioning the ESS stack. Specifically, it updates the `fleet.sh` script to send `-d '{ "force": true }'` in the request to the Fleet API when preinstalling integrations.
This change guarantees that the expected package versions are installed regardless of the existence of newer upstream versions.
Integrations are continuously released and updated, and this can break our CI if we rely on specific package versions during preinstallation. For instance, yesterday a new version of `osquery_manager` was released ([commit](https://github.com/elastic/integrations/commit/0196b0ebbaf82c5474bb41e98de88fd929e41891)), and this caused the CI step to fail with the following error: `osquery_manager-1.16.0 is out-of-date and cannot …
> [flaky] force the installing of packages after provisioning the ESS stack

- .buildkite/bk.integration.pipeline.yml
- .buildkite/pipeline.yml
- .buildkite/scripts/install-kubectl.sh
- docs/test-framework-dev-guide.md
- pkg/testing/kubernetes/supported.go
Kubernetes v1.32 released on Dec 11 2024, add it to test matrix.
- For https://github.com/elastic/ingest-dev/issues/4743
> ci: add kubernetes v1.32 to test matrix

- .ci/updatecli/updatecli-bump-golang.yml
This PR extends the existing Updatecli configuration to automatically bump the Go version in wrapper/windows/archive-proxy/go.mod, aligning it with the latest Go version used across the project. This ensures consistency in Go versioning for the Windows archive proxy wrapper.
We need to be consistent 🙂 
None
Not sure how you can run this locally 🙂 
N/A
> ci: extend updatecli to bump wrappers/windows/archive-proxy golang version

- changelog/fragments/1744022861-consistent-monitoring-config.yaml
- internal/pkg/agent/application/monitoring/server_test.go
- internal/pkg/agent/application/monitoring/testdata/monitoring_config_full.yaml
- internal/pkg/agent/application/monitoring/v1_monitor.go
- internal/pkg/agent/application/monitoring/v1_monitor_test.go
When generating the agent self-monitoring config, inputs were added by iterating over a map. This caused the output to be non-deterministic. This didn't have any effect on the logic, as input order doesn't have any effect on agent or beats behavior, but it would've resulted in some unnecessary configuration reloads.
I've also added a golden file test for the self-monitoring. This test enables as many options as possible and then checks the resulting configuration against a static file checked into the repository. This both makes it easier to understand what we generate, and makes future refactors (like the one in #7600) less risky.
Our configuration generation should be pure for a given environment. We should avoid unnecessary config reloading - this can be expensive in some environments, …
> Ensure consistent input order in self-monitoring configuration

- pkg/testing/runner/runner_test.go
Otherwise the version hardcoded in the test is missed by automated Go version bump PRs like https://github.com/elastic/elastic-agent/pull/7736.
> Dynamically set go version in test

- deploy/helm/elastic-agent/examples/kubernetes-custom-output/README.md
- deploy/helm/elastic-agent/examples/kubernetes-custom-output/agent-kubernetes-values.yaml
- deploy/helm/elastic-agent/examples/kubernetes-custom-output/rendered/manifest.yaml
- deploy/helm/elastic-agent/templates/agent/_helpers.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_apiserver.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_controller_manager.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_kubelet_containers.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_kubelet_nodes.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_kubelet_pods.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_kubelet_system.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_kubelet_volumes.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_logs_audit.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_logs_containers.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_proxy.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_scheduler.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_state.tpl
- deploy/helm/elastic-agent/templates/integrations/_system/_system_logs.tpl
- deploy/helm/elastic-agent/templates/integrations/_system/_system_metrics.tpl
This PR fixes a bug where the `output` configuration for standalone agents and their integration presets was not respected when using the Helm chart.
- Ensuring that the appropriate output is assigned to each standalone preset in all relevant Kubernetes and system integration templates.
- Providing an example (`examples/kubernetes-custom-output`) to demonstrate correct usage with a custom output (`test`) and verifying output selection through `use_output`.
Without this fix, even if a user defines a different output and assigns it to specific integrations via Helm values, the configuration is silently ignored, and data may still be routed to the default output. This is particularly problematic in standalone mode, where fine-grained control of outputs is expected.
This change is …
> [Helm] fix preset outputs

- magefile.go
Fix a bug introduced by https://github.com/elastic/elastic-agent/pull/7690 where dependency list is not correctly passed to `isPlatformIndependentPackage()`.
Without dependency list `isPlatformIndependentPackage()` did not recognize `connectors-9.1.0-SNAPSHOT.zip` as a platform independent package  so it wasn't copied in the `archives` directory.
This in turn would make the `elastic-agent-service` docker image spec fail because of these [lines](https://github.com/elastic/elastic-agent/blob/6abd585e55cbb27500b9821ddd94b80263ca150b/dev-tools/packaging/packages.yml#L582-L584) that expects the connectors zip to exist in the archive directory.
To fix unified release for elastic-agent
- ~~[ ] I have made corresponding …
> Correctly inject dependency list when packaging using DROP_PATH

- deploy/helm/elastic-agent/examples/kubernetes-custom-output/README.md
- deploy/helm/elastic-agent/examples/kubernetes-custom-output/agent-kubernetes-values.yaml
- deploy/helm/elastic-agent/examples/kubernetes-custom-output/rendered/manifest.yaml
- deploy/helm/elastic-agent/templates/agent/_helpers.tpl
- deploy/helm/elastic-agent/templates/agent/_outputs.tpl
- deploy/helm/elastic-agent/templates/agent/eck/secret.yaml
- deploy/helm/elastic-agent/templates/agent/k8s/_secret.tpl
- deploy/helm/elastic-agent/templates/integrations/_presets/_ksm_sidecar.tpl
- deploy/helm/elastic-agent/values.schema.json
This PR enhances the standalone deployment of Elastic Agent via the Helm chart by introducing support for configuring SSL settings on output definitions. Users can now specify custom certificate authorities, verification modes, and trusted CA fingerprints to establish secure connections to Elasticsearch clusters that use self-signed certificates.
Without this, standalone agents cannot connect to Elasticsearch clusters using custom or self-signed certificates. This makes it difficult to deploy agents in secured environments. The PR fixes that by allowing SSL configuration on outputs.
This is a backwards compatible change, so no impact is expected.
Follow the `kubernetes-custom-output` example.
- Closes https://github.com/elastic/elastic-agent/issues/6344
> [Helm] Allow providing SSL settings to the Elastic Agent (standalone mode)

- changelog/fragments/1744198660-add-nopexporter.yaml
- go.mod
- go.sum
- internal/pkg/otel/README.md
- internal/pkg/otel/components.go
- internal/pkg/otel/manager/manager_test.go
- internal/pkg/otel/testdata/all-components.yml
Adds the nopexporter component to EDOT. This is an exporter that drops all data sent to it. It only depends on otel core, so it doesn't pull in any new dependencies.
This exporter is useful for debugging, tests, and creating configurations which intentionally don't transmit any data, but do run extensions. 
We already include the nopreceiver, so we should include the exporter as well.
Build agent locally and run it using the following configuration
```
receivers:
nop:
exporters:
nop:
service:
pipelines:
logs:
exporters: [nop]
receivers: [nop]
```
> Add nopexporter

- dev-tools/packaging/packages.yml
Elastic-agent-core uploads in elastic-agent-binary-dra pipeline are breaking because fips elastic-agent-core artifacts are named `elastic-agent-fips-core`
Change Name and Qualifier of the fips `elastic-agent-core` artifact spec to get the correct name generated
To fix elastic-agent-binary-dra pipeline
- Supersedes  #7816
- ...
> Modify fips core spec qualifier and name

- internal/pkg/agent/application/monitoring/v1_monitor.go
Refactor how metrics input configuration is generated for agent self-monitoring. This was primarily focused on readability. Assembling the configuration involved handling large maps of parameters, which are quite unwieldy to deal with in Go code.
* The configuration is now assembled from pieces returned by smaller functions, making it much easier to see the overarching logic.
* There is much less nesting, making the code more readable.
* Generating processor configuration was moved to individual functions, which are now reused across different streams and inputs.
This PR covers the metrics part of #7600. The logs part will be covered in a follow-up.
The code is a lot more readable after this change. This will also make subsequent changes adding support for beats receivers smaller and …
> Refactor self-monitoring metrics config generation

- testing/integration/kubernetes_agent_standalone_test.go
This PR improves the Kubernetes integration test framework by including the full `corev1.ContainerStatus` for each container in the pod state dump when a test fails.
Instead of selectively collecting fields like `RestartCount`, `LastTerminationReason`, and `LastTerminationMessage`, we now inline the entire `ContainerStatus` struct. This change gives us complete visibility into the container's lifecycle state, reasons for failure, readiness status, and other useful debug information when integration tests fail.
A recent test failure in `TestKubernetesAgentHelm/helm_managed_agent_upgrade_older_version` (see [#7831](https://github.com/elastic/elastic-agent/issues/7831)) is difficult to debug due to limited diagnostic information. The container was stuck in `ContainerCreating`, but the logs …
> [ci] include the full containerStatus on k8s integration test failure

- internal/pkg/otel/manager/manager.go
If OTel collector fails to start say due to incorrect config - the logs do not output what went wrong. The only way to know that is by using `elastic-agent status` command.
This PR logs such errors.
Improve error logging when collector fails to start
> [Chore] Improve error reporting when otel collector fails to start

- changelog/fragments/1740773781-Add-elastic.agent.fips-to-local_metadata.yaml
- changelog/fragments/1741808763-FIPS-Compliant-agent-file-vault.yaml
- changelog/fragments/1741897911-fips-to-fips-upgrades.yaml
- dev-tools/packaging/packages.yml
- dev-tools/packaging/testing/package_test.go
- internal/pkg/release/version.go
- pkg/control/v2/cproto/control_v2.pb.go
This PR renames any occurrences in Agent code, comments, etc. matching `/fips.*compliant/i` to "FIPS-capable".  This is done to avoid giving the inaccurate impression that Agent is FIPS-compliant.
> Rename FIPS-compliant to FIPS-capable

- internal/pkg/agent/application/monitoring/v1_monitor.go
Refactor how logs input configuration is generated for agent self-monitoring. This was primarily focused on readability. Assembling the configuration involved handling large maps of parameters, which are quite unwieldy to deal with in Go code.
* The configuration is now assembled from pieces returned by smaller functions, making it much easier to see the overarching logic.
* There is much less nesting, making the code more readable.
* Generating processor configuration was moved to individual functions, which are now reused across different streams and inputs.
This PR covers the logs part of #7600. The metrics part was covered by #7734.
The code is a lot more readable after this change. This will also make subsequent changes adding support for beats receivers smaller and easier to …
> Refactor monitoring log config generation

- .buildkite/scripts/steps/integration_tests_tf.sh
This PR ensures that Fleet packages are preinstalled when provisioning a new ECH stack for the retried CI failed steps.
We need to pre-install to guarantee that packages are force installed
- Closes https://github.com/elastic/elastic-agent/issues/7852
> fix: preinstall fleet packages on the newly provisioned ESS stack of a retried step

- changelog/fragments/1744839123-fix-MOtel-config-image-value.yaml
- deploy/helm/edot-collector/kube-stack/managed_otlp/values.yaml
Updates `defaultCRConfig.image.repository` to use `docker.elastic.co/elastic-agent/elastic-agent`.
> [Managed OTLP][Helm] Update to use current container repo

- .buildkite/scripts/steps/fleet.sh
This PR updates the `curl` command used to preinstall packages for integration tests so that verbose output is no longer printed to the logs.
To avoid leaking sensitive information in logs.
- Follow up to #7651
> [Integration Tests] Do not print out curl verbose output

- .golangci.yml
Our linter has an allowlist for packages which are allowed to be replaced. We forgot to add the Otel prometheus receiver package there after replacing it with a fork before the 9.0.0/8.18.0 releases. Fix this.
Right now, any PR that changes the go.mod will run into a linter warning for this reason.
> Add prometheusreceiver to replace allowlist

- .buildkite/pipeline.agentless-app-release.yaml
- .buildkite/pipeline.agentless-tests.yaml
- .buildkite/scripts/steps/run-agentless-tests.sh
This PR follows https://github.com/elastic/elastic-agent/pull/7701 to
1. Fix reference to release script
2. Fix the service_versions that goes into quality gates (yq on v3 does not have `eval`)
> agentless release fix

- .buildkite/bk.integration.pipeline.yml
- .buildkite/integration.pipeline.yml
- .buildkite/scripts/buildkite-integration-tests.sh
- .buildkite/scripts/integration-tests.ps1
- .buildkite/scripts/steps/integration_tests_tf.sh
- .buildkite/scripts/steps/serverless.ps1
- .buildkite/scripts/steps/serverless.sh
- .buildkite/scripts/steps/serverless_down.sh
- .buildkite/scripts/steps/serverless_start.sh
- test_infra/serverless/.gitignore
- test_infra/serverless/deployment.tf
- test_infra/serverless/output.tf
- test_infra/serverless/terraform.tf
This PR migrates the Serverless integration tests from a single-step setup using OGC to a multi-step, Buildkite-native pipeline. The new approach provisions the Serverless Observability project using Terraform and executes the test suite across prebuilt VM images split by OS, similar to existing ESS and Kubernetes integration tests.
Key changes:
- Adds Terraform-based provisioning for Serverless stack and the necessary cleanup logic; "fun" fact: even with this PR, we still don't control the Serverless stack version 
- Refactors integration test scripts (`buildkite-integration-tests.sh`, `integration-tests.ps1`, `integration_tests_tf.sh`) to accept parameters for `test_name_pattern` and `stack_type`, allowing selective test execution and proper environment setup for either ESS or …
> [ci] migrate serverless integration tests to buildkite

- go.mod
- go.sum
- internal/pkg/otel/configtranslate/otelconfig_test.go
- testing/integration/beat_receivers_test.go
- testing/integration/otel_test.go
Bumps the beats dependency to the commit currently at the tip of main. Here are the changes affecting beats receivers that this pulls in:
- https://github.com/elastic/beats/commit/11df15387613f652ec19f34f4ea8d8d6fd8e2956
- https://github.com/elastic/beats/commit/2da0cdd5e3afd8d1a44851b886d122f7a8b1e0b9
- https://github.com/elastic/beats/commit/cf9ed29bb06ad52fed779223a0fd2c351ae44271
The test fixes in this PR are solely due to the last commit, which requires us to use ES api keys in the right format depending on if we're configuring an elasticsearch output or an elasticsearch exporter.
> Bump beats dependency version to 20250429215007-4c1bf91fe423

- changelog/fragments/1745923884-deb-rpm-preserve-run-state.yaml
- dev-tools/packaging/templates/linux/preinstall.sh.tmpl
- pkg/testing/fixture.go
- testing/integration/linux_deb_test.go
- testing/integration/linux_rpm_test.go
- testing/integration/restrict_upgrade_deb_test.go
This PR improves the upgrade experience of Elastic Agent installed via DEB and RPM packages. It updates the pre-installation script (`preinstall.sh.tmpl`) to copy the `run` directory from the previous agent installation into the new version's folder during an upgrade, preserving agent state that would otherwise be lost.
Additionally, it extends integration tests to:
- Introduce validation to ensure the `run` directory and migration marker are properly copied across an upgrade.
- Add Debian OS support in DEB-related upgrade tests.
A new helper function `FindRunDir` is also introduced in the testing framework to locate the agent's `run` directory based on versioned data paths.
Based on my investigation:
1. Fleet-related configuration is at `/etc/elastic-agent/fleet.enc` which is preserved …
> [deb/rpm] copy run folder from old agent installation

- pkg/testing/fetch_test.go
- pkg/testing/fetcher.go
- pkg/testing/fetcher_artifact.go
- pkg/testing/fixture.go
This PR enhances the integration testing framework by adding support for FIPS-capable artifacts.  It introduces a new `artifactFetcherOpt` named `WithArtifactFIPSOnly()`, which can be supplied when an integration test wishes to fetch a FIPS-capable artifact.  It also makes sure that the extracted artifact directory name is correctly set when extracting a FIPS-capable artifact.
So integration tests pertaining to FIPS can fetch, install, and use FIPS-capable Agent artifacts.
You can see an example of these enhancements being used in https://github.com/elastic/elastic-agent/pull/7804.
- ~[ ] I have made corresponding changes to the documentation~
- ~[ ] I have made corresponding change to the default configuration files~
- ~[ ] I have added an entry in `./changelog/fragments` using the …
> [Integration Testing] Add support for FIPS-capable artifacts

- deploy/helm/elastic-agent/examples/fleet-managed-ksm-sharding/README.md
Updated the example to install Elatic Agent with Helm chart plus KSM autosharding to indicate that the Kubernetes Integration should be configured using localhost:8080 as Host destination.
cc: @pkoutsovasilis
> ksm autosharing integration configuration update

- _meta/config/common.reference.p2.yml.tmpl
- changelog/fragments/1746197293-config-rollback-window.yaml
- elastic-agent.reference.yml
- internal/pkg/agent/configuration/upgrade.go
- internal/pkg/agent/configuration/upgrade_test.go
This PR adds a new optional Agent configuration setting, `agent.upgrade.rollback.window`.  This setting takes a string parseable by `time.Duration()`.  The default value of this setting is `168h` (== 7 days).  The value of this setting will determine how long after users upgrade an Agent will they be permitted to request a rollback to the previous version of the Agent on disk.
To allow users to perform manual rollbacks of upgraded Elastic Agent within a certain time window.
None; this PR adds a new, optional setting.  Further, older versions of Elastic Agent will ignore this setting if they encounter it.
```
$ echo "agent.upgrade.rollback.window: 12h" >> ./elastic-agent.yml
$ go build .
$ ./elastic-agent inspect    # check that this contains the new setting in it
```
- Resolves #6881
- …
> Adding new configuration setting: `agent.upgrade.rollback.window`

- internal/pkg/agent/application/monitoring/v1_monitor.go
- internal/pkg/agent/application/monitoring/v1_monitor_test.go
- internal/pkg/core/monitoring/config/config.go
- testing/integration/beat_receivers_test.go
Adds the ability to use beats receivers for agent self-monitoring. To do so, we add a new configuration key to `agent.monitoring` named `_runtime_experimental` - identical to how you can currently switch inputs to the Otel runtime.
In terms of implementation, the changes are very straightforward. In the monitoring injection manager, we set the runtime manager for inputs we add, if it's set in the monitoring configuration.
Most of this PR's code changes lie in tests, and more specifically in the `TestAgentMonitoring` E2E test. This test compares the data collected by agent self-monitoring using beats processes to an equivalent Otel configuration of beats receivers in Hybrid mode. Instead of doing that, we can now just change `agent.monitoring._runtime_experimental`, so the test becomes …
> Allow using beats receivers for self-monitoring

- changelog/fragments/1746113477-Retry-enrollment-for-all-errors.yaml
- internal/pkg/agent/cmd/container.go
- internal/pkg/agent/cmd/enroll.go
- internal/pkg/agent/cmd/enroll_cmd.go
- internal/pkg/agent/cmd/enroll_cmd_test.go
- internal/pkg/agent/cmd/setup_config.go
- internal/pkg/fleetapi/enroll_cmd.go
Retry enrollment requests when an error is returned until a timeout is reached.
Add `--enroll-timeout` and `FLEET_ENROLL_TIMEOUT` to control how long the timeout is; default 10m.
Increase reliability of enrollments.
- ~~I have commented my code, particularly in hard-to-understand areas~~
Agents running via container, or command line **without** the delay enrollment option will retry for 10m instead of indefinitely.
> Retry enrollment requests when an error is returned, add enrollment timeout

- changelog/fragments/1746636264-fix-notice.yaml
- dev-tools/mage/target/common/notice.go
This PR updates the code for `mage notice` so that the generated `NOTICE.txt` contains only those Go modules that are used by Elastic Agent binaries.  Specifically, it excludes any Go modules used only in tests, developer tooling, etc.
To generate an accurate `NOTICE.txt`.  We will build upon the changes in this PR to generate a separate `NOTICE-fips.txt` containing Go modules used in the FIPS-capable Elastic Agent binary. 
The code in this PR is inspired by [how APM Server is generating their `NOTICE.txt`](https://github.com/elastic/apm-server/blob/67b1d34a8faa9cee52f652e9dfb740b4089607b1/Makefile#L261-L274). 
- ~[ ] I have made corresponding changes to the documentation~
- ~[ ] I have made corresponding change to the default configuration files~
- ~[ ] I have added tests that prove my …
> Generate NOTICE.txt with only modules used by binaries

- testing/integration/beat_receivers_test.go
This PR adds a guard against a variable being `nil` before we try to dereference it.
> Guard against `nil` pointer dereference

- dev-tools/mage/clean.go
- docs/test-framework-dev-guide.md
This PR adds the .agent-testing folder to the mage clean target. This is necessary because, in some cases, stale Elastic Agent packages from .agent-testing may be used locally instead of the newer packages from build/distributions. This can lead to confusing test failures.
For example, it took hours to track down a failure caused by a leftover agent package at version 0.119.0, even though the main branch was already on version 0.123.0. Running mage clean and repackaging had no effect because the cached folder wasn't being cleared due to a permission issue.
This PR updates the mage clean task to explicitly remove the .agent-testing folder and adds a troubleshooting tip to help others avoid this issue.
> mage: clean up .agent-testing folder on mage clean

- .github/workflows/post-dependabot.yml
- Makefile
- README.md
- changelog/fragments/1746736812-fips-notice.yaml
- dev-tools/mage/pkg.go
- dev-tools/mage/target/common/notice.go
- dev-tools/notice/notice.go
- dev-tools/packaging/packages.yml
- dev-tools/packaging/testing/package_test.go
This PR introduces a number of changes to do with generating a separate NOTICE file for FIPS-capable Elastic Agent binaries, viz. `NOTICE-fips.txt`:
* Running `mage notice` now will generate both `NOTICE.txt` and `NOTICE-fips.txt`.
* The packaging spec will now copy the correct NOTICE file (`NOTICE.txt` or `NOTICE-fips.txt`) into the package.  Note that the file inside the package is always called `NOTICE.txt` for consistency from a user's perspective.
* Running `mage TestPackages` (which is internally run as part of `mage package`) will now check that the packaged NOTICE file is the correct one, depending on whether the package is FIPS-capable or not.
* The `post-dependabot` workflow will now generate the `NOTICE-fips.txt` file along with the `NOTICE.txt` file in Dependabot-created PRs. …
> Generate `NOTICE-fips.txt` file

- .buildkite/bk.integration.pipeline.yml
- .buildkite/pipeline.yml
This commit reverts the version pinning done for VM images in #7958, now that VM images used a pinned version of asdf-golang.
Only testable in Buildkite CI -- CI ought to get green and especially the check-ci step in unit tests should be green.
> Unpin VM images

- .github/workflows/golangci-lint.yml
- Enhancement
Bumps up the golangci-lint version to 2.1.0
golangci-lint-actions is expecting minimum 2.1.0 as seen in these error logs https://github.com/elastic/elastic-agent/actions/runs/14825631356/job/41618365213?pr=8073#step:4:19 for this pr https://github.com/elastic/elastic-agent/pull/8073 …
> enhancment: bumped golangci-lint version to 2.1.0

- testing/integration/linux_deb_test.go
- testing/integration/linux_rpm_test.go
This PR fixes the failing `.deb` and `.rpm` integration tests by replacing references to the now-unavailable `9.0.0-SNAPSHOT` version. The tests now use a hardcoded `9.0.0` version instead, which is the first version that supports flavor-based server installations. 
The CI integration tests for `.deb` and `.rpm` packages were failing due to reliance on the `9.0.0-SNAPSHOT` version, which has been removed from the artifact repository. These failures also affect any backports to the `9.0` branch. Fixing the test inputs ensures CI stability and test coverage continuity for flavor-based installation logic.
None. This change only affects internal test logic and CI stability.
Run the integration tests for `.deb` and `.rpm` flavors
N/A
> ci: fix deb and rpm flavor tests

- .buildkite/scripts/steps/ess.ps1
- .buildkite/scripts/steps/ess.sh
- .buildkite/scripts/steps/ess_start.sh
- .buildkite/scripts/steps/integration_tests_tf.sh
- docs/test-framework-dev-guide.md
- go.mod
- go.sum
- magefile.go
- pkg/testing/common/stack.go
- pkg/testing/ess/client_test.go
- pkg/testing/ess/deployment.go
- pkg/testing/ess/statful_provisioner.go
- pkg/testing/runner/runner.go
- pkg/testing/runner/runner_test.go
- test_infra/ess/output.tf
- testing/integration/fleetserver_fips_test.go
This PR adds an integration test that ensures that a FIPS-capable Elastic Agent running in an ECH FRH (FedRamp High) environment is able to successfully connect to its own local Fleet Server instance (which, by definition should also be FIPS-capable and running in the ECH FRH environment).  
To ensure that FIPS-capable Agent is able to connect to a FIPS-capable Fleet Server in an ECH FRH environment.
- ~[ ] I have made corresponding changes to the documentation~
- ~[ ] I have made corresponding change to the default configuration files~
- ~[ ] I have added tests that prove my fix is effective or that my feature works~
- ~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~
> [FIPS][Integration Test] Ensure FIPS-capable Agent can connect to FIPS-capable Fleet Server in an ECH FRH environment

- .ci/scripts/update-beats.sh
- .ci/updatecli/update-beats.yml
- .github/workflows/bump-beats-version.yml
- dev-tools/mage/target/update/update.go
- magefile.go
Adds automation for updating the beats dependency. This cannot be done using dependabot because:
* Beats isn't properly versioned. We use pseudoversions pointing at commits, which dependabot doesn't support.
* Each elastic-agent branch needs to point at the respective beats branch.
Instead, we take an approach similar to [apm-server](https://github.com/elastic/apm-server/blob/main/.github/workflows/update-beats.yml). We use a scheduled github actions job, which triggers an update using updatecli, which in turn runs the `update:beats` mage target and submits a PR with the changes.
See an example execution in a fork here: https://github.com/swiatekm/elastic-agent/actions/runs/15137576163, and the PRs it created here: https://github.com/swiatekm/elastic-agent/pull/7 …
> Automatically update beats module versions

- changelog/fragments/1747938268-fix-diag-race-condition.yaml
- internal/pkg/diagnostics/diagnostics.go
Handle a race condition that can occur in Agent diagnostics if log rotation happens while logs are being zipped. There is a time window between when `filepath.WalkDir` reads the directory contents and when log files are opened for reading. During this time window, log rotation can happen, resulting in files that no longer exist and cannot be added to the diagnostic archive.
To handle this, `fs.ErrNotExist` errors are ignored when attempting to add log files.
This race can happen at any time, so any user could be affected. The problem is worse if debug logging is enabled and logs are being rotated quickly.
This is the user reported error:
via OCR, it says:
> Error generating file: unable to open log file: open /opt/Elastic/Agent/ data/elastic-agent-8.17.0-96f2b9/ …
> fix(diagnostics): handle log rotation races

- .ci/updatecli/update-beats.yml
In the updatecli condition check if the update was necessary, here was an unnecessary `$`. As a result, we never skipped the update.
Tested this locally and it looked correct.
> Fix minor typo in beats update job

- testing/upgradetest/versions.go
- testing/upgradetest/versions_test.go
This PR updates the upgradable version selection logic in `FetchUpgradableVersions` to explicitly exclude previous patch versions when the major and minor versions match the `UpgradeToVersion` version.
Specifically:
- It introduces a check to skip any versions with the same major and minor as the upgrade target if their patch is less than or equal to the `UpgradeToVersion` patch part.
- It rewrites `TestFetchUpgradableVersionsAfterFeatureFreeze` to use table-driven tests with self-contained version data.
- Prevents redundant patch upgrades from being included as upgrade candidates when not applicable.
- Fixes test flakiness issue in `PreviousMinor()` where versions like `9.0.1` failed to resolve a previous minor due to ambiguous or stateful data dependencies.
None. This change only …
> [ci] fix update versions

- .buildkite/bk.integration.pipeline.yml
- .buildkite/integration.pipeline.yml
- .buildkite/scripts/buildkite-integration-tests.sh
- .buildkite/scripts/integration-tests.ps1
- .buildkite/scripts/steps/integration_tests_tf.sh
This PR migrates the **Extended Runtime Leak Tests** to Buildkite, where all other integration and Kubernetes tests now reside. The new setup runs these tests on Windows 2022, Windows 2025, and Ubuntu 24.04 using existing prebuilt VM images. The old step is removed to avoid duplication and eliminate the dependency on OGC.
Proof that we run the same tests:
* [Before this PR](https://buildkite.com/organizations/elastic/pipelines/elastic-agent-extended-testing/builds/8548/jobs/01966bdd-34a4-4cdb-877b-88899ecd5419/artifacts/01966c32-e5e2-4127-8081-2a3b365e70fb)
* [With this PR Windows 2022](https://buildkite.com/organizations/elastic/pipelines/elastic-agent/builds/21584/jobs/01971b2f-65bd-4674-83f1-78c516bf736f/artifacts/01971b51-8019-4b3d-9230-5c18d5f8ba7c), [With this PR Windows …
> [ci] migrate extended runtime leak tests to buildkite

- .buildkite/bk.integration.pipeline.yml
- .buildkite/pipeline.elastic-agent-helm-charts.yml
- .buildkite/pipeline.integration-test-matrix.yml
This PR updates all Buildkite pipeline steps that were previously using `n1-standard-8` GCP machine types to instead use `n2-standard-8`.
The following pipeline YAML files were updated:
- `.buildkite/bk.integration.pipeline.yml`
- `.buildkite/pipeline.elastic-agent-helm-charts.yml`
- `.buildkite/pipeline.integration-test-matrix.yml`
The `n1` machine series is deprecated and offers worse performance and price efficiency compared to the `n2` series. As noted in the review of a prior PR, using `n2-standard-8` helps prevent resource limitations and improves overall CI stability and performance. This change ensures consistency across all CI steps and aligns with best practices for machine type selection in GCP (context [here](https://github.com/elastic/elastic-agent/pull/7931#discussion_r212269 …
> ci: update all n1-standard-8 type runners to n2-standard-8

- .github/workflows/bump-agent-versions.yml
- .github/workflows/bump-beats-version.yml
- .github/workflows/post-dependabot.yml
Pin third-party actions
Pin mage version
Supply chain
Reproducible builds
-
- ...
> github-actions: pin mage action and use fixed version

- internal/pkg/agent/install/uninstall_test.go
This PR addresses increases the test context timeout from 5s to 20s of `Test_checkForUnprivilegedVault` to accommodate for slower machines, such as Mac CI runners, and to avoid intermittent failures due to timing out while trying to acquire a file lock.
The test `Test_checkForUnprivilegedVault/file_vault_exists_but_it's_unreadable_-_return_error` was observed to fail intermittently on slower environments (e.g., Mac runners) due to `context deadline exceeded` errors when attempting to acquire a file lock. These failures were not related to the actual logic being tested, but rather to insufficient timeout settings. Increasing the timeout ensures test stability across environments. In addition, updating the deprecated `logp.NewInMemory` call eliminates static analysis warnings.
None. This …
> fix: increase context timeout to accommodate for slower machines in Test_checkForUnprivilegedVault

- .buildkite/hooks/pre-command
Fix a pre-command hook to allow BUILDKITE_PIPELINE_SLUG to match elastic-agent for PRs, and elastic-agent-extended-tests once it has merged to main
> Fix pre-command to support extended testing

- testing/integration/fleetserver_fips_test.go
This PR amends the `TestFIPSAgentConnectingToFIPSFleetServerInECHFRH` integration test to wrap the flaky assertion and it's pre-requisite code in a `require.Eventually` block.
To avoid flakiness in the test.
Closes #8419
> `TestFIPSAgentConnectingToFIPSFleetServerInECHFRH `: Use `require.Eventually` to try and address flakiness

- .github/workflows/bump-otel-version.yml
Fixes the `bump-otel-version` Dependabot workflow by adding missing step to install Mage. Mage is needed later in the `update-otel.sh` script, which runs `mage notice` and `mage otel:readme`.
Without it, the workflow fails: https://github.com/elastic/elastic-agent/actions/runs/15576842484/job/43863265436
> .ci/scripts/update-otel.sh: line 41: mage: command not found …
> fix(ci): add missing install Mage step

- .ci/updatecli/updatecli-bump-vm-images.yml
- .github/workflows/bump-vm-images.yml
- .mergify.yml
* Run on Saturdays, a few hours after VM images are produced.
* Create PRs per active branch instead of using the backport labels.
* Use slack composite action.
* Notify the robots team if something goes wrong with the GH actions.
* Enable auto approval and auto-merge with `Mergify` [Need to configure the branch protections accordingly]
A follow-up from https://github.com/elastic/elastic-agent/pull/8211
```bash
$ GITHUB_TOKEN=$(gh auth token) \
GITHUB_ACTOR=v1v \
BRANCH_NAME=main updatecli apply \
--config .ci/updatecli/updatecli-bump-vm-images.yml \
--values .ci/updatecli/values.d/scm.yml
```
Produced https://github.com/v1v/elastic-agent/pull/7
Then I targeted a different branch
```bash
$ GITHUB_TOKEN=$(gh auth token) \
GITHUB_ACTOR=v1v \
BRANCH_NAME=main updatecli apply \
--config …
```
> updatecli: create PRs per active branch and refactor slack notifications

- internal/pkg/agent/application/monitoring/testdata/monitoring_config_full.yaml
- internal/pkg/agent/application/monitoring/v1_monitor.go
- internal/pkg/agent/application/monitoring/v1_monitor_test.go
- testing/integration/beat_receivers_test.go
- testing/integration/otel_test.go
Adds last part of comparing process based monitoring vs beat receiver based monitoring
- Adds Windows as test case
- adds filebeat_input metrics to config
- adds filebeat_input metrics to integration test
We need to make sure that both implementations produce the same documents.
None.  Unit test and changes to producing configuration when experimental runtime is used.
```shell
mage integration:single TestClassicAndReceiverAgentMonitoring
```
- Closes #8188
- Closes elastic/ingest-dev#4876
- ...
> Add filebeat_input to beat receiver agent monitoring integration test

- .github/workflows/bump-vm-images.yml
Add a branch name in the Slack error message.
Checkout the branch with the upatecli pipeline changes to fix this [error](https://github.com/elastic/elastic-agent/actions/runs/15609339029)
This will help when configuration changes are different between branches.
However, this will require maintaining the updatecli pipeline in different branches too.
https://github.com/elastic/elastic-agent/pull/8359 introduced the support for `.buildkite/bk.integration-fips.pipeline.yml` but https://github.com/elastic/elastic-agent/pull/8035 was only backported to `8.19`. Hence it failed for `9.0`, `8.18` and `8.17`.
-
- ...
> github-actions: updatecli bump for specific branches

- changelog/fragments/1749844873-Use-Debian-11-for-linux-arm-to-match-linux-amd64.yaml
- dev-tools/mage/crossbuild.go
- Relates https://github.com/elastic/elastic-agent/pull/8471
Splitting this fix out of https://github.com/elastic/elastic-agent/pull/8471 in which we were observing a linker error previously experienced in Beats which was resolved by building with Debian11, see https://github.com/elastic/beats/issues/41270.
```
2025-06-12 17:34:34 UTC | /usr/local/go/pkg/tool/linux_arm64/link: running gcc failed: exit status 1
/usr/bin/gcc -s -Wl,-z,relro -pie -Wl,-z,now -Wl,-z,nocopyreloc -fuse-ld=gold -Wl,--build-id=0xee5395581ef98b935ea709af599bac9aa3bac678 -o $WORK/b001/exe/a.out -rdynamic -Wl,--compress-debug-sections=zlib /tmp/go-link-732555023/go.o /tmp/go-link-732555023/000000.o /tmp/go-link-732555023/000001.o /tmp/go-link-732555023/000002.o /tmp/go-link-732555023/000003.o …
```
> Explicitly crossbuild linux/arm with debian11.

- .ci/updatecli/updatecli-bump-stack-version.yml
- .github/workflows/bump-stable-snapshot.yml
UpdateCLI ESS version pinning: Adds exclusions for release branches because we decided to merge them later. 
The exclusions must me removed when the backports are merged
Fixes a typo in pipeline name
-
- ...
> [CI] Add exclusions for release branches

- internal/pkg/agent/application/upgrade/artifact/artifact_test.go
Following up to https://github.com/elastic/elastic-agent/pull/7804, this PR cleans up unused fields and adds a test case to the `TestGetArtifactName` unit test introduced in that PR.
> `TestGetArtifactName`: Add test case + cleanup unused fields

- internal/pkg/agent/application/coordinator/coordinator.go
- internal/pkg/agent/application/coordinator/coordinator_unit_test.go
- internal/pkg/otel/translate/status.go
- internal/pkg/otel/translate/status_test.go
Otel component status processing needs to emit fake STOPPED events for components which don't exist anymore. This was incorrectly taking place for components running as beats processes, resulting in them incorrectly reporting a STOPPED state.
I've also made two minor refactoring changes:
* The coordinator's `watchRuntimeComponents` method now takes two channels as parameters instead of obtaining them from component fields. This makes it easier to test.
* The `translate.DropComponentStateFromOtelStatus` now no longer modifies its input, but instead returns a modified copy. …
> Fix non-otel component status being incorrectly deleted

- .ci/updatecli/update-beats.yml
- Fixes https://github.com/elastic/elastic-agent/issues/8382
Set `force: false` in the beats-bump updatecli SCM configuration to ensure concurrent runs in different branches can succeed as suggested in https://github.com/elastic/elastic-agent/issues/8382#issuecomment-2982893920
> Set force in update-beats scm configuration.

- testing/integration/k8s/kubernetes_agent_standalone_test.go
This PR restores the `ELASTIC_AGENT_OTEL=true` environment variable in the `TestKubernetesAgentOtel` test by adding it to the `agentContainerExtraEnv` slice. This is necessary for the test to properly validate the OpenTelemetry functionality of the standalone Elastic Agent running in Kubernetes.
This change fixes a regression introduced by a previously incorrect backport in [#8623](https://github.com/elastic/elastic-agent/pull/8623), which inadvertently removed the `ELASTIC_AGENT_OTEL=true` environment variable from the test. Without this variable, the test does not activate OTEL mode in the agent, rendering the test invalid.
None. This change only affects test code and has no impact on users or production deployments.
```
mage integration:buildKubernetesTestData
EXTERNAL=true …
```
> [ci] otel k8s integration tests

- dev-tools/packaging/templates/linux/postinstall.sh.tmpl
- testing/integration/endpoint_security_test.go
This PR fixes a regression introduced by #6907, which updated the RPM/DEB preinstall script to stop the `ElasticEndpoint` service during agent upgrades to work around tamper protection restrictions. While effective in stopping the service, the original change restarted the endpoint **before** restarting the agent. This sequence causes most of the time endpoint to try and reconnect to elastic-agent but without any time guarantees when this is gonna be successful.
To address this, the PR:
- Restart of the `ElasticEndpoint` service **after** the `elastic-agent` service has been restarted to guarantee that elastic-endpoint can connect to elastic-agent.
- Enhances integration tests to:
- Use locally built artifacts when testing same-version upgrades.
- Improve error messages and fixture …
> [deb/rpm] restart endpoint with tamper protection after elastic-agent 

- .buildkite/bk.integration-fips.pipeline.yml
This PR removes some environment variables from steps in the FIPS build pipeline, `.buildkite/bk.integration-fips.pipeline.yml`.  It turns out these environment variables are not actually needed in these steps.
Thanks to @pkoutsovasilis for spotting this while reviewing https://github.com/elastic/elastic-agent/pull/8417.
> [CI][FIPS] Remove unnecessary env vars from FIPS build pipeline steps

- deploy/helm/elastic-agent/README.md
- deploy/helm/elastic-agent/examples/kubernetes-onboarding/README.md
- deploy/helm/elastic-agent/examples/kubernetes-onboarding/agent-kubernetes-values.yaml
- deploy/helm/elastic-agent/examples/kubernetes-onboarding/rendered/manifest.yaml
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_apiserver.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_controller_manager.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_kubelet_containers.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_kubelet_nodes.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_kubelet_pods.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_kubelet_system.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_kubelet_volumes.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_logs_audit.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_logs_containers.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_proxy.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_scheduler.tpl
- deploy/helm/elastic-agent/templates/integrations/_kubernetes/_kubernetes_state.tpl
- deploy/helm/elastic-agent/values.schema.json
- deploy/helm/elastic-agent/values.yaml
This PR introduces support for an `onboardingID` field in the `kubernetes` integration of the Elastic Agent Helm chart. The onboarding ID is injected into all supported `kubernetes` data streams as an `add_fields` processor when specified. 
As part of the Observability Logs Essentials Serverless tier, metrics collection should be disabled in the onboarding quick-start flows. This PR aligns the Helm chart behavior with the intended onboarding experience by enabling an explicit onboarding identifier (`onboardingID`) to be passed to the deployed Elastic Agents, similar to the existing behavior in the Kustomize-based setup.
This onboarding ID is used by the backend to correlate logs/metrics to onboarding sessions and improve user experience and supportability during initial usage.
This is a …
> [Helm] support onboarding-id for kubernetes

- docs/test-framework-dev-guide.md
- magefile.go
As request in previous [PR reviews](https://github.com/elastic/elastic-agent/pull/8396#discussion_r2136156702) this PR introduces `Single` mage targets for the `serverless` and `leak` integration test packages, similar to the existing `TestKubernetesSingle` target. It adds the following functions to the `magefile.go`:
- `TestServerlessSingle`
- `TestForResourceLeaksSingle`
Internally, both new targets delegate to shared helper functions that support selecting a specific test by name. This unifies the way we run individual integration tests across packages and prepares the mage targets for further package splits.
As part of the effort to split the increasingly large integration test suite into smaller dedicated packages (see parent issue), we also need to ensure that developers can run …
> feat: singleTest mage target for each integration test package

- go.mod
- go.sum
- internal/pkg/otel/run_nofips_test.go
- pkg/component/component_test.go
- pkg/component/config_test.go
This PR bumps up the github.com/go-viper/mapstructure/v2 module dependency to the latest available version.
To keep our dependencies up to date.
> Bump up github.com/go-viper/mapstructure/v2 dependency

- .github/dependabot.yml
Removed reviewers section in dependabot.yml, since it duplicates the definition from CODEOWNERS.
Reviewers dependabot.yml configuration is being retired option because the functionality overlaps with GitHub code owners.
See: https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/
- ~[ ] I have commented my code, particularly in hard-to-understand areas~
- ~[ ] I have made corresponding changes to the documentation~
- ~[ ] I have made corresponding change to the default configuration files~
- ~[ ] I have added tests that prove my fix is effective or that my feature works~
- ~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~
- ~[ ] I have added an …
> Replace Dependabot reviewers with code owners

- testing/integration/ess/upgrade_rollback_test.go
Re-enable `TestStandaloneUpgradeRollbackOnRestarts` integration test on windows.
Modifications introduced with https://github.com/elastic/elastic-agent/pull/8407 should have fixed the timing issue that made TestStandaloneUpgradeRollbackOnRestarts flaky on windows
To re-enable testing of rolling back upgrade on windows operating systems
- Closes #6733 …
> Re-enable TestStandaloneUpgradeRollbackOnRestarts on windows

- changelog/fragments/1751455886-correct-log-level-for-standalone-agents.yaml
- internal/pkg/agent/application/info/agent_info.go
- internal/pkg/agent/application/info/agent_info_test.go
This PR fixes a bug where the log level for standalone Elastic Agent installations was incorrectly restored from the persisted state directory (`/var/lib/elastic-agent-standalone/...`) instead of being sourced from the current configuration file. This resulted in stale configuration values after updates to the ConfigMap, particularly when the pod was restarted without clearing the state directory.
The change ensures that for standalone mode, the `log.level` value is always taken from the configuration, not restored from previously persisted agent state. For managed (Fleet) mode, the previous behavior is preserved.
This fix addresses an issue where changes to logging configuration were not taking effect unless the agent's state directory was manually deleted. This led to operational …
> fix: don't override log level from state for standalone agents

- internal/pkg/composable/controller_test.go
This PR increases the timeout in `TestProvidersDefaultDisabled` from 1 second to 10 seconds and ensures the test uses `t.Context()` to inherit the test deadline. These changes accommodate slower CI runners, particularly on macOS, which have occasionally caused the test to fail due to race conditions or delayed initialization.
This test was observed to fail intermittently in CI environments with the following panic:
```
runtime error: index out of range [1] with length 1
```
This is likely caused by timing-related flakiness, where the test assumptions about initialization timing do not hold under slower CI conditions. Increasing the timeout and using `t.Context()` ensures proper cancellation and cleanup while reducing test flakiness.
None expected. This change only affects an internal unit …
> flaky: accommodate for slower CI runners in TestProvidersDefaultDisabled

- catalog-info.yaml
Register agentless component to the internal development platform
-
- ...
> chore(agentless): register to backstage

- testing/installtest/checks_unix.go
This PR adjusts the `validateFileTree` function in `installtest/checks_unix.go` to gracefully ignore `os.ErrNotExist` errors when traversing the Elastic Agent installation directory. Specifically, during file tree validation, if a file or directory no longer exists at the time of inspection, the function will now skip over it instead of failing the entire validation.
This change addresses flakiness in the `TestRepeatedInstallUninstallFleet` test. The test occasionally fails due to transient files (e.g., `.new` files) being deleted or replaced during the validation process. Since some of these files are expected to be short-lived or replaced atomically, their absence should not be treated as a fatal error.
By skipping over non-existent files, we reduce false negatives in tests and make the …
> flaky: ignore errors about non existing files in validateFileTree

- internal/pkg/otel/samples/darwin/autoops_es.yml
- internal/pkg/otel/samples/linux/autoops_es.yml
- internal/pkg/otel/samples/windows/autoops_es.yml
This forces the AutoOps data to provide a module level field named "temp_resource_id" that can be associated during the handshake period.
Adds a field that is needed during registration.
The resource (orchestrator) does not exist until after registration, so to associate events, such as errors, it needs this ID to associate them.
> [AutoOps] Support Temporary Resource ID

- testing/integration/ess/otel_test.go
Changes the logic of comparing documents produced by agent in non-otel and otel modes. Up until now, if neither document contained a field that should be ignored, the test would fail. After the change, the test proceeds with comparing the remaining fields.
There's some flakiness related to the ignored fields, which may sometimes not appear. This is largely unrelated to what these tests are actually checking, so disabling it temporarily shouldn't impact us negatively.
This should be re-enabled once we figure out the root cause of https://github.com/elastic/elastic-agent/issues/8486.
- ~~[ ] I have added tests that prove my fix is effective or that …
> Don't fail otel tests if both documents don't contain an ignored field

- changelog/fragments/1751960319-fix-blocking-issues-inside-runtime-communicator.yaml
- pkg/component/runtime/runtime_comm.go
- pkg/component/runtime/runtime_comm_test.go
This PR fixes multiple deadlock conditions in the runtime communicator logic and improves overall lifecycle handling. Specifically, it:
- Handles potential deadlock when sending the initial observed message to the runtime if the communicator is destroyed.
- Handles deadlock when the runtime calls `CheckinExpected` (init expected check-in) and the communicator is already destroyed.
- Handles deadlock when the runtime calls `CheckinExpected` (init expected check-in) and the server has been disconnected.
- Although highly unlikely due to existing synchronisation primitives, it doesn't block against multiple init checkin messages that arrive after the first that completed the init checkin process.
- Removes a redundant goroutine in the `checkin` method, which also allows returning accurate …
> fix: blocking issues of runtime communicator

- testing/integration/ess/apm_propagation_test.go
This PR skips the `TestAPMConfig` test in `apm_propagation_test.go` due to its flaky behavior. The flaky runs of this test fail with `index_not_found_exception` for the `traces-apm-default` index in Elasticsearch.
Flaky tests erode confidence in CI signal and can obscure genuine regressions. Skipping `TestAPMConfig` prevents CI failures while the root cause is investigated and resolved in [issue #5890](https://github.com/elastic/elastic-agent/issues/5890). This helps restore signal quality and developer productivity.
None. This change only affects the test suite by skipping a known-flaky test. There is no impact to users of the Elastic Agent.
```
mage integration:auth
STACK_PROVISIONER=stateful TEST_PLATFORMS="linux/amd64" mage integration:single TestAPMConfig
```
- Relates …
> flaky: skip TestAPMConfig

- deploy/helm/elastic-agent/examples/statefulset-preset/README.md
- deploy/helm/elastic-agent/examples/statefulset-preset/agent-values.yaml
- deploy/helm/elastic-agent/examples/statefulset-preset/rendered/manifest.yaml
- deploy/helm/elastic-agent/templates/agent/eck/statefulset.yaml
- deploy/helm/elastic-agent/templates/agent/k8s/statefulset.yaml
- deploy/helm/elastic-agent/templates/agent/service.yaml
This PR adds support for deploying Elastic Agent using StatefulSet by properly defining a `serviceName`, as required by the Kubernetes specification for StatefulSets.
Specifically, it:
- Introduces a headless service (`clusterIP: None`) per preset when `mode: statefulset` is used.
- Sets the `serviceName` field in the StatefulSet template to refer to the respective headless service.
- Provides a working example under `examples/statefulset-preset/` showcasing a NetFlow integration running as a StatefulSet.
StatefulSets in Kubernetes require the `serviceName` field to be specified to ensure stable network identities and persistent storage for each replica. 
None. This is an additive change that only affects users opting into StatefulSet mode. Existing other mode-based presets are …
> helm: define headless service for statefulset presets

- internal/pkg/agent/application/monitoring/process.go
- internal/pkg/agent/application/monitoring/v1_monitor.go
- internal/pkg/otel/manager/diagnostics.go
- internal/pkg/otel/manager/diagnostics_test.go
- testing/integration/ess/diagnostics_test.go
It adds beat stats and input metrics to beat receiver diagnostics.
Note that this currently targets #9095, and will switch to main once that is merged. 
Diagnostics for beat receivers should contain the same information as they do for beat processes.
Build agent from this PR, then start it with self-monitoring in otel mode and generate diagnostics. You should see `beats_metrics.json` and `input_metrics.json` in the components' respective subdirectories in the diagnostics archive.
- Relates …
> Add beat metrics to beat receiver diagnostics

- testing/integration/ess/upgrade_rollback_test.go
- testing/upgradetest/versions.go
Fix minimum version check to assert rollback reason when an elastic-agent upgrade is automatically rolled back.
PR #8407 didn't make it into 9.1 before the release branch is detached, so with the new version 9.1.0 being released, tests `TestStandaloneUpgradeRollback` wrongly expected to find the rollback reason from a 9.1.0 `elastic-agent status` output.
To have correct assertions for `TestStandaloneUpgradeRollback` integration tests.
- ~~[ ] I have added an entry in …
> Fix version check in rollback tests

- testing/integration/ess/inspect_test.go
Fix a race condition in an integration test by waiting until a policy change action is acked before running the inspect command.
The test is flaky without the change. The inspect command and the config change from the policy race against each other, and the test fails if inspect wins.
- Closes https://github.com/elastic/elastic-agent/issues/7171
> Wait for policy action to be acked in TestInspect

- changelog/fragments/1753906482-Don't-overwrite-elasticsearch-output-headers-from-enrollment---headers-flag.yaml
- pkg/component/component.go
- pkg/component/component_test.go
Changes the behavior of `toIntermediate` to only add headers to an output if the output doesn't already have that header defined.
This allows the use-case where the same header name is used for Fleet and Elasticsearch, but the value of each is different.
- ~~[ ] I have added an integration test or an E2E test~~ (covered by unit tests)
None
- Closes #9197
> Don't overwrite existing headers when mapping agentInfo headers into elasticsearch output

- testing/integration/ess/endpoint_security_test.go
This PR temporarily skips the `TestUpgradeAgentWithTamperProtectedEndpoint_DEB/Install_same_version_over_the_installed_agent` integration test.  
The test has started failing consistently in the last few days on `main` and also in draft PR pipelines.  
Reference failures: 
- [Main branch failure](https://buildkite.com/elastic/elastic-agent-extended-testing/builds/9611#019872a0-3088-40e5-a584-d4e93ac76c1f/381-732)  
- [Draft PR pipeline](https://buildkite.com/elastic/elastic-agent/builds/24748#01986997-a763-4569-b26e-90046657d3fa/220-566)  
The test will remain skipped until the root cause is identified and a fix is implemented cc @ebeahan 
- Keeps the CI green while the root cause of the failures is being investigated.  
- Prevents unrelated PRs from being blocked by a known failing test. …
> skip: TestUpgradeAgentWithTamperProtectedEndpoint_DEB 

- testing/integration/ess/upgrade_integrations_server_test.go
This PR restricts the versions used as start versions in `TestUpgradeIntegrationsServer` to those actually available in the ECH region where the integrations server is being run.
The test should not attempt to use a start version that doesn't actually exist in the ECH region where the integrations server deployment will be created.
None; this PR modifies an integration test.
Follow up to https://github.com/elastic/elastic-agent/pull/9207#issuecomment-3157529153
- ...
> [FIPS] Only consider versions available in ECH region for `TestUpgradeIntegrationsServer`

- internal/pkg/agent/application/upgrade/artifact/download/http/downloader.go
- Cleanup
Removing explicit use of the embedded `HTTPTransportSettings` field in http downloader
It is causing linting errors
none
not necessary
none
> enhancement(5235): removed HTTPTransportSettings embedded struct field use from http downloader

- .buildkite/bk.integration-fips.pipeline.yml
- .buildkite/bk.integration.pipeline.yml
- .buildkite/integration.pipeline.yml
- .buildkite/pipeline.yml
Reverts elastic/elastic-agent#9407
As per https://github.com/elastic/elastic-agent/issues/9433#issuecomment-3197240477, we need to revert it as it causes packaging problems due to git vcs errors.
> Revert "[9.1][Automation] Bump VM Image version to 1755306060"

- .buildkite/bk.integration.pipeline.yml
- .buildkite/integration.pipeline.yml
- .buildkite/pipeline.yml
Reverts elastic/elastic-agent#9403
As per https://github.com/elastic/elastic-agent/issues/9433#issuecomment-3197240477, we need to revert it as it causes packaging problems due to git vcs errors.
> Revert "[9.0][Automation] Bump VM Image version to 1755306060"

- .buildkite/bk.integration.pipeline.yml
- .buildkite/integration.pipeline.yml
- .buildkite/pipeline.yml
Reverts elastic/elastic-agent#9402
As per https://github.com/elastic/elastic-agent/issues/9433#issuecomment-3197240477, we need to revert it as it causes packaging problems due to git vcs errors.
> Revert "[8.17][Automation] Bump VM Image version to 1755306060"

- changelog/fragments/1755544412-Fix-default-constant-support-in-output-configuration.yaml
- elastic-agent.yml
- internal/pkg/agent/transpiler/vars.go
- internal/pkg/agent/transpiler/vars_test.go
Adds backwards compatibility for the `:` that comes from `go-ucfg` that was originally used in outputs before https://github.com/elastic/elastic-agent/commit/b59d51af881397da24efde53b33750be9132a1d0 was merged.
The `:` allows the following characters to be considered a constant where the `|` considers the following characters as a variable unless wrapped in quotes. This allows `${ELASTICSEARCH_USERNAME:}` to be used in outputs and work originally as it used to before variables provider was switch for output replacement.
This ensures that configurations that used the `go-ucfg` syntax in output configuration works as it always did, but continues to allow the composable providers in outputs.
- ~~[ ] I have made corresponding …
> Add support for variable parser to handle `:` as default constant .

- .github/dependabot.yml
This PR makes it so that all future Dependabot-created PRs will have the `backport-active-all` label on them.
To ensure that dependencies are updated in all active branches.
> Add "backport-active-all" label to Dependabot-created PRs

- internal/pkg/agent/application/coordinator/coordinator_unit_test.go
- internal/pkg/agent/application/enroll/options.go
- internal/pkg/agent/application/enroll/options_test.go
when we use enroll options in migrate flow constructed by FromFleetConfig we can fail on url.Parse as URL is preset from Host that omits protocol information. 
Prolematic is  subsequent call of
```
options := FromFleetConfig()
options.RemoteConfig()
```
where RemoteConfig parses URI 
Logic is the same as we use in [client URI function](https://github.com/elastic/elastic-agent/blob/392fc972241caf6043f477f5f4c08377b5588e54/internal/pkg/remote/client.go#L255).
This PR changes construction of EnrollOptions.URL in a way that Protocol information is not lost
Related: https://github.com/elastic/elastic-agent/issues/9574
> Enroll options contains parsable URI after FromFleetConfig call

- .github/workflows/backport-active.yml
Support backports after a PR has been merged and labelled with `backport-active-*`.
Fixes a corner case when the PRs have been labeled after being merged with the supported list of active branches.
-
- ...
> github-actions: support label after being merged

- internal/pkg/agent/application/actions/handlers/handler_action_policy_reassign.go
- internal/pkg/agent/application/upgrade/artifact/download/http/verify_backoff_rtt.go
- internal/pkg/agent/application/upgrade/upgrade.go
- internal/pkg/agent/migration/migrate_config.go
- internal/pkg/composable/providers/kubernetes/kubernetes.go
- internal/pkg/config/loader.go
- internal/pkg/remote/client.go
- pkg/testing/ess/serverless_provisioner.go
This PR fixes fatal go vet errors on calls to logp functions. Release [v0.22.1](https://github.com/elastic/elastic-agent-libs/releases/tag/v0.22.1) of elastic-agent-libs enabled proper go vet support for printf style calls in logp, and that uncovered many misuses of printing directives.
```bash
$ go get -u github.com/elastic/elastic-agent-libs@v0.22.1
$ go vet ./...
```
- Relates https://github.com/elastic/elastic-agent-libs/pull/340.
- Relates https://github.com/elastic/beats/pull/45944
> chore: fix formatting issues in logp printf-style calls

- dev-tools/mage/crossbuild.go
This PR updates the golangCrossBuild logic to conditionally mount `/opt/git-mirrors` into the container if it exists.  
This ensures that git alternates created by Buildkite PR checkouts can be resolved correctly when running `go build`.
In Buildkite, PRs are checked out using a local git mirror reference:
```bash
git clone -v --reference /opt/git-mirrors/git-github-com-elastic-elastic-agent-git -- git@github.com:elastic/elastic-agent.git .
git clean -ffxdq
git fetch -v --prune -- origin refs/pull/<PR>/head
git checkout -f <commit-sha>
git clean -ffxdq
```
This creates a `.git/objects/info/alternates` file pointing to `/opt/git-mirrors/....`
If this path is missing inside the container, any git invocation might fail because it cannot find the referenced object database.
Without this …
> fix: mount /opt/git-mirrors in golang-crossbuild container for VCS stamping

- dev-tools/mage/downloads/utils.go
- dev-tools/mage/downloads/utils_test.go
- dev-tools/mage/downloads/versions.go
Refactors how the agent packaging target downloads binaries. The intent is to make it possible to cache the binaries locally and avoid having to redownload them. See https://github.com/elastic/elastic-agent/pull/9133 for the full context.
The PR consists of the following changes:
* The download function now always gets a target path as an input, so it doesn't need to create it on its own conditionally.
* We use standard library functions for the download, so we don't need to pass the content as a string, and can instead write it directly to the target file, saving memory.
* Remove some unused functions.
This makes the download code more maintainable and more performant. It also unlocks further packaging improvements.
- ~~[ ] …
> Refactor binary downloads in agent packaging targets

- changelog/fragments/1758045690-clear-coordinator-state.yaml
- internal/pkg/agent/application/coordinator/coordinator.go
- internal/pkg/agent/application/coordinator/coordinator_test.go
This PR fixes a regression introduced by [#9634](https://github.com/elastic/elastic-agent/pull/9634) where the coordinator’s `overrideState` could remain set if an upgrade attempt failed early (e.g. agent not upgradeable, capability check denied, or pre-upgrade callback returned an error).  
Specifically, this PR:
- Adds calls to `ClearOverrideState()` before returning from all early failure branches inside `Coordinator.Upgrade`.
- Extends the coordinator test suite to assert that `overrideState` is reset to `nil` after a failing `preUpgradeCallback`, preventing stale state from leaking into subsequent upgrade attempts.
Without this change, failed upgrades could leave the coordinator in a state that incorrectly reflects an ongoing upgrade. This blocks future upgrade attempts until the …
> fix: always clear the coordinator overridden state on err inside upgrade of coordinator

- .buildkite/bk.integration-fips.pipeline.yml
- .buildkite/pipeline.yml
This PR temporarily creates ECH deployments for the FIPS integration testing Buildkite pipeline in the Production CFT ESS environment (as opposed to the Staging GovCloud ESS environment).
The FIPS integration tests pipeline is currently failing because the step where it provisions deployments in GovCloud Staging is consistently failing.
> Temporarily have FIPS integration tests spin up deployments in Production CFT environment

- .github/workflows/update-docs.yml
- docs/reference/edot-collector/components.md
- docs/reference/edot-collector/custom-collector.md
- docs/reference/edot-collector/download.md
- docs/scripts/update-docs/templates/components-table.jinja2
- docs/scripts/update-docs/templates/ocb.jinja2
- docs/scripts/update-docs/update-components-docs.py
This PR improves our Collector docs automation to avoid creating PRs for current docs from the changes in `main`, as the Collector reference docs always describe the latest version.
- Added logic to discover latest semantic version tag from Git repository
- Set LATEST_VERSION environment variable to pass version to Python script
- Updated PR title to include version: "Update generated documentation for {version}"
- Enhanced PR description with version information and source file references
- Added links to versioned source files (go.mod, core-components.yaml, release tag)
- Added read_file_from_git_tag() function to read files from specific Git tags
- Modified all data-reading functions to use git show {tag}:{file} commands:
- get_core_components() - reads from …
> Improve Collector docs automation script

- changelog/fragments/1757710842-Add-agent_policy_id-and-policy_revision_idx-to-checkin-requests.yaml
- internal/pkg/agent/application/actions/handlers/handler_action_policy_change.go
- internal/pkg/agent/application/actions/handlers/handler_action_policy_change_test.go
- internal/pkg/agent/application/actions/handlers/handler_action_unenroll.go
- internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
- internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
- internal/pkg/fleetapi/checkin_cmd.go
- pkg/features/features.go
Add the agent_policy_id and policy_revision_idx attributes to checkin requests.
These attributes are sources from the action stored as a part of the state.
Add a feature flag to disable sending acks for policy change actions; behaviour for policy change acks has not been changed with this addition (they are always sent).
The policy information in fleet-server and agent may go out of sync; this may occur in cases where a VM restores from a snapshot.
N/A
- Closes #6446
> Add agent_policy_id and policy_revision_idx to checkin requests

- internal/pkg/otel/samples/darwin/autoops_es.yml
- internal/pkg/otel/samples/linux/autoops_es.yml
- internal/pkg/otel/samples/windows/autoops_es.yml
This configures the standard `sending_queue` to batch-process and limit the maximum size of payloads being sent over the wire to avoid proxy and other rejections.
Note: `max_size` is uncompressed bytes and `enabled` defaults to `true`, but it's unused if no settings are set. I want to ensure a future release doesn't flip the default to `false`.
It limits the size of requests being sent over the wire to a more reasonable size.
Sending large payloads can trigger security issues as well as rejections at many levels.
> [AutoOps] Configure OTel Exporter to Send Maximum-sized Batches

- internal/pkg/otel/translate/otelconfig.go
- internal/pkg/otel/translate/otelconfig_test.go
Ensures the extension list in the otel config we generate for components always has only one instance of each extension. Currently, we get the same beatsauth extension multiple times, which only works due to a quirk of otel's config processing.
The config we currently generate for the otel collector is invalid, and is only accepted and works correctly due to implementation details.
- Closes https://github.com/elastic/elastic-agent/issues/10154
> Deduplicate extensions when generating otel config

- internal/pkg/otel/config/config.go
- internal/pkg/otel/manager/manager_test.go
- testing/integration/ess/metrics_monitoring_test.go
This PR makes the **EDOT collector subprocess execution mode the default** and extends our integration test coverage to ensure its resource metrics are visible under Fleet-managed setups.  
Key changes:
- **Default execution mode:** Switches the OTel collector from in-process (`EmbeddedExecutionMode`) to subprocess (`SubprocessExecutionMode`), insulating the Elastic Agent control plane from collector panics, segmentation faults, or memory leaks.
- **Enhanced integration test:** Extends `TestMetricsMonitoringCorrectBinaries/TestBeatsMetrics` in `testing/integration/ess/metrics_monitoring_test.go` to:
- Programmatically add an `_runtime_experimental: otel` agent monitoring policy overwrite.
- Query Elasticsearch for `elastic-agent/collector` resource metrics …
> feat: make EDOT subprocess the default execution mode

- internal/pkg/agent/cmd/otel_flags.go
- internal/pkg/agent/cmd/validate_test.go
This uses the expected `::` syntax instead of `.` for the `--set` argument.
Fixes the example text for showing users how to use the `--set` argument.
The documentation shows the correct format.
> [OTel] Fix CLI example to use proper syntax

- docs/docset.yml
- docs/reference/edot-collector/_snippets/edot-collector-auth.md
- docs/reference/edot-collector/_snippets/guided-instructions.md
- docs/reference/edot-collector/_snippets/process-config.md
- docs/reference/edot-collector/_snippets/retrieve-credentials.md
- docs/reference/edot-collector/_snippets/serverless-endpoint-api.md
- docs/reference/edot-collector/component-docs.yml
- docs/reference/edot-collector/components.md
- docs/reference/edot-collector/components/elasticapmintakereceiver.md
- docs/reference/edot-collector/components/elasticsearchexporter.md
- docs/reference/edot-collector/config/authentication-methods.md
- docs/reference/edot-collector/config/configure-logs-collection.md
- docs/reference/edot-collector/config/configure-metrics-collection.md
- docs/reference/edot-collector/config/configure-profiles-collection.md
- docs/reference/edot-collector/config/default-config-k8s.md
- docs/reference/edot-collector/config/default-config-standalone.md
- docs/reference/edot-collector/config/index.md
- docs/reference/edot-collector/config/proxy.md
- docs/reference/edot-collector/config/tail-based-sampling.md
- docs/reference/edot-collector/custom-collector.md
- docs/reference/edot-collector/customization.md
- docs/reference/edot-collector/download.md
- docs/reference/edot-collector/index.md
- docs/reference/edot-collector/modes.md
- docs/reference/edot-collector/toc.yml
- docs/reference/edot-collector/upstream-collector.md
Adds EDOT Collector docs files to `9.1`.
Prevents docs preview build errors as seen in https://github.com/elastic/elastic-agent/actions/runs/18225864630/job/51925318191. 
A preview docs build should be deployed in this PR.
Related to https://github.com/elastic/elastic-agent/pull/10308.
> [docs] Add EDOT Collector docs files

- changelog/fragments/1759334752-fix-error-logging-for-provider-failures.yaml
- internal/pkg/composable/controller.go
Avoid logging a nil error for provider exits.
Some providers intentionally stop and return a nil error; they already log the exit reason internally. The previous log formatted a nil error into "%!s()", which can be confusing (e.g. `provider "env" failed to run (will retry in 30s): %!s()`). This change removes the incorrect formatting and only includes the error text when non-nil.
None.
- Closes #9284
> Fix error logging for provider failures
