elastic/elastic-agent

testing/environments/snapshot.yml
[start_time:Tue, 1 Mar 2022 12:17:14 GMT, release_branch:master, prefix:, end_time:Tue, 1 Mar 2022 17:42:51 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-43df679f, build_duration_seconds:19537]
=> [automation] update elastic stack version for testing 8.2.0-43df679f

.ci/Jenkinsfile
Run build/test stages on Windows-2022 __ONLY__ for branches/tags, therefore, it won't run on a PR basis
- Do we want this kind of implementation? Or it does not require this kind of validation in the CI but using the e2e-testing instead (see https://github.com/elastic/e2e-testing/pull/2023) ?
Waiting for the support for windows-2022 in `fleet-ci`, infra is on it.
=> ci: enable windows-2022 support

testing/environments/snapshot.yml
[start_time:Wed, 2 Mar 2022 12:14:27 GMT, release_branch:master, prefix:, end_time:Wed, 2 Mar 2022 17:25:05 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-fdde08ec, build_duration_seconds:18638]
=> [automation] update elastic stack version for testing 8.2.0-fdde08ec

testing/environments/snapshot.yml
[start_time:Thu, 3 Mar 2022 00:17:14 GMT, release_branch:master, prefix:, end_time:Thu, 3 Mar 2022 05:11:32 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-190af159, build_duration_seconds:17658]
=> [automation] update elastic stack version for testing 8.2.0-190af159

testing/environments/snapshot.yml
[start_time:Fri, 4 Mar 2022 14:54:03 GMT, release_branch:master, prefix:, end_time:Fri, 4 Mar 2022 20:48:39 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-a12f7069, build_duration_seconds:21276]
=> [automation] update elastic stack version for testing 8.2.0-a12f7069

.github/workflows/elastic-agent-project-board.yml
Update Github action workflow to comply with ID values instead of String.
This mutation can be tested using: https://docs.github.com/en/graphql/overview/explorer
=> Update github action workflow for board management

testing/environments/snapshot.yml
[start_time:Thu, 10 Mar 2022 18:52:36 GMT, release_branch:master, prefix:, end_time:Thu, 10 Mar 2022 23:38:30 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-63265ec9, build_duration_seconds:17154]
=> [automation] update elastic stack version for testing 8.2.0-63265ec9

testing/environments/snapshot.yml
[start_time:Sun, 13 Mar 2022 12:16:37 GMT, release_branch:master, prefix:, end_time:Sun, 13 Mar 2022 17:22:42 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-d02c907a, build_duration_seconds:18365]
=> [automation] update elastic stack version for testing 8.2.0-d02c907a

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/flaky-test.md, .github/ISSUE_TEMPLATE/question.md
This uses the same template from the beats repository and adjusts the
wording for the Elastic Agent.
=> Add a base set of issues templates

testing/environments/snapshot.yml
[start_time:Mon, 14 Mar 2022 00:16:35 GMT, release_branch:master, prefix:, end_time:Mon, 14 Mar 2022 05:21:24 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-fee3b8d2, build_duration_seconds:18289]
=> [automation] update elastic stack version for testing 8.2.0-fee3b8d2

testing/environments/snapshot.yml
[start_time:Tue, 15 Mar 2022 12:16:35 GMT, release_branch:master, prefix:, end_time:Tue, 15 Mar 2022 16:54:57 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-9bac538c, build_duration_seconds:16702]
=> [automation] update elastic stack version for testing 8.2.0-9bac538c

dev-tools/packaging/packages.yml, dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
This PR enables unpacking of beats inside the container at build time, so that required `cap_net_raw, cap_setuid` capabilities can be assigned to the binary.
Without the required capabilities, heartbeat cannot execute ICMP pings or setuid calls. As it is now, agent is unpacking beats at runtime, most likely with a user that doesn't have permission to assign capabilities.
- Build elastic-agent containers, run:
`DEV=true SNAPSHOT=true PLATFORMS=linux/amd64 TYPES=docker mage package`
- Run one of the built containers and provide some heartbeat configuration:
```
docker run --name agent -it -u root --env FLEET_ENROLL=1 --env \
FLEET_URL=<url> --env \ 
FLEET_ENROLLMENT_TOKEN=<token> \ 
docker.elastic.co/beats/elastic-agent:8.2.0-SNAPSHOT
```
- Relates elastic/beats#27651
````bash
15:38:37.323 …
```
=> [Heartbeat] Unpack beats at build time on docker

CHANGELOG.next.asciidoc, internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
This code improve the error reporting when Elastic Agent is stopped
through the pass context. This move the state reporting closer to the
execution of the request. Error related to the request would still be
logged as error and will change the internal state to non healthy.
Fixes: #154
=> Move the `context cancelled` error message into a debug statement

testing/environments/snapshot.yml
[start_time:Wed, 16 Mar 2022 15:50:14 GMT, release_branch:master, prefix:, end_time:Wed, 16 Mar 2022 23:01:34 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-ff67d7b8, build_duration_seconds:25880]
=> [automation] update elastic stack version for testing 8.2.0-ff67d7b8

testing/environments/snapshot.yml
[start_time:Fri, 18 Mar 2022 00:16:30 GMT, release_branch:master, prefix:, end_time:Fri, 18 Mar 2022 04:22:19 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-82b803a1, build_duration_seconds:14749]
=> [automation] update elastic stack version for testing 8.2.0-82b803a1

testing/environments/snapshot.yml
[start_time:Mon, 21 Mar 2022 00:15:35 GMT, release_branch:master, prefix:, end_time:Mon, 21 Mar 2022 04:55:24 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-5cc993c1, build_duration_seconds:16789]
=> [automation] update elastic stack version for testing 8.2.0-5cc993c1

testing/environments/snapshot.yml
[start_time:Tue, 22 Mar 2022 00:14:32 GMT, release_branch:master, prefix:, end_time:Tue, 22 Mar 2022 04:41:52 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-63942b4d, build_duration_seconds:16040]
=> [automation] update elastic stack version for testing 8.2.0-63942b4d

testing/environments/snapshot.yml
[start_time:Wed, 23 Mar 2022 00:14:15 GMT, release_branch:master, prefix:, end_time:Wed, 23 Mar 2022 04:33:22 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-4509f321, build_duration_seconds:15547]
=> [automation] update elastic stack version for testing 8.2.0-4509f321

.github/workflows/golangci-lint.yml
By default `golangci-lint` will run the linters for the current running
platform and will only include the files for this platform. Using the `GOOS`
environment variable and a matrix defined in the github action we force
the linter to try all the supported operating system.
=> Force golangci-lint to run on every supported Os

CHANGELOG.next.asciidoc, internal/pkg/agent/cmd/inspect.go, internal/pkg/agent/cmd/inspect_test.go
Add the fleet-server input from the full filled config that is parsed
for programs in elastic-agent inspect output. This will show the policy
for fleet-server instead of the contents of fleet.yml
- Closes #103 
1. Create a policy that includes the fleet integration.
2. Enroll an agent using a the policy, and fleet flags.
3. Once the agent is healthy, run `elastic-agent inspect output -o default`
4. `fleet-server` should appear as a program in the output, i.e.:
```
[default] fleet-server:
data_stream:
namespace: default
id: fleet-server-fleet_server-da3b4b9e-24d1-47fc-9779-b0bc89ed113c
meta:
package:
name: fleet_server
version: 1.1.1
name: fleet_server-1
revision: 1
server:
host: 0.0.0.0
port: 8220
type: fleet-server
```
=> Add fleet-server to elastic-agent inspect output

testing/environments/snapshot.yml
[start_time:Thu, 24 Mar 2022 14:05:21 GMT, release_branch:master, prefix:, end_time:Thu, 24 Mar 2022 18:23:25 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-dcff22d7, build_duration_seconds:15484]
=> [automation] update elastic stack version for testing 8.2.0-dcff22d7

.github/workflows/macos.yml
Enable GitHub actions on MacOS for merge commits for the main and release branches.
Ensure the CI validates merges on branches.
=> github actions: enable for branches

CHANGELOG.next.asciidoc, internal/pkg/agent/cmd/container.go
Change the API paths used by the container command to reflect the updated paths.
Old paths are deprecated.
- [] ~~I have made corresponding changes to the documentation~~
- [] ~~I have made corresponding change to the default configuration files~~
- [] ~~I have added tests that prove my fix is effective or that my feature works~~
- Closes #111
=> Change kibana api paths used in container command

NOTICE.txt, go.mod, internal/pkg/agent/cmd/platformcheck.go, internal/pkg/agent/cmd/platformcheck_other.go, internal/pkg/agent/cmd/platformcheck_test.go, internal/pkg/agent/cmd/proc/job_unix.go, internal/pkg/agent/cmd/proc/job_windows.go, main.go
This PR copies two small packages from libbeat. I did not extract these because they are very small. As the Golang proverb says "a little copying is better than a little dependency".
Packages: 
* `github.com/elastic/beats/v7/libbeat/cmd/platformcheck`
* `github.com/elastic/beats/v7/x-pack/libbeat/common/proc`
This PR decreases the dependency on the beats repository.
~~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~
=> Move `platformcheck` and `common/proc` from libbeat

CHANGELOG.next.asciidoc, internal/pkg/agent/cmd/diagnostics.go, internal/pkg/agent/cmd/diagnostics_test.go
Three separate small fixes for the `elastic-agent diagnostic` command (including `collect`):
1. `diagnostics collect` will ignore failures where possible and log to stderr and to an `errors.txt` file in the archive.
2. Fixed log names when `diagnostics collect` is ran on a Windows machine
3. Add the elastic-agent ID to the output of `elastic-agent diagnostics` and into the archive in the `meta/elastic-agent.yaml` and `config/elastic-agent-local.yaml` files
- [] ~~I have made corresponding changes to the documentation~~
- [] ~~I have made corresponding change to the default configuration files~~
Run the agent on a Windows machine and run `elastic-agent diagnostics collect`.
Extract the archive (on a *nix machine) and ensure that the logs are named correctly, i.e.:
```
$ unzip …
```
=> Simple fixes for the diagnostics command

internal/pkg/agent/application/upgrade/step_download.go, internal/pkg/agent/operation/common_test.go, internal/pkg/agent/operation/operation_verify.go, internal/pkg/artifact/download/composed/verifier.go, internal/pkg/artifact/download/composed/verifier_test.go, internal/pkg/artifact/download/fs/verifier.go, internal/pkg/artifact/download/fs/verifier_test.go, internal/pkg/artifact/download/http/elastic_test.go, internal/pkg/artifact/download/http/verifier.go, internal/pkg/artifact/download/verifier.go
Modify verifier to only delete the binary and .sha512 files when there is a
checksum mismatch. And only delete the .asc file when the signature does not
validate.
Fixes https://github.com/elastic/elastic-agent/issues/252
Downloaded artifacts fail signature validation in SNAPSHOT builds. You cannot test Packetbeat or Auditbeat with 8.2.0-SNAPSHOT builds.
<!-- Recommended
Link related issues below. Insert the issue link or reference after the word "Closes" if merging this should automatically close it.
- Fixes https://github.com/elastic/elastic-agent/issues/252
=> Fix download verification in snapshot builds

.ci/Jenkinsfile
Adding condition for e2e tests to not run if there are only doc changes
e2e tests have failed after PR merge because of missing artifacts for docs only, the changes in Jenkins checks if files modified are limited to docs and does not run the tests.
=> no e2e if only docs

Makefile, magefile.go
removes `-d` flag as it only gets the package, does not install
remove `-d` flag as it only gets the package, does not install
related to issue https://github.com/elastic/elastic-agent/issues/264 and wrongly added in https://github.com/elastic/elastic-agent/pull/265 to remove the deprecation message
=> remove `-d` flag ad it only gets the package, does not install

testing/environments/snapshot.yml
[start_time:Fri, 1 Apr 2022 00:14:24 GMT, release_branch:8.2, prefix:, end_time:Fri, 1 Apr 2022 04:48:29 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-5d1042d1, build_duration_seconds:16445]
=> [automation] update elastic stack version for testing 8.2.0-5d1042d1

testing/environments/snapshot.yml
[start_time:Thu, 31 Mar 2022 12:15:08 GMT, release_branch:master, prefix:, end_time:Fri, 1 Apr 2022 02:36:15 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-1ecd9720, build_duration_seconds:51667]
=> [automation] update elastic stack version for testing 8.3.0-1ecd9720

testing/environments/snapshot.yml
[start_time:Mon, 4 Apr 2022 00:16:03 GMT, release_branch:8.2, prefix:, end_time:Mon, 4 Apr 2022 04:36:18 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-f531236e, build_duration_seconds:15615]
=> [automation] update elastic stack version for testing 8.2.0-f531236e

testing/environments/snapshot.yml
[start_time:Fri, 1 Apr 2022 12:14:43 GMT, release_branch:master, prefix:, end_time:Fri, 1 Apr 2022 16:30:17 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-4cd86339, build_duration_seconds:15334]
=> [automation] update elastic stack version for testing 8.3.0-4cd86339

testing/environments/snapshot.yml
[start_time:Tue, 5 Apr 2022 00:14:16 GMT, release_branch:8.2, prefix:, end_time:Tue, 5 Apr 2022 04:39:11 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-12b59372, build_duration_seconds:15895]
=> [automation] update elastic stack version for testing 8.2.0-12b59372

testing/environments/snapshot.yml
[start_time:Mon, 4 Apr 2022 15:09:13 GMT, release_branch:master, prefix:, end_time:Mon, 4 Apr 2022 21:39:53 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-657f2d50, build_duration_seconds:23440]
=> [automation] update elastic stack version for testing 8.3.0-657f2d50

testing/environments/snapshot.yml
[start_time:Tue, 5 Apr 2022 22:51:10 GMT, release_branch:master, prefix:, end_time:Wed, 6 Apr 2022 02:52:40 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-00f4f855, build_duration_seconds:14490]
=> [automation] update elastic stack version for testing 8.3.0-00f4f855

testing/environments/snapshot.yml
[start_time:Wed, 6 Apr 2022 00:18:20 GMT, release_branch:8.2, prefix:, end_time:Wed, 6 Apr 2022 04:10:23 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-fdfc79e3, build_duration_seconds:13923]
=> [automation] update elastic stack version for testing 8.2.0-fdfc79e3

testing/environments/snapshot.yml
[start_time:Thu, 7 Apr 2022 00:14:34 GMT, release_branch:master, prefix:, end_time:Thu, 7 Apr 2022 04:42:19 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-5bb6f468, build_duration_seconds:16065]
=> [automation] update elastic stack version for testing 8.3.0-5bb6f468

testing/environments/snapshot.yml
[start_time:Thu, 7 Apr 2022 00:14:27 GMT, release_branch:8.2, prefix:, end_time:Thu, 7 Apr 2022 04:19:11 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-c56d8262, build_duration_seconds:14684]
=> [automation] update elastic stack version for testing 8.2.0-c56d8262

testing/environments/snapshot.yml
[start_time:Thu, 7 Apr 2022 12:18:03 GMT, release_branch:8.2, prefix:, end_time:Thu, 7 Apr 2022 16:58:01 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-4df380a5, build_duration_seconds:16798]
=> [automation] update elastic stack version for testing 8.2.0-4df380a5

testing/environments/snapshot.yml
[start_time:Thu, 7 Apr 2022 12:14:18 GMT, release_branch:master, prefix:, end_time:Thu, 7 Apr 2022 16:41:59 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-76e0128f, build_duration_seconds:16061]
=> [automation] update elastic stack version for testing 8.3.0-76e0128f

testing/environments/snapshot.yml
[start_time:Mon, 11 Apr 2022 00:14:24 GMT, release_branch:8.2, prefix:, end_time:Mon, 11 Apr 2022 04:46:29 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-bcbc1a13, build_duration_seconds:16325]
=> [automation] update elastic stack version for testing 8.2.0-bcbc1a13

testing/environments/snapshot.yml
[start_time:Mon, 11 Apr 2022 00:14:22 GMT, release_branch:master, prefix:, end_time:Mon, 11 Apr 2022 04:44:10 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-8d19ff01, build_duration_seconds:16188]
=> [automation] update elastic stack version for testing 8.3.0-8d19ff01

testing/environments/snapshot.yml
[start_time:Mon, 11 Apr 2022 12:19:48 GMT, release_branch:master, prefix:, end_time:Mon, 11 Apr 2022 17:10:40 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-2c8f9574, build_duration_seconds:17452]
=> [automation] update elastic stack version for testing 8.3.0-2c8f9574

testing/environments/snapshot.yml
[start_time:Tue, 12 Apr 2022 13:46:39 GMT, release_branch:8.2, prefix:, end_time:Tue, 12 Apr 2022 18:03:38 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-a99722cc, build_duration_seconds:15419]
=> [automation] update elastic stack version for testing 8.2.0-a99722cc

testing/environments/snapshot.yml
[start_time:Thu, 14 Apr 2022 00:15:10 GMT, release_branch:8.2, prefix:, end_time:Thu, 14 Apr 2022 04:33:43 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-39d3fe7f, build_duration_seconds:15513]
=> [automation] update elastic stack version for testing 8.2.0-39d3fe7f

testing/environments/snapshot.yml
[start_time:Thu, 14 Apr 2022 00:14:21 GMT, release_branch:master, prefix:, end_time:Thu, 14 Apr 2022 04:44:55 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-4be61f32, build_duration_seconds:16234]
=> [automation] update elastic stack version for testing 8.3.0-4be61f32

.golangci.yml, CHANGELOG.next.asciidoc, NOTICE.txt, go.mod, internal/pkg/agent/application/upgrade/step_download.go, internal/pkg/artifact/config.go, internal/pkg/artifact/download/http/downloader.go, internal/pkg/artifact/download/http/downloader_test.go, internal/pkg/artifact/download/http/elastic_test.go, internal/pkg/artifact/download/localremote/downloader.go, internal/pkg/artifact/download/snapshot/downloader.go
Adds reporting of download progress every 5% interval of the total timeout for an artifact download over HTTP. Sets default timeout of downloading artifacts to 10 minutes.
There is no observability on the speed/time for downloading of artifacts, mainly an upgrade version for the Elastic Agent. In many cases on a slow network the download can timeout, with no information on why. This PR increases this timeout and provides downloading statistics so its clear how fast it is downloading and how long it is taking.
Easiest way to test is to compile the package with `SNAPSHOT="true" mage dev:package` then extract the *.tar.gz or *.zip depending on the …
=> Add download progress reporter to HTTP downloader.

testing/environments/snapshot.yml
[start_time:Fri, 15 Apr 2022 00:14:33 GMT, release_branch:master, prefix:, end_time:Fri, 15 Apr 2022 04:50:37 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-55ba6f37, build_duration_seconds:16564]
=> [automation] update elastic stack version for testing 8.3.0-55ba6f37

testing/environments/snapshot.yml
[start_time:Fri, 15 Apr 2022 00:14:25 GMT, release_branch:8.2, prefix:, end_time:Fri, 15 Apr 2022 04:41:47 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-edf55ea1, build_duration_seconds:16042]
=> [automation] update elastic stack version for testing 8.2.0-edf55ea1

testing/environments/snapshot.yml
[start_time:Sun, 17 Apr 2022 00:14:24 GMT, release_branch:8.2, prefix:, end_time:Sun, 17 Apr 2022 03:54:27 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-c65cb8e3, build_duration_seconds:13203]
=> [automation] update elastic stack version for testing 8.2.0-c65cb8e3

testing/environments/snapshot.yml
[start_time:Tue, 19 Apr 2022 00:14:07 GMT, release_branch:8.2, prefix:, end_time:Tue, 19 Apr 2022 04:50:58 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-3a7e2f99, build_duration_seconds:16611]
=> [automation] update elastic stack version for testing 8.2.0-3a7e2f99

testing/environments/snapshot.yml
[start_time:Tue, 19 Apr 2022 00:16:33 GMT, release_branch:master, prefix:, end_time:Tue, 19 Apr 2022 04:47:37 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-b671393e, build_duration_seconds:16264]
=> [automation] update elastic stack version for testing 8.3.0-b671393e

dev-tools/mage/crossbuild.go
Update the crossbuild list of build platform to match the docker images,
we are using the Debian10 images for mips, ppc and s390x to fix
issues with upstream dependencies.
depends on elastic/golang-crossbuild#175
-
=> Fix: uses Debian 10 for mips, ppc and s390x

testing/environments/snapshot.yml
[start_time:Wed, 20 Apr 2022 00:15:12 GMT, release_branch:8.2, prefix:, end_time:Wed, 20 Apr 2022 04:28:47 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-a7e9513d, build_duration_seconds:15215]
=> [automation] update elastic stack version for testing 8.2.0-a7e9513d

internal/pkg/core/process/process.go
The package `github.com/elastic/elastic-agent/internal/pkg/agent/cmd/proc` was moved to the Agent repo in https://github.com/elastic/elastic-agent/pull/258. In this PR I switch to the new local package, instead of using the one in libbeat.
One more step away from libbeat.
~~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~
=> Use local `github.com/elastic/elastic-agent/internal/pkg/agent/cmd/proc` package instead of the one from libbeat

testing/environments/snapshot.yml
[start_time:Wed, 20 Apr 2022 20:16:48 GMT, release_branch:master, prefix:, end_time:Thu, 21 Apr 2022 00:24:04 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-55bd5fae, build_duration_seconds:14836]
=> [automation] update elastic stack version for testing 8.3.0-55bd5fae

testing/environments/snapshot.yml
[start_time:Wed, 20 Apr 2022 12:14:52 GMT, release_branch:8.2, prefix:, end_time:Wed, 20 Apr 2022 17:25:38 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-000e1c18, build_duration_seconds:18646]
=> [automation] update elastic stack version for testing 8.2.0-000e1c18

testing/environments/snapshot.yml
[start_time:Fri, 22 Apr 2022 00:17:53 GMT, release_branch:8.2, prefix:, end_time:Fri, 22 Apr 2022 04:06:59 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-c47183cf, build_duration_seconds:13746]
=> [automation] update elastic stack version for testing 8.2.0-c47183cf

testing/environments/snapshot.yml
[start_time:Fri, 22 Apr 2022 00:17:44 GMT, release_branch:master, prefix:, end_time:Fri, 22 Apr 2022 04:37:45 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-04455a76, build_duration_seconds:15601]
=> [automation] update elastic stack version for testing 8.3.0-04455a76

testing/environments/snapshot.yml
[start_time:Mon, 25 Apr 2022 00:16:18 GMT, release_branch:master, prefix:, end_time:Mon, 25 Apr 2022 04:34:53 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-99e29e67, build_duration_seconds:15515]
=> [automation] update elastic stack version for testing 8.3.0-99e29e67

testing/environments/snapshot.yml
[start_time:Mon, 25 Apr 2022 00:16:18 GMT, release_branch:8.2, prefix:, end_time:Mon, 25 Apr 2022 04:48:40 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-14a8abdc, build_duration_seconds:16342]
=> [automation] update elastic stack version for testing 8.2.0-14a8abdc

testing/environments/snapshot.yml
[start_time:Tue, 26 Apr 2022 00:25:14 GMT, release_branch:master, prefix:, end_time:Tue, 26 Apr 2022 04:35:41 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-ed7759bd, build_duration_seconds:15027]
=> [automation] update elastic stack version for testing 8.3.0-ed7759bd

testing/environments/snapshot.yml
[start_time:Tue, 26 Apr 2022 00:14:18 GMT, release_branch:8.2, prefix:, end_time:Tue, 26 Apr 2022 04:06:52 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-63f66f47, build_duration_seconds:13954]
=> [automation] update elastic stack version for testing 8.2.0-63f66f47

dev-tools/packaging/templates/docker/docker-entrypoint.elastic-agent.tmpl
These are `elastic-agent`  changes related to elastic/beats#30869.
We need to change the default `umask 022` to `007` in order to retain group write permissions when `setuid` is executed.
Refer to elastic/beats#30869 instructions on how to test locally.
- Relates to elastic/beats#30171.
=> [Heartbeat] Fix umask on docker entrypoint

testing/environments/snapshot.yml
[start_time:Tue, 26 Apr 2022 12:13:43 GMT, release_branch:master, prefix:, end_time:Tue, 26 Apr 2022 16:20:43 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-6b041601, build_duration_seconds:14820]
=> [automation] update elastic stack version for testing 8.3.0-6b041601

testing/environments/snapshot.yml
[start_time:Tue, 26 Apr 2022 12:14:51 GMT, release_branch:8.2, prefix:, end_time:Tue, 26 Apr 2022 16:38:24 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-bdd1c93d, build_duration_seconds:15813]
=> [automation] update elastic stack version for testing 8.2.0-bdd1c93d

testing/environments/snapshot.yml
[start_time:Thu, 28 Apr 2022 00:14:10 GMT, release_branch:master, prefix:, end_time:Thu, 28 Apr 2022 04:07:24 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-cb2ce38c, build_duration_seconds:13994]
=> [automation] update elastic stack version for testing 8.3.0-cb2ce38c

testing/environments/snapshot.yml
[start_time:Thu, 28 Apr 2022 00:14:27 GMT, release_branch:8.2, prefix:, end_time:Thu, 28 Apr 2022 04:56:07 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-8b4cfac3, build_duration_seconds:16900]
=> [automation] update elastic stack version for testing 8.2.0-8b4cfac3

testing/environments/snapshot.yml
[start_time:Thu, 28 Apr 2022 12:14:16 GMT, release_branch:8.2, prefix:, end_time:Thu, 28 Apr 2022 16:53:35 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-2c25c9de, build_duration_seconds:16759]
=> [automation] update elastic stack version for testing 8.2.0-2c25c9de

testing/environments/snapshot.yml
[start_time:Mon, 2 May 2022 00:16:36 GMT, release_branch:8.2, prefix:, end_time:Mon, 2 May 2022 04:26:56 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-e7ad9ef0, build_duration_seconds:15020]
=> [automation] update elastic stack version for testing 8.2.0-e7ad9ef0

testing/environments/snapshot.yml
[start_time:Tue, 3 May 2022 00:14:07 GMT, release_branch:8.2, prefix:, end_time:Tue, 3 May 2022 04:22:51 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-56396fd0, build_duration_seconds:14924]
=> [automation] update elastic stack version for testing 8.2.0-56396fd0

testing/environments/snapshot.yml
[start_time:Mon, 2 May 2022 21:05:06 GMT, release_branch:master, prefix:, end_time:Tue, 3 May 2022 01:18:58 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-0b6ea9f2, build_duration_seconds:15232]
=> [automation] update elastic stack version for testing 8.3.0-0b6ea9f2

testing/environments/snapshot.yml
[start_time:Wed, 4 May 2022 00:14:21 GMT, release_branch:master, prefix:, end_time:Wed, 4 May 2022 04:11:39 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-7f585873, build_duration_seconds:14238]
=> [automation] update elastic stack version for testing 8.3.0-7f585873

testing/environments/snapshot.yml
[start_time:Thu, 5 May 2022 00:15:22 GMT, release_branch:master, prefix:, end_time:Thu, 5 May 2022 04:24:20 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-a1c5cfff, build_duration_seconds:14938]
=> [automation] update elastic stack version for testing 8.3.0-a1c5cfff

testing/environments/snapshot.yml
[start_time:Fri, 6 May 2022 00:14:54 GMT, release_branch:master, prefix:, end_time:Fri, 6 May 2022 04:20:36 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-6ba9f710, build_duration_seconds:14742]
=> [automation] update elastic stack version for testing 8.3.0-6ba9f710

testing/environments/snapshot.yml
[start_time:Mon, 9 May 2022 00:15:37 GMT, release_branch:master, prefix:, end_time:Mon, 9 May 2022 04:31:25 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-5c1ff35f, build_duration_seconds:15348]
=> [automation] update elastic stack version for testing 8.3.0-5c1ff35f

testing/environments/snapshot.yml
[start_time:Tue, 10 May 2022 00:14:18 GMT, release_branch:master, prefix:, end_time:Tue, 10 May 2022 04:17:54 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-d380914f, build_duration_seconds:14616]
=> [automation] update elastic stack version for testing 8.3.0-d380914f

testing/environments/snapshot.yml
[start_time:Tue, 10 May 2022 12:14:28 GMT, release_branch:master, prefix:, end_time:Tue, 10 May 2022 19:41:55 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-53513548, build_duration_seconds:26847]
=> [automation] update elastic stack version for testing 8.3.0-53513548

testing/environments/snapshot.yml
[start_time:Tue, 10 May 2022 12:14:03 GMT, release_branch:8.2, prefix:, end_time:Tue, 10 May 2022 17:09:44 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-2eb01953, build_duration_seconds:17741]
=> [automation] update elastic stack version for testing 8.2.1-2eb01953

testing/environments/snapshot.yml
[start_time:Thu, 12 May 2022 00:16:52 GMT, release_branch:master, prefix:, end_time:Thu, 12 May 2022 04:33:47 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-8ee1196f, build_duration_seconds:15415]
=> [automation] update elastic stack version for testing 8.3.0-8ee1196f

testing/environments/snapshot.yml
[start_time:Wed, 11 May 2022 12:17:18 GMT, release_branch:8.2, prefix:, end_time:Wed, 11 May 2022 16:33:31 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-91d7a53f, build_duration_seconds:15373]
=> [automation] update elastic stack version for testing 8.2.1-91d7a53f

testing/environments/snapshot.yml
[start_time:Mon, 16 May 2022 00:17:33 GMT, release_branch:master, prefix:, end_time:Mon, 16 May 2022 04:25:53 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-19aba912, build_duration_seconds:14900]
=> [automation] update elastic stack version for testing 8.3.0-19aba912

testing/environments/snapshot.yml
[start_time:Mon, 16 May 2022 00:17:45 GMT, release_branch:8.2, prefix:, end_time:Mon, 16 May 2022 04:48:36 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-3d12787c, build_duration_seconds:16251]
=> [automation] update elastic stack version for testing 8.2.1-3d12787c

testing/environments/snapshot.yml
[start_time:Mon, 16 May 2022 12:14:04 GMT, release_branch:master, prefix:, end_time:Mon, 16 May 2022 16:39:55 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-4149272f, build_duration_seconds:15951]
=> [automation] update elastic stack version for testing 8.3.0-4149272f

testing/environments/snapshot.yml
[start_time:Tue, 17 May 2022 00:14:25 GMT, release_branch:8.2, prefix:, end_time:Tue, 17 May 2022 04:25:16 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-736d131e, build_duration_seconds:15051]
=> [automation] update elastic stack version for testing 8.2.1-736d131e

testing/environments/snapshot.yml
[start_time:Tue, 17 May 2022 12:16:05 GMT, release_branch:8.2, prefix:, end_time:Tue, 17 May 2022 19:10:52 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-8d9ffca9, build_duration_seconds:24887]
=> [automation] update elastic stack version for testing 8.2.1-8d9ffca9

testing/environments/snapshot.yml
[start_time:Thu, 19 May 2022 00:14:06 GMT, release_branch:master, prefix:, end_time:Thu, 19 May 2022 04:19:11 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-a55286cc, build_duration_seconds:14705]
=> [automation] update elastic stack version for testing 8.3.0-a55286cc

testing/environments/snapshot.yml
[start_time:Wed, 18 May 2022 00:14:22 GMT, release_branch:8.2, prefix:, end_time:Wed, 18 May 2022 09:50:13 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-93582d09, build_duration_seconds:34551]
=> [automation] update elastic stack version for testing 8.2.1-93582d09

internal/pkg/agent/cmd/container.go, pkg/core/logger/logger.go
Additional changes required to close [https://github.com/elastic/beats/issues/30171](https://github.com/elastic/beats/pull/30869).
When started inside the container, elastic-agent will initialize the shared logs directory at `state/data/logs` with the [default directory mask](https://github.com/elastic/elastic-agent-libs/blob/cb28916182b8128fa73088caa965f77ced3f163b/file/rotator.go#L370). Since HB is running `setuid()`, it needs group access to be able to create log files inside `state/data/logs/default`.
- Build beats and elastic-agent locally:
````
x-pack/elastic-agent $  env PLATFORMS="+all linux/amd64" mage dev:package
...
````
- Run the container locally as `root`:
```bash
docker run -u root --rm --name agent --env FLEET_ENROLL=1 --env FLEET_URL=<fleet url> --env …
```
=> Initialize logger directory to allow group access

testing/environments/snapshot.yml
[start_time:Thu, 19 May 2022 12:14:07 GMT, release_branch:8.2, prefix:, end_time:Thu, 19 May 2022 16:42:43 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-54274789, build_duration_seconds:16116]
=> [automation] update elastic stack version for testing 8.2.1-54274789

dev-tools/mage/build.go
Fix hot the `gcflags` to disable inlining and optimizations are passed to mage.sh and after the go tool chain.
Currently even compiling in dev mode (`DEV=true`) inlining and optimizations are enabled, therefore adding breakpoints when debugging ins't possible in several places where it should.
- compile with `DEV=true`
- `DEV=true SNAPSHOT=true EXTERNAL=true PLATFORMS="linux/amd64" …
=> Fix disable optimizations and inlining for debug

testing/environments/snapshot.yml
[start_time:Fri, 20 May 2022 00:14:18 GMT, release_branch:master, prefix:, end_time:Fri, 20 May 2022 05:06:28 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-3a5a0cd2, build_duration_seconds:17530]
=> [automation] update elastic stack version for testing 8.3.0-3a5a0cd2

testing/environments/snapshot.yml
[start_time:Fri, 20 May 2022 00:14:54 GMT, release_branch:8.2, prefix:, end_time:Fri, 20 May 2022 05:17:46 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-539cf6f5, build_duration_seconds:18172]
=> [automation] update elastic stack version for testing 8.2.1-539cf6f5

testing/environments/snapshot.yml
[start_time:Mon, 23 May 2022 21:11:48 GMT, release_branch:master, prefix:, end_time:Tue, 24 May 2022 01:53:25 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-bf0ad929, build_duration_seconds:16897]
=> [automation] update elastic stack version for testing 8.3.0-bf0ad929

testing/environments/snapshot.yml
[start_time:Mon, 23 May 2022 20:52:44 GMT, release_branch:8.2, prefix:, end_time:Tue, 24 May 2022 01:04:12 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-e97da867, build_duration_seconds:15088]
=> [automation] update elastic stack version for testing 8.2.1-e97da867

testing/environments/snapshot.yml
[start_time:Tue, 24 May 2022 02:05:24 GMT, release_branch:master, prefix:, end_time:Tue, 24 May 2022 06:33:23 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-a2430aec, build_duration_seconds:16079]
=> [automation] update elastic stack version for testing 8.3.0-a2430aec

testing/environments/snapshot.yml
[start_time:Tue, 24 May 2022 02:15:00 GMT, release_branch:8.2, prefix:, end_time:Tue, 24 May 2022 06:37:00 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-f86dca4c, build_duration_seconds:15720]
=> [automation] update elastic stack version for testing 8.2.1-f86dca4c

testing/environments/snapshot.yml
[start_time:Wed, 1 Jun 2022 00:14:28 GMT, release_branch:8.3, prefix:, end_time:Wed, 1 Jun 2022 04:43:36 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-4644f7c7, build_duration_seconds:16148]
=> [automation] update elastic stack version for testing 8.3.0-4644f7c7

testing/environments/snapshot.yml
[start_time:Tue, 31 May 2022 14:03:59 GMT, release_branch:master, prefix:, end_time:Tue, 31 May 2022 21:51:22 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-481759a3, build_duration_seconds:28043]
=> [automation] update elastic stack version for testing 8.4.0-481759a3

testing/environments/snapshot.yml
[start_time:Thu, 2 Jun 2022 00:14:17 GMT, release_branch:master, prefix:, end_time:Thu, 2 Jun 2022 04:55:25 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-df27a645, build_duration_seconds:16868]
=> [automation] update elastic stack version for testing 8.4.0-df27a645

internal/pkg/agent/application/secret/secret.go, internal/pkg/agent/storage/encrypted_disk_store.go, internal/pkg/agent/storage/storage.go, internal/pkg/agent/vault/aesgcm.go, internal/pkg/agent/vault/vault_darwin.go, internal/pkg/testutils/testutils.go
=> Fix linter issues with doc strings

testing/environments/snapshot.yml
[start_time:Fri, 3 Jun 2022 00:14:13 GMT, release_branch:8.3, prefix:, end_time:Fri, 3 Jun 2022 04:06:58 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-378ebcca, build_duration_seconds:13965]
=> [automation] update elastic stack version for testing 8.3.0-378ebcca

testing/environments/snapshot.yml
[start_time:Thu, 2 Jun 2022 12:14:55 GMT, release_branch:master, prefix:, end_time:Thu, 2 Jun 2022 16:37:25 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-3525aaf7, build_duration_seconds:15750]
=> [automation] update elastic stack version for testing 8.4.0-3525aaf7

internal/pkg/agent/cmd/common.go, internal/pkg/agent/cmd/component.go, internal/pkg/agent/cmd/component_spec.go
Adds `elastic-agent component spec <file>` command that validates the provided file is a validate v2 component specification file. 
Idea here is that other commands for components can be placed under `component`. I am thinking that `view` can be added that prints all the components for the current Elastic Agent and each of their inputs that it can run. A `trust` command that can generate the trust unsigned.
Allows component developers to easily validate that their written component specification is valid.
- ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` …
=> [v2] Add component spec command to validate component specifications

testing/environments/snapshot.yml
[start_time:Sun, 5 Jun 2022 12:14:04 GMT, release_branch:master, prefix:, end_time:Sun, 5 Jun 2022 16:34:07 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-42ce0eef, build_duration_seconds:15603]
=> [automation] update elastic stack version for testing 8.4.0-42ce0eef

testing/environments/snapshot.yml
[start_time:Mon, 6 Jun 2022 13:14:20 GMT, release_branch:8.3, prefix:, end_time:Mon, 6 Jun 2022 17:41:54 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-f530a93f, build_duration_seconds:16054]
=> [automation] update elastic stack version for testing 8.3.0-f530a93f

testing/environments/snapshot.yml
[start_time:Tue, 7 Jun 2022 00:16:17 GMT, release_branch:master, prefix:, end_time:Tue, 7 Jun 2022 04:21:27 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-b8fce3f8, build_duration_seconds:14710]
=> [automation] update elastic stack version for testing 8.4.0-b8fce3f8

testing/environments/snapshot.yml
[start_time:Thu, 9 Jun 2022 00:14:24 GMT, release_branch:8.3, prefix:, end_time:Thu, 9 Jun 2022 04:38:16 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-3c22a7f7, build_duration_seconds:15832]
=> [automation] update elastic stack version for testing 8.3.0-3c22a7f7

testing/environments/snapshot.yml
[start_time:Fri, 10 Jun 2022 00:15:24 GMT, release_branch:master, prefix:, end_time:Fri, 10 Jun 2022 04:45:28 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-a27cbcfa, build_duration_seconds:16204]
=> [automation] update elastic stack version for testing 8.4.0-a27cbcfa

testing/environments/snapshot.yml
[start_time:Mon, 13 Jun 2022 00:14:44 GMT, release_branch:8.3, prefix:, end_time:Mon, 13 Jun 2022 04:40:53 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-db012561, build_duration_seconds:15969]
=> [automation] update elastic stack version for testing 8.3.0-db012561

testing/environments/snapshot.yml
[start_time:Mon, 13 Jun 2022 00:14:14 GMT, release_branch:master, prefix:, end_time:Mon, 13 Jun 2022 04:20:05 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-3bedeef4, build_duration_seconds:14751]
=> [automation] update elastic stack version for testing 8.4.0-3bedeef4

NOTICE.txt, go.mod, internal/pkg/agent/application/secret/secret.go, internal/pkg/agent/storage/encrypted_disk_storage_windows_linux_test.go, internal/pkg/agent/vault/seed.go, internal/pkg/agent/vault/seed_test.go, internal/pkg/agent/vault/vault_darwin.go, internal/pkg/agent/vault/vault_key.go, internal/pkg/agent/vault/vault_linux.go, internal/pkg/agent/vault/vault_test.go, internal/pkg/agent/vault/vault_windows.go, internal/pkg/core/plugin/process/stdlogger.go, internal/pkg/core/plugin/process/stdlogger_test.go, pkg/core/logger/testing.go
* Made the vault seed creation thread-safe
* Made the agent secret creation thread-safe
* Updated the calculation for the key file name, before it was hash(key), now it's a hash(seed+key).
Improves the implementation of the vault and the agent secret.
Should address the intermittent issue that popped up during E2E tests. 
https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/e2e-tests/pipelines/e2e-testing-mbp/pipelines/PR-2621/runs/1/nodes/701/steps/5681/log/?start=0
I could not reproduce the issue, but the looking at the implementation found couple of places where race condition was possible.
=> Config encryption: Fix the vault possible race conditions, harden the code for concurrent access

NOTICE.txt, go.mod, internal/pkg/agent/application/secret/secret.go, internal/pkg/agent/storage/encrypted_disk_storage_windows_linux_test.go, internal/pkg/agent/vault/seed.go, internal/pkg/agent/vault/seed_test.go, internal/pkg/agent/vault/vault_darwin.go, internal/pkg/agent/vault/vault_key.go, internal/pkg/agent/vault/vault_linux.go, internal/pkg/agent/vault/vault_test.go, internal/pkg/agent/vault/vault_windows.go, internal/pkg/core/plugin/process/stdlogger.go, internal/pkg/core/plugin/process/stdlogger_test.go, pkg/core/logger/testing.go
This is a backport of https://github.com/elastic/elastic-agent/pull/529 to 8.3 branch
* Made the vault seed creation goroutine-safe
* Made the agent secret creation goroutine-safe
* Make vault implementation goroutine-safe
* Updated the calculation for the key file name, before it was hash(key), now it's a hash(seed+key).
Improves the implementation of the vault and the agent secret.
Should address the intermittent issue that popped up during E2E tests. 
https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/e2e-tests/pipelines/e2e-testing-mbp/pipelines/PR-2621/runs/1/nodes/701/steps/5681/log/?start=0
I could not reproduce the issue, but the looking at the implementation found couple of places where race condition was possible.
=> [backport 8.3] Config encryption: Fix the vault possible race conditions, harden the code for concurrent access (#529)

testing/environments/snapshot.yml
[start_time:Tue, 14 Jun 2022 00:18:07 GMT, release_branch:8.3, prefix:, end_time:Tue, 14 Jun 2022 04:30:39 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-e4e76686, build_duration_seconds:15152]
=> [automation] update elastic stack version for testing 8.3.0-e4e76686

testing/environments/snapshot.yml
[start_time:Tue, 14 Jun 2022 00:14:26 GMT, release_branch:master, prefix:, end_time:Tue, 14 Jun 2022 04:50:43 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-7e67f5d9, build_duration_seconds:16577]
=> [automation] update elastic stack version for testing 8.4.0-7e67f5d9

testing/environments/snapshot.yml
[start_time:Wed, 15 Jun 2022 00:13:58 GMT, release_branch:master, prefix:, end_time:Wed, 15 Jun 2022 04:40:55 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-40cff009, build_duration_seconds:16017]
=> [automation] update elastic stack version for testing 8.4.0-40cff009

testing/environments/snapshot.yml
[start_time:Wed, 15 Jun 2022 00:18:08 GMT, release_branch:8.3, prefix:, end_time:Wed, 15 Jun 2022 04:39:23 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-460dc667, build_duration_seconds:15675]
=> [automation] update elastic stack version for testing 8.3.0-460dc667

testing/environments/snapshot.yml
[start_time:Wed, 15 Jun 2022 12:14:33 GMT, release_branch:8.3, prefix:, end_time:Wed, 15 Jun 2022 16:52:58 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-fe62331f, build_duration_seconds:16705]
=> [automation] update elastic stack version for testing 8.3.0-fe62331f

testing/environments/snapshot.yml
[start_time:Thu, 16 Jun 2022 00:14:47 GMT, release_branch:master, prefix:, end_time:Thu, 16 Jun 2022 04:24:56 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-5e6770b1, build_duration_seconds:15009]
=> [automation] update elastic stack version for testing 8.4.0-5e6770b1

testing/environments/snapshot.yml
[start_time:Thu, 16 Jun 2022 05:14:05 GMT, release_branch:8.2, prefix:, end_time:Thu, 16 Jun 2022 09:18:56 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-4cc4fbfd, build_duration_seconds:14691]
=> [automation] update elastic stack version for testing 8.2.4-4cc4fbfd

testing/environments/snapshot.yml
[start_time:Fri, 17 Jun 2022 00:14:23 GMT, release_branch:master, prefix:, end_time:Fri, 17 Jun 2022 04:19:18 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-da5a1c6d, build_duration_seconds:14695]
=> [automation] update elastic stack version for testing 8.4.0-da5a1c6d

testing/environments/snapshot.yml
[start_time:Thu, 16 Jun 2022 17:19:33 GMT, release_branch:8.2, prefix:, end_time:Thu, 16 Jun 2022 21:15:53 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-01ccaf06, build_duration_seconds:14180]
=> [automation] update elastic stack version for testing 8.2.4-01ccaf06

CHANGELOG.next.asciidoc, internal/pkg/agent/program/testdata/audit_config-auditbeat.yml, internal/pkg/agent/program/testdata/logstash_config-metricbeat.yml, internal/pkg/agent/program/testdata/namespace-metricbeat.yml, internal/pkg/agent/program/testdata/single_config-metricbeat.yml, internal/pkg/agent/program/testdata/usecases/generated/namespace.metricbeat.golden.yml, internal/pkg/agent/program/testdata/usecases/generated/single_config.filebeat.golden.yml, internal/pkg/agent/program/testdata/usecases/generated/single_config.metricbeat.golden.yml, internal/pkg/agent/transpiler/rules.go, internal/pkg/agent/transpiler/rules_test.go
This PR adds 2 additional values added to each event via the inject stream processor.
These 2 value are going to be used in the shipper to identify where an
event came from in order to apply processors accordingly.
Also, added test cases for the processor to verify the change.
**Since I'm not well familiar with the code base, I'm not 100% sure the IDs that I extract will be present before the processor is applied. Also, I didn't find where the IDs could be generated.**
It's needed to implement [Input/Stream Identification in the new Shipper Pipeline](https://docs.google.com/document/d/1fI6vBcxpxAhS4YtEhpveKR8y_irqPNqSOW2RTuRX8cc/edit) proposal.
I ran `go test -run ".*TestRules.*"` in the `internal/pkg/agent/transpiler` package
- Relates …
=> Add `@metadata.input_id` and `@metadata.stream_id` when injecting streams

CHANGELOG.next.asciidoc, internal/pkg/agent/cmd/diagnostics.go
Add filemod times to the files and directories in the zip archive.
Log files (and sub dirs) will use the modtime returned by the fileinfo
for the source. Others will use the timestamp from when the zip is
created.
Makes it easier to review diagnostics bundle content.
- Run `elastic-agent diagnostics collect`
- Unzip diagnostics bundle
- modtimes for directories and files will reflect reality
=> Add filemod times to contents of diagnostics collect command

testing/environments/snapshot.yml
[start_time:Sun, 19 Jun 2022 12:14:06 GMT, release_branch:8.3, prefix:, end_time:Sun, 19 Jun 2022 16:33:08 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-75d7500e, build_duration_seconds:15542]
=> [automation] update elastic stack version for testing 8.3.0-75d7500e

testing/environments/snapshot.yml
[start_time:Mon, 20 Jun 2022 00:14:27 GMT, release_branch:master, prefix:, end_time:Mon, 20 Jun 2022 04:17:38 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-b13123ee, build_duration_seconds:14591]
=> [automation] update elastic stack version for testing 8.4.0-b13123ee

testing/environments/snapshot.yml
[start_time:Sun, 19 Jun 2022 17:14:23 GMT, release_branch:8.2, prefix:, end_time:Sun, 19 Jun 2022 21:07:17 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-698e06ec, build_duration_seconds:13974]
=> [automation] update elastic stack version for testing 8.2.4-698e06ec

internal/pkg/agent/application/upgrade/step_mark.go, internal/pkg/agent/application/upgrade/upgrade.go, internal/pkg/agent/cleaner/cleaner.go, internal/pkg/agent/cleaner/cleaner_test.go, internal/pkg/agent/cmd/run.go, internal/pkg/fileutil/fileutil.go, internal/pkg/fleetapi/action.go
Fixes upgrade 8.2->8.3. 
There were two issues with upgrade:
1. The encryption of the agent fleet.yml and state.yml was happening in the wrong place. After some code digging, apparently the workflow is such that the old version of the agent unpacks the new version of the agent and tries to start it. With this change the agent checks if there are no fleet.enc or state.enc and there are fleet.yml or state.yml and encrypt them if needed upon the start.
2. After upgrade the upgrade action was never acked properly. 
The .update-marker file was dropped by the 8.2.4 version of the agent as 
```
hash: 5e3bdb
updated_on: 2022-06-17T16:42:20.371814-04:00
prev_version: 8.2.4
prev_hash: 9501a5
acked: false
action:
id: 4c09945a-3514-41e8-8680-283b156f4e29
type: UPGRADE
version: 8.3.0-SNAPSHOT 
```
but …
=> Fix Agent upgrade 8.2->8.3

testing/environments/snapshot.yml
[start_time:Tue, 21 Jun 2022 00:14:30 GMT, release_branch:8.3, prefix:, end_time:Tue, 21 Jun 2022 04:10:56 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-6d4bb852, build_duration_seconds:14186]
=> [automation] update elastic stack version for testing 8.3.0-6d4bb852

testing/environments/snapshot.yml
[start_time:Mon, 20 Jun 2022 17:14:26 GMT, release_branch:8.2, prefix:, end_time:Mon, 20 Jun 2022 21:08:40 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-b657c8f5, build_duration_seconds:14054]
=> [automation] update elastic stack version for testing 8.2.4-b657c8f5

testing/environments/snapshot.yml
[start_time:Tue, 21 Jun 2022 05:17:37 GMT, release_branch:8.2, prefix:, end_time:Tue, 21 Jun 2022 14:49:50 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-589bdf37, build_duration_seconds:34333]
=> [automation] update elastic stack version for testing 8.2.4-589bdf37

testing/environments/snapshot.yml
[start_time:Tue, 21 Jun 2022 17:14:26 GMT, release_branch:8.2, prefix:, end_time:Tue, 21 Jun 2022 23:01:19 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-a34570b4, build_duration_seconds:20813]
=> [automation] update elastic stack version for testing 8.2.4-a34570b4

testing/environments/snapshot.yml
[start_time:Wed, 22 Jun 2022 00:14:11 GMT, release_branch:master, prefix:, end_time:Wed, 22 Jun 2022 04:24:31 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-4fe26f2a, build_duration_seconds:15020]
=> [automation] update elastic stack version for testing 8.4.0-4fe26f2a

internal/pkg/agent/install/svc.go
Set explicit ExitTimeOut for MacOS agent launchd plist to 60 secs.
Addresses the issue https://github.com/elastic/elastic-agent/issues/593 where the agent is killed prematurely by launchd without having a chance to shut down gracefully.
See the issue https://github.com/elastic/elastic-agent/issues/593 for more details.
Addresses the issue https://github.com/elastic/elastic-agent/issues/593
The agent should be able to stop without leaving any child processes running. The agent should not receive SIGKILL from launchd. Refer to the issue for details https://github.com/elastic/elastic-agent/issues/593
- Closes https://github.com/elastic/elastic-agent/issues/593
The updated agent ```/Library/LaunchDaemons/co.elastic.elastic-agent.plist``` installed with ```ExitTimeOut```
Launchd log after the …
=> Set explicit ExitTimeOut for MacOS agent launchd plist

testing/environments/snapshot.yml
[start_time:Wed, 22 Jun 2022 12:14:08 GMT, release_branch:8.3, prefix:, end_time:Wed, 22 Jun 2022 17:26:40 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-47d97929, build_duration_seconds:18752]
=> [automation] update elastic stack version for testing 8.3.0-47d97929

testing/environments/snapshot.yml
[start_time:Wed, 22 Jun 2022 12:16:38 GMT, release_branch:master, prefix:, end_time:Wed, 22 Jun 2022 18:05:34 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-2e32a640, build_duration_seconds:20936]
=> [automation] update elastic stack version for testing 8.4.0-2e32a640

testing/environments/snapshot.yml
[start_time:Wed, 22 Jun 2022 17:14:18 GMT, release_branch:8.2, prefix:, end_time:Wed, 22 Jun 2022 21:23:40 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-b5aa40e4, build_duration_seconds:14962]
=> [automation] update elastic stack version for testing 8.2.4-b5aa40e4

.ci/Jenkinsfile
Create a GitHub issue:
* As soon as a build is failing an issue should be created
* It should be assigned to Elastic Agent Data Plane team (it relies on the GitHub labels to do so)
Use GitHub to drive the on-call process when the CI fails
Similar to https://github.com/elastic/beats/pull/31954
=> ci: enable build notifications as GitHub issues

testing/environments/snapshot.yml
[start_time:Fri, 24 Jun 2022 00:14:40 GMT, release_branch:8.3, prefix:, end_time:Fri, 24 Jun 2022 04:58:09 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-3b390c7b, build_duration_seconds:17009]
=> [automation] update elastic stack version for testing 8.3.0-3b390c7b

testing/environments/snapshot.yml
[start_time:Thu, 23 Jun 2022 12:14:12 GMT, release_branch:master, prefix:, end_time:Thu, 23 Jun 2022 16:35:54 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-722a7d79, build_duration_seconds:15702]
=> [automation] update elastic stack version for testing 8.4.0-722a7d79

testing/environments/snapshot.yml
[start_time:Thu, 23 Jun 2022 17:14:05 GMT, release_branch:8.2, prefix:, end_time:Thu, 23 Jun 2022 21:24:03 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-32b57cbe, build_duration_seconds:14998]
=> [automation] update elastic stack version for testing 8.2.4-32b57cbe

dev-tools/mage/common.go, dev-tools/mage/pkgtypes.go, magefile.go
During packaging for each spec file we compute sha512 hash as well as for its binary counterpart
Result:
Future trust/verification of integrity
=> Generate checksum file for components

.ci/Jenkinsfile
Enable `test-flakiness` detection
Track `test-flakiness` help to monitor how often a particular test failure happens and has been categorised as flaky.
This is similar done for Beats -> https://github.com/elastic/beats/issues?q=is%3Aissue+is%3Aopen+label%3Aflaky-test
=> ci: enable flaky test detector

testing/environments/snapshot.yml
[start_time:Fri, 24 Jun 2022 12:15:00 GMT, release_branch:master, prefix:, end_time:Fri, 24 Jun 2022 16:42:38 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-210dd487, build_duration_seconds:16058]
=> [automation] update elastic stack version for testing 8.4.0-210dd487

testing/environments/snapshot.yml
[start_time:Sat, 25 Jun 2022 00:18:11 GMT, release_branch:8.3, prefix:, end_time:Sat, 25 Jun 2022 04:28:19 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-fdf97a2e, build_duration_seconds:15008]
=> [automation] update elastic stack version for testing 8.3.0-fdf97a2e

testing/environments/snapshot.yml
[start_time:Fri, 24 Jun 2022 17:14:23 GMT, release_branch:8.2, prefix:, end_time:Fri, 24 Jun 2022 21:16:07 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-b7bb3a0c, build_duration_seconds:14504]
=> [automation] update elastic stack version for testing 8.2.4-b7bb3a0c

testing/environments/snapshot.yml
[start_time:Tue, 28 Jun 2022 00:14:46 GMT, release_branch:master, prefix:, end_time:Tue, 28 Jun 2022 04:37:57 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-a6aa9f3b, build_duration_seconds:15791]
=> [automation] update elastic stack version for testing 8.4.0-a6aa9f3b

testing/environments/snapshot.yml
[start_time:Mon, 27 Jun 2022 17:14:43 GMT, release_branch:8.2, prefix:, end_time:Mon, 27 Jun 2022 21:31:15 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-9b981623, build_duration_seconds:15392]
=> [automation] update elastic stack version for testing 8.2.4-9b981623

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
Set hostPID to true in the yaml for managed Agent in kubernetes. hostPID is a pod-wide policy that makes it so all containers in that pod share the host PID namespace.
This change enables containers in an elastic-agent pod to have visibility of other processes in the node where that pod is running, enabling integrations with capabilities that involve observing and/or affecting other processes (e.g., killing a process running).
- Closes #459 .
=> Set hostPID=true for managed agent in k8s

testing/environments/snapshot.yml
[start_time:Wed, 29 Jun 2022 12:14:26 GMT, release_branch:master, prefix:, end_time:Wed, 29 Jun 2022 16:19:29 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-86cc80f3, build_duration_seconds:14703]
=> [automation] update elastic stack version for testing 8.4.0-86cc80f3

testing/environments/snapshot.yml
[start_time:Wed, 29 Jun 2022 10:00:17 GMT, release_branch:8.3, prefix:, end_time:Wed, 29 Jun 2022 17:35:55 GMT, manifest_version:2.1.0, version:8.3.1-SNAPSHOT, branch:8.3, build_id:8.3.1-b95de5e6, build_duration_seconds:27338]
=> [automation] update elastic stack version for testing 8.3.1-b95de5e6

testing/environments/snapshot.yml
[start_time:Wed, 29 Jun 2022 05:14:48 GMT, release_branch:8.2, prefix:, end_time:Wed, 29 Jun 2022 09:39:00 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-e7c42e26, build_duration_seconds:15852]
=> [automation] update elastic stack version for testing 8.2.4-e7c42e26

CHANGELOG.next.asciidoc, internal/pkg/agent/cmd/diagnostics.go, internal/pkg/agent/cmd/diagnostics_test.go
Redacts sensitive information collected by the Elastic-Agent `diagnostics collect` command.
Prevent sensitive information being shared unintentionally.
Compile, install the agent, run the `diagnostics collect` command and check that the sensitive data was redacted.
- Closes #241
=> Redact sensitive information in diagnostics collect command

testing/environments/snapshot.yml
[start_time:Thu, 30 Jun 2022 12:14:14 GMT, release_branch:master, prefix:, end_time:Thu, 30 Jun 2022 16:33:00 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-3d206b5d, build_duration_seconds:15526]
=> [automation] update elastic stack version for testing 8.4.0-3d206b5d

testing/environments/snapshot.yml
[start_time:Mon, 4 Jul 2022 00:15:23 GMT, release_branch:master, prefix:, end_time:Mon, 4 Jul 2022 04:37:22 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-3ad82aa8, build_duration_seconds:15719]
=> [automation] update elastic stack version for testing 8.4.0-3ad82aa8

.ci/jobs/elastic-agent-mbp.yml
Avoid running builds for upstream branches which are not following the release branch strategy
See https://github.com/elastic/elastic-agent/pull/649#issuecomment-1171335699
=> jjbb: exclude allowed branches, tags and PRs

.ci/Jenkinsfile
Otherwise the `orka` workers will be provisioned since they have the same label
=> ci: fix labels that clashes with the Orka workers

testing/environments/snapshot.yml
[start_time:Mon, 4 Jul 2022 12:16:14 GMT, release_branch:master, prefix:, end_time:Mon, 4 Jul 2022 17:02:59 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-03bd6f3f, build_duration_seconds:17205]
=> [automation] update elastic stack version for testing 8.4.0-03bd6f3f

testing/environments/snapshot.yml
[start_time:Tue, 5 Jul 2022 00:14:19 GMT, release_branch:8.3, prefix:, end_time:Tue, 5 Jul 2022 04:22:13 GMT, manifest_version:2.1.0, version:8.3.2-SNAPSHOT, branch:8.3, build_id:8.3.2-d34285fd, build_duration_seconds:14874]
=> [automation] update elastic stack version for testing 8.3.2-d34285fd

testing/environments/snapshot.yml
[start_time:Tue, 5 Jul 2022 12:17:52 GMT, release_branch:master, prefix:, end_time:Tue, 5 Jul 2022 17:41:38 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-533f1e30, build_duration_seconds:19426]
=> [automation] update elastic stack version for testing 8.4.0-533f1e30

testing/environments/snapshot.yml
[start_time:Wed, 6 Jul 2022 00:15:45 GMT, release_branch:8.3, prefix:, end_time:Wed, 6 Jul 2022 04:35:35 GMT, manifest_version:2.1.0, version:8.3.2-SNAPSHOT, branch:8.3, build_id:8.3.2-56253b46, build_duration_seconds:15590]
=> [automation] update elastic stack version for testing 8.3.2-56253b46

testing/environments/snapshot.yml
[start_time:Wed, 6 Jul 2022 00:15:11 GMT, release_branch:master, prefix:, end_time:Wed, 6 Jul 2022 05:19:25 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-d0a4da44, build_duration_seconds:18254]
=> [automation] update elastic stack version for testing 8.4.0-d0a4da44

testing/environments/snapshot.yml
[start_time:Sun, 10 Jul 2022 12:14:29 GMT, release_branch:master, prefix:, end_time:Sun, 10 Jul 2022 16:52:30 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-dd98ded4, build_duration_seconds:16681]
=> [automation] update elastic stack version for testing 8.4.0-dd98ded4

testing/environments/snapshot.yml
[start_time:Mon, 11 Jul 2022 00:15:20 GMT, release_branch:8.3, prefix:, end_time:Mon, 11 Jul 2022 04:59:34 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-385d4fdb, build_duration_seconds:17054]
=> [automation] update elastic stack version for testing 8.3.3-385d4fdb

testing/environments/snapshot.yml
[start_time:Tue, 12 Jul 2022 00:14:47 GMT, release_branch:8.3, prefix:, end_time:Tue, 12 Jul 2022 04:33:00 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-46b07667, build_duration_seconds:15493]
=> [automation] update elastic stack version for testing 8.3.3-46b07667

testing/environments/snapshot.yml
[start_time:Mon, 11 Jul 2022 12:15:42 GMT, release_branch:master, prefix:, end_time:Mon, 11 Jul 2022 16:53:35 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-164d9a10, build_duration_seconds:16673]
=> [automation] update elastic stack version for testing 8.4.0-164d9a10

testing/environments/snapshot.yml
[start_time:Tue, 12 Jul 2022 12:14:45 GMT, release_branch:master, prefix:, end_time:Tue, 12 Jul 2022 16:51:42 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-00048b66, build_duration_seconds:16617]
=> [automation] update elastic stack version for testing 8.4.0-00048b66

testing/environments/snapshot.yml
[start_time:Thu, 14 Jul 2022 00:14:48 GMT, release_branch:8.3, prefix:, end_time:Thu, 14 Jul 2022 04:31:09 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-fba30f71, build_duration_seconds:15381]
=> [automation] update elastic stack version for testing 8.3.3-fba30f71

testing/environments/snapshot.yml
[start_time:Fri, 15 Jul 2022 00:14:35 GMT, release_branch:master, prefix:, end_time:Fri, 15 Jul 2022 04:54:08 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-3cd57abb, build_duration_seconds:16773]
=> [automation] update elastic stack version for testing 8.4.0-3cd57abb

testing/environments/snapshot.yml
[start_time:Mon, 18 Jul 2022 00:14:58 GMT, release_branch:master, prefix:, end_time:Mon, 18 Jul 2022 05:00:16 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-a324b98b, build_duration_seconds:17118]
=> [automation] update elastic stack version for testing 8.4.0-a324b98b

testing/environments/snapshot.yml
[start_time:Mon, 18 Jul 2022 00:14:17 GMT, release_branch:8.3, prefix:, end_time:Mon, 18 Jul 2022 04:33:35 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-99553f72, build_duration_seconds:15558]
=> [automation] update elastic stack version for testing 8.3.3-99553f72

.ci/Jenkinsfile
- Update labels to run on MacOS12
- Use `isDarwin`
- Ensure labels are the ones with the OS version to be tested otherwise it's hard to know what's the OS version for Darwin
Requires https://github.com/elastic/apm-pipeline-library/pull/1774
=> ci: run on MacOS12

testing/environments/snapshot.yml
[start_time:Tue, 19 Jul 2022 00:18:08 GMT, release_branch:master, prefix:, end_time:Tue, 19 Jul 2022 04:40:25 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-31315ca3, build_duration_seconds:15737]
=> [automation] update elastic stack version for testing 8.4.0-31315ca3

testing/environments/snapshot.yml
[start_time:Mon, 18 Jul 2022 12:14:36 GMT, release_branch:8.3, prefix:, end_time:Mon, 18 Jul 2022 16:38:07 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-302be7c1, build_duration_seconds:15811]
=> [automation] update elastic stack version for testing 8.3.3-302be7c1

README.md
This commit fixes the typo in the package command on the README.md.
It fixes a typo in the package command examples that can lead to very long build/waiting times.
- ~~[ ] I have commented my code, particularly in hard-to-understand areasv
1. Copy/paste/execute the package commands from the README.md
2. Assert it only built the docker package
~~## Logs~~
=> fix typo on package command

testing/environments/snapshot.yml
[start_time:Tue, 19 Jul 2022 12:14:18 GMT, release_branch:master, prefix:, end_time:Tue, 19 Jul 2022 16:59:58 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-31269fd2, build_duration_seconds:17140]
=> [automation] update elastic stack version for testing 8.4.0-31269fd2

testing/environments/snapshot.yml
[start_time:Wed, 20 Jul 2022 00:15:17 GMT, release_branch:8.3, prefix:, end_time:Wed, 20 Jul 2022 04:42:43 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-e5bc7e69, build_duration_seconds:16046]
=> [automation] update elastic stack version for testing 8.3.3-e5bc7e69

internal/pkg/agent/application/info/agent_id.go, internal/pkg/agent/application/info/agent_metadata.go, internal/pkg/agent/storage/encrypted_disk_store.go, internal/pkg/agent/vault/vault_darwin.go, internal/pkg/agent/vault/vault_linux.go
Wrap errors to add more context to them.
It makes easier to understand the root cause of an error.
=> Wrap errors and fix some docs typo and convention

internal/pkg/artifact/download/http/downloader_test.go
Fixes flaky test in https://github.com/elastic/elastic-agent/issues/640
Stops automatic bumps https://github.com/elastic/elastic-agent/pull/725
=> fix flaky test TestDownloadBodyError 

testing/environments/snapshot.yml
[start_time:Fri, 22 Jul 2022 00:15:12 GMT, release_branch:8.3, prefix:, end_time:Fri, 22 Jul 2022 04:42:51 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-bb633b08, build_duration_seconds:16059]
=> [automation] update elastic stack version for testing 8.3.3-bb633b08

.github/workflows/golangci-lint.yml, internal/pkg/agent/application/secret/secret.go
Alter the linter action to run on different OSs instead of on linux with
the $GOOS env var.
We have issues in other PRs where the linter actions create a lot of false positives.
- Closes #486
=> Alter github action to run on different OSs

testing/environments/snapshot.yml
[start_time:Fri, 22 Jul 2022 15:52:06 GMT, release_branch:master, prefix:, end_time:Fri, 22 Jul 2022 20:45:04 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-d058e92f, build_duration_seconds:17578]
=> [automation] update elastic stack version for testing 8.4.0-d058e92f

.github/CODEOWNERS, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml, deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-role.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-role.yaml
Signed-off-by: Tetiana Kravchenko <tetiana.kravchenko@elastic.co>
- add @elastic/obs-cloudnative-monitoring as a codeowner for k8s manifests
- add commentary for the daemonset of the managed elastic-agent. Later those changes will be backported to the kibana repo - draft PR https://github.com/elastic/kibana/pull/136394
- Relates https://github.com/elastic/observability-dev/issues/2251
=> elastic-agent manifests: add comments; add cloudnative team as a codeowner for the k8s manifests

testing/environments/snapshot.yml
[start_time:Tue, 26 Jul 2022 00:14:32 GMT, release_branch:8.3, prefix:, end_time:Tue, 26 Jul 2022 04:44:23 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-d520d440, build_duration_seconds:16191]
=> [automation] update elastic stack version for testing 8.3.3-d520d440

CHANGELOG.next.asciidoc, internal/pkg/agent/application/upgrade/cleanup.go, internal/pkg/agent/application/upgrade/cleanup_test.go, internal/pkg/agent/application/upgrade/upgrade.go
The update process will cleanup unneeded artifacts. When an update
starts all artifacts that do not have the current version number in it's
name will be removed. If artifact retrieval fails, downloaded artifacts
are removed. On a successful upgrade, all contents of the downloads dir
will be removed.
If verification fails because of an issue with the download, the agent will not be able to upgrade future attempts.
If the agent goes through a lot of upgrades it will use a lot of storage for binaries that are not used.
1. cherry-pick to `8.3`
2. Install agent running 8.4.0-SNAPSHOT
3. Upgrade agent through UI
4. After upgrade is successful, there is no `downloads` dir in old agent dir
- Closes #693 
- Closes #694
=> Update will cleanup unneeded artifacts.

testing/environments/snapshot.yml
[start_time:Wed, 27 Jul 2022 07:09:19 GMT, release_branch:8.3, prefix:, end_time:Wed, 27 Jul 2022 13:37:37 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-8631d33c, build_duration_seconds:23298]
=> [automation] update elastic stack version for testing 8.3.3-8631d33c

testing/environments/snapshot.yml
[start_time:Wed, 27 Jul 2022 07:02:31 GMT, release_branch:master, prefix:, end_time:Wed, 27 Jul 2022 12:07:51 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-60171339, build_duration_seconds:18320]
=> [automation] update elastic stack version for testing 8.4.0-60171339

testing/environments/latest.yml
Merge only after the release of 8.3.3.
=> [Release] Update test environments for 8.3.4

NOTICE.txt, go.mod, go.sum
Signed-off-by: Florian Lehner <florian.lehner@elastic.co>
Update the dependency `elastic/go-structform` from `v0.0.9` to `v0.0.10`.
The dependency `elastic/go-structform`  [v0.0.10](https://github.com/elastic/go-structform/commit/54c82b302f9adce354ec9b51abe9cef3bd4245ca) includes changes to reduce the memory footprint and so does have an positive effect also on `elastic/elastic-agent`.
PR does not introduce code changes.
PR does not introduce code changes.
PR does not introduce code changes.
No configuration changes with this PR.
PR does not introduce code changes.
PR does not introduce code changes.
=> update dependency elastic/go-structform from v0.0.9 to v0.0.10

testing/environments/snapshot.yml
[start_time:Sun, 31 Jul 2022 12:17:51 GMT, release_branch:8.4, prefix:, end_time:Sun, 31 Jul 2022 17:04:55 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-d88c8a44, build_duration_seconds:17224]
=> [automation] update elastic stack version for testing 8.4.0-d88c8a44

testing/environments/snapshot.yml
[start_time:Mon, 1 Aug 2022 00:17:44 GMT, release_branch:8.4, prefix:, end_time:Mon, 1 Aug 2022 05:27:02 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-5954f776, build_duration_seconds:18558]
=> [automation] update elastic stack version for testing 8.4.0-5954f776

testing/environments/snapshot.yml
[start_time:Mon, 1 Aug 2022 12:16:15 GMT, release_branch:master, prefix:, end_time:Mon, 1 Aug 2022 17:55:48 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-c54c3404, build_duration_seconds:20373]
=> [automation] update elastic stack version for testing 8.5.0-c54c3404

testing/environments/snapshot.yml
[start_time:Tue, 2 Aug 2022 00:18:09 GMT, release_branch:8.3, prefix:, end_time:Tue, 2 Aug 2022 04:56:14 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-9c50d4cb, build_duration_seconds:16685]
=> [automation] update elastic stack version for testing 8.3.4-9c50d4cb

testing/environments/snapshot.yml
[start_time:Tue, 2 Aug 2022 00:15:42 GMT, release_branch:master, prefix:, end_time:Tue, 2 Aug 2022 05:41:40 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-7dbc10f8, build_duration_seconds:19558]
=> [automation] update elastic stack version for testing 8.5.0-7dbc10f8

dev-tools/packaging/templates/linux/postinstall.sh.tmpl
Updates post-install script to handle the clean RPM/DEB install correctly if there were no previous agent installs were on the system.
Fixes the https://github.com/elastic/elastic-agent/issues/803 for 8.4.0 and latest 8.3.4 builds.
* Clean Install
1. Install 8.4.0 from RPM with not previous installs or previous agent data on the system.
* Upgrade Install
1. Install 8.3.1 from RPM, enroll and make sure it runs correctly
2. Stop the agent service.
3. Install 8.4.0 from RPM, start the service, make sure it runs correctly
- Closes https://github.com/elastic/elastic-agent/issues/803
=> Fix RPM/DEB clean install

testing/environments/snapshot.yml
[start_time:Wed, 3 Aug 2022 00:15:44 GMT, release_branch:8.3, prefix:, end_time:Wed, 3 Aug 2022 04:54:02 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-a15c6beb, build_duration_seconds:16698]
=> [automation] update elastic stack version for testing 8.3.4-a15c6beb

testing/environments/snapshot.yml
[start_time:Wed, 3 Aug 2022 17:30:29 GMT, release_branch:8.4, prefix:, end_time:Wed, 3 Aug 2022 22:37:06 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-b5074ef3, build_duration_seconds:18397]
=> [automation] update elastic stack version for testing 8.4.0-b5074ef3

testing/environments/snapshot.yml
[start_time:Wed, 3 Aug 2022 12:18:18 GMT, release_branch:8.3, prefix:, end_time:Wed, 3 Aug 2022 16:32:35 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-ce266bfe, build_duration_seconds:15257]
=> [automation] update elastic stack version for testing 8.3.4-ce266bfe

testing/environments/snapshot.yml
[start_time:Thu, 4 Aug 2022 12:15:38 GMT, release_branch:8.4, prefix:, end_time:Thu, 4 Aug 2022 17:41:18 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-43c061d1, build_duration_seconds:19540]
=> [automation] update elastic stack version for testing 8.4.0-43c061d1

testing/environments/snapshot.yml
[start_time:Thu, 4 Aug 2022 12:16:07 GMT, release_branch:8.3, prefix:, end_time:Thu, 4 Aug 2022 16:32:47 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-73c9af3c, build_duration_seconds:15400]
=> [automation] update elastic stack version for testing 8.3.4-73c9af3c

internal/pkg/agent/application/local_mode.go, internal/pkg/agent/application/managed_mode.go, internal/pkg/agent/application/pipeline/emitter/controller.go, internal/pkg/agent/application/pipeline/emitter/emitter.go, internal/pkg/agent/application/pipeline/router/router.go, internal/pkg/agent/application/pipeline/stream/operator_stream.go, internal/pkg/agent/operation/operator.go, internal/pkg/artifact/config.go, internal/pkg/artifact/download/composed/downloader.go, internal/pkg/artifact/download/composed/verifier.go, internal/pkg/artifact/download/http/downloader.go, internal/pkg/artifact/download/http/verifier.go, internal/pkg/artifact/download/reloadable.go, internal/pkg/artifact/download/snapshot/downloader.go, internal/pkg/artifact/download/snapshot/verifier.go
Downloaders have own instance of client which is used to download artifacts.
This client is created when constructing a downloader instance and exists for the time being. 
When configuration changes for `artifacts.download` client should be recreated to reflect new proxy/TLS/timeout settings.
On top of that this also fixes an issue when agent after failed download does not remove corrupted files which leads to retry of verification loop which fails on `asc and sha512` not found errors making downloads and upgrades unusable in a future.
This is source of many SDHs which requires manual intervention and cleaning up download directory by user. 
- reflecting changes in a client 
- reducing incident count for failed upgrades
- required to properly respond to proxy changes
- build agent
- …
=> Reload downloader client on config change

testing/environments/snapshot.yml
[start_time:Mon, 8 Aug 2022 00:15:48 GMT, release_branch:8.3, prefix:, end_time:Mon, 8 Aug 2022 04:55:10 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-9c6c318b, build_duration_seconds:16762]
=> [automation] update elastic stack version for testing 8.3.4-9c6c318b

testing/environments/snapshot.yml
[start_time:Sun, 7 Aug 2022 00:17:42 GMT, release_branch:8.4, prefix:, end_time:Sun, 7 Aug 2022 05:40:11 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-4b3e8f6e, build_duration_seconds:19349]
=> [automation] update elastic stack version for testing 8.4.0-4b3e8f6e

testing/environments/snapshot.yml
[start_time:Tue, 9 Aug 2022 00:16:04 GMT, release_branch:8.3, prefix:, end_time:Tue, 9 Aug 2022 04:43:07 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-fd43be48, build_duration_seconds:16023]
=> [automation] update elastic stack version for testing 8.3.4-fd43be48

testing/environments/snapshot.yml
[start_time:Mon, 8 Aug 2022 12:15:06 GMT, release_branch:8.4, prefix:, end_time:Mon, 8 Aug 2022 17:58:03 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-96568c7b, build_duration_seconds:20577]
=> [automation] update elastic stack version for testing 8.4.0-96568c7b

internal/pkg/agent/application/local_mode.go, internal/pkg/agent/application/managed_mode.go, internal/pkg/agent/application/pipeline/emitter/controller.go, internal/pkg/agent/application/pipeline/emitter/emitter.go, internal/pkg/agent/application/pipeline/router/router.go, internal/pkg/agent/application/pipeline/stream/operator_stream.go, internal/pkg/agent/operation/operator.go, internal/pkg/artifact/config.go, internal/pkg/artifact/config_test.go, internal/pkg/artifact/download/composed/downloader.go, internal/pkg/artifact/download/composed/verifier.go, internal/pkg/artifact/download/http/downloader.go, internal/pkg/artifact/download/http/verifier.go, internal/pkg/artifact/download/reloadable.go, internal/pkg/artifact/download/snapshot/downloader.go, internal/pkg/artifact/download/snapshot/verifier.go
Backport of #848 and #776 as prerequisite 
Downloaders have own instance of client which is used to download artifacts.
This client is created when constructing a downloader instance and exists for the time being. 
When configuration changes for `artifacts.download` client should be recreated to reflect new proxy/TLS/timeout settings.
On top of that this also fixes an issue when agent after failed download does not remove corrupted files which leads to retry of verification loop which fails on `asc and sha512` not found errors making downloads and upgrades unusable in a future.
This is source of many SDHs which requires manual intervention and cleaning up download directory by user. 
- reflecting changes in a client 
- reducing incident count for failed upgrades
- required to properly …
=> [8.4](backport #848) Reload downloader client on config change

dev-tools/mage/crossbuild.go
Signed-off-by: Florian Lehner <florian.lehner@elastic.co>
This PR ports over the fix that got into `elastic/beats` with https://github.com/elastic/beats/commit/d938679b499465690fae4a5a9b86ca8d8ff61df5 and https://github.com/elastic/beats/commit/ee6f4708451824bd8b8ee767e10e4f7f9a583ee7 as `elastic/elastic-agent` faces the very same issue.
For details about this bug please checkout https://github.com/elastic/beats/pull/32580.
No impacting changes for end users. So no update to the documentation.
No changes to the configuration files are required.
-  [ ] ~~I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~
This is a fix impacting developers and not end user facing. So I did not add an entry.
=> crossbuild: add fix to set ulimit for debian images

testing/environments/snapshot.yml
[start_time:Tue, 9 Aug 2022 12:17:46 GMT, release_branch:8.4, prefix:, end_time:Tue, 9 Aug 2022 17:58:06 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-9adc8090, build_duration_seconds:20420]
=> [automation] update elastic stack version for testing 8.4.0-9adc8090

testing/environments/snapshot.yml
[start_time:Tue, 9 Aug 2022 12:15:59 GMT, release_branch:master, prefix:, end_time:Tue, 9 Aug 2022 18:53:08 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-41aadc32, build_duration_seconds:23829]
=> [automation] update elastic stack version for testing 8.5.0-41aadc32

testing/environments/snapshot.yml
[start_time:Tue, 9 Aug 2022 12:15:41 GMT, release_branch:8.3, prefix:, end_time:Tue, 9 Aug 2022 17:00:53 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-b4aa6143, build_duration_seconds:17112]
=> [automation] update elastic stack version for testing 8.3.4-b4aa6143

testing/environments/snapshot.yml
[start_time:Wed, 10 Aug 2022 12:15:43 GMT, release_branch:8.4, prefix:, end_time:Wed, 10 Aug 2022 17:19:16 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-c17572db, build_duration_seconds:18213]
=> [automation] update elastic stack version for testing 8.4.0-c17572db

testing/environments/snapshot.yml
[start_time:Wed, 10 Aug 2022 12:17:48 GMT, release_branch:master, prefix:, end_time:Wed, 10 Aug 2022 18:36:28 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-60a4c029, build_duration_seconds:22720]
=> [automation] update elastic stack version for testing 8.5.0-60a4c029

testing/environments/snapshot.yml
[start_time:Thu, 11 Aug 2022 00:18:58 GMT, release_branch:8.3, prefix:, end_time:Thu, 11 Aug 2022 04:58:12 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-a5e24e15, build_duration_seconds:16754]
=> [automation] update elastic stack version for testing 8.3.4-a5e24e15

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
The K8S taint with key `node-role.kubernetes.io/control-plane` is set to replace the deprecated taint with key `node-role.kubernetes.io/master` which will be removed by Kubernetes v1.25, as described [here](https://kubernetes.io/docs/reference/labels-annotations-taints/#node-role-kubernetes-io-master).
Newly provisioned K8S clusters will have either both taints on the control-plane (previously known as master) node, or only the one with the new key. Example on a multi-node K8S v1.24 cluster provisioned with `kind`:
The effect in either case is that with our existing manifests, an Elastic Agent pod won't be scheduled on the control-plane node. Adding a toleration to these manifests that matches the new taint key fixes this problem.
Using `kind` with the following `config.yml`:
```
kind: …
```
=> Add control-plane toleration to Agent K8S manifests.

testing/environments/snapshot.yml
[start_time:Thu, 11 Aug 2022 12:17:23 GMT, release_branch:8.3, prefix:, end_time:Thu, 11 Aug 2022 16:55:27 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-adc3e57f, build_duration_seconds:16684]
=> [automation] update elastic stack version for testing 8.3.4-adc3e57f

testing/environments/snapshot.yml
[start_time:Sun, 14 Aug 2022 12:15:35 GMT, release_branch:8.4, prefix:, end_time:Sun, 14 Aug 2022 17:35:57 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-fea9abbe, build_duration_seconds:19222]
=> [automation] update elastic stack version for testing 8.4.0-fea9abbe

testing/environments/snapshot.yml
[start_time:Sun, 14 Aug 2022 12:23:06 GMT, release_branch:8.3, prefix:, end_time:Sun, 14 Aug 2022 18:07:08 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-6d6eaf28, build_duration_seconds:20642]
=> [automation] update elastic stack version for testing 8.3.4-6d6eaf28

testing/environments/snapshot.yml
[start_time:Mon, 15 Aug 2022 00:15:30 GMT, release_branch:8.3, prefix:, end_time:Mon, 15 Aug 2022 05:10:35 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-58ddca7b, build_duration_seconds:17705]
=> [automation] update elastic stack version for testing 8.3.4-58ddca7b

testing/environments/snapshot.yml
[start_time:Mon, 15 Aug 2022 12:18:10 GMT, release_branch:8.4, prefix:, end_time:Mon, 15 Aug 2022 18:08:58 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-9bd354a1, build_duration_seconds:21048]
=> [automation] update elastic stack version for testing 8.4.0-9bd354a1

internal/pkg/agent/application/gateway/fleet/fleet_gateway.go, internal/pkg/fleetapi/checkin_cmd.go
Expands the checkin payload with the new V2 payload.
@blakerouse I noticed that you added the Stringer API to the status/state constants in the latest elastic-agent-client but it was not picked up on this branch yet. When I tried to update I saw code breakage in other places. So leaving it for now. Can remove stringers later as needed.
I left some questions in the doc https://docs.google.com/document/d/1I0PeZKIkUTaWiY2F_Dum_gSi0cpbblcftl-tz81iYak/edit, seems like few things are missing in the code to match the doc format.
Will update fleet-server next.
Better, more granular agent status information.
- Relates https://github.com/elastic/elastic-agent/issues/100
```
{
"status": "online",
"events": null,
"local_metadata": {
"elastic": {
"agent": {
"id": …
```
=> Expand check-in payload for V2

testing/environments/snapshot.yml
[start_time:Tue, 16 Aug 2022 12:15:36 GMT, release_branch:8.4, prefix:, end_time:Tue, 16 Aug 2022 19:17:51 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-aff0df12, build_duration_seconds:25335]
=> [automation] update elastic stack version for testing 8.4.0-aff0df12

Makefile
Use [`go install`](https://pkg.go.dev/cmd/go#hdr-Compile_and_install_packages_and_dependencies). `go get` changes the  `go.mod` so it's not the preferred approach
After upgrading golang version `1.17.12` to `1.18.5` the `make mage` goal failed hence the Unified Release process cannot generate snapshots from `main`.
Something similar was done when 1.16 was available, see https://github.com/elastic/apm-pipeline-library/pull/1300
```bash
VERBOSE=true ./dev-tools/run_with_go_ver make mage
VERBOSE=true ./dev-tools/run_with_go_ver mage build
VERBOSE=true ./dev-tools/run_with_go_ver mage package
```
<details><summary>Expand to view</summary>
<p>
```
VERBOSE=true ./dev-tools/run_with_go_ver mage package                     
+ MSG='environment variable missing'
+ GO_VERSION=1.18.5
+ …
```
=> install mage with go install

internal/pkg/agent/application/pipeline/actions/handlers/handler_action_unenroll.go, internal/pkg/agent/application/upgrade/upgrade.go, internal/pkg/agent/operation/operation_retryable.go, internal/pkg/agent/stateresolver/resolve.go, internal/pkg/composable/providers/kubernetes/pod.go, internal/pkg/composable/providers/kubernetesleaderelection/config.go, internal/pkg/core/plugin/process/app.go, internal/pkg/core/state/state.go, internal/pkg/core/status/reporter.go, internal/pkg/crypto/io.go, internal/pkg/fleetapi/acker/retrier/retrier.go, internal/pkg/reporter/fleet/reporter.go
Reorder struct elements to reduce the memory footprint. Reducing memory footprint also have a direct impact on the GC as less work is needed on GC side.
This PR improves the performance of the Elastic Agent without changing its behavior or business logic.
PR does not introduce code changes.
PR does not introduce code changes.
PR does not introduce code changes.
No configuration changes with this PR.
PR does not introduce code changes.
PR does not introduce code changes.
=> Reduce memory footprint by reordering struct elements

testing/environments/snapshot.yml
[start_time:Wed, 17 Aug 2022 12:16:21 GMT, release_branch:8.3, prefix:, end_time:Wed, 17 Aug 2022 17:48:01 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-e23a59c6, build_duration_seconds:19900]
=> [automation] update elastic stack version for testing 8.3.4-e23a59c6

testing/environments/snapshot.yml
[start_time:Wed, 17 Aug 2022 12:18:02 GMT, release_branch:master, prefix:, end_time:Wed, 17 Aug 2022 20:19:44 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-6b9f92c0, build_duration_seconds:28902]
=> [automation] update elastic stack version for testing 8.5.0-6b9f92c0

testing/environments/snapshot.yml
[start_time:Wed, 17 Aug 2022 00:15:47 GMT, release_branch:8.4, prefix:, end_time:Wed, 17 Aug 2022 05:18:36 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-b95305c2, build_duration_seconds:18169]
=> [automation] update elastic stack version for testing 8.4.0-b95305c2

testing/environments/snapshot.yml
[start_time:Sun, 21 Aug 2022 12:22:02 GMT, release_branch:8.4, prefix:, end_time:Sun, 21 Aug 2022 17:48:21 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-910fe5e1, build_duration_seconds:19579]
=> [automation] update elastic stack version for testing 8.4.0-910fe5e1

testing/environments/snapshot.yml
[start_time:Sun, 21 Aug 2022 00:18:06 GMT, release_branch:8.3, prefix:, end_time:Sun, 21 Aug 2022 05:20:42 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-70c0b53c, build_duration_seconds:18156]
=> [automation] update elastic stack version for testing 8.3.4-70c0b53c

testing/environments/snapshot.yml
[start_time:Sat, 20 Aug 2022 00:15:57 GMT, release_branch:master, prefix:, end_time:Sat, 20 Aug 2022 05:58:58 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-0616acda, build_duration_seconds:20581]
=> [automation] update elastic stack version for testing 8.5.0-0616acda

testing/environments/snapshot.yml
[start_time:Mon, 22 Aug 2022 12:16:01 GMT, release_branch:8.4, prefix:, end_time:Mon, 22 Aug 2022 17:06:07 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-7f4eb04b, build_duration_seconds:17406]
=> [automation] update elastic stack version for testing 8.4.0-7f4eb04b

testing/environments/snapshot.yml
[start_time:Tue, 23 Aug 2022 00:15:33 GMT, release_branch:8.3, prefix:, end_time:Tue, 23 Aug 2022 04:46:48 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-45336fec, build_duration_seconds:16275]
=> [automation] update elastic stack version for testing 8.3.4-45336fec

testing/environments/snapshot.yml
[start_time:Mon, 22 Aug 2022 12:16:45 GMT, release_branch:master, prefix:, end_time:Mon, 22 Aug 2022 17:41:17 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-dd6f2bb0, build_duration_seconds:19472]
=> [automation] update elastic stack version for testing 8.5.0-dd6f2bb0

testing/environments/snapshot.yml
[start_time:Tue, 23 Aug 2022 12:16:12 GMT, release_branch:8.4, prefix:, end_time:Tue, 23 Aug 2022 18:23:50 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-fa661330, build_duration_seconds:22058]
=> [automation] update elastic stack version for testing 8.4.0-fa661330

testing/environments/snapshot.yml
[start_time:Tue, 23 Aug 2022 12:17:54 GMT, release_branch:master, prefix:, end_time:Tue, 23 Aug 2022 18:36:47 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-feb644de, build_duration_seconds:22733]
=> [automation] update elastic stack version for testing 8.5.0-feb644de

testing/environments/snapshot.yml
[start_time:Tue, 23 Aug 2022 12:15:44 GMT, release_branch:8.3, prefix:, end_time:Tue, 23 Aug 2022 16:47:14 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-97a7bb79, build_duration_seconds:16290]
=> [automation] update elastic stack version for testing 8.3.4-97a7bb79

internal/pkg/agent/application/actions/handlers/handler_action_application.go
Fixes action dispatching that was using ActionType instead of InputType as before
Without this fix the osquerybeat action fails with "action undefined" error, because the unit actions were using input type as the key for the lookup.
It's one line change, and there was a comment that got auto-formatted on save. Think it's convenient to have it fixed.
=> Fix action dispatching that was using ActionType instead of InputType as before

testing/environments/latest.yml
Merge only after the release of 8.4.0.
=> [Release] Update test environments for 8.4.1

testing/environments/snapshot.yml
[start_time:Wed, 24 Aug 2022 12:16:09 GMT, release_branch:master, prefix:, end_time:Wed, 24 Aug 2022 17:36:28 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-7783a03c, build_duration_seconds:19219]
=> [automation] update elastic stack version for testing 8.5.0-7783a03c

testing/environments/snapshot.yml
[start_time:Wed, 24 Aug 2022 12:21:51 GMT, release_branch:8.3, prefix:, end_time:Wed, 24 Aug 2022 16:38:44 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-5621f166, build_duration_seconds:15413]
=> [automation] update elastic stack version for testing 8.3.4-5621f166

testing/environments/snapshot.yml
[start_time:Thu, 25 Aug 2022 12:18:21 GMT, release_branch:8.4, prefix:, end_time:Thu, 25 Aug 2022 16:38:40 GMT, manifest_version:2.1.0, version:8.4.1-SNAPSHOT, branch:8.4, build_id:8.4.1-74c5d538, build_duration_seconds:15619]
=> [automation] update elastic stack version for testing 8.4.1-74c5d538

testing/environments/snapshot.yml
[start_time:Fri, 26 Aug 2022 00:16:02 GMT, release_branch:8.3, prefix:, end_time:Fri, 26 Aug 2022 04:54:20 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-22a90cba, build_duration_seconds:16698]
=> [automation] update elastic stack version for testing 8.3.4-22a90cba

testing/environments/snapshot.yml
[start_time:Thu, 25 Aug 2022 12:15:45 GMT, release_branch:master, prefix:, end_time:Thu, 25 Aug 2022 18:17:20 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-17b8a62d, build_duration_seconds:21695]
=> [automation] update elastic stack version for testing 8.5.0-17b8a62d

dev-tools/packaging/templates/ironbank/hardening_manifest.yaml.tmpl
This PR updates the image product name in the ironbank labels.
This is required to automate the creation of the ironbank merge requests as the ubireleaser is using this field to compute the elastic-agent artifact url. 
For example it is now trying to retrieve https://artifacts.elastic.co/downloads/beats/elastic-agent-8.4.0-linux-x86_64.tar.gz instead of https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.4.0-linux-x86_64.tar.gz
Relates to https://github.com/elastic/apm-server/pull/8959
=> update ironbank image product name

.ci/Jenkinsfile
Add _extended_ support for Windows in the CI (`windows-8`, `windows-10` and `windows-11`)
**NOTE**: `windows-2016` and `windows-2022` are the default Windows versions used for running on PRs/branches/tags.
Align with the existing support matrix in https://www.elastic.co/support/matrix
It will only run by default on merge-commits to any of the active branches/releases. Or changes in the `.ci/Jenkinsfile`
Easy to opt-in with GitHub labels, GitHub comment or manually using the Jenkins UI
=> ci: add extended support for windows

testing/environments/snapshot.yml
[start_time:Sun, 28 Aug 2022 12:15:39 GMT, release_branch:master, prefix:, end_time:Sun, 28 Aug 2022 17:38:38 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-9aed3b11, build_duration_seconds:19379]
=> [automation] update elastic stack version for testing 8.5.0-9aed3b11

internal/pkg/agent/application/application.go, internal/pkg/agent/application/coordinator/coordinator.go, internal/pkg/agent/application/fleet_server_bootstrap.go, internal/pkg/agent/application/fleet_server_bootstrap_test.go, internal/pkg/agent/application/managed_mode.go, internal/pkg/agent/cmd/run.go, internal/pkg/testutils/testutils.go, pkg/component/component_test.go, pkg/component/runtime/manager.go, pkg/component/runtime/manager_test.go, pkg/component/runtime/runtime.go, pkg/component/runtime/runtime_comm.go, pkg/component/runtime/state.go, specs/fleet-server.spec.yml
Fixes Fleet Server bootstrap process to work with the v2 architecture. Includes fix for #995 an issue during my testing.
Path to v2 architecture.
- Closes #995
=> Fix bootstrapping a Fleet Server with v2.

testing/environments/snapshot.yml
[start_time:Mon, 29 Aug 2022 12:15:48 GMT, release_branch:8.4, prefix:, end_time:Mon, 29 Aug 2022 16:57:06 GMT, manifest_version:2.1.0, version:8.4.1-SNAPSHOT, branch:8.4, build_id:8.4.1-b72ec52c, build_duration_seconds:16878]
=> [automation] update elastic stack version for testing 8.4.1-b72ec52c

magefile.go
Changes glob patter used during build to ignore all files in the drop path which don't include version number in the name
Proper build
without this all files are considered which creates a version conflics
=> Query just related files on build

testing/environments/snapshot.yml
[start_time:Tue, 30 Aug 2022 12:16:13 GMT, release_branch:master, prefix:, end_time:Tue, 30 Aug 2022 17:32:20 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-fedc3e60, build_duration_seconds:18967]
=> [automation] update elastic stack version for testing 8.5.0-fedc3e60

testing/environments/latest.yml
Merge only after the release of 8.4.1.
=> [Release] Update test environments for 8.4.2

magefile.go
While experimenting with the V2 branch I noticed when using AGENT_DROP_PATH that the `os.Rename` call in this diff would fail on my M1 Mac if the target directory for the renamed file didn't exist. This fixes that build error.
The `os.Rename` documentation says "OS-specific restrictions may apply when oldpath and newpath are in different directories" without specifying what they are.
=> Create the archive path if it doesn't already exist

testing/environments/snapshot.yml
[start_time:Wed, 31 Aug 2022 21:50:45 GMT, release_branch:8.4, prefix:, end_time:Thu, 1 Sep 2022 04:12:18 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-30e0a703, build_duration_seconds:22893]
=> [automation] update elastic stack version for testing 8.4.2-30e0a703

testing/environments/snapshot.yml
[start_time:Wed, 31 Aug 2022 14:16:09 GMT, release_branch:master, prefix:, end_time:Wed, 31 Aug 2022 19:59:26 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-b5001a6d, build_duration_seconds:20597]
=> [automation] update elastic stack version for testing 8.5.0-b5001a6d

testing/environments/snapshot.yml
[start_time:Thu, 1 Sep 2022 12:15:39 GMT, release_branch:8.4, prefix:, end_time:Thu, 1 Sep 2022 17:55:24 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-48cedf17, build_duration_seconds:20385]
=> [automation] update elastic stack version for testing 8.4.2-48cedf17

testing/environments/snapshot.yml
[start_time:Sun, 4 Sep 2022 12:15:33 GMT, release_branch:master, prefix:, end_time:Sun, 4 Sep 2022 18:22:39 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-1bd77fc1, build_duration_seconds:22026]
=> [automation] update elastic stack version for testing 8.5.0-1bd77fc1

testing/environments/snapshot.yml
[start_time:Mon, 5 Sep 2022 12:15:52 GMT, release_branch:master, prefix:, end_time:Mon, 5 Sep 2022 20:01:59 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-167dfc80, build_duration_seconds:27967]
=> [automation] update elastic stack version for testing 8.5.0-167dfc80

testing/environments/snapshot.yml
[start_time:Tue, 6 Sep 2022 12:16:15 GMT, release_branch:8.4, prefix:, end_time:Tue, 6 Sep 2022 17:44:35 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-b244ddfa, build_duration_seconds:19700]
=> [automation] update elastic stack version for testing 8.4.2-b244ddfa

testing/environments/snapshot.yml
[start_time:Tue, 6 Sep 2022 12:18:14 GMT, release_branch:master, prefix:, end_time:Tue, 6 Sep 2022 18:55:27 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-6b7dda2d, build_duration_seconds:23833]
=> [automation] update elastic stack version for testing 8.5.0-6b7dda2d

magefile.go
Fixed docker build when it failed on non existing components path
Blocking https://github.com/elastic/cloudbeat/pull/364#issuecomment-1236649141
cc @cmacknz
=> fixed docker build

testing/environments/snapshot.yml
[start_time:Wed, 7 Sep 2022 12:16:13 GMT, release_branch:master, prefix:, end_time:Wed, 7 Sep 2022 17:38:55 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-4140365c, build_duration_seconds:19362]
=> [automation] update elastic stack version for testing 8.5.0-4140365c

internal/pkg/agent/cmd/upgrade.go
Remove experimental warning log in upgrade command: `The upgrade process of Elastic Agent is currently EXPERIMENTAL and should not be used in production`
We GA'd this feature in 8.3.0 but didn't remove the log warning and it's confusing users.
=> Remove experimental warning log in upgrade command

testing/environments/snapshot.yml
[start_time:Thu, 8 Sep 2022 12:15:56 GMT, release_branch:8.4, prefix:, end_time:Thu, 8 Sep 2022 17:53:42 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-7c2154f4, build_duration_seconds:20266]
=> [automation] update elastic stack version for testing 8.4.2-7c2154f4

testing/environments/snapshot.yml
[start_time:Sun, 11 Sep 2022 00:15:47 GMT, release_branch:master, prefix:, end_time:Sun, 11 Sep 2022 06:16:32 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-589a4a10, build_duration_seconds:21645]
=> [automation] update elastic stack version for testing 8.5.0-589a4a10

internal/pkg/agent/application/gateway/fleet/fleet_gateway.go, internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
As per discussion on #1148 
When agent experiences connectivity issues on checkin it saves `Unhealthy` state but it does not report it. 
Offline is computed on kibana/fleet side and it does not make sense for us to report offline as we don't have ability to send the result.
At the point when agent is successful with checkin, `Unhealthy` state for gateway is not up to date anymore as connectivity was just restored. Therefore we don't report `Unhealthy` on connectivity issues so we don;t end up reporting `Unhealthy` for healthy agent as `Unhealthy` is historic state. 
We still log it as error so we know something's wrong.
We still use Unhealthy for other issues with gateway as dispatching config.
Avoid confusion with reported states
=> Avoid reporting `Unhealthy` on fleet connectivity issues

.ci/Jenkinsfile
Enable MacOS m1 stage
* Be able to trigger through github comments:
* `run extended m1` or github label `ci:extended-m1`
Test on M1
=> ci: enable MacOS M1 stages

testing/environments/snapshot.yml
[start_time:Mon, 12 Sep 2022 00:15:39 GMT, release_branch:master, prefix:, end_time:Mon, 12 Sep 2022 13:52:02 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-37418cf3, build_duration_seconds:48983]
=> [automation] update elastic stack version for testing 8.5.0-37418cf3

testing/environments/snapshot.yml
[start_time:Mon, 12 Sep 2022 12:16:31 GMT, release_branch:8.4, prefix:, end_time:Mon, 12 Sep 2022 19:04:16 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-fda47f6e, build_duration_seconds:24465]
=> [automation] update elastic stack version for testing 8.4.2-fda47f6e

.ci/Jenkinsfile
Run the `e2e-testing` stage as the last stage in the CI pipeline
e2e-testing are recurrently failing hence no further stages are executed. This will ensure other stages can be executed.
=> ci: run e2e-testing at the end

.ci/Jenkinsfile, .github/workflows/macos.yml
Use GitHub actions for the MacOS specific build/testing
Orka workers are causing some troubles in the last few days, already reported to the System owners, meanwhile let's avoid CI disruptions by using the SaaS provided by GitHub actions
=> ci: move macos to github actions

testing/environments/snapshot.yml
[start_time:Wed, 14 Sep 2022 00:16:00 GMT, release_branch:8.4, prefix:, end_time:Wed, 14 Sep 2022 04:59:09 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-4457f478, build_duration_seconds:16989]
=> [automation] update elastic stack version for testing 8.4.2-4457f478

testing/environments/snapshot.yml
[start_time:Tue, 13 Sep 2022 12:16:13 GMT, release_branch:master, prefix:, end_time:Tue, 13 Sep 2022 22:10:24 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-fcf3d4c2, build_duration_seconds:35651]
=> [automation] update elastic stack version for testing 8.5.0-fcf3d4c2

deploy/kubernetes/Makefile
Fixing bug for https://github.com/elastic/kibana/pull/140649#issuecomment-1245878070
To remove unecessary noise 
-
=> Fixing condition for PR creation

.ci/Jenkinsfile
Set the environment variable earlier
`withMageEnv` calls `withGoEnv` and it does use [goDefaultVersion](https://github.com/elastic/apm-pipeline-library/blob/main/vars/goDefaultVersion.groovy) but for some reason it does not use the `.go-version` file but the default hardcoded version in https://github.com/elastic/apm-pipeline-library/blob/54b4c9b43747d5a0c58bb8605f9f0c0d2d6510d5/vars/goDefaultVersion.groovy#L41
=> ci: force GO_VERSION

internal/pkg/agent/vault/vault_darwin.c
Cleans up tabs to whitespaces indentation in darwin_vault.c
Just stumbled upon this while browsing some of my old code. Consistent indentation is importante.
=> Fix whitespaces in vault_darwin.c

testing/environments/snapshot.yml
[start_time:Thu, 15 Sep 2022 00:16:21 GMT, release_branch:8.4, prefix:, end_time:Thu, 15 Sep 2022 04:55:32 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-36096067, build_duration_seconds:16751]
=> [automation] update elastic stack version for testing 8.4.2-36096067

testing/environments/snapshot.yml
[start_time:Sun, 18 Sep 2022 00:15:56 GMT, release_branch:8.4, prefix:, end_time:Sun, 18 Sep 2022 04:51:52 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-b98b12f1, build_duration_seconds:16556]
=> [automation] update elastic stack version for testing 8.4.2-b98b12f1

deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
Part 2 of https://github.com/elastic/elastic-agent/issues/662. See https://github.com/elastic/package-storage-infra/issues/163#issuecomment-1196509971 from more information.
So as to support https://github.com/elastic/elastic-agent/issues/613. 
<details>
<summary>elastic-agent-kubernetes.yml</summary>
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: agent-node-datastreams
namespace: kube-system
labels:
k8s-app: elastic-agent-standalone
data:
agent.yml: |-
outputs:
default:
allow_older_versions: true
type: elasticsearch
hosts:
- >-
${ES_HOST}
username: ${ES_USERNAME}
password: ${ES_PASSWORD}
ssl.verification_mode: none
agent:
monitoring:
enabled: true
logs: true
metrics: true
providers.kubernetes:
node: ${NODE_NAME}
scope: node
#Uncomment to enable hints' support …
```
=> Update k8s manifests to leverage hints

CHANGELOG.next.asciidoc
Go 1.18 breaks compatibility with SHA-1 signed certificates. Document this in the agent changelog.
=> Add Go 1.18 upgrade to breaking changes section.

testing/environments/latest.yml
Merge only after the release of 8.4.2.
=> [Release] Update test environments for 8.4.3

testing/environments/snapshot.yml
[start_time:Tue, 20 Sep 2022 12:16:54 GMT, release_branch:master, prefix:, end_time:Tue, 20 Sep 2022 18:40:35 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-7dc445a0, build_duration_seconds:23021]
=> [automation] update elastic stack version for testing 8.5.0-7dc445a0

testing/environments/snapshot.yml
[start_time:Thu, 22 Sep 2022 00:16:04 GMT, release_branch:8.4, prefix:, end_time:Thu, 22 Sep 2022 04:44:16 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-72a0900d, build_duration_seconds:16092]
=> [automation] update elastic stack version for testing 8.4.3-72a0900d

testing/environments/snapshot.yml
[start_time:Fri, 23 Sep 2022 00:15:40 GMT, release_branch:8.4, prefix:, end_time:Fri, 23 Sep 2022 04:56:22 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-24191b6e, build_duration_seconds:16842]
=> [automation] update elastic stack version for testing 8.4.3-24191b6e

internal/pkg/agent/cmd/container.go
This fixes formatting of errors resulting from non-error states but non-accepted HTTP status codes.
The failure conditions allow nil errors to result in an error being formatted, when formatting due to a non-accepted HTTP status code and a nil error, omit the error.
Reduces log syntax noise.
-
=> internal/pkg/agent/cmd: don't format error message with nil errors

testing/environments/snapshot.yml
[start_time:Sun, 25 Sep 2022 00:18:09 GMT, release_branch:8.5, prefix:, end_time:Sun, 25 Sep 2022 05:49:46 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-d04a8a8e, build_duration_seconds:19897]
=> [automation] update elastic stack version for testing 8.5.0-d04a8a8e

testing/environments/snapshot.yml
[start_time:Sun, 25 Sep 2022 12:16:28 GMT, release_branch:8.4, prefix:, end_time:Sun, 25 Sep 2022 17:07:38 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-f2e1ac46, build_duration_seconds:17470]
=> [automation] update elastic stack version for testing 8.4.3-f2e1ac46

testing/environments/snapshot.yml
[start_time:Sun, 25 Sep 2022 00:16:20 GMT, release_branch:master, prefix:, end_time:Sun, 25 Sep 2022 04:42:27 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-21651da3, build_duration_seconds:15967]
=> [automation] update elastic stack version for testing 8.6.0-21651da3

CHANGELOG.next.asciidoc, internal/pkg/agent/operation/operator.go, internal/pkg/agent/operation/operator_test.go, internal/pkg/artifact/config.go
During reload it happens that download/verify components reset source URI despite there's one provided by fleet. this is because fleet uses different keyword and components are not checking it. 
This PR adds fleet way as prefered value with traditional one as a fallback in case of reload.
Applying of a policy fails in case of missing beat and custom URI. 
Workaround: restart agent or download artifacts manually
Why restart works is that components are created initially with correct values.
- set custom source URI in fleet UI
- add packet capturing integration to a policy
- install agent
- install is Green and artifact downloaded from correct source (check logs)
- remove integration and clean download/install directories
- add integration again
- install is Green and artifact downloaded …
=> Fixed: source uri reload for download/verify components

CHANGELOG.next.asciidoc, internal/pkg/agent/application/gateway/fleet/fleet_gateway.go, internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go, internal/pkg/agent/application/gateway/fleet/noop_status_controller_test.go, internal/pkg/core/status/handler.go, internal/pkg/core/status/reporter.go, internal/pkg/testutils/status_reporter.go
Add a local reporter map to the status controller. These reporters are not used when updating status with fleet-server, they are only used to gather local state information - specifically if the agent is degraded because checkin with fleet-server has failed. Local reporters are used to generate a separate status. This status is used in the liveness endpoint.
This bypasses the bug (#1148) that was introduced with the liveness endpoint (#569) where the agent could checkin (to fleet-server) with a degraded status because a previous checkin failed, causing the agent to appear as unhealthy in the fleet-server when it checked in successfully. 
- Closes #1157
=> Expand status reporter/controller interfaces to allow local reporters

CHANGELOG.next.asciidoc, internal/pkg/agent/application/pipeline/actions/handlers/handler_action_upgrade.go, internal/pkg/agent/application/upgrade/cleanup.go, internal/pkg/agent/application/upgrade/cleanup_test.go, internal/pkg/agent/application/upgrade/rollback.go, internal/pkg/agent/application/upgrade/step_download.go, internal/pkg/agent/application/upgrade/step_mark.go, internal/pkg/agent/application/upgrade/step_relink.go, internal/pkg/agent/application/upgrade/step_unpack.go, internal/pkg/agent/application/upgrade/upgrade.go, internal/pkg/agent/cmd/watch.go, internal/pkg/agent/control/server/server.go
Improve our logging around agent upgrades, following the suggestions from https://github.com/elastic/elastic-agent/issues/1253.
The biggest issue I noticed was that we log action failures at the debug label by default, which includes the upgrade action. Upgrade action failures are infrequent and important enough that I switched to always logging them at error level. I think this will solve most of the problems, but I also followed through and added some additional logging in interesting places.
- Closes https://github.com/elastic/elastic-agent/issues/1253
Sample logs from a standalone upgrade, which always fails attempting to execute the upgrade watcher for reasons that aren't clear to me yet: `"fork/exec elastic-agent-8.5.0-SNAPSHOT-darwin-aarch64/data/elastic-agent-82ad1e/elastic-agent: …
=> Improve logging for agent upgrades.

testing/environments/snapshot.yml
[start_time:Mon, 26 Sep 2022 00:18:40 GMT, release_branch:8.4, prefix:, end_time:Mon, 26 Sep 2022 06:27:02 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-3f1f47b9, build_duration_seconds:22102]
=> [automation] update elastic stack version for testing 8.4.3-3f1f47b9

testing/environments/snapshot.yml
[start_time:Mon, 26 Sep 2022 12:16:45 GMT, release_branch:master, prefix:, end_time:Mon, 26 Sep 2022 16:24:21 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-326f84b0, build_duration_seconds:14856]
=> [automation] update elastic stack version for testing 8.6.0-326f84b0

testing/environments/snapshot.yml
[start_time:Mon, 26 Sep 2022 00:16:11 GMT, release_branch:8.5, prefix:, end_time:Mon, 26 Sep 2022 05:43:31 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-d6bc1fd7, build_duration_seconds:19640]
=> [automation] update elastic stack version for testing 8.5.0-d6bc1fd7

testing/environments/snapshot.yml
[start_time:Tue, 27 Sep 2022 12:15:32 GMT, release_branch:8.4, prefix:, end_time:Tue, 27 Sep 2022 17:14:03 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-e8645b30, build_duration_seconds:17911]
=> [automation] update elastic stack version for testing 8.4.3-e8645b30

testing/environments/snapshot.yml
[start_time:Tue, 27 Sep 2022 00:18:44 GMT, release_branch:8.5, prefix:, end_time:Tue, 27 Sep 2022 06:11:34 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-a415b54b, build_duration_seconds:21170]
=> [automation] update elastic stack version for testing 8.5.0-a415b54b

testing/environments/snapshot.yml
[start_time:Tue, 27 Sep 2022 12:16:05 GMT, release_branch:master, prefix:, end_time:Tue, 27 Sep 2022 17:13:08 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-df00693f, build_duration_seconds:17823]
=> [automation] update elastic stack version for testing 8.6.0-df00693f

CHANGELOG.next.asciidoc, internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
Adds an additional log message when a checkin with Fleet Server succeeds after previous failed attempts.
Helps users understand when the system recovered after failures
- Related to https://github.com/elastic/elastic-agent/pull/1218
=> Add success log message after previous checkin failures

internal/pkg/agent/cmd/inspect.go, internal/pkg/agent/install/uninstall.go, internal/pkg/agent/vars/vars.go
Fixes Elastic Agent install, to be precise the uninstall.
The uninstall was blocking at running composable controller @ 
https://github.com/elastic/elastic-agent/blob/feature-arch-v2/internal/pkg/agent/install/uninstall.go#L204
due to the V2 controller change to the watch channel instead of callbacks and in this particular place nothing was listening to these channels.
```
goroutine 1 [select]:
github.com/elastic/elastic-agent/internal/pkg/composable.(*controller).Run(0xc00089a810, {0x562b52028480, 0xc0000540c0})
/home/amaus/elastic/elastic-agent/internal/pkg/composable/controller.go:156 +0xa94
github.com/elastic/elastic-agent/internal/pkg/agent/install.applyDynamics({0x562b52028480, 0xc0000540c0}, 0xc00069f910, 0xc000834d50)
/home/amaus/elastic/elastic-agent/internal/pkg/agent/install/uni …
```
=> Fix [V2]: Elastic Agent Install is broken.

testing/environments/snapshot.yml
[start_time:Wed, 28 Sep 2022 12:16:00 GMT, release_branch:8.4, prefix:, end_time:Wed, 28 Sep 2022 18:05:03 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-d0e42d08, build_duration_seconds:20943]
=> [automation] update elastic stack version for testing 8.4.3-d0e42d08

testing/environments/snapshot.yml
[start_time:Wed, 28 Sep 2022 13:23:03 GMT, release_branch:master, prefix:, end_time:Wed, 28 Sep 2022 18:07:55 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-a2f4f140, build_duration_seconds:17092]
=> [automation] update elastic stack version for testing 8.6.0-a2f4f140

testing/environments/snapshot.yml
[start_time:Wed, 28 Sep 2022 09:37:58 GMT, release_branch:8.5, prefix:, end_time:Wed, 28 Sep 2022 14:41:10 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-dbc138b6, build_duration_seconds:18192]
=> [automation] update elastic stack version for testing 8.5.0-dbc138b6

CHANGELOG.next.asciidoc, internal/pkg/agent/application/gateway/fleet/fleet_gateway.go, internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go, internal/pkg/fleetapi/checkin_cmd.go
Added Message field to CheckinRequest
- Requirement for https://github.com/elastic/elastic-agent/issues/1151
=> Added status message to CheckinRequest

internal/pkg/core/monitoring/beats/sidecar_monitor.go
When enpoint is published over a network or npipe `monitorDrop` returns `""` 
In this valid scenario agent fails and reports unhealthy when it tries to create directory at this invalid path.
Fixes: #1361 
Fix just guards agains empty values and if drop is empty it does not proceed with a setup
Monitoring on Windows
=> Fix failures when using npipe monitoring endpoints

testing/environments/snapshot.yml
[start_time:Thu, 29 Sep 2022 00:19:36 GMT, release_branch:8.4, prefix:, end_time:Thu, 29 Sep 2022 06:25:42 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-0900b129, build_duration_seconds:21966]
=> [automation] update elastic stack version for testing 8.4.3-0900b129

testing/environments/snapshot.yml
[start_time:Thu, 29 Sep 2022 00:15:42 GMT, release_branch:8.5, prefix:, end_time:Thu, 29 Sep 2022 05:36:58 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-b22c068f, build_duration_seconds:19276]
=> [automation] update elastic stack version for testing 8.5.0-b22c068f

testing/environments/snapshot.yml
[start_time:Fri, 30 Sep 2022 00:15:45 GMT, release_branch:master, prefix:, end_time:Fri, 30 Sep 2022 04:40:25 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-158a13db, build_duration_seconds:15880]
=> [automation] update elastic stack version for testing 8.6.0-158a13db

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
Changes made on a Kubernetes node to files like `/etc/passwd` using Linux tools like `useradd` are not reflected in the mounted file on the Agent, because the tool replaces the file instead of changing it in-place.
Mounting the parent directory solves this problem.
Without this change, in some scenarios it is possible for users of the Cloud Security Posture integration on Kibana to be shown outdated/incorrect information.
Use the new manifest to install and run an Agent, and ensure that it has access to the node's `/etc` directory via the mount at `/hostfs/etc`.
Closes https://github.com/elastic/cloudbeat/issues/235
=> Mount /etc directory in Kubernetes DaemonSet manifests.

testing/environments/snapshot.yml
[start_time:Mon, 3 Oct 2022 12:16:03 GMT, release_branch:8.4, prefix:, end_time:Mon, 3 Oct 2022 17:19:22 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-5e0dd488, build_duration_seconds:18199]
=> [automation] update elastic stack version for testing 8.4.3-5e0dd488

testing/environments/snapshot.yml
[start_time:Mon, 3 Oct 2022 12:15:54 GMT, release_branch:master, prefix:, end_time:Mon, 3 Oct 2022 17:21:48 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-aea1c645, build_duration_seconds:18354]
=> [automation] update elastic stack version for testing 8.6.0-aea1c645

testing/environments/snapshot.yml
[start_time:Mon, 3 Oct 2022 16:39:13 GMT, release_branch:8.5, prefix:, end_time:Mon, 3 Oct 2022 21:30:10 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-49b2dce3, build_duration_seconds:17457]
=> [automation] update elastic stack version for testing 8.5.0-49b2dce3

testing/environments/snapshot.yml
[start_time:Tue, 4 Oct 2022 12:15:44 GMT, release_branch:8.4, prefix:, end_time:Tue, 4 Oct 2022 17:28:31 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-ff95b7c5, build_duration_seconds:18767]
=> [automation] update elastic stack version for testing 8.4.3-ff95b7c5

testing/environments/snapshot.yml
[start_time:Wed, 5 Oct 2022 00:15:55 GMT, release_branch:master, prefix:, end_time:Wed, 5 Oct 2022 04:46:47 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-0fca2953, build_duration_seconds:16252]
=> [automation] update elastic stack version for testing 8.6.0-0fca2953

testing/environments/snapshot.yml
[start_time:Thu, 6 Oct 2022 00:27:13 GMT, release_branch:master, prefix:, end_time:Thu, 6 Oct 2022 04:59:12 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-e4c15f15, build_duration_seconds:16319]
=> [automation] update elastic stack version for testing 8.6.0-e4c15f15

testing/environments/snapshot.yml
[start_time:Wed, 5 Oct 2022 00:15:52 GMT, release_branch:8.5, prefix:, end_time:Wed, 5 Oct 2022 06:28:22 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-58624073, build_duration_seconds:22350]
=> [automation] update elastic stack version for testing 8.5.0-58624073

changelog/fragments/1664989867-fix-docker-provider-processors.yaml, internal/pkg/composable/providers/docker/docker.go, internal/pkg/composable/providers/docker/docker_test.go
The Docker provider was using a wrong key when defining the `add_fields` processor, this causes Filebeat not to start the input and stay on a unhealthy state. This processor seems to be defined every time a variable like `${docker}` is used on a input configuration.
This commit fixes it.
It fixes a bug on Docker auto discovery provider
1. Make sure you have Docker installed and running
1. Deploy Elastic Stack
1. Start a container that will generate logs (e.g: `docker run --rm --name flog -d mingrammer/flog /bin/flog -s1 -d1 -l -f rfc3164`).
2. Create a standalone Elastic-Agent policy [using Kibana as suggested in the documentation](https://www.elastic.co/guide/en/fleet/current/create-standalone-agent-policy.html#create-standalone-agent-policy).
3. On this policy add the "Custom Logs …
=> Fix docker provider add_fields processors

testing/environments/snapshot.yml
[start_time:Thu, 6 Oct 2022 12:15:40 GMT, release_branch:8.4, prefix:, end_time:Thu, 6 Oct 2022 17:02:10 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-ac374c4b, build_duration_seconds:17190]
=> [automation] update elastic stack version for testing 8.4.4-ac374c4b

testing/environments/snapshot.yml
[start_time:Thu, 6 Oct 2022 12:19:07 GMT, release_branch:master, prefix:, end_time:Thu, 6 Oct 2022 17:32:07 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-d939cfde, build_duration_seconds:18780]
=> [automation] update elastic stack version for testing 8.6.0-d939cfde

testing/environments/snapshot.yml
[start_time:Thu, 6 Oct 2022 17:18:51 GMT, release_branch:8.5, prefix:, end_time:Thu, 6 Oct 2022 23:40:40 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-c52257ee, build_duration_seconds:22909]
=> [automation] update elastic stack version for testing 8.5.0-c52257ee

testing/environments/snapshot.yml
[start_time:Sun, 9 Oct 2022 12:16:02 GMT, release_branch:8.4, prefix:, end_time:Sun, 9 Oct 2022 17:16:03 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-17ce02d0, build_duration_seconds:18001]
=> [automation] update elastic stack version for testing 8.4.4-17ce02d0

testing/environments/snapshot.yml
[start_time:Sun, 9 Oct 2022 00:15:56 GMT, release_branch:8.5, prefix:, end_time:Sun, 9 Oct 2022 06:04:00 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-7d416dc4, build_duration_seconds:20884]
=> [automation] update elastic stack version for testing 8.5.0-7d416dc4

testing/environments/snapshot.yml
[start_time:Sun, 9 Oct 2022 00:16:22 GMT, release_branch:master, prefix:, end_time:Sun, 9 Oct 2022 05:40:47 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-7c9f25a9, build_duration_seconds:19465]
=> [automation] update elastic stack version for testing 8.6.0-7c9f25a9

internal/pkg/composable/providers/kubernetes/hints.go, internal/pkg/composable/providers/kubernetes/hints_test.go
This PR improves the way that hints mappings are emitted:
1. If no data_streams are specified enable the integration level so as the defaults to be enabled.
2. If data_streams are specified only those will be enabled.
Related to https://github.com/elastic/package-storage-infra/pull/264
With the given configuration:
```yml
providers:
kubernetes:
kube_config: /home/chrismark/.kube/config
node: "kind-control-plane"
hints.enabled: true
#include_annotations: ["foo"]
inputs:
- name: redis/metrics-redis
type: redis/metrics
streams:
- condition: ${kubernetes.hints.redis.info.enabled} == true or ${kubernetes.hints.redis.enabled} == true
data_stream:
dataset: redis.info
type: metrics
hosts:
- ${kubernetes.hints.redis.info.host|kubernetes.hints.redis.host|'127.0.0.1:6379'} …
```
=> Enable integration only when datastreams are not defined

CHANGELOG.next.asciidoc, internal/pkg/composable/providers/kubernetes/pod.go
After discussions in https://github.com/elastic/elastic-agent/issues/1284 there is an inconsistency when it comes to how kubernetes pod labels and annotations are handled in template based autodiscovery.
As stated in https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-autodiscover.html annotations can be used for condition matching in templates exactly as set inside the pod.
metricbeat example (same is for elastic-agent)
```
providers:
- type: kubernetes
include_annotations: ["prometheus.io.scrape"]
templates:
- condition:
contains:
kubernetes.annotations.prometheus.io/scrape: "true"
config:
- module: prometheus
metricsets: ["collector"]
hosts: "${data.host}:${data.port}"
```
For labels the situation is different. Labels are getting devoted first (when needed) and then …
=> Add not dedoted k8s pod labels in autodiscover provider to be used for templating, exactly like annotations

testing/environments/snapshot.yml
[start_time:Mon, 10 Oct 2022 12:16:20 GMT, release_branch:8.4, prefix:, end_time:Mon, 10 Oct 2022 17:57:12 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-221d2ff4, build_duration_seconds:20452]
=> [automation] update elastic stack version for testing 8.4.4-221d2ff4

testing/environments/snapshot.yml
[start_time:Mon, 10 Oct 2022 00:15:23 GMT, release_branch:8.5, prefix:, end_time:Mon, 10 Oct 2022 05:23:06 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-4f4df9f4, build_duration_seconds:18463]
=> [automation] update elastic stack version for testing 8.5.0-4f4df9f4

testing/environments/snapshot.yml
[start_time:Mon, 10 Oct 2022 18:58:59 GMT, release_branch:master, prefix:, end_time:Mon, 10 Oct 2022 23:29:50 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-c49fac70, build_duration_seconds:16251]
=> [automation] update elastic stack version for testing 8.6.0-c49fac70

CHANGELOG.next.asciidoc, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-role.yaml
Add get, list, watch permissions for storageclasses in kubernetes managed agent manifest.
Without this addition elastic agent does not have the correct permissions to list and watch kubernetes resource `storageclass`.
Just deploy elastic-agent managed in a kubernetes cluster and confirm that storage classes are being monitored.
=> Add storageclass permissions in agent clusterrole

testing/environments/snapshot.yml
[start_time:Wed, 12 Oct 2022 00:16:08 GMT, release_branch:8.4, prefix:, end_time:Wed, 12 Oct 2022 04:58:52 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-5fbb5bd0, build_duration_seconds:16964]
=> [automation] update elastic stack version for testing 8.4.4-5fbb5bd0

testing/environments/snapshot.yml
[start_time:Tue, 11 Oct 2022 00:20:39 GMT, release_branch:master, prefix:, end_time:Tue, 11 Oct 2022 06:28:26 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-5a8d757d, build_duration_seconds:22067]
=> [automation] update elastic stack version for testing 8.6.0-5a8d757d

testing/environments/snapshot.yml
[start_time:Tue, 11 Oct 2022 00:22:09 GMT, release_branch:8.5, prefix:, end_time:Tue, 11 Oct 2022 07:37:10 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-09886b6e, build_duration_seconds:26101]
=> [automation] update elastic stack version for testing 8.5.0-09886b6e

CHANGELOG.next.asciidoc, changelog/fragments/1665517984-improve-checkin-error-logging.yaml, internal/pkg/agent/application/gateway/fleet/fleet_gateway.go, internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go, internal/pkg/core/backoff/backoff.go, internal/pkg/core/backoff/backoff_test.go, internal/pkg/core/backoff/equal_jitter.go, internal/pkg/core/backoff/exponential.go, internal/pkg/fleetapi/checkin_cmd.go, internal/pkg/fleetapi/checkin_cmd_test.go
Adds some minor improvements to the log messages used around Fleet checkins. When a checkin fails, we now log the request duration and how long we'll wait until the next retry. We also log the first two failures at the warning level with a note that the problem may be intermittent and upgrade to an error after 2 repeated failures.
I wanted to do something similar for all of our uses of the fleet API but I ran out of time, and I want what I have now to make it into 8.5. The checkin request is by far the most important request we make.
- Closes https://github.com/elastic/elastic-agent/issues/1154
=> Improve logging around agent checkins.

testing/environments/snapshot.yml
[start_time:Wed, 12 Oct 2022 12:15:59 GMT, release_branch:8.4, prefix:, end_time:Wed, 12 Oct 2022 17:17:33 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-1129f33b, build_duration_seconds:18094]
=> [automation] update elastic stack version for testing 8.4.4-1129f33b

testing/environments/snapshot.yml
[start_time:Wed, 12 Oct 2022 12:16:08 GMT, release_branch:master, prefix:, end_time:Wed, 12 Oct 2022 16:34:46 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-40086bc7, build_duration_seconds:15518]
=> [automation] update elastic stack version for testing 8.6.0-40086bc7

deploy/kubernetes/Makefile
Fixing error in makefile step `Sync k8` of job: https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp/detail/main/497/pipeline/1935
In more details tab: `make ci-clone-kibana-repository cp Makefile ./kibana cd kibana make ci-create-kubernetes-templates-pull-request`
Fails with no diffs found
Locally by running:
Step 1:
```bash
cd deploy/kubernetes
```
Step2: Make a change in one of manifests
Step3:
```bash
WITHOUTCONFIG=true make generate-k8s
./creator_k8s_manifest.sh .
make ci-clone-kibana-repository
cp elastic_agent_manifest.ts  kibana/x-pack/plugins/fleet/server/services/
cp Makefile ./kibana
cd kibana
DRY_RUN=TRUE make ci-create-kubernetes-templates-pull-request
```
Outcome:
```bash
DRY_RUN=TRUE make ci-create-kubernetes-templates-pull-request
echo 1 …
```
=> Fixing makefile check

.github/workflows/changelog.yml
Enable validation for PRs with the changelog fragment approach
Use GitHub actions for this set of actions so the main pipeline will work as usual.
Similarly done in https://github.com/elastic/elastic-agent-changelog-tool/blob/ddafc5a717d1a9c3ed2651020bddffbb810846a2/.github/workflows/pull-request.yaml#L94-L114
=> action: validate changelog fragment

deploy/kubernetes/Makefile, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
We need to use branch version and release version in the archive link we use to download the k8s templates. 
Correct: `wget -O - https://github.com/elastic/elastic-agent/archive/8.5.tar.gz`
Wrong: `wget -O - https://github.com/elastic/elastic-agent/archive/8.5.0.tar.gz`
=> Fix k8s template link versioning

testing/environments/snapshot.yml
[start_time:Thu, 13 Oct 2022 12:16:41 GMT, release_branch:8.4, prefix:, end_time:Thu, 13 Oct 2022 17:40:37 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-fdf1902b, build_duration_seconds:19436]
=> [automation] update elastic stack version for testing 8.4.4-fdf1902b

testing/environments/snapshot.yml
[start_time:Thu, 13 Oct 2022 15:19:07 GMT, release_branch:master, prefix:, end_time:Thu, 13 Oct 2022 19:29:42 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-233dc5d4, build_duration_seconds:15035]
=> [automation] update elastic stack version for testing 8.6.0-233dc5d4

testing/environments/snapshot.yml
[start_time:Thu, 13 Oct 2022 00:18:58 GMT, release_branch:8.5, prefix:, end_time:Thu, 13 Oct 2022 05:33:07 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-976bca07, build_duration_seconds:18849]
=> [automation] update elastic stack version for testing 8.5.0-976bca07

testing/environments/snapshot.yml
[start_time:Sun, 16 Oct 2022 12:16:14 GMT, release_branch:8.4, prefix:, end_time:Sun, 16 Oct 2022 17:02:55 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-2db0c963, build_duration_seconds:17201]
=> [automation] update elastic stack version for testing 8.4.4-2db0c963

testing/environments/snapshot.yml
[start_time:Sun, 16 Oct 2022 12:15:58 GMT, release_branch:master, prefix:, end_time:Sun, 16 Oct 2022 16:04:15 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-54a302f0, build_duration_seconds:13697]
=> [automation] update elastic stack version for testing 8.6.0-54a302f0

testing/environments/snapshot.yml
[start_time:Sun, 16 Oct 2022 00:15:37 GMT, release_branch:8.5, prefix:, end_time:Sun, 16 Oct 2022 05:34:22 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-f8c98e5d, build_duration_seconds:19125]
=> [automation] update elastic stack version for testing 8.5.0-f8c98e5d

.github/workflows/golangci-lint.yml, .golangci.yml
Sync the configuration with the one used in Beats, which has disabled the majority of the least useful linters already.
=> Update the linter configuration.

changelog/fragments/1665784342-use-stack-version-npm-synthetics.yaml, dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl, dev-tools/packaging/templates/docker/Dockerfile.tmpl
Always use the `stack_release` label for `npm i`
No changelog necessary since there are no user-visible changes
This lets us ensure we've carefully reviewed and labeled the version of the `@elastic/synthetics` NPM library that's bundled in docker images
=> Elastic agent counterpart of https://github.com/elastic/beats/pull/33362

testing/environments/snapshot.yml
[start_time:Mon, 17 Oct 2022 12:16:24 GMT, release_branch:8.4, prefix:, end_time:Mon, 17 Oct 2022 17:30:17 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-93b2bfdf, build_duration_seconds:18833]
=> [automation] update elastic stack version for testing 8.4.4-93b2bfdf

testing/environments/snapshot.yml
[start_time:Mon, 17 Oct 2022 00:17:28 GMT, release_branch:8.5, prefix:, end_time:Mon, 17 Oct 2022 05:59:35 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-7c74e950, build_duration_seconds:20527]
=> [automation] update elastic stack version for testing 8.5.0-7c74e950

testing/environments/snapshot.yml
[start_time:Mon, 17 Oct 2022 12:16:19 GMT, release_branch:master, prefix:, end_time:Mon, 17 Oct 2022 16:11:30 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-cae815eb, build_duration_seconds:14111]
=> [automation] update elastic stack version for testing 8.6.0-cae815eb

testing/environments/snapshot.yml
[start_time:Tue, 18 Oct 2022 00:15:53 GMT, release_branch:8.4, prefix:, end_time:Tue, 18 Oct 2022 06:14:56 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-e97ba82f, build_duration_seconds:21543]
=> [automation] update elastic stack version for testing 8.4.4-e97ba82f

testing/environments/snapshot.yml
[start_time:Tue, 18 Oct 2022 12:20:09 GMT, release_branch:master, prefix:, end_time:Wed, 19 Oct 2022 01:59:14 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-6545f2df, build_duration_seconds:49145]
=> [automation] update elastic stack version for testing 8.6.0-6545f2df

testing/environments/snapshot.yml
[start_time:Tue, 18 Oct 2022 00:16:10 GMT, release_branch:8.5, prefix:, end_time:Tue, 18 Oct 2022 05:44:24 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-792499b4, build_duration_seconds:19694]
=> [automation] update elastic stack version for testing 8.5.0-792499b4

testing/environments/snapshot.yml
[start_time:Wed, 19 Oct 2022 12:16:02 GMT, release_branch:8.4, prefix:, end_time:Wed, 19 Oct 2022 17:48:13 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-51bbfe53, build_duration_seconds:19931]
=> [automation] update elastic stack version for testing 8.4.4-51bbfe53

testing/environments/snapshot.yml
[start_time:Wed, 19 Oct 2022 00:16:15 GMT, release_branch:8.5, prefix:, end_time:Wed, 19 Oct 2022 06:05:43 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-7e528e3e, build_duration_seconds:20968]
=> [automation] update elastic stack version for testing 8.5.0-7e528e3e

changelog/fragments/1666281194-Fix-how-multiple-Fleet-Server-hosts-are-handled.yaml, internal/pkg/agent/application/pipeline/actions/handlers/handler_action_policy_change.go, internal/pkg/fleetapi/client/client.go, internal/pkg/remote/client.go, internal/pkg/remote/client_test.go
Fix how the agent handles fleet-server hosts.
**It changes the fleet-server client to:**
- when creating a new client:
- succeed if at least one host is health
- shuffle the hosts, avoiding all the agents reacing to the same fleet-server on the first request
- makes `(remote.*Client).Send` try all the hosts before failing, returning the last error if all hosts fail
- if debug logs are enabled, `Send` will log each error as with debug level
- modifies `remopte.requestClient`:
- now `requestClient` holds its host
- remove `requestFunc`
- `(remopte.requestClient).newRequest uses the new `host` property to build the final URL for the request
Right now, when creating a new fleet API client it only verifies if one new host is reachable, therefore if the first isn't reachable, it ignore the …
=> make policy change handler try all fleet hosts before failing

testing/environments/snapshot.yml
[start_time:Thu, 20 Oct 2022 12:15:32 GMT, release_branch:8.4, prefix:, end_time:Thu, 20 Oct 2022 18:55:40 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-4edb5c6b, build_duration_seconds:24008]
=> [automation] update elastic stack version for testing 8.4.4-4edb5c6b

testing/environments/snapshot.yml
[start_time:Fri, 21 Oct 2022 00:15:47 GMT, release_branch:master, prefix:, end_time:Fri, 21 Oct 2022 04:31:51 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-baf193e8, build_duration_seconds:15364]
=> [automation] update elastic stack version for testing 8.6.0-baf193e8

testing/environments/snapshot.yml
[start_time:Thu, 20 Oct 2022 13:32:18 GMT, release_branch:8.5, prefix:, end_time:Thu, 20 Oct 2022 20:19:57 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-754ef325, build_duration_seconds:24459]
=> [automation] update elastic stack version for testing 8.5.0-754ef325

testing/environments/snapshot.yml
[start_time:Sun, 23 Oct 2022 12:16:00 GMT, release_branch:8.4, prefix:, end_time:Sun, 23 Oct 2022 18:09:57 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-9b801d60, build_duration_seconds:21237]
=> [automation] update elastic stack version for testing 8.4.4-9b801d60

testing/environments/snapshot.yml
[start_time:Sun, 23 Oct 2022 12:16:04 GMT, release_branch:master, prefix:, end_time:Sun, 23 Oct 2022 16:44:33 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-22d60ec9, build_duration_seconds:16109]
=> [automation] update elastic stack version for testing 8.6.0-22d60ec9

testing/environments/snapshot.yml
[start_time:Sat, 22 Oct 2022 00:18:19 GMT, release_branch:8.5, prefix:, end_time:Sat, 22 Oct 2022 06:25:34 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-d7b01592, build_duration_seconds:22035]
=> [automation] update elastic stack version for testing 8.5.0-d7b01592

specs/cloudbeat.spec.yml
This is part of https://github.com/elastic/cloudbeat/pull/458
The cloudbeat folks are running into an issue where they're getting a `input not supported` error when installing an integration, and I assume the issue is because the name used in the integration (`- input: cloudbeat/cis_k8s`) doesn't appear in the specfile. 
I did a quick grep through the integrations, and it appears that `cloudbeat/cis_k8s` is the only cloudbeat input type, so I think this is all we'll need to add?
We need cloudbeat to work under V2.
=> Add input name alias for cloudbeat integrations

testing/environments/snapshot.yml
[start_time:Mon, 24 Oct 2022 00:18:19 GMT, release_branch:8.4, prefix:, end_time:Mon, 24 Oct 2022 08:07:26 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-46f2f222, build_duration_seconds:28147]
=> [automation] update elastic stack version for testing 8.4.4-46f2f222

testing/environments/snapshot.yml
[start_time:Mon, 24 Oct 2022 12:15:56 GMT, release_branch:master, prefix:, end_time:Mon, 24 Oct 2022 16:17:06 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-b8b35931, build_duration_seconds:14470]
=> [automation] update elastic stack version for testing 8.6.0-b8b35931

testing/environments/snapshot.yml
[start_time:Tue, 25 Oct 2022 00:16:03 GMT, release_branch:8.5, prefix:, end_time:Tue, 25 Oct 2022 08:36:17 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-bdb74671, build_duration_seconds:30014]
=> [automation] update elastic stack version for testing 8.5.0-bdb74671

testing/environments/snapshot.yml
[start_time:Tue, 25 Oct 2022 00:15:35 GMT, release_branch:8.4, prefix:, end_time:Tue, 25 Oct 2022 06:42:27 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-1ee39d03, build_duration_seconds:23212]
=> [automation] update elastic stack version for testing 8.4.4-1ee39d03

.github/stale.yml
Purpose of this is to frequently clean up elastic agent repo
Issues will be marked as stale after 90days without activities.
Stale issues without activities for 90 days will be closed.
=> Create stale config

testing/environments/snapshot.yml
[start_time:Wed, 26 Oct 2022 15:48:54 GMT, release_branch:8.4, prefix:, end_time:Wed, 26 Oct 2022 21:02:19 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-d66e996a, build_duration_seconds:18805]
=> [automation] update elastic stack version for testing 8.4.4-d66e996a

testing/environments/snapshot.yml
[start_time:Wed, 26 Oct 2022 00:17:52 GMT, release_branch:8.5, prefix:, end_time:Wed, 26 Oct 2022 08:03:41 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-eb17cbd2, build_duration_seconds:27949]
=> [automation] update elastic stack version for testing 8.5.0-eb17cbd2

testing/environments/snapshot.yml
[start_time:Wed, 26 Oct 2022 15:48:54 GMT, release_branch:master, prefix:, end_time:Wed, 26 Oct 2022 21:14:19 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-a892f234, build_duration_seconds:19525]
=> [automation] update elastic stack version for testing 8.6.0-a892f234

NOTICE.txt, changelog/fragments/1666789812-Improve-shutdown-logs.yaml, go.mod, go.sum, internal/pkg/agent/application/pipeline/actions/handlers/handler_action_settings.go, internal/pkg/agent/application/upgrade/upgrade.go, internal/pkg/agent/cmd/common.go, internal/pkg/agent/cmd/run.go
Improve logs when handling shutdown.
Often we investigate problems which one of the symptom is the Elastic Agent or beats restarting. However often it's uncertain what is making the agent to shutdown.
Run the egant normally and try different methods to shut it down or restart it. Observe the new logs
- Closes #1358
TODO
=> Improve shutdown logs

testing/environments/snapshot.yml
[start_time:Thu, 27 Oct 2022 13:12:21 GMT, release_branch:8.4, prefix:, end_time:Thu, 27 Oct 2022 17:47:34 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-6eb63640, build_duration_seconds:16513]
=> [automation] update elastic stack version for testing 8.4.4-6eb63640

testing/environments/snapshot.yml
[start_time:Thu, 27 Oct 2022 21:30:37 GMT, release_branch:8.5, prefix:, end_time:Fri, 28 Oct 2022 04:13:48 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-4028b295, build_duration_seconds:24191]
=> [automation] update elastic stack version for testing 8.5.0-4028b295

testing/environments/snapshot.yml
[start_time:Thu, 27 Oct 2022 12:15:57 GMT, release_branch:master, prefix:, end_time:Thu, 27 Oct 2022 21:32:41 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-89d224d2, build_duration_seconds:33404]
=> [automation] update elastic stack version for testing 8.6.0-89d224d2

.github/workflows/add-issues-to-ingest-board.yml
Issues labeled w/ the control plane or data plane labels in this repository will be added to the ingest project w/ `Area: Elastic Agent` set
=> [Automation] Add GH action to add issues to ingest board

testing/environments/snapshot.yml
[start_time:Sat, 29 Oct 2022 12:15:37 GMT, release_branch:8.4, prefix:, end_time:Sat, 29 Oct 2022 17:42:22 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-f3b8851a, build_duration_seconds:19605]
=> [automation] update elastic stack version for testing 8.4.4-f3b8851a

testing/environments/snapshot.yml
[start_time:Sat, 29 Oct 2022 12:15:30 GMT, release_branch:master, prefix:, end_time:Sat, 29 Oct 2022 16:00:26 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-949a38d2, build_duration_seconds:13496]
=> [automation] update elastic stack version for testing 8.6.0-949a38d2

testing/environments/snapshot.yml
[start_time:Sat, 29 Oct 2022 04:07:22 GMT, release_branch:8.5, prefix:, end_time:Sat, 29 Oct 2022 09:13:48 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-f48cdca0, build_duration_seconds:18386]
=> [automation] update elastic stack version for testing 8.5.0-f48cdca0

testing/environments/snapshot.yml
[start_time:Mon, 31 Oct 2022 12:16:05 GMT, release_branch:8.4, prefix:, end_time:Mon, 31 Oct 2022 18:30:49 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-55734bd7, build_duration_seconds:22484]
=> [automation] update elastic stack version for testing 8.4.4-55734bd7

testing/environments/snapshot.yml
[start_time:Mon, 31 Oct 2022 14:45:15 GMT, release_branch:master, prefix:, end_time:Mon, 31 Oct 2022 19:08:41 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-26dc1164, build_duration_seconds:15806]
=> [automation] update elastic stack version for testing 8.6.0-26dc1164

testing/environments/snapshot.yml
[start_time:Wed, 2 Nov 2022 00:15:58 GMT, release_branch:master, prefix:, end_time:Wed, 2 Nov 2022 04:57:55 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-4765d2b0, build_duration_seconds:16917]
=> [automation] update elastic stack version for testing 8.6.0-4765d2b0

testing/environments/snapshot.yml
[start_time:Wed, 2 Nov 2022 12:17:07 GMT, release_branch:master, prefix:, end_time:Wed, 2 Nov 2022 16:53:57 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-8a615646, build_duration_seconds:16610]
=> [automation] update elastic stack version for testing 8.6.0-8a615646

internal/pkg/agent/application/paths/common.go, internal/pkg/agent/cmd/container.go
Syncs components in a containers so they are available at the runtime
Container agent won't run components without this. It will run into input not supported
cc @cmacknz
=> Sync components with state during container start

testing/environments/snapshot.yml
[start_time:Thu, 3 Nov 2022 21:35:24 GMT, release_branch:8.5, prefix:, end_time:Fri, 4 Nov 2022 02:17:02 GMT, manifest_version:2.1.0, version:8.5.1-SNAPSHOT, branch:8.5, build_id:8.5.1-7fd6ffae, build_duration_seconds:16898]
=> [automation] update elastic stack version for testing 8.5.1-7fd6ffae

testing/environments/snapshot.yml
[start_time:Thu, 3 Nov 2022 12:16:03 GMT, release_branch:master, prefix:, end_time:Thu, 3 Nov 2022 16:45:36 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-3f5f98b7, build_duration_seconds:16173]
=> [automation] update elastic stack version for testing 8.6.0-3f5f98b7

testing/environments/snapshot.yml
[start_time:Sun, 6 Nov 2022 12:15:33 GMT, release_branch:8.5, prefix:, end_time:Sun, 6 Nov 2022 17:43:52 GMT, manifest_version:2.1.0, version:8.5.1-SNAPSHOT, branch:8.5, build_id:8.5.1-2ceb7fad, build_duration_seconds:19699]
=> [automation] update elastic stack version for testing 8.5.1-2ceb7fad

testing/environments/snapshot.yml
[start_time:Fri, 4 Nov 2022 14:42:08 GMT, release_branch:master, prefix:, end_time:Fri, 4 Nov 2022 22:58:50 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-f20b7179, build_duration_seconds:29802]
=> [automation] update elastic stack version for testing 8.6.0-f20b7179

testing/environments/snapshot.yml
[start_time:Tue, 8 Nov 2022 12:16:12 GMT, release_branch:master, prefix:, end_time:Tue, 8 Nov 2022 19:54:15 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-da453972, build_duration_seconds:27483]
=> [automation] update elastic stack version for testing 8.6.0-da453972

testing/environments/snapshot.yml
[start_time:Tue, 8 Nov 2022 12:16:08 GMT, release_branch:8.5, prefix:, end_time:Wed, 9 Nov 2022 04:55:08 GMT, manifest_version:2.1.0, version:8.5.1-SNAPSHOT, branch:8.5, build_id:8.5.1-2041424b, build_duration_seconds:59940]
=> [automation] update elastic stack version for testing 8.5.1-2041424b

testing/environments/latest.yml
Merge only after the release of 8.4.3.
=> [Release] Update test environments for 8.4.4

testing/environments/snapshot.yml
[start_time:Thu, 10 Nov 2022 12:15:45 GMT, release_branch:8.5, prefix:, end_time:Thu, 10 Nov 2022 17:34:17 GMT, manifest_version:2.1.0, version:8.5.1-SNAPSHOT, branch:8.5, build_id:8.5.1-1f91140d, build_duration_seconds:19112]
=> [automation] update elastic stack version for testing 8.5.1-1f91140d

testing/environments/snapshot.yml
[start_time:Mon, 14 Nov 2022 00:15:30 GMT, release_branch:8.5, prefix:, end_time:Mon, 14 Nov 2022 04:51:59 GMT, manifest_version:2.1.0, version:8.5.1-SNAPSHOT, branch:8.5, build_id:8.5.1-d7343c55, build_duration_seconds:16589]
=> [automation] update elastic stack version for testing 8.5.1-d7343c55

dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl, magefile.go
Endpoint and fleet server permissions were incorrectly set.
This PR fixes that to be 755 instead of 660
This PR also makes EXTERNAL true by default so each dependency is fetched on build for packaging when using `mage dev:package` 
EXTERNAL is not set when EXTERNAL was already provided or DROP PATH is used.
When using EXTERNAL all dependencies (incl fleet-server, apm, endpoint) are fetched compared to the list of beats from beats repo when used without this flag.  This is to be as close to CI package as possible.
Fixes: #1712
=> Fix components permissions on build

testing/environments/snapshot.yml
[start_time:Mon, 14 Nov 2022 12:15:55 GMT, release_branch:8.5, prefix:, end_time:Mon, 14 Nov 2022 16:21:00 GMT, manifest_version:2.1.0, version:8.5.1-SNAPSHOT, branch:8.5, build_id:8.5.1-49e04c16, build_duration_seconds:14705]
=> [automation] update elastic stack version for testing 8.5.1-49e04c16

pkg/component/component_test.go
Avoids comparisons on internal proto fields and pointer equality when comparing protobuf fields.
This makes the test succeed most of the time, but is still flaky because the input list isn't sorted.
Edit: Sorting was done in https://github.com/elastic/elastic-agent/pull/1723. This just using cmp/protocmp to generate a stable diff between the messages.
=> Use protocmp instead of assert.Equal in component test

testing/environments/snapshot.yml
[start_time:Tue, 15 Nov 2022 05:40:39 GMT, release_branch:master, prefix:, end_time:Tue, 15 Nov 2022 13:07:48 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-9a0f87a9, build_duration_seconds:26829]
=> [automation] update elastic stack version for testing 8.6.0-9a0f87a9

changelog/fragments/1668645651-apm-fleet-config.yaml, internal/pkg/agent/application/application.go, internal/pkg/agent/application/fleet_server_bootstrap.go
Injects the fleet configuration for APM the same way it was done for Endpoint.
Tested against APM PR for V2 https://github.com/elastic/apm-server/pull/9544
Fixes Agent with APM for V2.
- Closes https://github.com/elastic/elastic-agent/issues/1737
The following is the APM input configuration captured in apm-server built off of the PR https://github.com/elastic/apm-server/pull/9544
```
{
"apm-server": {
"agent_config": [],
"aggregation": {
"service": {
"enabled": false
}
},
"auth": {
"anonymous": {
"allow_agent": [
"rum-js",
"js-base",
"iOS/swift"
],
"allow_service": null,
"enabled": true,
"rate_limit": {
"event_limit": 300,
"ip_limit": 1000
}
},
"api_key": {
"enabled": false,
"limit": 100
},
"secret_token": null
},
"capture_personal_data": true,
"default_service_environment": null, …
```
=> V2: Provide fleet configuration to APM server

changelog/fragments/1668591286-fix-beats-logs.yaml, internal/pkg/agent/application/monitoring/v1_monitor.go
This commit fixes the JSON parsing from Beats logs. The configuration
sent to Filebeat did not contain the input type, hence a log input
instead of a filestream one was being started.
This commit also improves the configuraiton of the ndjson parser.
It fixes a bug.
1. Build and run the Elastic-Agent
2. Go to Kibana and assert the logs from Beats and Elastic-Agent are being correctly parsed
~~## Logs~~
=> monitoring: fix JSON logs parsing for Beats

changelog/fragments/1668679987-apm-monitoring.yaml, internal/pkg/agent/application/monitoring/v1_monitor.go
Add "apm-server" to the list of supported beats to ensure the libbeat monitoring flags are added to its command line.
To ensure:
- APM Server is directed to log to the right location
- APM Server is directed to open a unix socket for exposing metrics
- Metricbeat is directed to pull said metrics
~- [ ] I have commented my code, particularly in hard-to-understand areas~
~- [ ] I have made corresponding changes to the documentation~
~- [ ] I have made corresponding change to the default configuration files~
I've tested this with https://github.com/elastic/apm-server/pull/9544
Otherwise you can run the APM integration, and verify `apm-default.sock` is created, then use `curl --unix-socket` to query the "/stats" endpoint.
=> V2: fix monitoring for APM Server

testing/environments/snapshot.yml
[start_time:Thu, 17 Nov 2022 12:21:14 GMT, release_branch:8.5, prefix:, end_time:Thu, 17 Nov 2022 16:55:27 GMT, manifest_version:2.1.0, version:8.5.2-SNAPSHOT, branch:8.5, build_id:8.5.2-733d317b, build_duration_seconds:16453]
=> [automation] update elastic stack version for testing 8.5.2-733d317b

testing/environments/snapshot.yml
[start_time:Fri, 18 Nov 2022 00:14:42 GMT, release_branch:master, prefix:, end_time:Fri, 18 Nov 2022 04:38:35 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-eb092238, build_duration_seconds:15833]
=> [automation] update elastic stack version for testing 8.7.0-eb092238

testing/environments/snapshot.yml
[start_time:Mon, 21 Nov 2022 00:14:45 GMT, release_branch:master, prefix:, end_time:Mon, 21 Nov 2022 03:45:52 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-84b6e00d, build_duration_seconds:12667]
=> [automation] update elastic stack version for testing 8.7.0-84b6e00d

testing/environments/snapshot.yml
[start_time:Sun, 20 Nov 2022 12:15:17 GMT, release_branch:8.5, prefix:, end_time:Sun, 20 Nov 2022 16:52:33 GMT, manifest_version:2.1.0, version:8.5.2-SNAPSHOT, branch:8.5, build_id:8.5.2-13a22054, build_duration_seconds:16636]
=> [automation] update elastic stack version for testing 8.5.2-13a22054

pkg/component/component.go, pkg/component/component_test.go
Ensure each input configuration gets a policy.revision key that contains the revision number of the Fleet policy, but correctly handle the case where a policy object already exists.
The policy.revision key was added as a requirement to support endpoint security, and is probably generally useful for detecting when the overall agent policy has changed.
Output from `elastic-agent inspect components --show-config` with this change showing the policy.revision field is correctly injected into the existing endpoint policy object:
- Closes https://github.com/elastic/elastic-agent/issues/1757
=> Inject input.policy.revision without overwriting.

testing/environments/snapshot.yml
[start_time:Mon, 21 Nov 2022 12:15:56 GMT, release_branch:8.5, prefix:, end_time:Mon, 21 Nov 2022 16:49:51 GMT, manifest_version:2.1.0, version:8.5.2-SNAPSHOT, branch:8.5, build_id:8.5.2-c2e5a3f4, build_duration_seconds:16435]
=> [automation] update elastic stack version for testing 8.5.2-c2e5a3f4

testing/environments/snapshot.yml
[start_time:Tue, 22 Nov 2022 00:14:30 GMT, release_branch:8.6, prefix:, end_time:Tue, 22 Nov 2022 04:45:32 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-e72cd235, build_duration_seconds:16262]
=> [automation] update elastic stack version for testing 8.6.0-e72cd235

testing/environments/latest.yml
Merge only after the release of 8.5.1.
=> [Release] Update test environments for 8.5.2

testing/environments/latest.yml
Merge only after the release of 8.5.2.
=> [Release] Update test environments for 8.5.3

testing/environments/snapshot.yml
[start_time:Tue, 22 Nov 2022 12:15:35 GMT, release_branch:8.5, prefix:, end_time:Tue, 22 Nov 2022 16:54:26 GMT, manifest_version:2.1.0, version:8.5.2-SNAPSHOT, branch:8.5, build_id:8.5.2-98bdbc90, build_duration_seconds:16731]
=> [automation] update elastic stack version for testing 8.5.2-98bdbc90

testing/environments/snapshot.yml
[start_time:Wed, 23 Nov 2022 00:14:43 GMT, release_branch:8.6, prefix:, end_time:Wed, 23 Nov 2022 04:52:03 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-3747fc18, build_duration_seconds:16640]
=> [automation] update elastic stack version for testing 8.6.0-3747fc18

testing/environments/snapshot.yml
[start_time:Tue, 22 Nov 2022 12:14:37 GMT, release_branch:master, prefix:, end_time:Tue, 22 Nov 2022 15:47:57 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-c5c709bf, build_duration_seconds:12800]
=> [automation] update elastic stack version for testing 8.7.0-c5c709bf

changelog/fragments/1669159455-reimplement-processes-route.yaml, internal/pkg/agent/application/monitoring/error.go, internal/pkg/agent/application/monitoring/process.go, internal/pkg/agent/application/monitoring/processes.go, internal/pkg/agent/application/monitoring/server.go, internal/pkg/agent/cmd/run.go, pkg/component/runtime/manager.go
Reimplemented the ```/processes``` routes as minimum sufficient health check for the cloud.
Addresses "V2: 8.6.0-SNAPSHOT not starting in ESS"
https://github.com/elastic/elastic-agent/issues/1731
This doesn't reimplement the full `/stats` collection functionality for example, because there is a new V2 way to check the health and stats that is decoupled from internal child processes handling implementation.
This change is added just to fix the cloud deployments health breakage short term. In the long term cloud would need to be updated for V2, @blakerouse can provide more details.
We had a brief conversation today about this today and reimplementing ```processes``` route fully would take longer, breaks V2 model and might not be necessary. It would be nice if @simitt or @gcpagano could …
=> Re-implement processes route to restore compatibility with the current cloud health checks

internal/pkg/agent/application/monitoring/processes.go
Cloud monitoring is hard coded to look for /processes/apm-server using the processes API. Force us to always use that name for reporting when APM server is running.
This is can certainly be considered a hack, but it's simple and it should work.
- Relates #1780
=> Fix APM server not being available in cloud.

testing/environments/snapshot.yml
[start_time:Thu, 24 Nov 2022 00:14:39 GMT, release_branch:8.6, prefix:, end_time:Thu, 24 Nov 2022 04:27:29 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-742fd135, build_duration_seconds:15170]
=> [automation] update elastic stack version for testing 8.6.0-742fd135

testing/environments/snapshot.yml
[start_time:Wed, 23 Nov 2022 12:14:56 GMT, release_branch:master, prefix:, end_time:Wed, 23 Nov 2022 16:05:51 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-11ac5926, build_duration_seconds:13855]
=> [automation] update elastic stack version for testing 8.7.0-11ac5926

testing/environments/snapshot.yml
[start_time:Wed, 23 Nov 2022 12:16:16 GMT, release_branch:8.5, prefix:, end_time:Wed, 23 Nov 2022 16:51:33 GMT, manifest_version:2.1.0, version:8.5.3-SNAPSHOT, branch:8.5, build_id:8.5.3-760caed9, build_duration_seconds:16517]
=> [automation] update elastic stack version for testing 8.5.3-760caed9

internal/pkg/agent/application/coordinator/coordinator.go
Fix a typo that was preventing upgrades under V2.
It fixes the upgrade process for versions >= 8.6.0
1. Build the `8.6` branch (it will build the version `8.6.0`)
2. Build the `main` branch (it will build the version `8.7.0`)
3. Get a Elastic-Stack up and running with Fleet server
4. Install the Elastic-Agent `v8.6.0`
5. Ensure it is healthy
6. Stop the Elastic-Agent
7. Edit it's `elastic-agent.yml` and add the `dropPath` settings:
```yaml
agent.download:
dropPath: /home/vagrant/dropPath
````
8. Restart the Elastic-Agent
9. Run the upgrade command as root (just to be on the safe side, also export the dropPath env var):
```
AGENT_DROP_PATH=/home/vagrant/dropPath/ ./elastic-agent …
```
=> Fix upgrade under V2

internal/pkg/agent/application/monitoring/process.go, internal/pkg/agent/application/monitoring/processes.go, internal/pkg/agent/application/monitoring/processes_cloud.go, internal/pkg/agent/application/monitoring/processes_cloud_test.go
Add special handling for the apm-server process ID for the /processes/$ID route as well as the /processes response body.
V2 changed the process IDs used for these APIs, which has broken health checks in the cloud provisioning infrastructure. It is much faster to add a few lines of code to special case this in the agent than it is to update all of the cloud monitoring infrastructure.
- Relates https://github.com/elastic/ingest-dev/issues/1418
=> Handle requests for /processes/apm-server.

testing/environments/snapshot.yml
[start_time:Thu, 24 Nov 2022 21:21:39 GMT, release_branch:8.6, prefix:, end_time:Fri, 25 Nov 2022 01:13:02 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-94ebec53, build_duration_seconds:13883]
=> [automation] update elastic stack version for testing 8.6.0-94ebec53

testing/environments/snapshot.yml
[start_time:Fri, 25 Nov 2022 00:15:36 GMT, release_branch:8.5, prefix:, end_time:Fri, 25 Nov 2022 04:13:34 GMT, manifest_version:2.1.0, version:8.5.3-SNAPSHOT, branch:8.5, build_id:8.5.3-c0681f01, build_duration_seconds:14278]
=> [automation] update elastic stack version for testing 8.5.3-c0681f01

testing/environments/snapshot.yml
[start_time:Sun, 27 Nov 2022 00:14:50 GMT, release_branch:8.6, prefix:, end_time:Sun, 27 Nov 2022 03:48:26 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-3e06249e, build_duration_seconds:12816]
=> [automation] update elastic stack version for testing 8.6.0-3e06249e

testing/environments/snapshot.yml
[start_time:Mon, 28 Nov 2022 00:15:35 GMT, release_branch:8.5, prefix:, end_time:Mon, 28 Nov 2022 04:44:32 GMT, manifest_version:2.1.0, version:8.5.3-SNAPSHOT, branch:8.5, build_id:8.5.3-a0b682b9, build_duration_seconds:16137]
=> [automation] update elastic stack version for testing 8.5.3-a0b682b9

internal/pkg/agent/application/fleet_server_bootstrap.go, internal/pkg/agent/application/fleet_server_bootstrap_test.go
In case host has a value and hosts is omitted injected config is without hosts information.
this pr copies host into hosts if needed.
`fleet.hosts` is omitted when only `fleet.host` is specified. 
when we inject config  we replace `fleet.host` with information about id e.g
```
"fleet": {
"access_api_key": "xxxxxxdvUUJITm80OFQyb1YwOU86clBNalZ2ZjNUM0M5a0U2SEgzc2N4Zw==",
...
"host": {
"id": "2628AB39-F770-5FC3-B7F1-8CC95E506B0D"
},
"hosts": [
"https://ffffe9b5f47d409099163e5e8e5e4f4e.fleet.us-west2.gcp.elastic-cloud.com:443"
],
},
```
in case we have input config:
```json
"fleet": {
"access_api_key": "xxxxxxdvUUJITm80OFQyb1YwOU86clBNalZ2ZjNUM0M5a0U2SEgzc2N4Zw==",
...
"host":  "https://ffffe9b5f47d409099163e5e8e5e4f4e.fleet.us-west2.gcp.elastic-cloud.com:443",
"hosts":  { …
```
=> Include host in hosts

testing/environments/snapshot.yml
[start_time:Tue, 29 Nov 2022 00:15:45 GMT, release_branch:8.5, prefix:, end_time:Tue, 29 Nov 2022 04:53:16 GMT, manifest_version:2.1.0, version:8.5.3-SNAPSHOT, branch:8.5, build_id:8.5.3-770e9287, build_duration_seconds:16651]
=> [automation] update elastic stack version for testing 8.5.3-770e9287

changelog/fragments/1669665017-fix-nil-action-ack-crash-after-local-upgrade.yaml, internal/pkg/agent/application/upgrade/upgrade.go
Fixes the crash on agent restart after local upgrade, when the upgrade action is missing (nil)
Fixed crash https://github.com/elastic/elastic-agent/issues/1788
Check the original issue for the repro steps.
One update is that the ```dropPath``` has two different configuration and yml tags and issue  step uses the yml tag ```dropPath```, while it should be ```drop_path```.
```
agent.download:
dropPath: /your/drop/path
drop_path: /your/drop/path  
```
- Closes https://github.com/elastic/elastic-agent/issues/1788
The agent is restarted after upgrade 
Content of the ```.update-marker``` after upgrade
=> Fix: Elastic-Agent fails to re-start during upgrade

changelog/fragments/1669668741-fix-erroneous-http-url-directory-created-for-monitoring.yaml, internal/pkg/agent/application/monitoring/server.go, internal/pkg/agent/application/monitoring/server_test.go
Fixes erroneously created http url directory path for monitoring when the agent runs. 
Added a check if the url is passed in the path.
```
➜ sudo ls -la /Library/Elastic/Agent/http\:/localhost\:6791
total 0
drwxr-x---  2 root  wheel  64 Nov 28 11:12 .
drwxr-x---  3 root  wheel  96 Nov 28 11:12 ..
```
No erroneous directories should be created during the agent execution.
1. Install the agent
2. Make sure the agent create "http" directory, something like: ``` /Library/Elastic/Agent/http\:/localhost\:6791``` 
- Closes https://github.com/elastic/elastic-agent/issues/1806
=> Fix erroneously created http url directory path for monitoring

internal/pkg/agent/application/monitoring/v1_monitor.go
Drops all events from being published from the `component.dataset: elastic_agent.filestream_monitoring`,  `component.dataset: elastic_agent.beats_metrics_monitoring`, and  `component.dataset: elastic_agent.http_metrics_monitoring`.
Without dropping these events the filestream gets stuck in an infinite loop. If filestream hits an issue publishing the events it logs an error which then filestream monitor will read from the logs and try to also publish that new log message (thus the infinite loop).
This means that no logs from the monitoring components will be made available in Fleet UI. They will still be retrievable with diagnostics as well as included in the unified elastic-agent log.
- ~~[ ] I have made corresponding change …
=> Drop events from monitoring components

changelog/fragments/1669739947-fix-osqueryd-and-osquery-extension.ext-permissions.yaml, dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Fixes permissions for osqueryd and osquery-extension.ext
Was:
Should be:
Fixes the agent going unhealthy when osquery integration is added to the policy (Not linking to the issue since it is in the private repo). Osquerybeat is unable to run the osqueryd 
```
Exiting: fork/exec /usr/share/elastic-agent/data/elastic-agent-0e669f/components/osqueryd: operation not permitted
```
=> Fix osqueryd and osquery-extension.ext permissions

testing/environments/snapshot.yml
[start_time:Wed, 30 Nov 2022 00:15:29 GMT, release_branch:8.5, prefix:, end_time:Wed, 30 Nov 2022 04:59:28 GMT, manifest_version:2.1.0, version:8.5.3-SNAPSHOT, branch:8.5, build_id:8.5.3-a46b25ec, build_duration_seconds:17039]
=> [automation] update elastic stack version for testing 8.5.3-a46b25ec

testing/environments/snapshot.yml
[start_time:Wed, 30 Nov 2022 00:14:37 GMT, release_branch:8.6, prefix:, end_time:Wed, 30 Nov 2022 03:40:29 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-ecfefdaf, build_duration_seconds:12352]
=> [automation] update elastic stack version for testing 8.6.0-ecfefdaf

.github/workflows/changelog.yml, .github/workflows/golangci-lint.yml, .github/workflows/macos.yml
Use the `setup-go` action with the `go-version-file` input so it reads the file `.go-version`
Avoid the logic to read and create env variables and use the undocumented `.go-version-file` 
See https://github.com/actions/setup-go/pull/295
=> actions: use go-version-file: .go-version

pkg/component/runtime/command.go
Changes the elastic-agent log monitoring to use the old names that match v1. This is for 8.6 only!
So no fixes are required on Fleet side for new v2 architecture to work with 8.6.
- Relates https://github.com/elastic/elastic-agent/issues/1814
- Closes https://github.com/elastic/elastic-agent/issues/1847
=> [8.6] Use v1 data stream names for log shipping

internal/pkg/agent/application/monitoring/v1_monitor.go
Changes the elastic-agent metrics monitoring to use the old names that match v1. This is for 8.6 only!
So no fixes are required on Fleet side for new v2 architecture to work with 8.6.
- Closes #1849
=> [8.6] Use v1 data stream names for metric shipping

testing/environments/snapshot.yml
[start_time:Thu, 1 Dec 2022 00:14:50 GMT, release_branch:8.6, prefix:, end_time:Thu, 1 Dec 2022 04:12:49 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-87c26073, build_duration_seconds:14279]
=> [automation] update elastic stack version for testing 8.6.0-87c26073

testing/environments/snapshot.yml
[start_time:Thu, 1 Dec 2022 00:15:48 GMT, release_branch:8.5, prefix:, end_time:Thu, 1 Dec 2022 05:00:21 GMT, manifest_version:2.1.0, version:8.5.3-SNAPSHOT, branch:8.5, build_id:8.5.3-268167d7, build_duration_seconds:17073]
=> [automation] update elastic stack version for testing 8.5.3-268167d7

changelog/fragments/1669845868-add-agent-logging-level-to-fleet-configuration.yaml, internal/pkg/agent/application/application.go, internal/pkg/agent/application/fleet_server_bootstrap.go, internal/pkg/agent/application/fleet_server_bootstrap_test.go
Adds missing agent logging level to fleet configuration. 
The Endpoint expects as
```
fleet:
agent:
logging:
level: info
```
Refer for more details to https://github.com/elastic/elastic-agent/issues/1853
The fleet configuration example after this change:
```
"fleet": {
"access_api_key": "xXxXYnlvUUJPYzlfZ1A4X0ZlWnk6ZGVEQ2RaR3ZUWWV6UldrbDd4VUJ2QQ==",
"agent": {
"id": "88e91b22-2f3a-4047-a951-48255c5b3026",
"logging": {
"level": "debug"
}
},
"enabled": true,
"host": {
"id": "b62e91be682a4108bbb080152cc5eeac"
},
"hosts": [
"https://ccccc998d3c74a64890381fdcc38c9c9.fleet.us-central1.gcp.foundit.no:443"
],
"protocol": "http",
"ssl": {
"renegotiation": "never",
"verification_mode": "full"
},
"timeout": "10m0s"
}
```
Fixed the issue for Endpoint missing logging configuration …
=> Add agent logging level to fleet configuration

internal/pkg/agent/application/monitoring/process.go, internal/pkg/agent/application/monitoring/processes_cloud.go, internal/pkg/agent/application/monitoring/processes_cloud_test.go
fixed apm naming weirdness and empty path redirect handling.
in processes we need to return `apm-server-{outputName}` instead of our representation where we replaced binary name with input type.
then on process handler we need to translate it back from `apm-server-{outputName}` to `apm-{outputName}` so we find correct socket with endpoint.
=> Allow empty redirect for processes endpoint

testing/environments/snapshot.yml
[start_time:Thu, 1 Dec 2022 12:15:51 GMT, release_branch:8.5, prefix:, end_time:Thu, 1 Dec 2022 16:11:54 GMT, manifest_version:2.1.0, version:8.5.3-SNAPSHOT, branch:8.5, build_id:8.5.3-1625ae9f, build_duration_seconds:14163]
=> [automation] update elastic stack version for testing 8.5.3-1625ae9f

testing/environments/snapshot.yml
[start_time:Thu, 1 Dec 2022 20:00:57 GMT, release_branch:8.6, prefix:, end_time:Fri, 2 Dec 2022 01:32:22 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-f96862e0, build_duration_seconds:19885]
=> [automation] update elastic stack version for testing 8.6.0-f96862e0

testing/environments/snapshot.yml
[start_time:Fri, 2 Dec 2022 00:15:08 GMT, release_branch:master, prefix:, end_time:Fri, 2 Dec 2022 04:30:28 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-1b0dc867, build_duration_seconds:15320]
=> [automation] update elastic stack version for testing 8.7.0-1b0dc867

changelog/fragments/1669928791-Ensure-unique-input-ID-when-variable-substition-occurs-from-a-dynamic-provider.yaml, internal/pkg/agent/transpiler/ast_test.go, internal/pkg/agent/transpiler/utils.go, internal/pkg/agent/transpiler/utils_test.go, internal/pkg/agent/transpiler/vars.go, internal/pkg/agent/transpiler/vars_test.go, internal/pkg/composable/controller.go, pkg/component/component.go
This updates the ID of an input to concat the current ID with the unique ID of the variable context from the dynamic provided that provided the replacement.
The original ID is moved to `original_id` and the new id is placed on the input.
Ensures that when a variable substitution is performed for an input definition duplicate of that input results in a unique ID for that newly defined input.
- Closes #1751
=> Ensure unique ID for dynamic variable replacement.

internal/pkg/agent/cmd/common.go, internal/pkg/agent/cmd/diagnostics.go, internal/pkg/agent/cmd/inspect.go, internal/pkg/agent/cmd/status.go
We're loading path overrides in every command and few of them were left unnoticed. 
This PR moves the logic to Prehook so paths are always updated in all cases.
Restart and version does not work in a container
Fixes https://github.com/elastic/elastic-agent/issues/1713
=> Add pre-hook to load paths overrides in container

changelog/fragments/1669940990-Remove-inputs-when-all-streams-are-removed.yaml, internal/pkg/agent/transpiler/utils.go, internal/pkg/agent/transpiler/utils_test.go
When an input has conditions on all of its streams and the conditions result in all streams being removed from the input the entire input is removed. 
This solves the issue described here https://github.com/elastic/integrations/issues/4725 without having to change the integration. I think it provides a better experience than also having a condition on the input.
- Closes #1868
=> Remove inputs when all streams are removed

testing/environments/snapshot.yml
[start_time:Mon, 5 Dec 2022 00:14:47 GMT, release_branch:8.6, prefix:, end_time:Mon, 5 Dec 2022 03:44:34 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-368aeeae, build_duration_seconds:12587]
=> [automation] update elastic stack version for testing 8.6.0-368aeeae

testing/environments/snapshot.yml
[start_time:Mon, 5 Dec 2022 00:15:25 GMT, release_branch:8.5, prefix:, end_time:Mon, 5 Dec 2022 04:43:34 GMT, manifest_version:2.1.0, version:8.5.3-SNAPSHOT, branch:8.5, build_id:8.5.3-0a7c209d, build_duration_seconds:16089]
=> [automation] update elastic stack version for testing 8.5.3-0a7c209d

testing/environments/snapshot.yml
[start_time:Sun, 4 Dec 2022 12:15:05 GMT, release_branch:master, prefix:, end_time:Sun, 4 Dec 2022 16:28:20 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-1fff43d4, build_duration_seconds:15195]
=> [automation] update elastic stack version for testing 8.7.0-1fff43d4

internal/pkg/agent/application/upgrade/artifact/download/snapshot/downloader.go
When parsing the response from the artifacts-api to get the latest snapshot (https://artifacts-api.elastic.co/v1/search/%s-SNAPSHOT/elastic-agent) it could happen that an entry that is not from the Elastic-Agent (like the Elastic-Agent-Shipper) would be evaluated and it would cause the `snapshotURI` function return an error.
This PR fixes it by iterating the whole map before returning an error.
It fixes a bug
~~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~
1. Build the `8.6` branch (it …
=> snapshot/downloader: fix fetching snapshot URI

pkg/component/component_test.go, pkg/component/load_test.go, specs/endpoint-security.spec.yml
Allows endpoint to run in a kubernetes cluster. The spec.yml wasn't updated correctly for the new v2 changes.
This was tested manually on kubernetes, before there would not be any policy response for the integration, and now the policy response is received, and the kubernetes security dashboard is populated.
- Closes https://github.com/elastic/endpoint-dev/issues/12195
Apologies that this is not as thorough as the template showed. I'm at the end of my day, want CI to run, and will fill in more details tomorrow.
=> add container platforms to endpoint spec

testing/environments/snapshot.yml
[start_time:Mon, 5 Dec 2022 12:14:24 GMT, release_branch:master, prefix:, end_time:Mon, 5 Dec 2022 16:03:39 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-7fe23b13, build_duration_seconds:13755]
=> [automation] update elastic stack version for testing 8.7.0-7fe23b13

testing/environments/snapshot.yml
[start_time:Mon, 5 Dec 2022 12:15:33 GMT, release_branch:8.5, prefix:, end_time:Mon, 5 Dec 2022 16:55:18 GMT, manifest_version:2.1.0, version:8.5.3-SNAPSHOT, branch:8.5, build_id:8.5.3-55d94167, build_duration_seconds:16785]
=> [automation] update elastic stack version for testing 8.5.3-55d94167

testing/environments/snapshot.yml
[start_time:Tue, 6 Dec 2022 00:14:58 GMT, release_branch:8.6, prefix:, end_time:Tue, 6 Dec 2022 10:25:41 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-57f16700, build_duration_seconds:36643]
=> [automation] update elastic stack version for testing 8.6.0-57f16700

testing/environments/snapshot.yml
[start_time:Tue, 6 Dec 2022 12:14:42 GMT, release_branch:master, prefix:, end_time:Tue, 6 Dec 2022 15:55:56 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-2c7c2bad, build_duration_seconds:13274]
=> [automation] update elastic stack version for testing 8.7.0-2c7c2bad

testing/environments/snapshot.yml
[start_time:Tue, 6 Dec 2022 12:16:04 GMT, release_branch:8.5, prefix:, end_time:Tue, 6 Dec 2022 16:48:24 GMT, manifest_version:2.1.0, version:8.5.3-SNAPSHOT, branch:8.5, build_id:8.5.3-e63a0e72, build_duration_seconds:16340]
=> [automation] update elastic stack version for testing 8.5.3-e63a0e72

testing/environments/snapshot.yml
[start_time:Thu, 8 Dec 2022 00:17:45 GMT, release_branch:master, prefix:, end_time:Thu, 8 Dec 2022 04:32:18 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-188e6a3a, build_duration_seconds:15273]
=> [automation] update elastic stack version for testing 8.7.0-188e6a3a

testing/environments/snapshot.yml
[start_time:Wed, 7 Dec 2022 12:16:19 GMT, release_branch:8.5, prefix:, end_time:Wed, 7 Dec 2022 16:51:43 GMT, manifest_version:2.1.0, version:8.5.3-SNAPSHOT, branch:8.5, build_id:8.5.3-ec242734, build_duration_seconds:16524]
=> [automation] update elastic stack version for testing 8.5.3-ec242734

testing/environments/snapshot.yml
[start_time:Thu, 8 Dec 2022 00:14:56 GMT, release_branch:8.6, prefix:, end_time:Thu, 8 Dec 2022 04:09:41 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-7c9fd7a8, build_duration_seconds:14085]
=> [automation] update elastic stack version for testing 8.6.0-7c9fd7a8

changelog/fragments/1669929902-fix-local-fleet-server-port.yaml, internal/pkg/agent/cmd/enroll_cmd.go, internal/pkg/remote/client.go
Fix an issue where the local fleet-server port was not properly used by the elastic-agent when running an instance of fleet-server.
When running a large scale of agents, the fleet-server may hit the connection limit if it's running on the same port as the other agents. this causes the elastic-agent running the fleet-server to be marked as degraded.
=> Change local fleet-server connection to localhost:8221

testing/environments/snapshot.yml
[start_time:Fri, 9 Dec 2022 00:15:07 GMT, release_branch:master, prefix:, end_time:Fri, 9 Dec 2022 03:47:13 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-59d5589a, build_duration_seconds:12726]
=> [automation] update elastic stack version for testing 8.7.0-59d5589a

testing/environments/snapshot.yml
[start_time:Fri, 9 Dec 2022 00:14:54 GMT, release_branch:8.6, prefix:, end_time:Fri, 9 Dec 2022 04:22:16 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-3bb8e729, build_duration_seconds:14842]
=> [automation] update elastic stack version for testing 8.6.0-3bb8e729

testing/environments/snapshot.yml
[start_time:Thu, 8 Dec 2022 00:15:29 GMT, release_branch:8.5, prefix:, end_time:Thu, 8 Dec 2022 05:18:52 GMT, manifest_version:2.1.0, version:8.5.3-SNAPSHOT, branch:8.5, build_id:8.5.3-91bdfab4, build_duration_seconds:18203]
=> [automation] update elastic stack version for testing 8.5.3-91bdfab4

testing/environments/snapshot.yml
[start_time:Sun, 11 Dec 2022 12:15:20 GMT, release_branch:master, prefix:, end_time:Sun, 11 Dec 2022 15:47:46 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-e9833f49, build_duration_seconds:12746]
=> [automation] update elastic stack version for testing 8.7.0-e9833f49

testing/environments/snapshot.yml
[start_time:Sun, 11 Dec 2022 00:17:33 GMT, release_branch:8.6, prefix:, end_time:Sun, 11 Dec 2022 05:26:16 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-febebae1, build_duration_seconds:18523]
=> [automation] update elastic stack version for testing 8.6.0-febebae1

internal/pkg/agent/application/application.go, internal/pkg/agent/application/monitoring/v1_monitor.go, internal/pkg/agent/cmd/run.go
This PR checks upon run whether or not we're in bootstrap mode and if so we initiate application with disable monitoring override. 
We do this by passing override to avoid loading fleet config in case of standalone in `application.go`
During bootstrap monitoring is not needed and it causes some confusing logs
Fixes: https://github.com/elastic/elastic-agent/issues/1761
=> Disable monitoring in bootstrap mode

testing/environments/snapshot.yml
[start_time:Tue, 13 Dec 2022 00:15:02 GMT, release_branch:8.6, prefix:, end_time:Tue, 13 Dec 2022 04:17:34 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-6538107d, build_duration_seconds:14552]
=> [automation] update elastic stack version for testing 8.6.0-6538107d

testing/environments/snapshot.yml
[start_time:Tue, 13 Dec 2022 00:15:13 GMT, release_branch:master, prefix:, end_time:Tue, 13 Dec 2022 03:51:41 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-08cd8ac3, build_duration_seconds:12988]
=> [automation] update elastic stack version for testing 8.7.0-08cd8ac3

internal/pkg/agent/application/monitoring/v1_monitor.go, pkg/component/runtime/command.go, pkg/component/runtime/manager_test.go
Coming from #1894
when unit ID is longer than limit we plan on placing HTTP socket to `/tmp/elastic-agent` 
We should create this directory when calling `Prepare()`
Prepare is although unaware of exceeding limit and prepares structure for normal length ID which is within elastic agent directory layout. 
This PR fixes `Prepare()` to accept unit ID so it can properly target directory holding HTTP socket
_note: we need to think about testing filesystem operations, either integration tests or wrapping these behind interface and refactoring._
No metrics are collected for unit IDs longer than 106 characters
=> Fixed Monitoring.Prepare for IDs exceeding filepath length limit

testing/environments/snapshot.yml
[start_time:Tue, 13 Dec 2022 12:15:20 GMT, release_branch:master, prefix:, end_time:Tue, 13 Dec 2022 15:44:47 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-04d5f080, build_duration_seconds:12567]
=> [automation] update elastic stack version for testing 8.7.0-04d5f080

testing/environments/snapshot.yml
[start_time:Thu, 15 Dec 2022 00:16:06 GMT, release_branch:master, prefix:, end_time:Thu, 15 Dec 2022 04:09:50 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-4441fcfd, build_duration_seconds:14024]
=> [automation] update elastic stack version for testing 8.7.0-4441fcfd

testing/environments/snapshot.yml
[start_time:Thu, 15 Dec 2022 00:15:00 GMT, release_branch:8.6, prefix:, end_time:Thu, 15 Dec 2022 03:29:53 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-919399a0, build_duration_seconds:11693]
=> [automation] update elastic stack version for testing 8.6.0-919399a0

testing/environments/snapshot.yml
[start_time:Fri, 16 Dec 2022 00:15:04 GMT, release_branch:master, prefix:, end_time:Fri, 16 Dec 2022 03:52:36 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-319a9bee, build_duration_seconds:13052]
=> [automation] update elastic stack version for testing 8.7.0-319a9bee

testing/environments/snapshot.yml
[start_time:Fri, 16 Dec 2022 00:17:39 GMT, release_branch:8.6, prefix:, end_time:Fri, 16 Dec 2022 06:05:25 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-d5c0a6be, build_duration_seconds:20866]
=> [automation] update elastic stack version for testing 8.6.0-d5c0a6be

testing/environments/snapshot.yml
[start_time:Mon, 19 Dec 2022 12:59:34 GMT, release_branch:8.6, prefix:, end_time:Mon, 19 Dec 2022 22:12:32 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-a85d8f17, build_duration_seconds:33178]
=> [automation] update elastic stack version for testing 8.6.0-a85d8f17

testing/environments/snapshot.yml
[start_time:Mon, 19 Dec 2022 22:55:35 GMT, release_branch:master, prefix:, end_time:Tue, 20 Dec 2022 03:27:00 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-bb19a9d1, build_duration_seconds:16285]
=> [automation] update elastic stack version for testing 8.7.0-bb19a9d1

specs/cloud-defend.spec.yml
Renames the integration input of a new "wip" integration called cloud_defend (for containers). 
Also, creates a distinct input for metrics data stream config.
To ensure everything hooks up correctly.
- Relates https://github.com/elastic/integrations/pull/4680
=> Integration input name updated for new cloud-defend service

testing/environments/snapshot.yml
[start_time:Tue, 20 Dec 2022 12:18:01 GMT, release_branch:master, prefix:, end_time:Tue, 20 Dec 2022 19:53:27 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-19f30181, build_duration_seconds:27326]
=> [automation] update elastic stack version for testing 8.7.0-19f30181

testing/environments/snapshot.yml
[start_time:Wed, 21 Dec 2022 00:17:09 GMT, release_branch:8.6, prefix:, end_time:Wed, 21 Dec 2022 04:18:42 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-734df845, build_duration_seconds:14493]
=> [automation] update elastic stack version for testing 8.6.0-734df845

pkg/component/runtime/manager.go
Signed-off-by: Florian Lehner <florian.lehner@elastic.co>
The  `%w` verb is intended for error operands but not for human readable error messages. Therefore the `%s` verb should be preferred for logging over `%w`.
```
control protocol failed: %!w(*errors.errorString=&{grpc: the server has been stopped})
```
to 
```
control protocol failed: grpc: the server has been stopped
```
=> runtime/manager: make error message human readable

internal/pkg/fleetapi/acker/lazy/lazy_acker.go, internal/pkg/fleetapi/acker/lazy/lazy_acker_test.go
It uses `%s` instead of `%#v` to print actions, that way the `String()` method is called and the pointers are dereferenced.
The actual values of the pointers are printed instead of the memory address the pointers are pointing to.
From the root run:
```
go test -v github.com/elastic/elastic-agent/internal/pkg/fleetapi/acker/lazy
```
if run without the fix, the pointers will print the memory address they point to
- Before:
```
{[...],"message":"lazy acker: failed ack batch, …
```
=> Lazy Acker print actions as string so indeed prints them

internal/pkg/agent/application/dispatcher/dispatcher.go, internal/pkg/agent/application/dispatcher/dispatcher_test.go
This PR resets last error coupled with action batch in dispatcher. when action comes and is invalid last error is set. we never reset this value. even when new config comes and is ok.
resetting this before actions are processed will cause some interesting side effect. agent won't get into failed state.
setting fail/succ conditionally like in this PR works better within these loops
Whenever action fails error will persist forever until agent restarts.
Fixes: #1926
=> Do not persist action error with new action batch

testing/environments/snapshot.yml
[start_time:Thu, 22 Dec 2022 01:27:43 GMT, release_branch:8.6, prefix:, end_time:Thu, 22 Dec 2022 04:36:36 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-55d181cf, build_duration_seconds:11333]
=> [automation] update elastic stack version for testing 8.6.0-55d181cf

testing/environments/snapshot.yml
[start_time:Thu, 22 Dec 2022 00:16:50 GMT, release_branch:8.5, prefix:, end_time:Thu, 22 Dec 2022 04:16:35 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-880022a5, build_duration_seconds:14385]
=> [automation] update elastic stack version for testing 8.5.4-880022a5

internal/pkg/agent/application/coordinator/coordinator.go, internal/pkg/agent/application/monitoring/v1_monitor.go, internal/pkg/agent/cmd/inspect.go, pkg/component/component.go
This adds to the filestream monitor so it can gather log files from any service based component that defined a log path to be used in its specification.
This fixes the issue where 8.6 was not shipping log information for Endpoint Security.
- Closes #1939
=> Fix logging of service based components (aka. endpoint)

testing/environments/snapshot.yml
[start_time:Thu, 22 Dec 2022 12:15:47 GMT, release_branch:8.5, prefix:, end_time:Thu, 22 Dec 2022 16:21:04 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-9612e66a, build_duration_seconds:14717]
=> [automation] update elastic stack version for testing 8.5.4-9612e66a

internal/pkg/agent/application/monitoring/v1_monitor.go
Removes endpoint from supported binaries for metrics collection. 
Reduces logs by not hitting 
```
Error fetching data for metricset http.json: error making http request: 
Get \"http://unix/stats\": dial unix /opt/Elastic/Agent/data/tmp/endpoint-default.sock: connect: no such file or directory" 
```
as endpoint does not expose metrics on used path.
Fixes: #1965
=> [V2] Do not collect endpoint metrics on /stats endpoint

internal/pkg/agent/application/coordinator/coordinator.go
It updates the logging messages for component and unit state changes to be easier to understand and read.
Without this change viewing state change information in the logs is hard to read and doesn't show properly when the logs are rendered in the Fleet UI.
- Closes #1954
```
{"log.level":"info","@timestamp":"2022-12-23T09:04:07.182-0500","log.origin":{"file.name":"coordinator/coordinator.go","file.line":831},"message":"State changed …
```
=> Improve state change messages

testing/environments/snapshot.yml
[start_time:Mon, 26 Dec 2022 00:17:39 GMT, release_branch:8.6, prefix:, end_time:Mon, 26 Dec 2022 04:28:15 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-f6d7d537, build_duration_seconds:15036]
=> [automation] update elastic stack version for testing 8.6.0-f6d7d537

testing/environments/snapshot.yml
[start_time:Sun, 25 Dec 2022 12:18:04 GMT, release_branch:master, prefix:, end_time:Sun, 25 Dec 2022 15:22:59 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-0f74a2e9, build_duration_seconds:11095]
=> [automation] update elastic stack version for testing 8.7.0-0f74a2e9

testing/environments/snapshot.yml
[start_time:Mon, 26 Dec 2022 00:15:42 GMT, release_branch:8.5, prefix:, end_time:Mon, 26 Dec 2022 04:59:16 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-09ced402, build_duration_seconds:17014]
=> [automation] update elastic stack version for testing 8.5.4-09ced402

testing/environments/snapshot.yml
[start_time:Tue, 27 Dec 2022 00:17:52 GMT, release_branch:8.6, prefix:, end_time:Tue, 27 Dec 2022 03:33:58 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-a026c2fe, build_duration_seconds:11766]
=> [automation] update elastic stack version for testing 8.6.0-a026c2fe

testing/environments/snapshot.yml
[start_time:Tue, 27 Dec 2022 00:16:05 GMT, release_branch:8.5, prefix:, end_time:Tue, 27 Dec 2022 04:42:49 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-53cae6e0, build_duration_seconds:16004]
=> [automation] update elastic stack version for testing 8.5.4-53cae6e0

testing/environments/snapshot.yml
[start_time:Wed, 28 Dec 2022 00:17:28 GMT, release_branch:8.6, prefix:, end_time:Wed, 28 Dec 2022 04:40:37 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-7e55dcb1, build_duration_seconds:15789]
=> [automation] update elastic stack version for testing 8.6.0-7e55dcb1

testing/environments/snapshot.yml
[start_time:Tue, 27 Dec 2022 12:17:19 GMT, release_branch:master, prefix:, end_time:Tue, 27 Dec 2022 15:53:15 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-b3da67ae, build_duration_seconds:12956]
=> [automation] update elastic stack version for testing 8.7.0-b3da67ae

testing/environments/snapshot.yml
[start_time:Tue, 27 Dec 2022 12:20:45 GMT, release_branch:8.5, prefix:, end_time:Tue, 27 Dec 2022 16:20:38 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-b44284e8, build_duration_seconds:14393]
=> [automation] update elastic stack version for testing 8.5.4-b44284e8

_meta/config/common.p2.yml.tmpl, _meta/config/common.reference.p2.yml.tmpl, _meta/config/elastic-agent.docker.yml.tmpl, _meta/elastic-agent.yml, changelog/fragments/1671748292-input-ids-are-required.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml, elastic-agent.docker.yml, elastic-agent.reference.yml, elastic-agent.yml, pkg/component/component.go, pkg/component/component_test.go
As part of the agent V2 change, unique input IDs are mandatory. Add a changelog fragment for this, and update the example agent policies to include IDs where necessary.
I made this fairly quickly and may have missed an update to a reference file.
- Relates https://github.com/elastic/elastic-agent/issues/1991
=> All inputs in an agent policy must have a unique ID

testing/environments/snapshot.yml
[start_time:Thu, 29 Dec 2022 00:17:11 GMT, release_branch:8.6, prefix:, end_time:Thu, 29 Dec 2022 04:01:07 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-08909b84, build_duration_seconds:13436]
=> [automation] update elastic stack version for testing 8.6.0-08909b84

testing/environments/snapshot.yml
[start_time:Thu, 29 Dec 2022 00:16:26 GMT, release_branch:8.5, prefix:, end_time:Thu, 29 Dec 2022 04:51:03 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-63dd32c9, build_duration_seconds:16477]
=> [automation] update elastic stack version for testing 8.5.4-63dd32c9

internal/pkg/agent/application/monitoring/v1_monitor.go, internal/pkg/composable/controller.go, internal/pkg/composable/controller_test.go
This PR adds a context cancellation check in controller.
It can happen that controllers will hang on `c.ch <- vars` because coordinator is handling cancellation already and never gets to handling `case vars := <-varsWatcher.Watch():` part of the loop and never drains the channel.
Including also fix for index name generation for monitoring metricbeat
Sometimes very occasionally we're experiencing agent stuck in REEXECuting (unhealthy in UI)
Related: https://github.com/elastic/elastic-agent/issues/1861
it should fix it but i'd rather wait for test results. I haven't run into the situation after this fix in place
=> Respect context cancellation when waiting for Vars

testing/environments/snapshot.yml
[start_time:Fri, 30 Dec 2022 00:18:05 GMT, release_branch:8.6, prefix:, end_time:Fri, 30 Dec 2022 03:48:37 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-2d1af9b1, build_duration_seconds:12632]
=> [automation] update elastic stack version for testing 8.6.0-2d1af9b1

testing/environments/snapshot.yml
[start_time:Fri, 30 Dec 2022 00:22:46 GMT, release_branch:master, prefix:, end_time:Fri, 30 Dec 2022 04:16:19 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-d6e7f5ec, build_duration_seconds:14013]
=> [automation] update elastic stack version for testing 8.7.0-d6e7f5ec

testing/environments/snapshot.yml
[start_time:Thu, 29 Dec 2022 12:15:52 GMT, release_branch:8.5, prefix:, end_time:Thu, 29 Dec 2022 16:14:33 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-2ce7df52, build_duration_seconds:14321]
=> [automation] update elastic stack version for testing 8.5.4-2ce7df52

pkg/component/runtime/command.go, pkg/component/runtime/conn_info_server_test.go, pkg/component/runtime/runtime_comm.go, pkg/component/runtime/service.go
When a previously running process exits, it is possible that the most recent checkin expected message for that process was queued to be sent in the communicator checkin expected channel but never sent.
When the process is restarted, this stale previous checkin expected message  would then be sent to the new process as the first checkin.
This can lead to invalid or unexpected initial checkin expected messages being sent to component processes, for example the config index can be set to the correct value but the actual configuration set to nil because the stale message was for a process that was already up to date. This can lead to component processes ignoring the actual initial configuration that is sent later because the config index was the same as it was in the stale initial checkin …
=> Fix stale checkin expected messages being sent on process restart

internal/pkg/agent/cmd/diagnostics.go
Fixes omitting the file extensions when writing per component diagnostic files to disk.
Picked this change out of https://github.com/elastic/elastic-agent/pull/2005.
Before:
```
ls diag/components/system-metrics-default/system-metrics-default
allocs               block.txt            heap                 threadcreate
beat-rendered-config goroutine            mutex
```
After:
```
ls diag/components/system-metrics-default/system-metrics-default
allocs.txt               block.txt                heap.txt                 threadcreate.txt
beat-rendered-config.yml goroutine.txt            mutex.txt
```
=> Use full filename for component diagnostic files.

internal/pkg/agent/cmd/diagnostics.go
Restores the redaction step from https://github.com/elastic/elastic-agent/pull/566 during diagnostic building to ensure that most secrets in configuration are not included in the diag.
There are situations where the YAML is not always unmarshallable https://github.com/elastic/elastic-agent/issues/1907#issuecomment-1363224642 which limits the ability to redact the agent's `state.yml` diag file. This will need to be fixed by either a smarter generic redaction implementation that can selectively unmarshall/redact parts of the file or by redacting the state.yml file before it's serialized in `coordinator.go`.
In the meantime, I have made redaction best-effort and will allow any file that cannot be successfully unmarshalled to be written to the diag as-is with secrets in place. A warning log …
=> Add generic diagnostic redactor back to v2

pkg/component/component_test.go, specs/endpoint-security.spec.yml, specs/osquerybeat.spec.yml
- Closes https://github.com/elastic/security-team/issues/5572
Osquerybeat support for Logstash was removed when it should not have been. Put it back.
=> Add osquery and endpoint security logstash output support

dev-tools/packaging/templates/ironbank/Dockerfile.tmpl, dev-tools/packaging/templates/ironbank/hardening_manifest.yaml.tmpl
Signed-off-by: Adrien Mannocci <adrien.mannocci@elastic.co>
* Update ironbank base image to ubi 8.7
* We need to use the latest ubi 8.x base image available.
=> Update ironbank base image to ubi 8.7

testing/environments/snapshot.yml
[start_time:Fri, 6 Jan 2023 00:18:00 GMT, release_branch:8.6, prefix:, end_time:Fri, 6 Jan 2023 04:51:07 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-08ebeaf7, build_duration_seconds:16387]
=> [automation] update elastic stack version for testing 8.6.0-08ebeaf7

testing/environments/snapshot.yml
[start_time:Mon, 9 Jan 2023 00:17:13 GMT, release_branch:master, prefix:, end_time:Mon, 9 Jan 2023 03:41:46 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-df9bb536, build_duration_seconds:12273]
=> [automation] update elastic stack version for testing 8.7.0-df9bb536

testing/environments/snapshot.yml
[start_time:Mon, 9 Jan 2023 12:17:52 GMT, release_branch:master, prefix:, end_time:Mon, 9 Jan 2023 15:56:00 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-61c35791, build_duration_seconds:13088]
=> [automation] update elastic stack version for testing 8.7.0-61c35791

version/version.go
Updates references to the new release 8.6.1.
Merge after the release 8.6.0.
=> [Release] Update version to 8.6.1

specs/metricbeat.spec.yml
Add **statsd/metrics** missing input. We are working on **integrations/input package** using **statsd/metrics** In both the cases we noticed:
- Some issues in the new agent, where **statsd** metrics were not pushed to ES.
- Working for older agents but not in new agents.
-  statsd entry to be missing in the recently added metricbeat spec file in V2 elastic-agent.
CC: @ishleenk17 
- Gating the development of new statsd input package, while using latest V2 elastic-agent.
NA
-->
=> Add statsd metricbeat input.

dev-tools/mage/build.go
Fix the issue with the `CVE-2022-24765`, so the workspace is set as safe
Otherwise, it will fail with:
```
[2023-01-11T09:58:36.531Z] >> Building using: cmd='build/mage-linux-amd64 golangCrossBuild', env=[CC=o64-clang, CXX=o64-clang++, GOARCH=amd64, GOARM=, GOOS=darwin, PLATFORM_ID=darwin-amd64]
[2023-01-11T09:58:36.632Z] fatal: detected dubious ownership in repository at '/go/src/github.com/elastic/beats'
```
=> Add agent directory into git safe dirs

NOTICE.txt, go.mod, go.sum
Removes a debug log that would print certificate private keys.
=> Upgrade elastic-agent-libs to v0.2.16.

testing/environments/snapshot.yml
[start_time:Tue, 17 Jan 2023 00:18:02 GMT, release_branch:8.6, prefix:, end_time:Tue, 17 Jan 2023 04:19:06 GMT, manifest_version:2.1.0, version:8.6.1-SNAPSHOT, branch:8.6, build_id:8.6.1-cc0796ca, build_duration_seconds:14464]
=> [automation] update elastic stack version for testing 8.6.1-cc0796ca

.ci/Jenkinsfile
Adds support for Kubernetes 1.26.x version and update kind version to 0.17.0
- Relates to https://github.com/elastic/observability-dev/issues/2345
=> [Kubernetes] Add support to 1.26 k8s version

specs/metricbeat.spec.yml
Adds the `enterprisesearch/metrics` input to the metricbeat spec. 
This is necessary for the [related package](https://github.com/elastic/integrations/pull/4926) to work. If not agent will throw an `input not supported` error starting 8.6.0
```
{"log.level":"error","@timestamp":"2023-01-16T22:21:10.953Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":833},"message":"Spawned new unit enterprisesearch/metrics-default-enterprisesearch/metrics-enterprisesearch-3ac61e2c-dfa1-4d5b-af90-4ab353a576cb: input not supported","component":{"id":"enterprisesearch/metrics-default","state":"FAILED"},"unit":{"id":"enterprisesearch/metrics-default-enterprisesearch/metrics-enterprisesearch-3ac61e2c-dfa1-4d5b-af90-4ab353a576cb","type":"input","state":"FAILED"},"ecs.version":"1.6.0"}
```
=> add enterprisesearch input to metricbeat spec

.github/CODEOWNERS
Change codeowners for the path /dev-tools/kubernetes to the cloud-native monitoring team since it contains k8s manifests and scripts
So that we don't ping the Elastic Agent Control Plane when it is not necessary
=> change code owners of dev-tools/kubernetes

pkg/component/runtime/manager_test.go
Increases timeouts for `TestManager_FakeShipper`.
Sometimes the test fails with `context deadline exceeded` because not enough time is given on slower CI nodes.
- Closes #1725
=> Increase timeouts in TestManager_FakeShipper for slower CI nodes

.ci/Jenkinsfile
Use ubuntu:22 workers in the CI
Ubuntu 18 is a kind of old
Similar to https://github.com/elastic/beats/pull/34315
=> ci: use ubuntu:22 workers

internal/pkg/agent/application/coordinator/coordinator.go, internal/pkg/agent/cmd/inspect.go, internal/pkg/agent/install/uninstall.go, pkg/component/component.go, pkg/component/component_test.go
This PR takes custom headers defined during enroll and injects them into Elasticsearch config. 
Other output types do not pick these up. 
This is due to https://github.com/elastic/beats/issues/32993 which was introduced by V2 in a breaking manner. 
Every deployment with EA/APM enabled, that is using traffic filter will be broken on upgrade to 8.6.
=> Inject custom headers defined during enroll

dev-tools/kubernetes/base/elastic-agent-managed/.env, dev-tools/kubernetes/base/elastic-agent-managed/daemonset.yaml, dev-tools/kubernetes/base/elastic-agent-standalone/.env, dev-tools/kubernetes/base/elastic-agent-standalone/daemonset.yaml
Document environment variables in .env files instead of leaving comments in daemonset. it also adds extra documentation
It makes clear where to define env variables
- Relates #2104
=> pull out env vars from daemonset and document them

internal/pkg/agent/application/actions/handlers/handler_action_policy_change.go, internal/pkg/agent/cmd/enroll_cmd.go
This PR prevents headers to disappear when policy is fetched and stored
So headers from enrollment time can be applied to outputs later on.
- Build 
- Install and Enroll to fleet (default policy with system integration) with ` --header="custom=header"` flag
- run `sudo elastic-agent inspect components log-default --show-config`
- header is part of output config ✅
=> Prevent losing Headers

pkg/component/runtime/command.go, pkg/component/runtime/command_test.go
Some testcases insert 3 or more events in a loop to test the rate limiter.
On windows machines system clock ticks every 15ms so the loop we use to add events to the rate limiter run slower (we set the timer to 2 ms which translates to ~20 ms between iterations on windows). 
Using a timeframe of 50ms for the rate limiter makes the unit tests flaky when running on windows (there's a growing chance of the loop running for longer than that the more items we add)
This commit extends the timeframe of the rate limiter from 50ms to 150ms in such testcases to make sure that all the events we use in the unit tests are kept into account of a single timeframe.
This eliminates flakiness of unit tests run on CI.
To test this we can simply run the tests for a few times (10 in the example below)
```
go …
```
=> Fix TestAddToBucket flakiness on Windows

changelog/fragments/1675151497-Add-Universal-Profiling-Agent.yaml, dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl, magefile.go, pkg/component/load_test.go, specs/pf-host-agent.spec.yml
Signed-off-by: Florian Lehner <florian.lehner@elastic.co>
Add specification file for the [Universal Profiling Agent](https://www.elastic.co/observability/universal-profiling).
This change will allow elastic/elastic-agent to deploy, run and manage the [Universal Profiling Agent](https://www.elastic.co/observability/universal-profiling).
=> Add spec for Universal Profiling Agent

internal/pkg/agent/application/gateway/fleet/fleet_gateway.go, internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go, internal/pkg/agent/application/gateway/gateway.go, internal/pkg/agent/application/managed_mode.go
This PR removes reporting of errors to status reporter. We keep logs.
This was agreed https://github.com/elastic/elastic-agent/issues/1148
and implemented https://github.com/elastic/elastic-agent/pull/1152 in V1.
Change got lost in migration to V2 architecture
Fixes: #2194
=> Do not propagate gateway errors.

changelog/fragments/1675085396-preserve-state-on-upgrade.yaml, internal/pkg/agent/application/upgrade/upgrade.go, version/version.go
This PR copies run directory from stale agent to a new version of agent. Component can then pick up the state and continue where it was interrupted. This prevents creating duplicate events. 
Without this component loses state and can process whole file (in case of logs) again generating a lot of duplicate entries
Fixes: #2136
=> Preserve component state on upgrade

dev-tools/packaging/package_test.go
Adds support for excluded paths when testing the packaging.
After an update in heartbeat we have have a path like `usr/share/heartbeat/.node/node/lib/node_modules/@elastic/synthetics/templates/lightweight/heartbeat.yml` which matches the `configFilePattern` which causes a permission check which the file does not satisfy. It has nothing to do with the actual heartbeat configuration file.
```sh
cd ./dev-tools/packaging
go test package_test.go
```
- Relates https://github.com/elastic/beats/pull/33894
=> Add support for excluded paths in packaging

changelog/fragments/1674757194-entity-analytics-input.yaml, specs/filebeat.spec.yml
Adds the new Entity Analytics Filebeat input to elastic-agent added in elastic/beats#34305.
This makes that input available to be used as an integration.
- Relates elastic/beats#34305
=> filebeat.spec: Add new Entity Analytics input

internal/pkg/agent/application/upgrade/cleanup.go, internal/pkg/agent/application/upgrade/step_download.go
During upgrade we cleanup `downloads` directory after ourselves. 
This makes troubles when upgrade is fine or rolled back, and then next upgrade needs to happen. 
Downloads directory does not exist and upgrade fails
Related PR here: https://github.com/elastic/elastic-agent/pull/752
Running multiple upgrades not possible
Logs from an example failure
```json
{"log.level":"info","@timestamp":"2023-01-13T10:03:54.035+0100","log.origin":{"file.name":"upgrade/upgrade.go","file.line":111},"message":"Upgrading agent","version":"8.6.0","source_uri":"","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-01-13T10:03:54.035+0100","log.origin":{"file.name":"upgrade/upgrade.go","file.line":132},"message":"Unable to clean downloads before update","error":{"message":"unable to read directory …
```
=> Restore downloads directory before downloading

changelog/fragments/1675379107-heartbeat-engine-strict-validation.yaml, dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Agent changes matching https://github.com/elastic/beats/pull/34470.
Enables node engine validation when bundling synthetics.
https://discuss.elastic.co/t/synthetic-browser-tests-are-failing-in-version-7-x/324440/8
Change node installed version to `NODE_VERSION=13.1.0` and build heartbeat docker image locally. It should fail with:
```
#22 2.226 npm verb stack Error: Unsupported engine for @elastic/synthetics@1.0.0-beta.40: wanted: {"node":">14.14.0"} (current: {"node":"13.1.0","npm":"6.12.1"})
```
=> [Heartbeat] Enable engine strict validation for synthetics install and update node

internal/pkg/agent/application/upgrade/upgrade.go
returns nil error when failure is not there
Upgrade scenario wont work
=> Do not always fail on copy

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
There are still some unresolved questions around how we plan to get these mount points into the agent yaml (as well as the privileged flag). The cloud_defend integration won't be released until 8.8, so we are removing these commented out mount points to avoid any confusion.
As to not confuse the user or reveal details around an unfinished feature set in 8.7
~~- [ ] My code follows the style guidelines of this project~~
~~- [ ] I have added an entry in `./changelog/fragments` using the …
=> [Cloud Defend] removing these commented mounts as this feature is not going out until 8.8

.github/workflows/bump-golang.yml
Use GitHub composite action
Reuse code and solve the existing issue with Workflows won't be enabled for PRs created on behalf of `GitHub actions [bot]`, see https://github.com/elastic/ecs-logging-java/pull/200
Similar to https://github.com/elastic/ecs-logging-java/pull/201
Requires https://github.com/elastic/apm-pipeline-library/pull/2076
=> action: use composite updatecli

internal/pkg/diagnostics/diagnostics.go
Re-apply the changes from https://github.com/elastic/elastic-agent/pull/2047 again since they somehow got lost on main again.
I think this was lost during merge conflict resolution in https://github.com/elastic/elastic-agent/pull/1703 and so this only applies to 8.7 and main
=> Add the file extension in unit diagnostics again.

magefile.go
When we fail to download an artifact from the artifact API, log the affected binary and platform to make debugging easier.
Before:
```
❯ DEV=true EXTERNAL=true SNAPSHOT=true PLATFORMS=darwin/arm64 PACKAGES=tar.gz mage -v package
Running target: Package
package ran for 56.499300208s
Error: fetchBinaryFromArtifactsApi failed: the artifact was not found
```
After:
```
❯ DEV=true EXTERNAL=true SNAPSHOT=true PLATFORMS=darwin/arm64 PACKAGES=tar.gz mage -v package
Running target: Package
package ran for 56.44111175s
Error: fetchBinaryFromArtifactsApi failed for auditbeat on darwin/arm64: the artifact was not found
```
This is currently failing because the unified release snapshot for main is failing, see 7
=> Log the binary and platform on build failure.

changelog/fragments/1676358802-migrate-unencrypted-config.yaml, internal/pkg/agent/cmd/run.go, internal/pkg/agent/migration/migrate_config.go, internal/pkg/agent/migration/migrate_config_test.go
Fix upgrading from 7.17 where the unencrypted configuration contained in `fleet.yml` and `state.yml` is not copied into the corresponding encrypted stores `fleet.enc` and `state.enc`. This would cause the agent to fail reconnecting to fleet in a healthy state after upgrade.
We need to make sure that agent reconnects to fleet after upgrade.
- Install an old version of agent that does not use encrypted configuration and enroll it to a fleet server.
- Upgrade to a recent agent version that expects to find encrypted config
-  Check the health of the corresponding agent
- Closes #2249
=> Migrate unencrypted config if fleet.enc does not exist

_meta/config/common.p2.yml.tmpl, _meta/config/common.reference.p2.yml.tmpl, _meta/config/elastic-agent.docker.yml.tmpl, _meta/elastic-agent.fleet.yml, _meta/elastic-agent.yml, elastic-agent.docker.yml, elastic-agent.reference.yml, elastic-agent.yml, internal/pkg/agent/application/upgrade/artifact/download/verifier.go, internal/pkg/agent/cmd/upgrade.go
Followup to #2246
- restricts URI to be HTTPS
- ~~adds Elastic GPG as a backup~~
!! Manual backport to 7.17
=> Support only HTTPS for remote upgrade PGP

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml, dev-tools/kubernetes/base/elastic-agent-managed/daemonset.yaml
The CPU and memory requests for a standalone agent were updated to higher values than what is currently used for Fleet managed agents. Update the managed configuration to match the standalone configuration there is no reason for them to be different.
=> Fleet managed K8S resources should match standalone resources

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml, dev-tools/kubernetes/base/elastic-agent-managed/daemonset.yaml
The CPU and memory requests for a standalone agent were updated to higher values than what is currently used for Fleet managed agents. Update the managed configuration to match the standalone configuration there is no reason for them to be different.
(cherry picked from commit 9c6c5ae88001bff1756e31ff679d52456b835fde)
=> Managed K8S resources should match standalone. (#2288)

changelog/fragments/1677000534-Restore-support-for-memcached-metrics-inputs.yaml, specs/metricbeat.spec.yml
- Closes #2293
We lost support for the memcached/metrics input in 8.6 when we introduced the new specification file syntax. This PR adds it back.
@elastic/obs-service-integrations FYI since it looks like this integration is yours 
https://github.com/elastic/integrations/blob/cde97a82070665c8e2e0780401f6d4c5ceafb734/.github/CODEOWNERS#L128
=> Restore support for the memcached/metrics input.

changelog/fragments/1677048898-render-config-for-inspect-with-variable-wait.yaml, internal/pkg/agent/cmd/inspect.go
Render configuration when specifying `elastic-agent inspect --variables-wait 10s`
This way `--variables-wait` implies `--variables`
This is important to allow investigations in case of issues, as reported in the original issue #2206 
- Closes #2206
=> Render config using variables if --wait-variable option has been specified

changelog/fragments/1677255543-upgrade-watcher-fix-log.yaml, internal/pkg/agent/cmd/watch.go
This PR fixes a small bug where the incorrect log message was being emitted by the Upgrade Watcher if a crash was detected by it.
For more accurate troubleshooting.
-
=> Upgrade Watcher: Fix notification channel for crashes

changelog/fragments/1677572502-add-fleet-checkin-starting-state.yaml, internal/pkg/agent/application/gateway/fleet/fleet_gateway.go, internal/pkg/agent/application/gateway/fleet/fleet_gateway_test.go
This PR maps the State.STARTING into "starting" string sent to fleet during checkin.
This will prevent a starting agent to be flagged as unhealthy in fleet UI until the next checkin.
This should avoid confusion in the users when they see a starting agent with unhealthy state just after enrolling only to become healthy at next checkin
- Closes #2272 
We need to add an additional log call at checkin time to see what's going on:
```
diff --git a/internal/pkg/agent/application/gateway/fleet/fleet_gateway.go b/internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
index 9d9024ef5..748bf73f4 100644
--- …
```
=> Map State.STARTING as "starting" at fleet checkin to avoid presenting the agent as unhealthy at startup

_meta/config/common.p2.yml.tmpl, _meta/config/common.reference.p2.yml.tmpl, _meta/config/elastic-agent.docker.yml.tmpl, _meta/elastic-agent.yml, changelog/fragments/1677711770-fix-standalone-system-config.yaml, elastic-agent.docker.yml, elastic-agent.reference.yml, elastic-agent.yml
This fixes the config in the standalone example elastic-agent.yml files; the key should be `metricsets` not `metricset`. 
Quickly looked around some of the other k8s/docker configs, and it looks to be correct elsewhere.
The config is currently invalid in the example file.
=> Fix formatting of system metricsets in example elastic-agent config

README.md
Make the architecture file obvious by linking it from the top of the readme.
Also update the build instructions which were incomplete. We should probably find a way to link to the agent onboarding Google doc directly from the repository.
=> Link to ARCHITECTURE.md from README.md

.gitattributes
Adds
```
*.go text eol=lf
```
to `.gitattributes` as recommended by https://github.com/golangci/golangci-lint-action so `golangci-lint` works correctly under windows
golangci-lint checks aren't working without it
~~- [ ] My code follows the style guidelines of this project~~
=> fix checkout under windows for golangci-lint

changelog/fragments/1675352435-Pre-create-state-directory-inside-Docker-image-to-allow-writes-to-named-volumes.yaml, dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Type of change: Enhancement
Allows the state directory to be [mounted from a named volume](https://github.com/deviantony/docker-elk/blob/1943f25282082c561072a4705d450b9cfe246a40/extensions/fleet/fleet-compose.yml#L9-L10).
Without this change, Docker creates the directory with owner `root:root` (✅) and permissions `0640` (group read-only ❌) while mounting the volume, which prevents the default [`elastic-agent:root`](https://github.com/elastic/elastic-agent/blob/v8.6.1/dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl#L143-L145) user/group from writing inside of it.
This approach is also used in the [container image for Elasticsearch](https://github.com/elastic/elasticsearch/blob/4c15cd8a6af2572e69cee48ab6021e31864197b4/distribution/docker/src/docker/Dockerfile#L106) to …
=> Pre-create `state/` directory inside Docker image to allow writes to named volumes

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
This PR adds the required mounts and capabilities for Defend for Containers. 
`Defend for Containers` uses BPF to provide runtime security for a user's containerized workloads. The changes grant it the minimum set of privileges for these operations. 
1. I have also added the `dropall` flag with the goal of further increasing the security posture of this container. This may interfere with other integrations. I would be glad to remove this or, even better, work with other teams to help identify a reduced set of caps as needed. (Part of me is hoping that this addition will cause CI/CD to fail.) I found a great Brendan Gregg [tool](https://github.com/iovisor/bcc/blob/master/tools/capable.py) to audit the required caps of a running process. 
2. I understand that a Kustomize overlay may be …
=> Enhancement: Adding required mounts and capabilities for `Defend for containers`

changelog/fragments/1678553750-ventura-permission-issue.yaml, internal/pkg/agent/cmd/enroll.go
Monkey patch to fix the Ventura permission problem.
My PR needs to be reviewed by someone with more understanding about why it has been implemented that way (https://github.com/elastic/elastic-agent/commit/48a4703cf28ba7fd05d8f2cb1680438514a78736)
During my investigation time, I discovered that installing Elastic Agent and then Enroll it was working.
`sudo ./elastic-agent install -f`
`sudo ./elastic-agent enroll --url= --enrollment-token= `
The problem happens only when we are doing both in the same time
`sudo ./elastic-agent install --url= --enrollment-token=`
By investigating into the code, I discovered that during enrollment in the same time than installation, we are triggering two times the  FixPermissions() func
According to me, there is no reason to trigger this function during …
=> Ventura Permissions Issue

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml
Removes backticks (`) from the Elastic Agent manifests as they break the JS build when the manifests are ported to Kibana, e.g. https://github.com/elastic/kibana/pull/152936. I've opted to replace the backticks with single quotes (') to maintain the intended effect. 
There's also some autoformatting that ran on these files and improved indentation/spacing for some of the explanatory comments included in the diff.
Change allows automation for K8's manifest syncing to continue functioning.
=> [Fleet] Fix backticks in k8's manifests

deploy/kubernetes/Makefile
This PR adds an additional label to the CI Job of elastic-agent in order to allow auto merging from Fleet team side
See relevant info [here](https://github.com/elastic/kibana/pull/151500#issuecomment-1477846238)
=> Adding Label in CI of cloudnative automation for autoapprove

Vagrantfile, internal/pkg/agent/application/coordinator/coordinator.go, pkg/component/runtime/command.go, pkg/component/runtime/manager.go, pkg/component/runtime/runtime_comm.go
This PR does some minor code cleanup that was originally being done as part of https://github.com/elastic/elastic-agent/pull/2218
To keep the changes in https://github.com/elastic/elastic-agent/pull/2218/files strictly relevant to feature flags and FQDN. 
-
=> Minor code cleanup

deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
Backticks in YML comments break the Kibana build because they cause a JS syntax error. See https://github.com/elastic/kibana/pull/153515
This PR removes any instances of backticks in the various K8's manifest template files.
=> [Fleet] Remove more K8's manifest backticks that break Kibana's build

deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml, internal/pkg/composable/providers/kubernetes/config.go, internal/pkg/composable/providers/kubernetes/kubernetes.go, internal/pkg/composable/providers/kubernetes/pod.go
This PR enhances hints mechanism for logging use cases by adding the following:
1. emit mapping for all of the containers that belong to a discovered Pod and not only those that have defined Ports. This is needed so as to ensure that logs from all containers will be collected.
2. if no hints are detected then emit a generic_logs mapping so as to start collecting logs for all the discovered containers even if those are not annotated properly. This can be disabled with  `hints.default_container_logs: false`
Define the following Agent config:
```yml
providers:
kubernetes:
kube_config: /home/chrismark/.kube/config
node: "kind-control-plane"
hints.enabled: true
inputs:
- name: filestream-redis
type: filestream
streams:
- condition: ${kubernetes.hints.redis.log.enabled} == …
```
=> Fix log collection with hints when missing container ports or annotations

changelog/fragments/1679986811-pf-elastic-collector.yaml, dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl, magefile.go, pkg/component/load_test.go, specs/pf-elastic-collector.spec.yml
Add specification file for the [Universal Profiling Collector](https://www.elastic.co/observability/universal-profiling).
This change will allow elastic/elastic-agent to deploy, run and manage the [Universal Profiling Collector](https://www.elastic.co/observability/universal-profiling).
=> Add spec for Universal Profiling Collector

changelog/fragments/1680101776-Fix-actions-acks-delay.yaml, internal/pkg/remote/client.go, internal/pkg/remote/client_test.go
Fixes the issue with acks being delayed by the agent.
The cause of the issue is the shared fleet server "client" being locked here
https://github.com/elastic/elastic-agent/blob/018bc0bcd2412fbd357fac2f28140b1543f63456/internal/pkg/remote/client.go#L164
preventing any fleet server requests until the existing requests is finished.
The problem is exacerbated by the fact that there the long poll request doesn't return until there is any new action or timeout which as far as I remember was 5 minutes or possibly longer.
In such cases the acks request will be awaiting to acquire that which can only happens when the user either changes the policy or executes the action.
Depending on the timing the checkins and the actions dispatching loops, they competed with each other for one single shared …
=> Fix actions acks delay

_meta/config/common.p2.yml.tmpl, _meta/config/common.reference.p2.yml.tmpl, elastic-agent.reference.yml, elastic-agent.yml, internal/pkg/config/loader_test.go, internal/pkg/config/testdata/standalone-with-inputs.yml, internal/pkg/config/testdata/standalone1.yml
`api_key` is the correct syntax and is what is actually used in most of our example documentation. I wasted some time today starting from the reference config in the repository without noticing this.
For examples see https://www.elastic.co/guide/en/fleet/current/grant-access-to-elasticsearch.html
We should probably be using our reference examples to drive integration tests.
=> Correct api-key to api_key in example configurations

internal/pkg/agent/application/info/agent_metadata.go
Removes two statements introduced in https://github.com/elastic/elastic-agent/pull/2218 for debugging-only purposes.
The statements should've been removed before https://github.com/elastic/elastic-agent/pull/2218 was merged but I forgot to do that in my excitement to merge that PR.
=> Removing debugging statements

Vagrantfile
- Use latest Ubuntu LTS
- Change the name to elastic-agent
Updates the vagrant dev box
The current box uses a old ubuntu image and its name is a way too generic
- ~~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool]~~(https://github.com/elastic/elastic-agent#changelog)~~
Run
```vagrant up elastic-agent```
a Vagrant box using virtualbox should …
=> Update Vagrantfile dev box

changelog/fragments/1680764383-Respecting-logging.level-settings.yaml, internal/pkg/agent/cmd/run.go, internal/pkg/composable/providers/kubernetes/kubernetes.go, internal/pkg/config/operations/inspector.go, pkg/component/runtime/command.go, pkg/component/runtime/runtime.go, pkg/core/logger/logger.go, pkg/core/logger/logger_test.go
This PR sorts out loggers we have,
- internal logger was not updated with log level
- internal logger was treated as normal one and vice versa
Also avoiding calling `logger.New` wherever possible and preferring `{baseLogger}.Named`
Internal logger was not responding to level config change and as it was also the logger logging to `home/elastic-agent-hash/logs` level change was not visible in UI.
This was this way forever, what uncovered the issue was changing log level without restarting agent. When agent restarts log level is initiated from config properly.
Fixes: https://github.com/elastic/elastic-agent/issues/2450
Fixes: https://github.com/elastic/elastic-agent/issues/2399
=> Fix logger not respecting updated level

internal/pkg/agent/application/monitoring/v1_monitor.go
See https://github.com/elastic/elastic-agent-shipper/issues/267
This requires https://github.com/elastic/elastic-agent-shipper/pull/289
This adds shipper  monitoring support to elastic-agent. Right now I'm opening this as a draft PR for a few reasons:
- the `index` field in the config doesn't seem to do anything, and we just create a datastream, and I'm not sure if it needs to be there at all
- I'm not 100% sure the `dataset` and various `id` fields are set correctly.
Right now, when run with monitoring enabled, this results in two documents-per-period: one with queue metrics, and one with system resource metrics
<details>
<summary> The complete document for resource metrics</summary>
```
{
"_index": ".ds-metrics-elastic_agent.shipper-default-2023.03.29-000001",
"_id": …
```
=> Support Shipper monitoring in elastic-agent

pkg/core/logger/logger.go
This PR ensures that Elastic Agent writes its internal logs to its versioned home's `logs` folder.
When `elastic-agent diagnostics` is run, it tries to collect logs from the versioned home logs folder.  Before this PR logs were not being written to this folder so `elastic-agent diagnostics` was not collecting any Elastic Agent logs. 
Since this PR is a follow up to https://github.com/elastic/elastic-agent/pull/2456, I did test with this PR that enrolling the Elastic Agent in Fleet and changing the log level there still works as expected.  In other words, I verified that the change in this PR will not cause a regression in the bug fixed by https://github.com/elastic/elastic-agent/pull/2456.
1. Install Agent in Standalone mode.
```
sudo ./elastic-agent install
```
2. Get diagnostics bundle. …
=> Write internal logs under versioned home logs folder

internal/pkg/composable/providers/host/host_test.go
This PR doubles the sleep periods used in the `TestFQDNFeatureFlagToggle` unit test from `10ms` to `20ms`.
The `TestFQDNFeatureFlagToggle` unit test failed in CI when it ran on https://github.com/elastic/elastic-agent/pull/2472 (a PR that contains an unrelated change to this test).  When CI was re-run on the same PR without any changes, the same unit test passed.  This indicates that the test might be flaky.
I suspect the flakiness comes from not waiting long enough at critical points in the test for asynchronous operations to "catch up".  So this PR here increases those waits.
=> `TestFQDNFeatureFlagToggle` unit test: Increase sleep to avoid flakiness

internal/pkg/composable/providers/host/host_test.go, pkg/features/features.go
This PR uses `require.Eventually` instead of `time.Sleep` in a unit test.
It makes the test's timing less dependent on the speed of the system the test is being executed on, thus making the test less likely to be flaky.
Follow up to https://github.com/elastic/elastic-agent/pull/2473.
=> Use `require.Eventually` instead of `time.Sleep` in unit test

internal/pkg/agent/application/application.go, internal/pkg/agent/cmd/run.go, internal/pkg/agent/vars/vars.go, internal/pkg/composable/controller.go, internal/pkg/composable/controller_test.go, internal/pkg/composable/providers/host/host.go, internal/pkg/composable/providers/host/host_test.go, internal/pkg/core/composable/providers.go, pkg/features/features.go
This PR makes the following changes to the host provider:
* It moves the registration of the FQDN feature flag change callback function to the host provider's constructor.  
* It introduces a new `CloseableProvider` interface and updates the host provider to use this new interface. Specifically, the `Close()` method on the host provider is used to deregister the FQDN feature flag change callback.
It also changes when the feature flags from a standalone configuration are applied - at the very end of the Agent's construction process (`application.New()`).
Prior to this PR, callback registration (and deregistration) were happening inside the host provider's `Run()` method.  This introduced a race condition between when the FQDN feature flag change callback registration happened and when the …
=> Better callback registration/deregistration in host provider's lifecycle

changelog/fragments/1681311024-Ensure-local-bin-directory-exists-on-Mac-OS-during-installation..yaml, internal/pkg/agent/install/install.go
Ensures that the `/usr/local/bin` directory exists on Mac OS before it places the `/usr/local/bin/elastic-agent` symlink.
On a fresh installation of Mac OS the `/usr/local/bin` doesn't exist causing the `install` subcommand to fail to complete installation.
- Closes #2487
=> Fix install on Mac OS to ensure that the /usr/local/bin exists

pkg/component/runtime/manager_test.go
Removes skip on the `TestManager_FakeShipper` and fixes the flakiness of the test. The issue was the test didn't wait for the shippers input and output unit to be healthy before performing the sending of the event test.
Ensures that testing and configuration of a component and shipper works correctly.
- Closes #2301
=> Fix TestManager_FakeShipper flakiness.

.ci/Jenkinsfile, .ci/schedule-daily.groovy
This change is going to disable triggering the stage of e2e testing when
running from the context of a branch or tag. 
It also disabled the scheduled job from running them constantly.
We would be still able to 
trigger it by commenting `e2e tests` or putting the label `ci:end-to-end`
Signed-off-by: Alexandros, Sapranidis <alexandros@elastic.co>
The existing e2e tests are failing always. Until we fix this change disables 
them from being triggered always.
This change is affecting the CI, thus requires to setup the local elastic Jenkins setup to test this change.
- #2457
cc @cmacknz @pierrehilbert
=> Disable E2E testing stage for branch/tags

internal/pkg/agent/configuration/fleet_server_test.go
Follow up to #2495 to add tests for additional coverage
=> Add additional unit tests to fleet-server config

changelog/fragments/1677780422-fix-container-paths-config-parsing.yaml, internal/pkg/agent/cmd/container.go, internal/pkg/agent/cmd/container_test.go
This PR fixes the parsing of paths from the `container-paths.yml` file used internally when `elastic-agent container` is run.
So the expected paths are loaded from `container-paths.yml`.
-
=> Fix container paths config

internal/pkg/agent/application/upgrade/service.go, internal/pkg/agent/install/install_unix.go
This PR performs a bunch of cleanup, as suggested by golangci-lint.
When https://github.com/elastic/elastic-agent/pull/2500 was created, the `golangci-lint` linter made several suggestions in files touched by the PR, but not on lines related to the changes in that PR.  This created unnecessary noise in the PR.  To reduce that noise, I've extracted the changes to address those linter suggestions into this separate PR here.
=> Cleanup in preparation for #2500

changelog/fragments/1681842199-re-add-lumberjack-input-spec.yaml, specs/filebeat.spec.yml
Between v8.5.3 and v8.6.0 the lumberjack input was lost from the filebeat spec file.
From v8.5.3:
https://github.com/elastic/elastic-agent/blob/c0367b97a255484c3414995f32cefe6de3a12f17/internal/spec/filebeat.yml#L49
The barracuda_cloudgen_firewall integration depends on this input type.
- Relates https://github.com/elastic/integrations/issues/5912
From v8.6.0 when running https://docs.elastic.co/integrations/barracuda_cloudgen_firewall.
```
{
"@timestamp": "2023-04-18T17:03:46.412Z",
"component": {
"id": "lumberjack-default",
"state": "FAILED"
},
"ecs.version": "1.6.0",
"log.level": "error",
"log.origin": {
"file.line": 833,
"file.name": "coordinator/coordinator.go"
},
"message": "Spawned new unit lumberjack-default: input not supported",
"unit": {
"id": "lumberjack-default",
"state": …
```
=> specs/filebeat.spec.yml - Re-add lumberjack input

.ci/Jenkinsfile
Run packaging on PRs if:
- `.go-version` changes
- `Dockerfile` changes
Validate golang-crossbuild docker images are in place
Otherwise, https://github.com/elastic/elastic-agent/pull/2475#issuecomment-1514008803
=> ci: run packaging if .go-version/Dockefile changes

NOTICE.txt, go.mod, go.sum, internal/pkg/agent/application/upgrade/upgrade.go
In #2448 we I introduced custom OnErr functionality into my own fork of copy utility to help us ignore errors on copy.
This got into upstream yesterday so i'm moving back to proper repo instead of my fork
=> Copy utility pointing back to proper repo

changelog/fragments/1681942680-fix-diag-zip-file.yaml, internal/pkg/diagnostics/diagnostics.go, internal/pkg/diagnostics/dianostics_test.go
Prior to this change sub-directories within `logs/` were not created properly and resulted in unexpected directories within diagnostics files. A path separator was missing. Before the change the new test was failing with
-  Name: (string) (len=13) "logs/sub-dir/",
+  Name: (string) (len=12) "logssub-dir/",
It makes the diag zip file layout match what's on the agent host filesystem. The diag file should be correct to be trustworthy.
=> internal/pkg/diagnostics - Fix creation of sub-directories in logs/

specs/cloud-defend.spec.yml
This PR updates the args being passed to the `cloud-defend` binary on startup. 
The `run` argument was acting as a terminator. This meant that the `fleet-managed` parameter was not being parsed.
=> Update cloud defend args to run as tested in `https://github.com/elastic/elastic-agent/cloud-defend`

specs/cloud-defend.spec.yml
Updates the arguments passed to the `cloud_defend` binary. The `--fleet-managed` and `--process-managed` arguments were recently replaced with `--agent-managed`, causing cloud_defend to error-out on startup when launched by agent.
Cloud defend will not work at all without this change.
=> Update arguments in cloud_defend spec file

NOTICE.txt, changelog/fragments/1682442537-fix-pprof-diagnostics.yaml, go.mod, go.sum, internal/pkg/diagnostics/diagnostics.go, internal/pkg/diagnostics/dianostics_test.go
Change the pprof diagnostic out from text(debug) to gzipped pprof.  The text output did not contain full information to do analysis.
improves ability to debug issues.
1. install agent
2. run `elastic-agent diagnostics`
3. run `go tool pprof -http=:8080 heap.pprof.gz`
4. view in web browser
- Closes #2530
=> fix diagnostics pprof output

changelog/fragments/1682455535-Adding-Cloud-Defend-application-to-Elastic-Agent.yaml
This PR adds a change log entry for introducing Cloud Defend in 8.8 as per this [comment](https://github.com/elastic/elastic-agent/pull/2477#discussion_r1169961676)
=> Add changelog entry for Cloud Defend

changelog/fragments/1682599444-Disable-policy-and-action-signature-validation-in-the-Agent.yaml, internal/pkg/agent/application/actions/handlers/handler_action_application.go, internal/pkg/agent/application/actions/handlers/handler_action_policy_change.go, internal/pkg/agent/application/coordinator/coordinator.go
This disables the policy and the agent validation for 8.8.0 release as requested in the 
https://github.com/elastic/security-team/issues/6501
The policy and the action signature validation is handled by Endpoint only in order to reduce the impact and the scope of the release of the new feature.
The change is requested for 8.8.0 in order to reduce the impact of the completely new feature.
Full regression testing. The agent can install/enroll, receive policy, osquery and endpoint actions continue working.
- Closes https://github.com/elastic/security-team/issues/6501
=> Disable signature validation for policy and actions

changelog/fragments/1682599444-Disable-policy-and-action-signature-validation-in-the-Agent.yaml, internal/pkg/agent/application/actions/handlers/handler_action_application.go, internal/pkg/agent/application/actions/handlers/handler_action_policy_change.go, internal/pkg/agent/application/coordinator/coordinator.go
This disables the policy and the agent validation for 8.8.0 release as requested in the
https://github.com/elastic/security-team/issues/6501
The policy and the action signature validation is handled by Endpoint only in order to reduce the impact and the scope of the release of the new feature.
This is a backport to 8.8 of https://github.com/elastic/elastic-agent/pull/2562
that was merged after the switch to 8.9
The change is requested for 8.8.0 in order to reduce the impact of the completely new feature.
- Relates https://github.com/elastic/security-team/issues/6501
=> [Backport 8.8]: Disable signature validation for policy and actions (#2562)

changelog/8.7.1.yaml, changelog/fragments/1681942680-fix-diag-zip-file.yaml
This PR adds an entry we missed (for https://github.com/elastic/elastic-agent/pull/2448) to the `8.7.1` release notes.  It also deletes a fragment file whose entry (for https://github.com/elastic/elastic-agent/pull/2523) had already been merged into the `8.7.1` release notes.
So that `8.7.1` release notes are accurate + cleaning out the `changelog/fragments/` folder for the `8.7.2` release's CHANGELOG fragments.
=> Fix up 8.7.1 release notes

changelog/fragments/1682953274-Fix-container-service-token-path-issue.yaml, internal/pkg/agent/cmd/container.go, internal/pkg/agent/cmd/container_test.go
Part of the bootstrap code in container will read the service token file in order to make requests against Kibana. When the file is read the fleet.Elasticsearch.ServiceToken attribute is set and as a result both --service-token and --service-token-path flags are sent to the enroll command. This changes the flags to send only --service-token-path if both attributes are defined.
using the service token secret file is currently broken for containers
- ~~I have commented my code, particularly in hard-to-understand areas~~
- ~~I have added an integration test or an E2E test~~ e2e tests added as part of fleet-server pr: …
=> Fix issue with service token path in fleet-server bootstrap of container

internal/pkg/agent/cmd/install.go, internal/pkg/agent/cmd/install_test.go, internal/pkg/agent/cmd/install_windows_test.go, version/version.go
This PR validates the value of the `--base-path` CLI option of the `elastic-agent install` command.  If the value is not an absolute path, it returns an error. 
To prevent users accidentally attempting to install Elastic Agent in the same folder where they extracted the downloaded Elastic Agent archive, and corrupting the contents of the folder in the process.
- Fixes #2558
=> Validate install base path

_meta/config/common.p2.yml.tmpl, elastic-agent.yml
The inputs.d feature was added in https://github.com/elastic/beats/pull/30087 for elastic agent but unfortunately without any documentation. inputs.d directory is especially useful in the elastic-agent standalone mode. The close the first gap around documentation, I added it to the elastic-agent.yml file.
For awareness, this is an open issue around inputs.d directory: https://github.com/elastic/elastic-agent/issues/622
=> Add documentation around inputs.d to config file

internal/pkg/agent/application/managed_mode_test.go
Allow the dispatcher to be called multiple times in a flakey test case. Ensure that is called at least once by the periodic timer.
Fix flakey test on windows CI instances.
- ~~I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~~
- Closes #2585
=> Address flakey dispatcher flush test

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
This PR comments out the additional capabilities required to run cloud-defend. 
The BPF and PERFMON capabilities are not compatible with some older system dependencies. This includes Kubernetes 1.23 and Docker Engine v20. 
See [this](https://github.com/elastic/security-team/issues/6538) conversation for further background 
This patch removes the capabilities by default until we can deprecate support for some older depedencies or introduce a templating mechanism.
=> Comment out cloud-defend caps

catalog-info.yaml
Sets the build settings for the elastic-agent repo. 
This is part of the Buildkite migration and it is required so we trigger properly Buildkite only using the bot.
This change does not affect the elastic-agent product.
=> Set the build settings for the elastc-agent

magefile.go, pkg/testing/ess/users.go
This PR adds a `mage integration:auth` target.  For starters, it just implements authentication against GCP and ESS (QA).
This target will be invoked either directly by the user or indirectly by the integration testing framework to authenticate the user to various IaaS CSPs (GCP, AWS, Azure) and ESS (QA).   The framework will need this authentication so it can provision the necessary resources (VMs, Elastic stack deployments) as needed for the integration/E2E tests.
* [Install](https://cloud.google.com/sdk/docs/install) the `gcloud` CLI.
1. Run `mage integration:auth`
2. First, you should be taken through the GCP authentication workflow, which includes opening your browser and signing in with your `@elastic.co` Google account.  When you are done in the browser, return to your terminal.
3. …
=> Adding `integration:auth` target

.github/workflows/build.yml, .github/workflows/sonarcloud.yml
Split the GH workflow into 2 workflows. 
Using `workflow_run` the job is going to be triggered from the scope of the upstream repository.
=> Split GH workflows

pkg/control/v2/server/server.go, pkg/control/v2/server/server_test.go
Fix mapping of fleet state and message in the `StateResponse`
To avoid having always Fleet state: STARTING in `elastic-agent status` output
- Closes #2528 
- ...
=> Fix mapping of Fleet status and message in protobuf StateResponse

magefile.go
This PR enhances the `mage integration:auth` target to include a link to the ESS QA API keys page.
```
$ mage integration:auth
✔️  GCP authentication successful
❌  ESS authentication unsuccessful. Retrying...
Please provide a ESS (QA) API key. To get your API key, visit https://console.qa.cld.elstc.co/deployment-features/keys:
```
To make it easy for developers to find their ESS QA API key.  Thanks @blakerouse for the suggestion.
=> Add link to ESS QA API keys page

.github/workflows/build.yml, .github/workflows/sonarcloud.yml
This change adjusts the workflows so that the first one will build and generate the required file of a PR and archive and the second will be triggered to upload the results into the sonar cloud.
This will allow pull_requests from forks to be analyzed before merging.
=> Adjust the workflows for SonarCloud

.github/workflows/sonarcloud.yml
This commit adds a new job in the sonarcloud workflow that will be executed on push events.
Additionally, add a push trigger for the main branch, so when new code is merged on main this will be triggered and send the results into SonarCloud.
Adding also a workflow_dispatch to be able to trigger it manually
This is going to keep the main branch up-to-date in sonarcloud and the badge updated.
=> Add a new job for Sonar only on push on main

NOTICE.txt, go.mod, go.sum, pkg/testing/tools/agents.go, pkg/testing/tools/tools.go, testing/integration/fqdn_test.go, testing/integration/upgrade_test.go
This PR defines an end-to-end test — involving Elastic Agent, Fleet (Kibana + Fleet Server), and Elasticsearch — to test the FQDN feature flag feature.
To ensure that the FQDN feature flag feature works as expected with Fleet-managed Agents.
=> E2E test for FQDN feature flag

docs/test-framework-dev-guide.md
This PR starts to add a developer guide for the integration and E2E testing framework.
Closes #2640
=> Adding developer guide for integration and E2E testing framework

sonar-project.properties
Add specs folder to the sonar exclusions list
So changes in this folder are not accounted into the sonar report.
cc @cmacknz in case you have any objections and think we should include them.
=> Add specs to Sonar exclusions

changelog/fragments/1685029627-Fix-deadlock-condition-in-RuntimeManager.yaml, pkg/component/fake/component/comp/component.go, pkg/component/runtime/command.go, pkg/component/runtime/manager.go, pkg/component/runtime/manager_test.go, pkg/component/runtime/runtime.go, pkg/component/runtime/runtime_comm.go, pkg/component/runtime/service.go
Fixes a deadlock issue that can occur in the communication of updated components with the `RuntimeManager` and each of the `CommandRuntime` and `ServiceRuntime` component managers.
It is possible for a component to become disconnected from the Elastic Agent control protocol and unable to complete re-connection because a concurrent update of the component model was occurring.
This change also allows for the runtime manager to not need to settle before calling the initial `m.Update`. You can see that I was able to remove the initial delay in the existing runtime manager tests.
Only way to …
=> Fix deadlock in RuntimeManager

pkg/testing/fixture_install.go
Fix a SIGSEGV when cleaning up agent installed using fixture functionality
Integration tests fail during cleanup phase and pollute the test output
- 
- What are the …
=> Avoid SEGFAULT when cleaning up installation in integration tests fixture

.github/dependabot.yml, .github/workflows/post-dependabot.yml
Configures dependabot to automatically keep internal dependencies up to date. This was recently enabled for Beats with reasonable results. 
Example PR: 
- https://github.com/elastic/beats/pull/35533
Related:
- https://github.com/elastic/beats/pull/35525
- https://github.com/elastic/beats/pull/35538
=> Enable auto-updates of github.com/elastic/* dependencies.

changelog/fragments/1685442237-add-logs-subcommand.yaml, internal/pkg/agent/cmd/common.go, internal/pkg/agent/cmd/logs.go, internal/pkg/agent/cmd/logs_test.go
It adds the `logs` subcommand.
Following is supported:
* Print the last `-n` lines of the logs (10 by default)
* Follow the logs after printing
* Filter logs by a component ID
Improves development and troubleshooting experience.
* Unit tests with a very good coverage (all the successful paths and edge cases are covered)
* Install the agent built from this branch and then use `elastic-agent logs -f`
- Fixes #114
https://github.com/elastic/elastic-agent/assets/887952/d74fe794-25e6-493b-8045-6539e048f761
=> Add the `logs` subcommand to the CLI

NOTICE.txt, go.mod, go.sum
Dependency-only change, created with:
```
go get github.com/elastic/elastic-agent-client/v7@v7.1.2
go mod tidy
make check-ci
```
=> Bump elastic-agent-client to v7.1.2

internal/pkg/agent/cmd/logs_test.go
Fix race detector errors in `TestPrintLogs` by adding a helper implementation of `io.Writer` that synchronizes writes through a channel instead of sharing a writable buffer between goroutines.
Running `go test -race` on this test previously produced several race detector errors. With this PR there are none. The other logic of the test is unchanged.
- Followup from https://github.com/elastic/elastic-agent/pull/2790
=> Fix race detector errors in TestPrintLogs

internal/pkg/agent/application/coordinator/coordinator.go, internal/pkg/agent/application/coordinator/coordinator_test.go, internal/pkg/agent/application/coordinator/state/state.go, internal/pkg/agent/cmd/run.go, pkg/component/runtime/manager.go, pkg/component/runtime/manager_test.go, pkg/component/runtime/runtime.go
This is just a cleanup and makes no behavior changes.
- Comment functions related to `Coordinator` and `CoordinatorState` to note what goroutine(s) they're called from
- Break a large anonymous goroutine in the Coordinator out into its own helper function, `watchRuntimeComponents`
- Make the test helper `runtime.(*Manager).WaitForReady` private
- Tidy up `Coordinator.handleCoordinatorDone`, fix an if statement that previously worked by accident so it's more clear that it does the right thing
- Fix some tests that were exercising behavior that was only used by the tests.
=> Document goroutine call patterns, cleanup

docs/test-framework-dev-guide.md, magefile.go, pkg/testing/runner/config.go, pkg/testing/runner/debian.go, pkg/testing/runner/runner.go, pkg/testing/runner/supported.go
Adds a new `integration:matrix` target that explodes the possible instances to run tests on to include all possible combinations. `integration:test` always just picks the first for each OS type, the `integration:matrix` will run it on the same OS type if the runner supports different distros and versions of that type. Currently running `integration:test` the tests only run on Ubuntu 22.04, running `integration:matrix` the tests are run on Ubuntu 22.04 and Ubuntu 20.04.
Adds a new `integration:single [testName]` target that allows the selection of only a single integration test to run. This makes it easier on the developer to work and fix a single test without having to run all tests.
Fixes issue where the mage target would not return a bad exit code in the case of test failures. This now …
=> Add `integration:matrix` and `integration:single` mage targets
