.ci/Jenkinsfile
Move integration tests order
Related https://github.com/elastic/elastic-agent/issues/64
=> Move integration tests order

.ci/Jenkinsfile
Run build/test stages for `windows-2016` and `windows-2022` on a PR basis too.
e2e and ITs will always run on branches/tags
=> ci: windows os matrix and e2e/ITs for branches/tags

internal/pkg/agent/cmd/install.go
- adds non-interactive mode support to install command 
- Fixes https://github.com/elastic/elastic-agent/issues/106
=> Add non-interactive support

.github/PULL_REQUEST_TEMPLATE.md
=> Add the missing PR template

.github/workflows/golangci-lint.yml
Regarding `--whole-files`, the linter is supposed to support linting of changed a patch only but,
for some reason, it's very unreliable this way - sometimes it does not report any or some
issues without linting the whole files, so we have to use `--whole-files`
which can lead to some frustration from developers who would like to
fix a single line in an existing codebase and the linter would force them
into fixing all linting issues in the whole file instead.
-
=> Use `--whole-files` as golangci-lint argument

Makefile
Fixes https://github.com/elastic/elastic-agent/issues/264
Fixes https://github.com/elastic/elastic-agent/issues/264
- Closes [#264](https://github.com/elastic/elastic-agent/issues/264)
=> Update mage version in `makefile`

version/version.go
=> Update to 8.3.0

.mergify.yml
Adjust mergify with the 8.2 branch
=> Adjust mergify with the 8.2 branch

CHANGELOG.next.asciidoc
=> Add changelog entry for Cloudbeat and the verifier

CHANGELOG.next.asciidoc, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-role.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-role.yaml
Update deploy/kube elastic agent templates (add cronjob)
Related to https://github.com/elastic/beats/pull/30619
Update deploy/kube elastic agent templates (add cronjob)
Libbeat version used in the repo supports cronjobs
=> Update deploy/kube elastic agent templates (add cronjob)

internal/pkg/artifact/download/http/downloader_test.go
Fixes flaky test - TestDownloadBodyError
- Closes #352
=> [Flaky Test] Fix TestDownloadBodyError

.ci/Jenkinsfile
Report test results in the CI
It was not enabled and therefore the post build notifications didn't provide those details.
=> ci: enable junit reporting

internal/pkg/id/generate.go, internal/pkg/id/generate_test.go
This removes the usage of `math.rand` as the source of random data for generating ulid, this remove one of the gosec warning.
-
=> use crypto.rand in generate id with ulid.

internal/pkg/fleetapi/enroll_cmd.go
The code was incorrectly using `errors.As` to compare a received error
to an expected one. The expected type was nil and this was causing a panic.
~~- [ ] My code follows the style guidelines of this project~~
~~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~
-
=> Incorrect use of errors.As

CHANGELOG.next.asciidoc, dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl, dev-tools/packaging/templates/docker/Dockerfile.tmpl
Upgrade to a more modern node version, 16.15.0 . Draft pending more testing.
=> Update agent-complete node version to 16.15.0

version/version.go
=> Update main to 8.4.0

testing/environments/docker/redis/Dockerfile
Follow up from https://github.com/elastic/elastic-agent/pull/472
-
=> Remove redis dockerfile

internal/pkg/agent/cmd/run.go
Fixes Agent failing to run in standalone mode.
This is a backport of PR https://github.com/elastic/elastic-agent/pull/501 to 8.3 branch
```
Error: could not load agent info: storing generated agent id: open /usr/share/elastic-agent/state/data/vault/2bb80d5...7bf527a25b: no such file or directory
```
Related to the following issue: https://github.com/elastic/cloud-on-k8s/issues/5720
The root cause of the issue here is that Agent when running standalone tries to write the agentID into fleet.enc (which is encrypted former fleet.yml).
If fails because the the encryption seed was not created if the agent was not enrolled.
The fix here is to create the agent secret on run. This will not create the new key if there is one that already exists after enrollment. At it allows the agent to write the …
=> [backport 8.3]: Fix Agent failing to run in standalone mode (#501)

dev-tools/packaging/packages.yml
Adds cloudbeat as bundled in beat.
-
=> added cloudbeat to packages.yml

version/version.go
=> Update to 8.2.4

.ci/Jenkinsfile
Fix regression from https://github.com/elastic/elastic-agent/pull/509
-
=> Fix regression and use comma separated values

.ci/Jenkinsfile
Change in Jenkinsfile will trigger k8s run
-
=> Change in Jenkinsfile will trigger k8s run

version/version.go
=> update to 8.3.1

internal/pkg/artifact/download/http/downloader_test.go
Disable flaky test download test https://github.com/elastic/elastic-agent/issues/640
-
=> Disable flaky test download test

testing/environments/latest.yml
Updates test environments for 8.3.2.
=> [Release] Update test environments for 8.3.2

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, version/docs/version.asciidoc
Updates docs versions to 8.3.2.
=> docs: update docs versions 8.3.2

version/version.go
Updates references to the new release 8.3.3.
Merge after the release 8.3.2.
=> [Release] Update version to 8.3.3

internal/pkg/core/status/handler.go, internal/pkg/testutils/status_reporter.go
=> Add missing license headers

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, version/docs/version.asciidoc
Updates docs versions to 8.3.3.
=> docs: update docs versions 8.3.3

version/version.go
=> Update main to 8.5.0

version/version.go
Updates references to the new release 8.3.4.
Merge after the release 8.3.3.
=> [Release] Update version to 8.3.4

.ci/Jenkinsfile, deploy/kubernetes/Makefile, deploy/kubernetes/creator_k8s_manifest.sh, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
This PR provides the relevant Jenkins CI automation to open Pull requests to kibana github repository in order to keep Cloud-Native teams manifests in sync with the manifests that are used into Fleet UI.
For full information check https://github.com/elastic/elastic-agent/issues/706
- Updated .ci/Jenkins file that is triggered upon PR requests of /elastic-agent/deploy/kubernetes/* changes
- Updated Makefile to add functionality needed to create the extra files for the new prs to kibana remote repository
Because syncing of Manifests was until now a manual job and was prone to errors.
~~https://github.com/elastic/kibana/pull/138260~~ 
~~https://github.com/elastic/kibana/pull/138393~~
https://github.com/elastic/kibana/pull/138713
- Clone elastic-agent repo
- gh pr checkout 837
- Make a change …
=> Cloudnative ci automation

README.md
When I came across this repo, I thought it was only about docs. Changing the markdown structure clarify that it's not only docs.
Because it can prevent users to find the code and contribute while giving the impression that Elastic Agent is closed source.
N/A
N/A
N/A
N/A
=> Clarify that this repo is not only docs

version/version.go
Updates references to the new release 8.4.1.
Merge after the release 8.4.0.
=> [Release] Update version to 8.4.1

magefile.go
=> small fix to build cloudbeat into the agent on my local setup

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, version/docs/version.asciidoc
Updates docs versions to 8.4.1.
=> docs: update docs versions 8.4.1

deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
This PR is the final test for https://github.com/elastic/elastic-agent/issues/706#issuecomment-1219595181
We want to simulate a user senario where his changes will only create a PR to relevant kibana repository only when this PR is merged to master
(https://github.com/elastic/elastic-agent/issues/706#issuecomment-1219595181)
Closes #706
=> Testing PR creation for 706

internal/pkg/composable/providers/kubernetes/pod.go
Fixup leftover log levels from https://github.com/elastic/elastic-agent/pull/698.
=> Fix leftover log level

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, version/docs/version.asciidoc
Updates docs versions to 8.4.2.
=> docs: update docs versions 8.4.2

version/version.go
Updates references to the new release 8.4.3.
Merge after the release 8.4.2.
=> [Release] Update version to 8.4.3

version/version.go
The 8.5.0 branch is created, bump the version on main to 8.6.0.
@v1v I think we can automate this for agent like we have for Beats (see https://github.com/elastic/beats/pull/33154).
=> Bump version to 8.6.0.

internal/pkg/core/status/reporter.go, internal/pkg/core/status/reporter_test.go
- Fixes https://github.com/elastic/elastic-agent/issues/1340
=> Fix status reporter initialization

.ci/schedule-daily.groovy
`7.17` branch is not available in this repository
=> ci: 7.17 is not available for the daily run

version/version.go
Updates references to the new release 8.4.4.
Merge after the release 8.4.3.
=> [Release] Update version to 8.4.4

deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-role.yaml
Aligning the manifests with adding storageclass related role to stanadlone agent
Missing config. Alighnement
=> Allign managed with standalone role

deploy/kubernetes/Makefile, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset-configmap.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-role.yaml
Removing Label that breaks https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp/detail/main/507/pipeline/
=> Allighningmanifests

changelog/fragments/1667243040-Upgrade-node-to-18.12.0.yaml, dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl, dev-tools/packaging/templates/docker/Dockerfile.tmpl
This puts us on to the latest LTS release of node.
Test by using a private location with Uptime to run a browser monitor.
=> Update node version to 18.12.0 on complete image

version/version.go
Updates references to the new release 8.5.1.
Merge after the release 8.5.0.
=> [Release] Update version to 8.5.1

changelog/fragments/1668483030-common-expression-language.yaml, specs/filebeat.spec.yml
This teaches elastic-agent about the new Common Expression Language input added to Filebeat in elastic/beats#31233.
This makes that input available to be used as an integration.
- Relates elastic/beats#31233
=> filebeat.spec: make Common Expression Languate input available

version/version.go
Updates references to the new release 8.5.2.
Merge after the release 8.5.1.
=> [Release] Update version to 8.5.2

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, version/docs/version.asciidoc
Updates docs versions to 8.5.1.
=> docs: update docs versions 8.5.1

pkg/component/component_test.go
config source was not sorted.
added sorting for this as well. types makes this a bit ugly but it works
=> Sort config source for TestToComponents

version/version.go
Updates references to the new release 8.5.3.
Merge after the release 8.5.2.
=> [Release] Update version to 8.5.3

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, version/docs/version.asciidoc
Updates docs versions to 8.5.2.
=> docs: update docs versions 8.5.2

testing/environments/latest.yml
Updates test environments for 8.5.2.
=> [Release] Update test environments for 8.5.2

specs/heartbeat.spec.yml
Rename `synthetics/synthetics` integration to `synthetics/browser` to match integration spec.
1. In a cloud cluster, create a synthetics browser integration inside a policy and enroll an agent.
2.  Check that the integration is recognized and processed by heartbeat.
-  Linked to https://github.com/elastic/elastic-agent/issues/1807
=> [Synthetics] Fix synthetics-browser integration name

NOTICE.txt, go.mod, go.sum, internal/pkg/agent/application/coordinator/coordinator.go, internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
Updated elastic-agent-client to latest version fixing casing in reported unit state
Fix: https://github.com/elastic/elastic-agent/issues/1762
=> Report uppercase Unit State

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, version/docs/version.asciidoc
Updates docs versions to 8.5.3.
=> docs: update docs versions 8.5.3

internal/pkg/agent/application/monitoring/v1_monitor.go
Fixes issue where the unit name was not replacing the `/` with `_`.
Without this change the event cannot be published.
- Closes #1846
=> Fix data_stream.dataset for metrics monitoring

internal/pkg/agent/cmd/container.go
Mainly changing input type and setting proper working directory
Do not merge, i'm going to merge after checking with apm team
=> Fix how apm is started in cloud legacy mode

version/version.go
Updates references to the new release 8.5.4.
Merge after the release 8.5.3.
=> [Release] Update version to 8.5.4

specs/filebeat.spec.yml
- Enhancement
Added CometD filebeat input to elastic-agent.
Salesforce filebeat module uses `CometD` input for data collection. While working with the Salesforce migration from beats to integration, it seems like the CometD input is not added in elastic-agent. And for that reason we are not able to perform data-collection for data streams which uses the CometD filebeat input. It could be possibility that the elastic-agent `filebeat.spec.yml` doesn't have the entry for `cometd` input.
- Relates #1684
=> [O11y] Add cometd filebeat input to elastic-agent

internal/pkg/agent/application/monitoring/v1_monitor.go
Fixes: https://github.com/elastic/elastic-agent/issues/1939
=> Normalise dataset name for service logs monitor

NOTICE.txt
The check step of all PRs will fail without this.
=> Update copyright year to 2023.

deploy/kubernetes/elastic-agent-standalone/templates.d/apache.yml, deploy/kubernetes/elastic-agent-standalone/templates.d/crowdstrike.yml, deploy/kubernetes/elastic-agent-standalone/templates.d/cyberarkpas.yml, deploy/kubernetes/elastic-agent-standalone/templates.d/hid_bravura_monitor.yml, deploy/kubernetes/elastic-agent-standalone/templates.d/infoblox_nios.yml, deploy/kubernetes/elastic-agent-standalone/templates.d/iptables.yml, deploy/kubernetes/elastic-agent-standalone/templates.d/microsoft_sqlserver.yml, deploy/kubernetes/elastic-agent-standalone/templates.d/mimecast.yml, deploy/kubernetes/elastic-agent-standalone/templates.d/mongodb.yml, deploy/kubernetes/elastic-agent-standalone/templates.d/nginx_ingress_controller.yml, deploy/kubernetes/elastic-agent-standalone/templates.d/panw.yml, deploy/kubernetes/elastic-agent-standalone/templates.d/sentinel_one.yml, deploy/kubernetes/elastic-agent-standalone/templates.d/snort.yml, deploy/kubernetes/elastic-agent-standalone/templates.d/symantec_endpoint.yml, deploy/kubernetes/elastic-agent-standalone/templates.d/synthetics.yml, deploy/kubernetes/elastic-agent-standalone/templates.d/udp.yml
Automated by https://internal-ci.elastic.co/job/package_storage/job/refresh-kubernetes-templates-job/job/main/157/
=> Update kubernetes templates for elastic-agent [templates.d]

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, version/docs/version.asciidoc
Updates docs versions to 8.6.1.
=> docs: update docs versions 8.6.1

dev-tools/kubernetes/base/elastic-agent-managed/.env, dev-tools/kubernetes/base/elastic-agent-standalone/daemonset.yaml
Fix a minor bug in kustomize so that you can use it to run elastic-agent in managed mode
fix a bug
- Relates https://github.com/elastic/elastic-agent/issues/2175
- Relates https://github.com/elastic/elastic-agent/pull/2104
=> remove quotes from FLEET_ENROLL that prevented kustomize to create valid manifest

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, version/docs/version.asciidoc
Updates docs versions to 8.6.2.
=> docs: update docs versions 8.6.2

specs/cloudbeat.spec.yml
As part of the vulnerability management epic, there will be a new integration that will trigger cloudbeat to run a vulnerability scanning. This PR adds support for a new input type named `cloudbeat/vuln_mgmt_aws`.
Reolves https://github.com/elastic/cloudbeat/issues/608
-
=> [Cloud Security] Add vulnerability management support

internal/pkg/agent/application/dispatcher/dispatcher_test.go
Fix flaky unit test for dispatcher
Reduce CI failures due 
Try running the flaky unit test multiple times with and without the fix using
`go test -timeout 30s -count 10000 -run '^\QTestActionDispatcher\E$/^\QCancel_queued_action\E$' ./internal/pkg/agent/application/dispatcher`
- Closes #2302
=> Fix flaky dispatch cancel action unit test

internal/pkg/agent/storage/store/action_store.go, internal/pkg/agent/storage/store/action_store_test.go, internal/pkg/agent/storage/store/state_store.go, internal/pkg/agent/storage/store/state_store_test.go
This PR un-exports identifiers related to the Action Store from the `store` package.
The Action Store is deprecated and, AFAICT, no longer used by any code outside the `store` package.  As such, un-exporting it's identifiers will prevent any unintentional use in the future.
-
=> Un-export action store identifiers

dev-tools/mage/gotest_test.go, dev-tools/mage/keychain.go, internal/pkg/agent/application/actions/handlers/handler_action_application.go, internal/pkg/agent/application/actions/handlers/handler_action_settings.go, internal/pkg/agent/application/application.go, internal/pkg/agent/application/coordinator/coordinator.go, internal/pkg/agent/application/filters/stream_checker.go, internal/pkg/agent/application/managed_mode_test.go, internal/pkg/agent/application/monitoring/v1_monitor.go, internal/pkg/agent/application/reexec/reexec_windows.go, internal/pkg/agent/errors/error.go, internal/pkg/composable/context.go, internal/pkg/composable/dynamic.go, internal/pkg/composable/testing/dynamic.go, internal/pkg/fleetapi/ack_cmd.go, internal/pkg/fleetapi/enroll_cmd.go, internal/pkg/remote/client.go, pkg/component/component.go, pkg/component/config.go, pkg/component/runtime/command.go, pkg/component/runtime/manager.go, pkg/component/runtime/manager_test.go, pkg/component/runtime/runtime.go, pkg/component/runtime/runtime_comm.go, pkg/component/runtime/state.go, pkg/control/v2/server/server.go
This PR makes some trivial cleanup changes, in preparation for https://github.com/elastic/elastic-agent/pull/2218.
To reduce noise in https://github.com/elastic/elastic-agent/pull/2218, hopefully making it a bit easier to review.
-
=> Code cleanup

version/version.go
Updates references to the new release 8.7.1.
Merge after the release 8.7.0.
=> [Release] Update version to 8.7.1

.github/PULL_REQUEST_TEMPLATE.md
Fixes a couple of minor typos in the PR template
It's not 😄.  Just being proper.
-
=> Fix typos in PR template

internal/pkg/agent/application/coordinator/diagnostics_test.go
This PR replaces the hardcoded path to the agent config file uses in the `TestCoordinatorDiagnosticHooks` test with the path from the table-driven test parameters.
To have flexibility in using different agent configs in tests.
-
=> Un-harcode config file path

NOTICE.txt, go.mod, go.sum
This PR bumps up the dependencies of internal Elastic-owned dependencies to their next minor versions.
To avoid using pseudo-version numbers.
=> Bumping up versions for Elastic-owned internal dependencies

changelog/fragments/1681340196-More-consistent-language-in-CLI-commands.yaml, internal/pkg/agent/cmd/container.go, internal/pkg/agent/cmd/diagnostics.go, internal/pkg/agent/cmd/enroll.go, internal/pkg/agent/cmd/inspect.go, internal/pkg/agent/cmd/install.go, internal/pkg/agent/cmd/run.go, internal/pkg/agent/cmd/status.go, internal/pkg/agent/cmd/uninstall.go, internal/pkg/agent/cmd/upgrade.go, internal/pkg/agent/cmd/watch.go
This PR makes the language used by various `elastic-agent ...` CLI commands more consistent.
More polished UX.
- 
- ...
=> Make language in CLI commands more consistent

internal/pkg/agent/application/actions/handlers/handler_action_diagnostics.go
Log errors previously ignored on the diagnostics action handler
We suspect errors are happening during the diagnostics action, but there is no log showing it.
N/A
N/A
- 
- ...
=> Log errors on diagnostics handler

internal/pkg/agent/application/actions/handlers/handler_action_diagnostics.go
This reverts commit 9553905c3c13f9c25c95b497b239c71000caf632.
- 
- ...
=> Revert "log errors on diagnostics handler (#2533)"

specs/pf-elastic-collector.spec.yml, specs/pf-elastic-symbolizer.spec.yml, specs/pf-host-agent.spec.yml
Allow the Universal Profiling inputs to run in containerized environments.
=> [Universal Profiling] run components in containerized environment

version/version.go
Reverts elastic/elastic-agent#2557
=> Revert "[Release] Update version to 8.8.1"

deploy/kubernetes/creator_k8s_manifest.sh
Fixing white spaces related to https://github.com/elastic/kibana/pull/155279#issuecomment-1524988387
Cleanup
=> Fixing white spaces in desc of kibana Manifests auto generated from CI

internal/pkg/agent/application/managed_mode_test.go
Relates: https://github.com/elastic/elastic-agent/issues/2585
Disable the `Test_runDispatcher/no_gateway_actions,_dispatcher_is_flushed` test on Windows as it has been reported as flaky, and I've personally run into this test failing in one of my PRs.
=> Skip flaky dispatch test on Windows.

version/version.go
Updates references to the new release 8.7.2.
Merge after the release 8.7.1.
=> [Release] Update version to 8.7.2

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-managed/elastic-agent-managed-daemonset.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
Mount a hostPath volume to store elastic-agent state.
When the agent runs on ECK this is done by default, this PR should be considered as an alignment.
Note: There exist an env variable `STATE_PATH` https://github.com/elastic/beats/pull/24817 to define a path, but for now is used default value
in Kubernetes the agent.id is created per enroll, without persisting state agent.id will be different after each restart:
that contradict with definition of agent.id in [ecs documentation](https://www.elastic.co/guide/en/ecs/current/ecs-agent.html): `agent.ephemeral_id normally changes across restarts, but agent.id does not.`
- Relates https://github.com/elastic/elastic-agent/issues/2109
- How are we …
=> Add hostPath to store elastic-agent state

.buildkite/pull-requests.json, catalog-info.yaml
This PR adds the required configuration for the Buildkite_pr_bot that is going to be trigger builds in Buildkite
As part of the migration to Buildkite we need to be using this bot as it is part of the Elastic tooling for triggering Builds.
This is for the CI of the project and does not affect the code of the project
=> Add PR bot and update CI settings

README.md
=> Adding code coverage badge

catalog-info.yaml
Add a reference to the Backstage for the new Sonarcube project
=> Add the sonarqube project key

.github/workflows/fragment-in-pr.yml
Github Action to verify if a fragment is in the PR and to check if the syntax is correct.
Close https://github.com/elastic/elastic-agent/issues/2584
To ensure that PR that should have an entry in the changelog will have one and that we won't discover the release day that the syntax wasn't correct
- 
- ...
=> Changelog fragment Github Action

catalog-info.yaml
This commit updates the catalog-info with the annotation for the sonarcloud project-key
This commit updates the catalog-info with the annotation for the sonarcloud project-key
=> Update backstage catalog-info

README.md
Update the repository badge for the code coverage.
=> Update README with the badge

pkg/component/fake/component/main.go, pkg/component/runtime/manager.go, pkg/component/runtime/manager_test.go
Reintroduces TestManager_FakeInput_OutputChange with a small refactor
Because it's a test
- spin up the windows VM
```
vagrant up win2016
```
- connect to the VM
```
vagrant rdp win2016 
```
it did not work for me. I connected manually using [Remmina](https://remmina.org/how-to-install-remmina/) …
=> Reintroduce TestManager_FakeInput_OutputChange

.buildkite/hooks/post-checkout, .buildkite/pipeline.elastic-agent-package.yml, .buildkite/pull-requests.json, catalog-info.yaml
This is an empty initial pipeline that is going to be packaging elastic-agent.
This pipeline is intended to be used for packaging elastic-agent.
related: https://github.com/elastic/elastic-agent/issues/2595
=> Add a new packaging pipeline

version/version.go
Updates references to the new release 8.8.1.
=> [Release] Update version to 8.8.1

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, version/docs/version.asciidoc
Updates docs versions to 8.8.1.
=> docs: update docs versions 8.8.1

internal/pkg/composable/providers/host/host_test.go
Fix race detector errors in `TestFQDNFeatureFlagToggle` and `TestContextProvider` by removing a leaking error variable and reworking the test listeners to use channels.
Running `go test -race` these tests previously produced consistent race detector errors. With this PR they pass.
- Followup from https://github.com/elastic/elastic-agent/pull/2743
=> Fix race detector errors in TestFQDNFeatureFlagToggle, TestContextProvider

version/version.go
Updates references to the new release 8.8.2.
Merge after the release 8.8.1.
=> [Release] Update version to 8.8.2

catalog-info.yaml
Fix definition of the filter_condition, removing the newline character.
=> Remove newlines filter_condition

catalog-info.yaml
Specify in what branches Buildkite is going to run builds.
=> Update branch configuration

dev-tools/mage/pkg.go, magefile.go, pkg/testing/define/batch.go, pkg/testing/fixture.go, pkg/testing/fixture_install.go, pkg/testing/tools/cmd.go, pkg/testing/tools/tools.go
Small changes improving name consistency and error reporting on mage tools and the testing framework
It avoids the need to go through the code to understand why an error happened or why something does not behaves as expected.
Use `mage integration:single` to run a test that fail the build. Now you can see the error, not just "build failed"
- N/A
Before:
```
Error: failed …
```
=> Small fixes and improvements on non production code

.buildkite/pipeline.yml
It adds slack notification for buildkite pipeline results
- 
- ...
=> Add slack notification for buildkite build

.buildkite/pipeline.yml, catalog-info.yaml
=> Add slack var at the root level.

changelog/fragments/1686833548-service-runtime-info-logging.yaml, pkg/component/runtime/service.go
This PR changes the log level of messages being emitted from the `start` and `stop` methods of the service runtime to `INFO` (was `DEBUG`).
Logging from these methods at an `INFO` level provides more visibility into the installation (and therefore upgrade) and uninstallation processes of a service runtime component. Starting and stopping a service runtime component does not happen frequently so logging at `INFO` level should not add much noise.
- Fixes #2864
=> [Service runtime] Change log level to `INFO` for logging in `start`/`stop` methods

pkg/testing/runner/runner.go
Changes `ogc:latest` to `ogc:blake` that has the fixes for the firewall quota issue. Using temporary tag until this change confirms that its fully fixed and that `:blake` can be promoted to `:latest`.
Fixes for the firewall quota issue
- Closes #2806
=> Update the integration OGC usage to tag :blake

magefile.go, pkg/testing/runner/json.go
Fixes issue where the JSON testing output from `mage integration:*` was the same content as the standard output file.
JSON output is available.
- Closes #2821
=> Fix JSON output from integration tests

deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml, deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml, deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml, deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml, deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml, deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml
=> Update version to 8.9.0

deploy/kubernetes/README.md
- Bug
Fixing broken links of https://github.com/elastic/elastic-agent/tree/main/deploy/kubernetes
=> fixing links with updated urls

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, version/docs/version.asciidoc
Updates docs versions to 8.8.2.
=> docs: update docs versions 8.8.2

.dockerignore, Dockerfile.skaffold, deploy/skaffold/.env.example, deploy/skaffold/.gitignore, deploy/skaffold/kustomization.yaml, deploy/skaffold/patches/elastic-agent-managed-entrypoint.yaml, deploy/skaffold/patches/elastic-agent-standalone-entrypoint.yaml, deploy/skaffold/patches/elasticsearch-env-vars.yaml, deploy/skaffold/patches/fleet-env-vars.yaml, docs/local-k8s-testing.md, skaffold.yaml
Creates a skaffold config along with the necessary bits for (quickly) creating a docker image and manifest transformation for running/debugging agent on a local k8s cluster.
Two profiles `elastic-agent-standalone` and `elastic-agent-managed` have been created to run the agent in both modes.
*Note*: this has been tested with [kind](https://kind.sigs.k8s.io/) and [k3d](https://k3d.io/) but it should work with other local k8s cluster. It can be used also with external clusters, although the details about pushing the agent image on remote docker registries have not yet been worked out.
*Note 2*: the build of the elastic agent image is very hacky at the moment, a better way should be implemented before this change is merged
- ~~[ ] …
=> Use skaffold to run agent in k8s

testing/integration/fqdn_test.go
This PR fixes the integration/E2E tests on `main`. 
Currently, `FQDNTest` is [failing](https://buildkite.com/elastic/elastic-agent/builds/1394#01890d53-55b0-4225-8786-35bb175ef164/56-241) on `main` with a compile error like so:
```
testing/integration/fqdn_test.go:113:109: too many arguments in call to tools.InstallAgentWithPolicy
  | have (*"testing".T, *"github.com/elastic/elastic-agent/pkg/testing".Fixture, *kibana.Client, *elasticsearch.Client, kibana.AgentPolicy)
  | want (*"testing".T, *"github.com/elastic/elastic-agent/pkg/testing".Fixture, *kibana.Client, kibana.AgentPolicy)
  | FAIL	github.com/elastic/elastic-agent/testing/integration [build failed]
```
```
$ SNAPSHOT=true mage integration:single TestFQDN
>>> Pulling latest ogc image
>>> Creating zip archive of repo to send to …
```
=> Fix FQDNTest

.buildkite/pipeline.yml
- Enhancement
Enables integration tests for pull requests
Make sure that integration tests are executed on pull requests to main branch
=> Run ITs on PRs

deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
Fix path in the hints feature example
- 
- ...
=> [8.9] Update elastic-agent-standalone-kubernetes.yaml

magefile.go
Fix https://github.com/elastic/elastic-agent/issues/3004 by adding `all` as an argument to `mage integration:local` if we want to run all local test
- 
- ...
=> mage integration:local all

docs/test-framework-dev-guide.md
Enhance test framework docs.
Because we want to have good docs.
Read [docs/test-framework-dev-guide.md](docs/test-framework-dev-guide.md)
- Relates #2482
- What are the …
=> Enhance test framework docs

testing/integration/enroll_test.go
This PR removes the `EnrollRunner` test suite struct that's used by the `TestEnrollAndLog` function.
The `EnrollRunner` test suite only contains a single test method.  As such, the contents of this test method could simply be inlined into the `TestEnrollAndLog` function itself, thereby removing unnecessary complexity of the test suite. 
As an additional benefit, this change will also reduce double counting in test reports ([example](https://buildkiteartifacts.com/e0f3970e-3a75-4621-919f-e6c773e2bb12/0187faac-2a90-4642-bc78-c33cefa167ba/01892a41-e00e-49f9-8c6f-66f133491e86/01892a42-99f5-4d7d-9d50-ce150671e842/build/TEST-report.html?response-content-type=text%2Fhtml&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAQPCP3C7L5WM5OD4T%2F20230706%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20 …
=> `TestEnrollAndLog`: Remove test suite struct

testing/integration/fqdn_test.go
This PR removes the `FQDN` test suite struct that's used by the `TestFQDN` function.
The `FQDN` test suite only contains a single test method.  As such, the contents of this test method could simply be inlined into the `TestFQDN` function itself, thereby removing unnecessary complexity of the test suite. 
As an additional benefit, this change will also reduce double counting in test reports ([example](https://buildkiteartifacts.com/e0f3970e-3a75-4621-919f-e6c773e2bb12/0187faac-2a90-4642-bc78-c33cefa167ba/01892a41-e00e-49f9-8c6f-66f133491e86/01892a42-99f5-4d7d-9d50-ce150671e842/build/TEST-report.html?response-content-type=text%2Fhtml&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAQPCP3C7L5WM5OD4T%2F20230706%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230706T172631Z&X-Amz-Expires=600 …
=> `TestFQDN`: Remove test suite struct

pkg/testing/define/define.go, pkg/testing/tools/elasticsearch.go, testing/integration/enroll_test.go, testing/integration/fqdn_test.go
Fix the namespace error in the enroll integration test by setting namespace in lowercase and without special char for the policy creation.
- 
- ...
=> Testing: fix namespace error

internal/pkg/agent/application/actions/handlers/handler_action_unenroll_test.go
This PR fixes the data race found by `go test -race` in the `TestActionUnenrollHandler` unit test.
So the test passes consistently.
=> Fix data race in `TestActionUnenrollHandler` test

catalog-info.yaml
Allows @elastic/release-eng  to trigger agent package pipeline
- 
- ...
=> add permissions for release-eng to trigger package pipeline

docs/test-framework-dev-guide.md, magefile.go
Adds the `TEST_RUN_UNTIL_FAILURE=true` option to the integration testing suite.
When debugging flaky tests is helpful to have the test run over and over again until it fails.
=> Add TEST_RUN_UNTIL_FAILURE option to integration suite

.buildkite/scripts/steps/integration_tests.sh, magefile.go, pkg/testing/ogc/provisioner.go, pkg/testing/runner/config.go, pkg/testing/runner/provisioner.go, pkg/testing/runner/runner.go, pkg/testing/runner/runner_test.go
Fixes issue where `mage integration:clean` was not removing instances and stacks.
This includes a small change in the buildkite script to have it be called at the end of the `mage integration:test` like it used to. Having it do it automatically makes the script simpler and easier to read the output from buildkite.
When `mage integration:clean` is performed it does what it supposed to.
- Closes #3200
=> Fix `mage integration:clean` to actually delete instances and stacks

pkg/testing/ess/provisioner.go
Adds log message that includes the deployment ID for the ESS stack that was created for the integration suite.
To help debug issues when the stack fails to become ready.
=> Add deployment ID to ESS stack create console output

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, version/docs/version.asciidoc, version/version.go
Fix human error causing wrong version numbers.
- 
- ...
=> Fix branch version number

deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml, deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml, deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml, deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml, deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml, deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml, version/docs/version.asciidoc
Updates docs versions to 8.9.1.
=> docs: update docs versions 8.9.1

changelog/fragments/1691647290-kibana-diag-collection.yaml, internal/pkg/agent/application/actions/handlers/handler_action_diagnostics.go, internal/pkg/agent/application/actions/handlers/handler_action_diagnostics_test.go, internal/pkg/agent/application/actions/handlers/mocks/diagnostics_provider.go
This PR is adding components in the diagnostic collection when initialized from Kibana.
To get components when diag are collected from Kibana.
- Closes https://github.com/elastic/elastic-agent/issues/3294
- ...
=> Fix components in diag collection from Kibana

dev-tools/packaging/packages.yml, internal/pkg/diagnostics/diagnostics.go, testing/integration/diagnostics_test.go, version/helper.go
Rename the package version file from `.package.version` to `elastic-agent.package.version` to prevernt removal during MacOS artifact signing
To avoid logging error about the missing package version file and allow us to repackage agent also for Mac
Wait for a signed MacOS artifact, extract it and …
=> Rename package version file so it's not hidden anymore

NOTICE.txt, go.mod, go.sum
- Update elastic-agent-libs to v0.3.13
- Run go mod tidy
- Update elastic-agent-libs to v0.3.13
~~## Logs~~ …
=> Update elastic-agent-libs to v0.3.13

deploy/kubernetes/Makefile, deploy/kubernetes/elastic-agent-standalone/elastic-agent-standalone-daemonset.yaml
- Bug
Fixes the variable that produces the BRANCH value of daemonsets. The value was hardcoded. 
Relates to https://github.com/elastic/elastic-agent/pull/3246/files
```bash
cd elastic-agent/deploy/kubernetes
make generate-k8s
```
Test file `elastic-agent/deploy/kubernetes/elastic-agent-stanadlone/elastic-agent-standalone.yaml`
that contains
```yaml
```
```bash
cd elastic-agent/deploy/kubernetes
GENERATEKUSTOMIZE=tue make ci-create-kustomize
```
Test file `elastic-agent/deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml`
that contains
```yaml
```
-  …
=> Updating variable %BRANCH% to repalce hardcoded value main

internal/pkg/agent/application/upgrade/upgrade.go, testing/integration/upgrade_test.go
This reverts commit a8d8fce9073dbe08952b31a23c3df54f731d1c90.
Caused issue #3377
- Closes #3377
=> Revert "skip test while snapshot downloader cannot handle downgrades (#3314)"

NOTICE.txt, go.mod, go.sum
Use the new kibana client that sends `Elastic-Api-Version` header in all kibana http requests.
Bump `elastic-agent-libs` version to get the new kibana client
- Closes #3362
- How are …
=> Bump elastic-agent-libs to get the new kibana client

version/version.go
=> Update version to 8.10.1

internal/pkg/agent/install/uninstall_windows_test.go
Currently not working as expected and we have an issue for it [#3221](https://github.com/elastic/elastic-agent/issues/3221)
- 
- ...
=> Skip TestRemovePath

version/version.go
Updates references to the new release 8.10.2.
Merge after the release 8.10.1.
=> [Release] Update version to 8.10.2

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, version/docs/version.asciidoc
Updates docs versions to 8.10.1.
=> docs: update docs versions 8.10.1

.buildkite/scripts/steps/integration_tests.sh, version/version.go
Updates references to the new release 8.10.3.
Merge after the release 8.10.2.
=> [Release] Update version to 8.10.3

.buildkite/scripts/steps/integration_tests.sh
=> pin the agent version to 8.10.2 until new version is available

.buildkite/hooks/pre-exit
Add a buildkite pre exit hook for cleaning up of integration tests stacks and vms
Guarantees that we run `mage integration:clean` at the end of `integration test` job avoid leaking VMs and stack deployments.
We can see an example here where the build was cancelled on purpose ---> https://buildkite.com/elastic/elastic-agent/builds/3464#018abc62-f7c8-4d23-b3a5-471039638950
- ~~[ ] I have added an entry in `./changelog/fragments` …
=> add pre exit hook for integration test cleanup

specs/cloudbeat.spec.yml
As part of the CSPM for Azure epic, a new integration will trigger Cloudbeat to assess misconfiguration in the client's Azure subscription. This PR adds support for a new input type named cloudbeat/cis_azure.
- 
- ...
=> [Cloud Security] Support Azure CSPM integration

.buildkite/scripts/steps/integration_tests.sh
Stack deployments 8.10.3-SNAPSHOT and 8.11.0-SNAPSHOT are currently broken, we temporarily switch to 8.10.2 and azure ESS QA region to be able to run integration tests
We need to unblock merging of other PRs
-  …
=> Temporarily set the version to 8.10.2 and switch ESS region to run integration tests

deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
Changes url to match what `make check` will output.  Will need to reconcile in future.
get the build to run
- 
- ...
=> update kubernetes deploy yaml to match `make check` output

testing/environments/cloud/Makefile
Fixes agent version detection in [cloud first testing makefile ](testing/environments/cloud/Makefile)
- 
- ...
=> Fix version detection in cloud first testing makefile

internal/pkg/agent/install/progress_test.go
Increase the sleep timeout for testcase `TestProgress/single_step_delayed_failure` to avoid flakiness on Windows.
The tick interval for the test is set to 10 ms but the code allows for variance between 65% and 250% of such value and it expects at least 1 tick to happen (it is asserted on the regexp match as at least 1 additional `.`)
Original sleep time of 15 ms would not cover the whole possible interval, after testing on windows with different timings the most reliable seems to be ~100ms (40-50 ms would still yield a few failures when run 10000 times in a loop)
Remove flakiness for test `TestProgress/single_step_delayed_failure`
To avoid random failures in CI build
- ~~[ ] I have made corresponding changes to …
=> Increase sleep time for install progress tests

internal/pkg/agent/install/progress_test.go
allow progress tests to take more time than expected for CI
tests are flaky in CI without it
- Closes #3520 
- ...
=> make delayed progress tests more resilient

docs/test-framework-dev-guide.md
Updates documentation with the correct url for creating an API key.
We want to make full use of staging ESS to improve stability of our integration tests runs
- Relates #3535 
- ...
=> Update integ tests doc after moving to ESS staging

dev-tools/packaging/templates/ironbank/Dockerfile.tmpl, dev-tools/packaging/templates/ironbank/hardening_manifest.yaml.tmpl
=> Ironbank ubi image to 8.8

dev-tools/packaging/templates/ironbank/Dockerfile.tmpl, dev-tools/packaging/templates/ironbank/hardening_manifest.yaml.tmpl
=> UBI image to 9.2

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, version/docs/version.asciidoc
Updates docs versions to 8.10.3.
=> docs: update docs versions 8.10.3

pkg/component/fake/component/comp/apm.go
- Improve logging for apm fake input
- Close default APM tracer (would only generate noise in the logs while trying to connect to `localhost` by default)
It helps with diagnosing issues when testing APM config propagation
- ~[ ] I have made corresponding changes to the documentation~~
-  …
=> Minor fixes to apm fake component and integration test

version/version.go
Updates references to the new release 8.10.5.
Merge after the release 8.10.4.
=> [Release] Update version to 8.10.5

changelog/fragments/1696319263-add-assetbeat-dependency.yaml, dev-tools/mage/manifest/manifest.go, magefile.go
Add `assetbeat` among the external build dependencies.
`assetbeat` is a new binary designed for collecting infrastructure assets. It is intended to be included in the 8.11 release and bundled with Elastic Agent. Although the necessary steps to publish DRAs and create a filespec for assetbeat have already been completed, this particular change was inadvertently missed.
- Relates https://github.com/elastic/obs-infraobs-team/issues/1114
- Relates https://github.com/elastic/release-eng/issues/725
=> Add assetbeat as external component

pkg/component/runtime/manager_test.go
Fix the test flakiness reported in https://github.com/elastic/elastic-agent/issues/3659 by rewriting the test to have more straightforward sequencing and be more tolerant of the occasional redundant states that can happen during configuration transitions. (The reported issue happened because a component with two units sometimes reports two state changes as each unit finishes startup, but the test failed when this happened because it assumed startup could only ever produce one state change.)
- Fixes https://github.com/elastic/elastic-agent/issues/3659
=> Fix TestManager_FakeInput_GoodUnitToBad

version/version.go
Updates references to the new release 8.11.1.
Merge after the release 8.11.0.
=> [Release] Update version to 8.11.1

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, version/docs/version.asciidoc
Updates docs versions to 8.11.1.
=> docs: update docs versions 8.11.1

dev-tools/packaging/packages.yml, dev-tools/packaging/templates/ironbank/Dockerfile.tmpl, dev-tools/packaging/templates/ironbank/hardening_manifest.yaml.tmpl
Bump the `ubi:9` version to `9.3` as requested
Ironbank to use the latest secured version
- 
- ...
=> ironbank: use ubi:9.3

dev-tools/packaging/templates/ironbank/Dockerfile.tmpl
Create symlink to `/usr/bin/tini` in the ironbank docker images.
`ironbank` images can be used in ECK.
- 
- ...
=> ironbank: enable /usr/bin/tini

_meta/config/common.p2.yml.tmpl, _meta/config/common.reference.p2.yml.tmpl, _meta/config/elastic-agent.docker.yml.tmpl, changelog/fragments/1701882851-performance-presets.yaml, elastic-agent.docker.yml, elastic-agent.reference.yml, elastic-agent.yml
Update changelog and default/reference configs to reflect the performance presets feature that just went into Beats (https://github.com/elastic/beats/pull/37259)
=> Update changelog and configs for performance presets

changelog/8.11.3.asciidoc, changelog/8.11.3.yaml
=> Changelog for version 8.11.3

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, version/docs/version.asciidoc
Updates docs versions to 8.11.3.
=> docs: update docs versions 8.11.3

internal/pkg/agent/cmd/platformcheck_test.go
Skip flaky test TestCheckPlatformCompat
The test is flaky and does not seem to be testing anything as it does not have an assertion or failure condition.
Run the test `TestCheckPlatformCompat`, it should be skipped
- Relates #3964
- What are the …
=> Skip flaky test TestCheckPlatformCompat

NOTICE.txt
=> Update notice year to 2024

testing/integration/container_cmd_test.go
Skips TestContainerCMD
There is a bug in the test and it's blocking other PRs
- Run the integration tests, TestContainerCMD should be skipped
- [N/A](https://github.com/elastic/elastic-agent/issues/3984) …
=> Skip flaky test TestContainerCMD

internal/pkg/agent/application/upgrade/marker_access_test.go
Fixes TestWriteMarkerFileWithTruncation flaky test
Addresses [Flaky Test TestMarkerWatcher](https://github.com/elastic/elastic-agent/issues/3981) 
This is one way to fix this without rewriting the test too much.
The actual problem is in the TestWriteMarkerFileWithTruncation test, which also corresponds with the stack trace in the original issue.
There are few problems with that tests:
1. Race condition between Go routines that this tests starts upon the cancelling the shared context. 
Need to wait for the watcher to exit first, and only then exit from the Go routine that listens on  errCh (otherwise the watcher Go routine that writes into errCh can get blocked and leak).
https://github.com/aleksmaus/elastic-agent/blob/main/internal/pkg/agent/application/upgrade/marker_access_test.go#L44 …
=> Fix TestWriteMarkerFileWithTruncation flaky test

magefile.go
=> Fix DRA Regex

magefile.go
=> Fix separator with no value caught

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, version/docs/version.asciidoc
Updates docs versions to 8.11.4.
=> docs: update docs versions 8.11.4

.github/ISSUE_TEMPLATE/flaky-test.md
* Make it easier to create a flaky test issue
* Add labels and the project automatically.
=> Update flaky-test.md template

internal/pkg/agent/application/application.go, internal/pkg/agent/application/paths/common.go, internal/pkg/agent/application/paths/common_test.go, internal/pkg/agent/cmd/common.go, internal/pkg/release/version.go, version/helper.go
This PR allows running the agent both from a legacy directory name like `elastic-agent-<agent hash>` and the new directory name format like `elastic-agent-<agent version>-<agent hash>`.
This is needed for the downgrades in our integration tests to end up with a running agent in the integration tests for #3950 
- Relates #3950 
- How are we going to support this in …
=> Agent runs from directory with or without version

internal/pkg/agent/application/paths/paths_test.go, internal/pkg/agent/application/paths/paths_windows.go
Fixes bug in Windows implementation of HasPrefix function
bugfix
backport not required because this was added to the backport first.
https://github.com/elastic/elastic-agent/pull/4144
- #4108
- ...
=> Windows has prefix fix

catalog-info.yaml
Signed-off-by: David Natachanny <David.Natachanny@elastic.co>
Enable intermediate builds on version branches
- 
- ...
=> enable intermediate builds on version branches

dev-tools/mage/settings.go, dev-tools/packaging/packages.yml, dev-tools/packaging/templates/linux/postinstall.sh.tmpl, internal/pkg/agent/install/install.go, internal/pkg/agent/install/install_test.go
This is a subset of a bigger PR #3950, so CI is not expected to be green, especially regarding the integration tests
This PR uses the package manifest included in elastic-agent packages to map the package contents onto disk when installing. In the context of #2579 the path mapping is used to install agent in a directory like `data/elastic-agent-<package version>-<hash>`.
The install process now looks for the package manifest file and start copying mapped paths first, then copy all the unmapped files and finally creates the symlinks after remapping their targets.
This PR is needed to ensure that new versions of agents get installed to a new path containing the version from a package `data/elastic-agent-<package version>-<hash>` that still uses the legacy structure …
=> Use package manifest for install

internal/pkg/agent/application/upgrade/rollback_test.go, internal/pkg/agent/application/upgrade/step_unpack.go, internal/pkg/agent/application/upgrade/step_unpack_test.go, internal/pkg/agent/application/upgrade/upgrade.go, internal/pkg/agent/application/upgrade/upgrade_test.go, internal/pkg/agent/install/install.go, internal/pkg/agent/install/install_windows.go
This is a subset of a bigger PR #3950, so CI is not expected to be green, especially regarding the integration tests.
This PR reintroduces a modified version check when upgrading, to ensure we don't upgrade to the exact same version of the current agent. The code will check if the triplet (package version, snapshot flag and hash) are the same between the existing agent installation and the package we downloaded for the upgrade.
This prevents any collisions on the filesystem between the agent install and the files we are going to extract from the package. …
=> Reintroduce upgrade version check

version/docs/version.asciidoc
Updates docs versions to 8.12.1.
=> docs: update docs versions 8.12.1

deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, version/version.go
Updates references to the new release 8.12.2.
Merge after the release 8.12.1.
=> [Release] Update version to 8.12.2

catalog-info.yaml
This adds the ability for some folks in the `endpoint-ci-admin` group to be able to Build and Read the `elastic-agent-package` pipeline.  Here's the group: https://github.com/orgs/elastic/teams/endpoint-ci-admin
I chose this group to add since it's a pretty small group rather than the much larger `endpoint` group.
This is so @dwhyrock and @gogochan can do testing to help with implementing the Independent Agent Release workflow.
- 
- ...
=> Add Endpoint access to Build and Read for Independent Agent testing

internal/pkg/agent/application/upgrade/upgrade_test.go
Fix timeouts for `waitForWatcher()` tests so they run reliably in CI
Avoid unit test flakiness on MacOS
- 
- ...
=> Increase timeout to prevent failures on MacOS

version/docs/version.asciidoc
Updates docs versions to 8.12.2.
=> docs: update docs versions 8.12.2

.buildkite/scripts/steps/integration_tests.sh
Remove the agent version pinning to 8.12.0 for the integration tests.
Such pinning is meant to keep the integration tests running when we release a new version but we cannot package the new  version because the dependencies for such version are not available.
This has been set and forgotten causing the agent to keep using 8.12.0 version even after newer versions have been created on the branch
This restores the correct run of elastic agent integration tests in CI for 8.12 branch
- ~~[ ] I have added tests that …
=> remove 8.12.0 version pinning

testing/integration/upgrade_gpg_test.go
Temporarily disable GPG integration tests that are failing until #4317 is resolved
To have green CI builds on 8.12 branches
- Relates #4317 …
=> disable failing GPG integration tests

.buildkite/scripts/steps/integration_tests.sh, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, version/version.go
Updates references to the new release 8.12.3.
Merge after the release 8.12.2.
=> [Release] Update version to 8.12.3

internal/pkg/agent/application/actions/handlers/handler_action_cancel.go, internal/pkg/agent/application/actions/handlers/handler_action_policy_change.go, internal/pkg/agent/application/actions/handlers/handler_action_policy_change_test.go, internal/pkg/agent/application/actions/handlers/handler_action_settings.go, internal/pkg/agent/application/actions/handlers/handler_action_upgrade.go, internal/pkg/agent/application/actions/handlers/handler_action_upgrade_test.go, internal/pkg/agent/application/dispatcher/dispatcher.go, internal/pkg/agent/application/dispatcher/dispatcher_test.go, internal/pkg/agent/application/upgrade/step_mark.go, internal/pkg/agent/storage/store/action_store.go, internal/pkg/agent/storage/store/action_store_test.go, internal/pkg/agent/storage/store/state_store.go, internal/pkg/agent/storage/store/state_store_test.go, internal/pkg/config/operations/inspector.go, internal/pkg/fleetapi/ack_cmd_test.go, internal/pkg/fleetapi/acker/fleet/fleet_acker_test.go, internal/pkg/fleetapi/action.go, internal/pkg/fleetapi/action_test.go, internal/pkg/fleetapi/checkin_cmd_test.go
Refactor the agent action models to match [fleet-server's model](https://github.com/elastic/fleet-server/blob/main/model/schema.json#L5-L84) and removes the YAML serialisation, using only JSON.
Each action might have custom fields, fleet-server uses JSON, which is fine to support multiple schema, but YAML isn't. The agent having their internal action structures with a different schema cause the action to be denationalised from one schema and serialised to another, therefore loosing data when the action store loads the actions from disk.
To reduce the maintenance cost it's better to match fleet-server schema and have a single schema and serializer/deserializer for the whole code.
- ~~[ ] I have made corresponding change to …
=> Match fleet server action model and use on JSON for serialisation

pkg/testing/fetcher_http.go, pkg/testing/fetcher_http_test.go, testing/integration/upgrade_gpg_test.go, testing/upgradetest/upgrader.go
Add a simple http artifact fetcher with configurable baseURL defaulting to `artifacts.elastic.co/beats/elastic-agent`
This allows to create an agent fixture that uses officially released elastic-agent artifacts.
Downloading directly the artifact from artifacts.elastic.co ensures that we use the same artifact for the end fixture as the one downloaded by agent during an upgrade without source-uri, resolving the hash mismatch problem we have due to artifact API presenting additional builds on top of the officially released one. …
=> Fix GPG test hash mismatch

changelog/fragments/1708732907-add-postrm-script-to-deb-and-rpm-packages.yaml, dev-tools/mage/pkgtypes.go, dev-tools/packaging/packages.yml, dev-tools/packaging/templates/linux/postrm.sh.tmpl
Adds a postrm script to the deb and rpm packages.  Script does the following.
On `rpm -e` and `apt-get remove` does the following:
- stops `elastic-agent` if it is running
- deletes symlink `/usr/share/elastic-agent/bin/elastic-agent` that post install script makes
- does a systemd daemon-reload, this is necessary since the systemd unit file will be removed.
on `apt-get purge` does the following:
- recursively deletes the following directories
+ `/var/lib/elastic-agent`
+ `/var/log/elastic-agent`
+ `/etc/elastic-agent`
1) leaving `elastic-agent` running after uninstall is unexpected, and policy updates may fail because necessary resources on disk may be missing
2) leaving the symlink has lead to updates failing
3) not doing `systemctl daemon-reload` after removing the elastic-agent unit …
=> add postrm script to deb and rpm packages

.github/workflows/bump-agent-versions.yml
Otherwise, the action cannot commit and push.
Related to https://github.com/elastic/elastic-agent/pull/4331
Failed job is here https://github.com/elastic/elastic-agent/actions/runs/8180691581/job/22369212159
=> Add git credentials for versions update Github action

docs/elastic-agent-logging.md
This commit adds a brief description of how our loggers are configured and instantiated.
It improves our documentation
- How are …
=> Add documentation about logging

testing/integration/upgrade_standalone_retry_test.go, testing/integration/upgrade_uninstall_test.go
`TestStandaloneUpgradeRetryDownload` and
`TestStandaloneUpgradeUninstallKillWatcher` don't require to have a build version for the actual test. These test cases should be fine with any version that does not match the current commit hash. The previous minor version is guaranteed to not match the hash.
This change is based on this comment https://github.com/elastic/elastic-agent/issues/4320#issuecomment-2010050195
We must eventually stop using the artifact API due to its instability and deprecation.
Fetching builds for these test cases slows down the CI runtime as well.
~~- [ ] I have added tests that prove my fix is effective or that my feature …
=> Avoid using the artifact API for test-cases where it's not needed

version/docs/version.asciidoc
Updates docs versions to 8.13.1.
=> docs: update docs versions 8.13.1

.buildkite/scripts/steps/integration_tests.sh, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, testing/integration/upgrade_broken_package_test.go, version/version.go
Updates references to the new release 8.13.2.
Merge after the release 8.13.1.
=> [Release] Update version to 8.13.2

.github/workflows/bump-agent-versions.yml, magefile.go
* Fix missing snapshots due to not fetched branches
* Improve PR description + add the version requirements to the description/commit message
=> Update versions file automation

.buildkite/pipeline.yml
It started failing with permission errors, disabling while the investigation is in progress.
Build https://buildkite.com/elastic/elastic-agent/builds/8146#018eaff4-e3a8-49b4-8248-42a5727d7967
=> Temporary disable K8s sync

.github/workflows/bump-agent-versions.sh
New line characters were not recognized.
Tested locally:
=> Fix description formatting in the versions file automation

version/docs/version.asciidoc
Updates docs versions to 8.13.2.
=> docs: update docs versions 8.13.2

.buildkite/pipeline.yml, .buildkite/scripts/steps/sync-k8s.sh, deploy/kubernetes/Makefile
Changes Kibana repo URL to HTTPS
- Closes https://github.com/elastic/ingest-dev/issues/3117
=> Fix sync k8s step

.buildkite/scripts/steps/integration_tests.sh, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, testing/integration/upgrade_broken_package_test.go, testing/upgradetest/upgrader.go, version/version.go
Updates references to the new release 8.13.3.
Merge after the release 8.13.2.
=> [Release] Update version to 8.13.3

catalog-info.yaml
This commit changes the pipeline description.
This commit changes the pipeline description to match the pipeline intention. This helps when searching for pipelines and when people try to understand what they do.
=> Fix pipeline description for the gce-clean

.agent-versions.json
This file is used for picking agent versions in integration tests.
The file's content is based on responses from https://www.elastic.co/api/product_versions and https://snapshots.elastic.co
The current update is generated based on the following requirements:
```json
{
"UpgradeToVersion": "8.14.0",
"CurrentMajors": 1,
"PreviousMajors": 1,
"PreviousMinors": 2,
"SnapshotBranches": [
"8.13",
"8.12",
"7.17"
]
}
```
=> [main][Automation] Update .agent-versions.json

catalog-info.yaml
This PR enables build on branches for publishing elastic-agent-core DRA.
We need regular `elastic-agent-core` publishing to use the artifacts for elastic-agent early releases.
- Relates #4403 
- ...
=> Add build for main and release branches on elastic-agent-core DRA pipeline

.github/workflows/bump-agent-versions.sh, .github/workflows/bump-agent-versions.yml
Also, use the new / non-deprecated approach to outputs.
=> Post a link to a created PR on Slack when versions file is updated

.github/workflows/bump-agent-versions.sh, .github/workflows/bump-agent-versions.yml
So, the Slack notifications are sent when a versions file update is created.
=> Fix typo in the outputs variable

.buildkite/pipeline.elastic-agent-package.yml, .buildkite/scripts/steps/package.sh, dev-tools/mage/settings.go, magefile.go
Renames ManifestUrl environment variable to MANIFEST_URL  to align it with main and 7.17 versions
It allows unified-release jobs to run using the same set of environment variables
- 
- ...
=> Rename ManifestUrl env variable to MANIFEST_URL

changelog/fragments/1713289288-Removed-cloud-defend-from-.tar.gz-archives.yaml, dev-tools/mage/pkgtypes.go
This change filters out `cloud-defend` and `cloud-defend.spec.yml` when packaging .tar.gz archives
Cloud defend is needed only on docker images, removing it reduces the size of linux .tar.gz package by about 40 MB. 
- ...
=> Exclude cloud-defend from linux .tar.gz packages

testing/integration/package_version_test.go
Properly close `state.yaml` file in TestComponentBuildHashInDiagnostics
To fix our automated tests.
- Closes #4595 
- ...
=> close state file in TestComponentBuildHashInDiagnostics

.buildkite/scripts/steps/integration_tests.sh, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, testing/integration/upgrade_broken_package_test.go, version/version.go
Updates references to the new release 8.13.4.
Merge after the release 8.13.3.
=> [Release] Update version to 8.13.4

version/docs/version.asciidoc
Updates docs versions to 8.13.3.
=> docs: update docs versions 8.13.3

internal/pkg/agent/application/application.go, internal/pkg/config/loader.go, testing/integration/otel_test.go
Fix dependency on `elastic-agent.yml`
Fixes: #4660
=> Fix dependency on `elastic-agent.yml`

internal/pkg/otel/README.md, internal/pkg/otel/templates/README.md.tmpl
Updated readme with otel subcommand incl validate and feature flags
=> Updated otel readme

NOTICE.txt, go.mod, go.sum
See release notes here https://github.com/elastic/e2e-testing/releases/tag/v1.2.1
=> Update elastic/e2e-testing to 1.2.1

changelog/fragments/1715158488-use-snapshot-api.yaml, internal/pkg/agent/application/upgrade/artifact/download/snapshot/downloader.go, internal/pkg/agent/application/upgrade/artifact/download/snapshot/downloader_test.go, internal/pkg/agent/application/upgrade/artifact/download/snapshot/testdata/latest-snapshot.json, pkg/testing/fetcher_artifact.go, pkg/testing/fetcher_artifact_test.go
* The Elastic Agent upgrade to a snapshot is now using the more reliable snapshot API
* The artifact fetcher in testing is now using the same snapshot API
The artifact API is now used only in a single integration test-case `TestStandaloneDowngradeToSpecificSnapshotBuild`.
The artifact API is unstable and often has outages. This service is going to be deprecated soon.
The current integration tests cover the changed code.
- Closes https://github.com/elastic/elastic-agent/issues/4458
=> Don't use artifact API for snapshot downloads

.buildkite/scripts/steps/integration_tests.sh, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, version/version.go
Updates references to the new release 8.13.5.
Merge after the release 8.13.4.
=> [Release] Update version to 8.13.5

version/docs/version.asciidoc
Updates docs versions to 8.13.4.
=> docs: update docs versions 8.13.4

internal/pkg/agent/application/actions/handlers/handler_action_settings.go
Resolve https://github.com/elastic/elastic-agent/issues/4749
Fix log message when setting log level from settings action to display the log level we are setting from action, policy or default one.
=> fix log message when settings log level from SETTINGS action

dev-tools/mage/settings.go
This PR pins the default beat name to be `elastic-agent` instead of the repo directory name
This will ensure packaging succeeds regardless of the name of the directory that the code is checked out into
-
- How are we going to support …
=> Fix default beat name to elastic-agent instead of the repo directory name

.github/workflows/bump-golang.yml
Use GitHub secrets rather than Vault secrets.
GitHub secrets have been created, there is a linked PR to a private repository in this PR - in case someone wanna see this
Remove unrequited secrets for security reasons
-
- ...
=> github-actions: use GitHub secrets

.github/workflows/bump-agent-versions.yml
Use GitHub secrets for the slack bot and the `github.secret` with the proper permissions
Remove the support for accessing vault to gather those secrets.
This project uses Buildktie therefore it can use the github-bot user.
-
- ...
=> github-actions: remove apm-ci role/secret vault

internal/pkg/remote/config.go, testing/integration/proxy_url_test.go
Refactor ProxyURL integration tests into table-driven tests.
This is a commit extracted from #4770 for ease of review
This is a prerequisite for https://github.com/elastic/elastic-agent/pull/4770
- Relates #4770 
- What are the metrics I should …
=> Refactor ProxyURL integration tests

changelog/fragments/1717523676-Add-benchmark-input.yaml
Add changelog entry for adding benchmark input
Document adding enhancement
-  Relates elastic/beats#39789
- ...
=> Add changelog for adding benchmark input

magefile.go, pkg/testing/tools/git/git.go
After we create release branches we still need to maintain the right package and test versions using the Github action on demand.
=> Support package version update on any release branch

.github/workflows/bump-agent-versions.yml
Fixes the existing error after moving away from the Vault access in https://github.com/elastic/elastic-agent/pull/4790
Fixes a regression
```
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
```
-
- ...
=> github-actions: set git config user/email

testing/integration/proxy_url_test.go
Temporarily disable Proxy URL integration tests until they are not flaky anymore
To unblock other PRs
- Relates #4861 …
=> Skip flaky proxy URL tests

internal/pkg/agent/application/gateway/fleet/fleet_gateway.go, internal/pkg/agent/application/info/agent_metadata_test.go, pkg/testing/fixture.go, testing/integration/log_level_test.go
Reverts elastic/elastic-agent#4838 due to https://github.com/elastic/elastic-agent/issues/4929
=> Revert "Fix log level value reported by Agent to Fleet"

.buildkite/integration.pipeline.yml, catalog-info.yaml
Disables any github triggers for the extended testing pipeline. Since we trigger it from the main pipeline we don't need any github triggers for it
-
- ...
=> [CI] Disabled Github triggers for extended testing

catalog-info.yaml
Allows members of other teams to trigger the extended testing pipeline from the main pipeline
-
- ...
=> [CI] Relaxed permissions for extended testing pipeline

changelog/fragments/1719483857-Upgrade-NodeJS-to-LTS-18.20.3.yaml, dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Upgrade node to latest LTS v18.20.3.
=> [Heartbeat] Upgrade node to latest LTS v18.20.3

pkg/testing/fixture.go, pkg/testing/fixture_install.go
This PR adds a process dump to be taken just after the elastic-agent install fails. It is related to failures we see in the integration tests similar to 
```json
{"log.level":"info","@timestamp":"2024-06-12T18:03:34.276Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":518},"message":"Starting enrollment to URL: http://localhost:50163/","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-06-12T18:03:35.147Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":481},"message":"Restarting agent daemon, attempt 0","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-06-12T18:03:35.150Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":495},"message":"Restart attempt 0 failed: 'rpc error: code = Unavailable desc = connection error: desc = …
```
=> add process dump after failed install

testing/integration/otel_test.go
Adds an integration test for OTel logs ingestion.
```console
SNAPSHOT=true mage integration:single TestOtelLogsIngestion
```
- Closes https://github.com/elastic/elastic-agent/issues/4858
=> [otel] Add integration test for logs ingestion

.buildkite/hooks/pre-command, .buildkite/integration.pipeline.yml
Each failed integration test step will be retried once
Sometimes the tests are flaky. It's not the best practice but anyway we retry them manually 
- Closes https://github.com/elastic/ingest-dev/issues/3568
- ...
=> [CI] Automatic retries for integration tests

.buildkite/integration.pipeline.yml
Reverted integration tests retries
MAnual retries more efficient in terms of resources 
-
- ...
=> [CI] Revert integration tests retries

.buildkite/pipeline.elastic-agent-package.yml
Adds missing `DRA_WORKFLOW` variable 
-
- ...
=> [CI] Fix DRA variables

.github/workflows/post-dependabot.yml
Fixes `check for modified NOTICE.txt` and `check for modified otel README.md`. 
In cases when `NOTICE.txt` or `README.md` are already updated the `post-dependabot` workflow fails with `Nothing to commit` message.
-
- ...
=> [CI] Fix post-dependabot commit step conditionals

testing/integration/event_logging_test.go
Re-Skip Flaky test TestEventLogOutputConfiguredViaFleet
-
- ...
=> Re-Skip Flaky test TestEventLogOutputConfiguredViaFleet

testing/integration/event_logging_test.go
Skip flaky test - related https://github.com/elastic/elastic-agent/issues/5397
-
- ...
=> Skip eventlogfile test

testing/integration/upgrade_rollback_test.go, testing/upgradetest/upgrader.go
This commit fixes two problems:
1. When getting the Elastic-Agent status to check for state.UpgradeDetails, it could happen that the upgrade had already finished, thus state.UpgradeDetails was nil. Now we only check for state.UpgradeDetails if the status is upgrading
2. When CheckHealthyAndVersion checks for the version during the rollback it could get the previous version, thus failing. This is fixed by ignoring version mismatch error.
It fixes flaky tests
There is no disruptive user impact
Run …
=> Fix TestStandaloneUpgradeRollback

.mergify.yml
Use `backport-<major>.<minor>` GitHub labels  for Mergify.
We have agreed to use `backport-<major>.<minor>` GitHub labels rather than `backport-v<major>.<minor>.0` so the same GH label strategy works for the ingest and observability projects.
I decided to keep the current minor versions with the support for both labels.
-
- ...
=> mergify: support for backport-major.minor

NOTICE.txt, go.mod, go.sum
=> Update docker dependency to latest

NOTICE.txt, changelog/fragments/1726739016-otel-pprof-extension.yaml, go.mod, go.sum, internal/pkg/otel/README.md, internal/pkg/otel/components.go
This comit adds the pprofextension to the OTel collector.
As part of running benchmarks for Elastic-Agent we need to be able to take diagnostic profiles and as we onboard the OTel collector to the framework we need to enable Pprof for the OTel collector.
Once you have a packaged version of Elastic-Agent then you can start it with the following OTel config
```yaml 
#.... other stuff....
extensions:
pprof:
endpoint: localhost:5066
#... some other....
service:
extensions:
- pprof
#.. other extensions
```
- Relates: https://github.com/elastic/ingest-dev/issues/4027
- ...
=> Add pprofextension from the OTel-contrib

testing/integration/apm_propagation_test.go
Disables `TestAPMConfig` integration tests - https://github.com/elastic/elastic-agent/issues/5624
Green CI
=> Skip flaky integration test - TestAPMConfig

testing/integration/install_test.go
Follow up to https://github.com/elastic/elastic-agent/pull/5302, based on this conversation: https://github.com/elastic/elastic-agent/pull/5302/files#r1738582241
=> Add comment to replace ES query with API call

catalog-info.yaml
Temporarily makes the new integration testing pipeline run every 6 hours (4 times per day). 
We have to make sure that the new pipeline is stable and faster than the current one in all cases
- Closes https://github.com/elastic/ingest-dev/issues/4465
- ...
=> [CI] Run Buildkite integration tests by CRON

.buildkite/bk.integration.pipeline.yml
Fixed the VM image definition in the new integration pipeline
-
- ...
=> [CI] Fix windows image prefix in the new integration pipeline

.buildkite/bk.integration.pipeline.yml, .buildkite/scripts/integration-tests.ps1, .buildkite/scripts/steps/ess.ps1
Adds `ess.ps1` script that controls ess deployments for windows tests. If a test retried, it will spin up a new ESS deployment for the retried test group for better reproducibility.
Improves log integration tests log messages
[Retried test on Windows(simulated test failure)](https://buildkite.com/elastic/elastic-agent-extended-testing-bk/builds/137#01932ba4-2794-4720-9510-813ee73c81b6) 
- On the 1st run it uses the shared ESS deployment
- On the 2nd run it created its own deployment and destroyed it in the end
[Positive scenario without retries and simulated test failures](https://buildkite.com/elastic/elastic-agent-extended-testing-bk/builds/138#_)
Logs structure is refactored 
That allows to retry Windows tests in an isolated environment 
- Closes …
=> [CI] Buildkite integration tests: Windows ess retry script

.buildkite/bk.integration.pipeline.yml, .buildkite/scripts/sudo-integration-tests.sh
Added sudo int tests running on RHEL8
Buildkite builds: https://buildkite.com/elastic/elastic-agent-extended-testing-bk/builds?branch=rhel8-tests-for-elastic-agent
To run int tests separately and initiate independent restarts, granularly run tests and optimize the tests duration
- Relates: https://github.com/elastic/ingest-dev/issues/4454
- ...
=> Add RHEL8 rpm sudo integration tests step

.buildkite/bk.integration.pipeline.yml
AWS ARM instance CPU and mem count equal to `n1-standard-8` that we use on GCP
-
- ...
=> [CI] Buildkite integration tests: Made AWS ARM instance size equal to GCP x86_64

testing/integration/logs_ingestion_test.go
Fixes `logs integration test` by ignoring the error with GCP.
Addition to https://github.com/elastic/elastic-agent/pull/6031
-
- ...
=> [CI] Fix logs integration test

.buildkite/bk.integration.pipeline.yml
Adding analytics plugin to automate flaky tests analysis 
Buildkite builds: [![Build status](https://badge.buildkite.com/1830453c9a36b16044d1302f73befd7a2b748a199bcc8c3391.svg?branch=analytics-plugin-for-bk-int-tests)](https://buildkite.com/elastic/elastic-agent-extended-testing-bk/builds?branch=analytics-plugin-for-bk-int-tests)
- Relates: https://github.com/elastic/ingest-dev/issues/4516
- ...
=> Added analytics plugin

pkg/testing/tools/fleettools/fleet.go
when [GetAgentByPolicyIDAndHostnameFromList](https://github.com/elastic/elastic-agent/blob/15e1e95ebaf4d41d42eccf5f6bb5c405c2290d6a/pkg/testing/tools/fleettools/fleet.go#L32) fails it prints found hostnames which are always empty.
If the agent is not found by hostname it always prints `Found: []` because the hostnames are not appended to the slice. ([error example](https://buildkiteartifacts.com/e0f3970e-3a75-4621-919f-e6c773e2bb12/019268b5-d168-481c-adb4-97dc4815ef86/0193670f-ad64-476f-9c1b-eaebe6b7e754/01936710-38e2-4529-bb07-fc36aa309554/build/TEST-report.html?response-content-type=text%2Fhtml&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAQPCP3C7L24YRUQA4%2F20241126%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241126T102158Z&X-Amz-Expires=600&X-Amz-Security-Token=IQoJb3JpZ2luX2V …
=> [CI] Test improvement: propely collect hostnames for logging

.buildkite/hooks/pre-command, .buildkite/scripts/integration-tests.ps1, .buildkite/scripts/steps/integration_tests.sh, .buildkite/scripts/steps/integration_tests_tf.sh
Adds `BUILDKITE_ANALYTICS_TOKEN` to enable test analytics. 
[Test run](https://buildkite.com/elastic/elastic-agent-extended-testing-bk/builds/229)
It will detects flaky and long-running tests. [Example analysis](https://buildkite.com/organizations/elastic/analytics/suites/elastic-agent-ci/tests/6ad53661-4e24-8534-aa76-fd2c9868b1d5?branch=main)
-
- ...
=> [CI] Add BUILDKITE_ANALYTICS_TOKEN to buildkite integration tests

.buildkite/hooks/pre-command, .buildkite/scripts/steps/integration_tests.sh
Fixes `BUILDKITE_ANALYTICS_TOKEN` usage for OGC integration tests
-
- ...
=> Hotfix BUILDKITE_ANALYTICS_TOKEN

internal/pkg/agent/application/monitoring/v1_monitor.go, internal/pkg/agent/application/monitoring/v1_monitor_test.go
Increase the default failure threshold introduced in #5999 from 2 to 5
The increase of failure threshold should reduce the number of false positive DEGRADED states for elastic-agent due to transient errors.
- Closes #5332  …
=> Increase failure threshold for agent monitoring inputs from 2 to 5

.github/workflows/bump-agent-versions.yml, .github/workflows/bump-golang.yml, .github/workflows/updatecli-compose.yml
2.0 was a breaking change and the signature changed, https://github.com/elastic/elastic-agent/pull/6032 missed to update the relevant inputs.
-
- ...
=> gh-actions: fix slack bump

.buildkite/bk.integration.pipeline.yml
Relates https://github.com/elastic/ingest-dev/issues/4610
ARM tests make tests flaky
-
- ...
=> [CI] Skip new ARM tests

.buildkite/bk.integration.pipeline.yml
Reverts test-collector plugin. 
It fails main branch builds and doesn't support windows
-
- ...
=> [CI] Reverted test collector plugin for BK integration tests. 

internal/pkg/agent/application/monitoring/v1_monitor.go, internal/pkg/agent/application/monitoring/v1_monitor_test.go
Support parsing elastic-agent `monitoring.failure_threshold` from a float64 (as it's received in this format when setting an integer in fleet config)
Allows setting the value as an integer in Fleet policy (setting it as a string already works)
- Closes #6152 
- ...
=> Add support for failureThreshold passed as float64 from policy

pkg/testing/define/define.go, pkg/testing/define/define_autodiscovery.go, pkg/testing/define/define_autodiscovery_test.go, pkg/testing/define/define_flags.go, testing/integration/main_test.go
Implement integration test autodiscovery using a plain `go test` call like `go test -tags integration github.com/elastic/elastic-agent/testing/integration -v -args -integration.dry-run=true -integration.autodiscover`.
The YAML output is written in a file (by default `discovered_tests.yaml`) and is structured  like the sample below (some parts have been omitted to keep the sample short)
```yaml
- os_family: windows    # This indicates on which OS type we need to run the test
arch: amd64                 # This indicates on which CPU architecture we need to run the test
os: ""                              # This indicates on which OS (by name) we need to run the test ("" means any OS for the given type)
version: ""                     # This indicates on which OS version we need to run the …
```
=> Integration tests autodiscovery

.buildkite/bk.integration.pipeline.yml, .buildkite/hooks/pre-command, .buildkite/scripts/buildkite-integration-tests.sh, .buildkite/scripts/integration-tests.ps1
Introduces an Aggregator step that downloads all JUnit reports and sends them Buildkite test analytics.
All test reports now have a fully-qualified name with OS information and sudo/non-sudo flag. 
[Build example](https://buildkite.com/elastic/elastic-agent-extended-testing-bk/builds/294#0193abd8-36ff-4d88-bac2-07c268d5d2a1) for Windows, RPM and Ubuntu with the aggregator step usage. 
[Buildkite test analytics report](https://buildkite.com/organizations/elastic/analytics/suites/elastic-agent-ci/runs/ed88cd5c-ae39-81d4-94d2-3d9b4a5abd96)
- Closes https://github.com/elastic/ingest-dev/issues/4516
- ...
=> [CI] Added test report aggregation for test-collector plugin

deploy/helm/elastic-agent/Chart.yaml, deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/fleet-managed/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/kubernetes-default/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/kubernetes-only-logs/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/nginx-custom-integration/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/system-custom-auth-paths/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/user-cluster-role/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/user-service-account/rendered/manifest.yaml, magefile.go
This PR extends the logic of `mage helm:updateAgentVersion` to include updating the `version` (chart version) and `appVersion` keys in the Chart.yaml of the Elastic-Agent Helm chart. Note that since the chart is not yet GA for the chart version we always append `-SNAPSHOT` to mark it as devel. This will have to change when we reach the version that the Helm chart is GA.
It is important because it sets correctly the chart and the app version in the Chart.yaml of the Elastic-Agent Helm chart and this is required before being able to release the Helm chart.
N/A
change either or both `version` and `appVersion` in `deploy/helm/elastic-agent/Chart.yaml` and then run `mage helm:updateAgentVersion`. The two fields will get updated to reflect the correct values based on the branch you are.
- …
=> chore: update version and appVersion in the elastic-agent helm chart

testing/environments/cloud/variables.tf
This PR updates the GCP region and ESS deployment template ID in the Terraform variables file to values that are currently acceptable in ESS, as per https://www.elastic.co/guide/en/cloud/current/ec-regions-templates-instances.html.
So ESS deployments can be spun for testing Elastic Agent changes in ESS, as per https://github.com/elastic/elastic-agent?tab=readme-ov-file#testing-on-elastic-cloud
None, as this change only impacts Elastic Agent developers.
1. Run `EC_API_KEY=your_api_key make apply`, replacing `your_api_key` with an [API key from your ESS account](https://cloud.elastic.co/account/keys).
2. You may see failures about the Elastic Agent version and the command may not succeed, but you should **not** see failures like `api error: deployments.elasticsearch_using_legacy_dt: The …
=> [ESS Testing] Update ESS region and deployment template ID

.github/workflows/mergify-labels-copier.yml
Copy GitHub labels from the original PR to the mergify backports.
-
- ...
=> github-actions: copy gh labels to the mergify backports

.github/workflows/pre-commit.yml, .pre-commit-config.yaml
Use pre-commit with a subset of checks and run in the CI always.
Similarly done at https://github.com/elastic/beats/pull/42377
Help with detecting merge conflicts or shebang issues 
-
- ...
=> github-actions(pre-commit): detect merge conflicts and shebangs

changelog/fragments/1738234199-heartbeat-upgrade-nodejs-18-20-6.yaml, dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Upgrade node to latest LTS v18.20.6.
=> [Heartbeat] Upgrade Node to LTS v18.20.6

catalog-info.yaml
This commit updates branch_configuration and branch filters in CI pipeline definitions to support the new 9.* branches.
Enables automated runs of important CI jobs like DRA on new 9.* branches
Can only tested in BK after merge.
=> Update branch filters to include/exclude 9.*

testing/integration/upgrade_gpg_test.go, testing/integration/upgrade_rollback_test.go, testing/integration/upgrade_standalone_retry_test.go, testing/integration/upgrade_standalone_same_commit_test.go
This PR skips 4 integration tests that are flaky on windows to unblock agent CI
To allow CI to become stable again
- Supersedes https://github.com/elastic/elastic-agent/pull/6728
- ...
=> Skip flaky tests on windows while root cause is being investigated

.buildkite/pull-requests.json
Skip CI for `.mergify.yml`
faster builds. `.mergify.yml` is not honoured in the CI, it's a SaaS and cannot be tested directly in our CI
-
- ...
=> ci(buildkite): skip ci builds when changing the .mergify.yml file

.mergify.yml
=> Mergify: add backport-9.0

.buildkite/bk.integration.pipeline.yml, .buildkite/pipeline.yml
Adds Windows 2025  integration tests 
-
- ...
=> [CI] Windows 2025 integration tests

changelog/fragments/1740492672-set-replicas-for-gateway-collector.yaml, deploy/helm/edot-collector/kube-stack/managed_otlp/values.yaml, testing/integration/otel_helm_test.go
If the `spec.replicas` field is not set for the gateway OpenTelemetry Collector, the horizontal Pod autoscaler fails with the following error:
```
Conditions:
Type         Status  Reason          Message
----         ------  ------          -------
AbleToScale  False   FailedGetScale  the HPA controller was unable to get the target's current scale: Internal error occurred: the spec replicas field ".spec.replicas" does not exist
Events:
Type     Reason          Age                     From                       Message
----     ------          ----                    ----                       -------
Warning  FailedGetScale  107s (x779 over 3h14m)  horizontal-pod-autoscaler  Internal error occurred: the spec replicas field ".spec.replicas" does not exist
```
The configuration will still …
=> fix: set gateway k8s replicas spec

.buildkite/pipeline.elastic-agent-binary-dra.yml
Fixes Core DRA snapshot build by splittion the build step into separate steps
`x86_64: Elastic-Agent Core Snapshot` produces:
* elastic-agent-core-9.1.0-SNAPSHOT-linux-x86_64.tar.gz 
* elastic-agent-core-9.1.0-SNAPSHOT-darwin-aarch64.tar.gz
* elastic-agent-core-9.1.0-SNAPSHOT-darwin-x86_64.tar.gz
* elastic-agent-core-9.1.0-SNAPSHOT-windows-x86_64.zip
`ARM: Elastic-Agent Core Snapshot` produces:
* elastic-agent-core-9.1.0-SNAPSHOT-linux-arm64.tar.gz + sha + csv
[Build example](https://buildkite.com/elastic/elastic-agent-binary-dra/builds/2548)
-
- ...
=> [CI] Fix Core DRA crossbuild

.buildkite/pipeline.elastic-agent-package.yml
Fixes unified release ARM artifacts packaging caused by the golang-crossbuild issue. 
Introduces an additional ARM packaging step that unilizes an ARM VM instead of the broken emulation.
Similar to https://github.com/elastic/elastic-agent/pull/7203
[Example build](https://buildkite.com/elastic/elastic-agent-package/builds/4586#01956b0c-9062-4dbd-b10f-46ae0084052a) provides the same artifacts as before
Test triggered via this PR in Buildkite: https://buildkite.com/elastic/elastic-agent-package/builds/4570
-
- ...
=> [CI] Fix unified release ARM packaging

pkg/testing/kubernetes/kind/provisioner.go
Fixes a bug preventing the kind provisioner for integration tests from deleting the clusters it creates. The provisioner was trying to delete the cluster using the wrong name.
This wasn't visible in logs because the `kind delete cluster` command always returns success, even if the cluster doesn't exist. I added a check for this to detect this situation in the future.
We should clean up resources after integration tests.
```
SNAPSHOT=true EXTERNAL=true PACKAGES=docker PLATFORMS="linux/amd64" mage -v  package
TEST_INTEG_CLEAN_ON_EXIT=true INSTANCE_PROVISIONER=kind STACK_PROVISIONER=stateful SNAPSHOT=true mage integration:kubernetesMatrix
```
Possibly related to #7060.
=> Fix a bug preventing kind cluster deletion in K8s tests

deploy/helm/elastic-agent/Chart.lock, deploy/helm/elastic-agent/Chart.yaml, deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/fleet-managed-ksm-sharding/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/fleet-managed/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/kubernetes-default/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/kubernetes-ksm-sharding/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/user-service-account/rendered/manifest.yaml
This PR bumps the `kube-state-metrics` (KSM) subchart dependency in the Elastic Agent Helm chart to its latest version.  
Specifically, it updates `kube-state-metrics` from version `5.28.0` to `5.30.1`, along with the corresponding digest update in `Chart.lock`. The generated manifests and configuration files have been updated to reflect this change, including updating the associated KSM application version from `2.14.0` to `2.15.0`.
Keeping dependencies up to date ensures compatibility with the latest features, security patches, and performance improvements. This update helps maintain alignment with the latest `kube-state-metrics` Helm chart from the Prometheus community.
This change should not introduce any disruptive impact. 
Install any of the kubernetes examples with ksm enabled in a …
=> [helm]: bump elastic-agent helm chart ksm dependency

changelog/fragments/1740692584-Fixes-an-issue-where-FixPermissions-on-Windows-incorrectly-returned-an-error-message-due-to-improper-handling-of-Windows-API-return-values.yaml, go.mod, go.sum, internal/pkg/acl/acl.go, internal/pkg/acl/acl_windows.go, internal/pkg/acl/acl_windows_test.go, internal/pkg/agent/install/uninstall_windows.go, internal/pkg/agent/install/user_windows.go, internal/pkg/agent/perms/windows.go, pkg/ipc/listener_windows.go, testing/installtest/checks_windows.go, testing/integration/logs_ingestion_test.go, testing/upgradetest/upgrader.go
This PR fixes an issue in Windows permission handling where `FixPermissions` could return an incorrect error message: `"The operation completed successfully."` The issue was caused by improper handling of the return value from Windows API calls, such as in `SetNamedSecurityInfoW`. 
Previously, the code was relying on `GetLastError`, which does not always provide relevant information in this context. Instead, the correct approach is to check the primary return value (`ret`) from the system call itself. The fix ensures that errors are propagated correctly, preventing misleading error messages.
To achieve the above, this PR removes the dependency on `github.com/hectane/go-acl` and replaces it with an internal implementation of `acl.Apply`.
- Prevents misleading error messages.
- Ensures …
=> [bug] handle syscall errno in windows permissions

internal/pkg/otel/manager/manager_test.go
Disables building and running flaky unit-test of internal/pkg/otel/manager on windows
Because the unit-tests of this package are causing too frequent CI failures on windows
- Relates https://github.com/elastic/elastic-agent/issues/7069
=> [Flaky Test]: skip running unit-tests for internal/pkg/otel/manager on windows

catalog-info.yaml
Let the given GH team to run the builds, that pipeline was created in https://github.com/elastic/elastic-agent/pull/7176
This will let us trigger the BK pipelines in GH actions when a release >= 8.18 has been shipped.
Relates to https://github.com/elastic/elastic-agent/issues/5486
- ...
=> catalog-info: add GH team to automate triggering the build in GH actions

catalog-info.yaml
- grant me access to run elastic-agent-package
- remove access for everyone to build beats-agent-serverless-tests
Help me to run https://github.com/elastic/elastic-agent/pull/7232 and apply changes from the discussion  at https://github.com/elastic/elastic-agent/pull/7204
-
- ...
=> catalog-info: allow robots to elastic-agent-package and avoid everyone to run beats-agent-serverless-tests

.github/workflows/release-helm-charts.yml
Enable GH action to [listen for any GH releases](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#release) that are published in https://github.com/elastic/elastic-agent/releases. If so, it will use the BK service pipeline to publish the release.
Support helm charts from >= `8.18`.
Report failures in Slack if a release.
Enable GH action to run on 'demand' to test the workflow works as expected using DEV and SNAPSHOTS.
```mermaid
sequenceDiagram
%% Boxes
box rgb(33,66,99) GitHub Elastic Agent
participant gh_release as GitHub release
participant gh_workflow as GitHub workflow
end
box Purple Buildkite Elastic Agent
participant bk_helm_charts as elastic-agent-helm-charts
end
box OIDC
participant gcp_storage as GCP Storage
end …
```
=> github-actions: post-release event to publish helm-chart

testing/integration/kubernetes_agent_standalone_test.go
This PR skips the TestKubernetesAgentStandaloneKustomize k8s integration test because recently they showcase flakiness
our CI needs to remain green
None
- Relates https://github.com/elastic/elastic-agent/issues/7356
=> [skip] flaky TestKubernetesAgentStandaloneKustomize

.buildkite/pipeline.elastic-agent-binary-dra.yml
Run staging when staging and run snapshot when snapshot
https://github.com/elastic/elastic-agent/pull/7232 introduced the triggering but it did not split by type of DRA workflow
-
- ...
=> bk: helmcharts for snapshot in the snapshot group

.github/workflows/release-helm-charts.yml
https://github.com/elastic/elastic-agent/pull/7303 created the GH workflow but it was not tested in isolation
fixes
```
jq: invalid JSON text passed to --argjson
Use jq --help for help with command-line options,
or see the jq manpage, or online docs  at https://jqlang.github.io/jq
Error: BUILD_ENV_VARS provided invalid JSON: SNAPSHOT="true"
```
see https://github.com/elastic/elastic-agent/actions/runs/13814636784/job/38644542221
quotes don't work
in the CI see https://github.com/elastic/elastic-agent/actions/runs/13814727361
-
- ...
=> github-actions: use raw values

internal/pkg/agent/application/dispatcher/dispatcher.go
```
.../application/dispatcher: use reflect.Type rather than string for dispatch
reflect.Type is comparable and stable for any given type, so rather than
rendering a string to key dispatch on, use the reflect.Type. This saves
allocations and hashing time.
```
Improves performance and reduces code.
No user impact.
Run `go test` in internal/pkg/agent/application/dispatcher.
-
- ...
=> .../application/dispatcher: use reflect.Type rather than string for dispatch

.buildkite/bk.integration.pipeline.yml
Makes integration tests use specific elastic-agent VM images. 
Elastic-agent specific VM images will use a different approach to pre-install tools
-
- ...
=> [CI] Dedicated elastic-agent VM images for integration tests

.buildkite/pipeline.yml
Replaces core VM images with advanced custom VM images with preinstalled go, mage, and many other tools
It will make CI a bit faster and consistent with the integration tests
-
- ...
=> [CI] Run Ubuntu and Windows unit tests using custom VM images

pkg/component/runtime/manager.go
```
pkg/component/runtime: limit scope of updateInProgress status flag
The updateDoneChan and upDateInProgress status variables were not accessed or
updated outside the scope of (*Manager).runLoop except during initialisation,
and the scope is only in existence once, so make them local to that scope.
```
Reduces code and limits range for bug in doing so.
This is unclear to me. Running `go test` in the package at main (currently 456bcdad83e58b34286af4cb137fac7529b29b42) fails, so what a correct test set-up is is unclear.
-
- ...
=> pkg/component/runtime: limit scope of updateInProgress status flag

catalog-info.yaml
Add permissions for triggering a build from another build. Even though it's a merge commit event.
This [BK build](https://buildkite.com/elastic/elastic-agent-binary-dra/builds/2711) failed
See https://buildkite.com/docs/pipelines/configure/step-types/trigger-step#permissions
The current security model is a little bit complicated now:
- https://github.com/elastic/elastic-agent/blob/a439f4edecaf176d463bf10a9057f6f54a58fd45/.buildkite/pull-requests.json#L35-L50
- https://github.com/elastic/elastic-agent/blob/a439f4edecaf176d463bf10a9057f6f54a58fd45/catalog-info.yaml#L369-L370
- https://github.com/elastic/elastic-agent/blob/a439f4edecaf176d463bf10a9057f6f54a58fd45/catalog-info.yaml#L244-L245
In my view, we should not need this... since it's a merge commit hence it should not take into account …
=> catalog-info: permissions for triggering builds does not work

catalog-info.yaml
Raises permisions to `BUILD_AND_READ` for all Elastic organisation members for Serverless beats test pipeline
The PR authors outside of ingest can't trigger Serverless tests
-
- ...
=> [CI] Grant build and read permission for serverless beats pipeline

pkg/component/runtime/runtime.go
```
pkg/component/runtime: use atomic.Pointer rather than locks for current component
Locking to obtain write boundaries when obtaining the current component.Component
makes use of a read-write mutex. This protection only protects the access and does
not ensure that the current is not mutated with a logical race. The same semantics
can be obtained more cheaply and without the risk of recursive read-lock deadlock
by using an atomic value. This could either be via atomic.Value or atomic.Pointer;
atomic.Pointer is chosen since it can be type-defined in code, rather than by the
addition of a comment.
```
Simpler code that is more closely aligned with the semantics of the apparently intended behaviour. Reduced potential for incorrect use of locks.
Unclear, `go test` in pkg/component/runtime …
=> pkg/component/runtime: use atomic.Pointer rather than locks for current component

changelog/fragments/1743004444-synthetics-upgrade-node-18.20.7.yaml, dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Upgrade node to latest LTS 18.20.7
=> [Synthetics] Upgrade node to latest LTS 18.20.7

magefile.go
Generating the component hash was failing when packaging the Elastic-Agent for Windows because the '.exe' was not taken into consideration.
-
- ...
=> Fix SHA512 generation for windows

internal/pkg/agent/application/coordinator/coordinator_test.go, internal/pkg/agent/application/monitoring/v1_monitor.go, pkg/component/runtime/command.go, pkg/component/runtime/manager_test.go
Clarifies the documentation for `runtime.MonitoringManager`.
-
- ...
=> pkg/component/runtime: improve documentation for MonitoringManager

.buildkite/bk.integration.pipeline.yml, .buildkite/pipeline.yml
Reverts elastic/elastic-agent#7665
=> Revert "Pinned broken CI images to the previous version"

deploy/helm/elastic-agent/templates/agent/service.yaml
This PR adds a missing inclusion of the elasticagent.init named template at the top of the service.yaml file under templates/agent. This is necessary to ensure that common initialization logic is executed when rendering this file, consistent with the rest of the templates in the chart.
This is a bug fix. We had inadvertently omitted the elasticagent.init template inclusion in the service.yaml file. This template is important for preparing shared variables and running pre-processing logic that other parts of the Helm chart depend on.
None expected. This change does not modify any user-facing values or behavior, but ensures the Helm chart templates are initialized consistently and safely.
Run `mage helm:renderExamples` and see that all examples are rendered successfully
N/A
=> [Helm]: add missing 'elasticagent.init' inclusion in service.yaml

.mergify.yml
Allow github-actions bot to execute backport command by mergify bot.
=> Update mergify to allow command from github-actions bot

.github/workflows/golangci-lint.yml, .golangci.yml
This PR updates the GitHub Actions workflow and the `.golangci.yml` configuration to align the `golangci-lint` version with recent updates of go version (`1.23.8`) in the `8.17` branch.
The `golangci-lint` update ensures that the latest linting rules and features are applied, and deprecated linters are removed or replaced.
None, this is purely a CI change
N/A
N/A
=> fix: bump golangci-lint-action@v6.5.0 and golangci-lint@v1.64.5

dev-tools/packaging/packages.yml
Restore qualifier for elastic-agent-core packaging specs to avoid changing the rootDir name of the archives.
The qualifier had been removed in PR #7690 trying to use the spec name: this worked to get the desired file name but changed the root Dir name which uses `{{.BeatName}}{{if .Qualifier}}-{{.Qualifier}}{{end}}` in the template definition instead of `{{.Name}}` which would render the spec name.
To fix the unified release
- …
=> Restore qualifier=core for elastic-agent-core packaging specs

.buildkite/pipeline.elastic-agent-package.yml, dev-tools/mage/pkgtypes.go, dev-tools/packaging/packages.yml
Enables elastic-agent FIPS packages build using a manifest
To produce `elastic-agent-package` DRAs during unified releases
As soon as the `elastic-agent-core-fips` artifacts are available in main snapshot DRA, grab a manifest URL and run
```shell
FIPS=true …
```
=> Enable building FIPS packages using manifest

.buildkite/scripts/steps/package.sh
This PR skips `ironBank` mage target when packaging with `FIPS=true` as `ironBank` does not have a specific packaging in that case, it would only end up duplicating the packaging for no benefit
To avoid generating the same package twice
None
-
- ...
=> Disable ironbank target when packaging with FIPS=true

.github/workflows/release-helm-charts-manual.yml
Support release the helm-charts using a given [commit/branch](https://github.com/elastic/oblt-actions/tree/v1/buildkite/run#inputs).
Control who can run the GH workflow using a [deployment](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-deployments/reviewing-deployments)
Unified Release uses fixed commits, but helm-charts might need further changes after a release.
I created an upstream branch with some default values (9.0 and https://github.com/elastic/elastic-agent/commit/b6262f14acdb6def657de69e5ac170d160e4e105)
Then If you run the workflow then
https://github.com/elastic/elastic-agent/actions/runs/14361418331/job/40263636278
Leverages https://github.com/elastic/elastic-agent/commits/main/.github/workflows/release-helm-charts.yml …
=> github-actions: support release helm-chart for a given commit/branch

.buildkite/bk.integration.pipeline.yml, .buildkite/pipeline.yml
Pinning versions of VM images in the pipelines
Required to avoid spontaneous failures caused by regular image update && promotion.
- Relates: https://github.com/elastic/elastic-agent/issues/7959
- ...
=> Pin VM version for check-ci

docs/test-framework-dev-guide.md
Fix tiny typos from https://github.com/elastic/elastic-agent/pull/7932
=> docs: fix OTel casing

internal/pkg/otel/manager/manager_test.go
Add better status reporting to an Otel manager test. This test has been flaky in the past, but the failures didn't give us enough information, and reproducing them locally was challenging.
This required some conversion of aggregate statuses from the healthcheckv2 extension in Otel, as they're not amenable to reflection-based serialization in and out of themselves.
The status output used to look like this:
```
&{Event:0xc000972f90 ComponentStatusMap:map[pipeline:logs:0xc000cfcba0 pipeline:metrics:0xc000cfcc60 pipeline:traces:0xc000cfcc00]}
```
and now it looks like this:
```yaml
status: StatusOK
error: null
timestamp: 2025-04-29T10:14:09.928119169+02:00
componentstatusmap:
pipeline:logs:
status: StatusOK
error: null
timestamp: 2025-04-29T10:14:09.928114529+02:00
componentstatusmap: …
```
=> Improve status reporting in Otel manager test

testing/integration/otel_helm_test.go
Tests that metrics generated by the `k8s_cluster` receiver are being generated and pushed to Elasticsearch.
To ensure the `cluster` collector is running properly. Tests added in https://github.com/elastic/elastic-agent/issues/7381 validate that the `daemon` and `gateway` are working as expected (no startup errors, proper data forwarding), but no test case for the `cluster` one. The `k8s_cluster` receiver is part of the `cluster` collector, thus ensuring its correct behavior. 
-
- ...
=> test: validate cluster-stats collector metrics

go.mod, go.sum
This PR updates beats dependency version
=> bump beats dependency version to v7.0.0-alpha2.0.20250504204236-6a467e25d3a5

.buildkite/scripts/steps/run-agentless-tests.sh
Address errors in [buildkite](https://buildkite.com/elastic/agentless-tests/builds/24/steps?sid=0196a69a-8f99-408a-baa7-509c858723c5) where I assume the exit code 141 comes from the closed pipe
-
- ...
=> fix(agentless): overcome SIGPIPE in agentless promotion pipeline

deploy/helm/edot-collector/kube-stack/managed_otlp/values.yaml, deploy/helm/edot-collector/kube-stack/values.yaml, deploy/helm/elastic-agent/Chart.yaml, deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/fleet-managed-certificates/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/fleet-managed-ksm-sharding/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/fleet-managed/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/kubernetes-custom-output/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/kubernetes-default/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/kubernetes-ksm-sharding/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/kubernetes-only-logs/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/netflow-service/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/nginx-custom-integration/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/priority-class/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/system-custom-auth-paths/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/user-cluster-role/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/user-service-account/rendered/manifest.yaml, deploy/helm/elastic-agent/values.yaml, deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml, deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml, deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml, deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml, deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml, deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml, deploy/kubernetes/elastic-agent-kustomize/ksm-hints/elastic-agent-standalone/kustomization.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, version/version.go
Updates references to the new release 9.0.2.
Merge after the release 9.0.1.
=> [Release] Update version to 9.0.2

.buildkite/bk.integration.pipeline.yml
This PR updates the list of Kubernetes versions we run our k8s tests against.  It also adds comments explaining why each version exists in the list.
So our K8s tests run against K8s versions that are supported by various cloud service providers and/or being maintained by the K8s community itself.
=> [k8s tests] Add versions + comments explaining why

go.mod, go.sum
This PR bumps the `github.com/ebitengine/purego` dependency from `v0.8.2` to `v0.8.3` to resolve a linker error introduced with Go 1.24.3.
Specifically, the `v0.8.2` version of PureGo causes the following error during compilation [ref](https://buildkite.com/elastic/elastic-agent/builds/21345#0196ef0d-a8ab-4876-bdab-594d6808b04c/86-278)
```
--
  | link: duplicated definition of symbol dlopen, from github.com/ebitengine/purego and github.com/ebitengine/purego
  | Error: error compiling magefiles
```
This issue was addressed in PureGo [v0.8.3](https://github.com/ebitengine/purego/releases/tag/v0.8.3).
Go 1.24.3 introduced stricter linker checks that surfaced a duplicated symbol definition in PureGo v0.8.2.  Upgrading to PureGo v0.8.3 resolves this issue and restores CI compatibility with Go …
=> chore: bump github.com/ebitengine/purego to v0.8.3

docs/test-framework-dev-guide.md
=> [documentation] Update test-framework-dev-guide.md

.ci/scripts/otel-update.sh, README.md, dev-tools/mage/target/common/check.go, dev-tools/mage/target/common/notice.go, dev-tools/mage/target/common/tidy.go, dev-tools/mage/target/update/update.go, wrapper/windows/archive-proxy/go.mod, wrapper/windows/archive-proxy/go.sum
This PR introduces a new `Tidy` Mage target that recursively runs `go mod tidy` across all `go.mod` files in the repository. This ensures that module dependencies stay clean and consistent throughout the codebase.
In addition:
- The `Tidy` target is invoked explicitly in places where `go mod tidy` was previously executed inline, such as in `generateNotice()` and the `update` Mage target.
- The `check` target now includes `Tidy` as a dependency.
- The Go module dependency `golang.org/x/sys` was updated to `v0.33.0` in the `wrapper/windows/archive-proxy` package.
The Elastic Agent repository now includes packages like `github.com/elastic/elastic-agent/wrapper/windows/archive-proxy` that import the root `elastic-agent` module. This introduces the need for running `go mod tidy` not only in …
=> feat: introduce new mage tidy target

internal/pkg/agent/application/upgrade/watcher_test.go
This PR fixes the `TestWatcher_PIDChangeSuccess` unit test by introducing a more robust and deterministic mechanism for asserting test success. The changes include:
- Switching from a fixed 1-second timeout context to `t.Context()` for better test control and cleanup.
- Introducing a `sentEverything` channel to signify completion of all mock server messages.
* Added a buffered error channel to avoid blocking sends while we wait for `sentEverything` to close
- Waiting for `sentEverything` before asserting on the error channel.
- Replacing time-based context expiration checks with logic that drains the error channel and exits cleanly.
These changes eliminate reliance on fixed timeouts and improve test determinism.
The `TestWatcher_PIDChangeSuccess` test is currently flaky and has been …
=> fix: proper time constraints in TestWatcher_PIDChangeSuccess unit test

.buildkite/bk.integration.pipeline.yml, .buildkite/integration.pipeline.yml, .github/workflows/serverless-project.yml, docs/test-framework-dev-guide.md
Enable `Serverless` IT step using:
- `oblt-cli`
- OIDC
Use `production` to run the serverless ITs.
Enable automated provisioning of new serverless projects using GitHub actions.
Delegate the provision to the existing curated tool and service we provide with `oblt-cli`, and use OIDC to access `ephemeral` secrets only to the serverless projects created automatically.
Delegate the clean-up to the `oblt-test-environment` framework.
See https://github.com/elastic/elastic-agent/actions/workflows/serverless-project.yml for the project creation
See for [buildkite](https://buildkite.com/elastic/elastic-agent/builds/21657#0197309c-32d0-4c74-add3-b16a9f86d035)
- Requires https://github.com/elastic/elastic-agent/pull/8358
- How are we going to measure …
=> ci(serverless): use OIDC for running the serverless ITs

dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
Reverts base image rename introduced in https://github.com/elastic/elastic-agent/pull/8079.
-
- ...
=> [8.19][Synthetics] Revert base image rename from ubuntu to ubi

deploy/helm/edot-collector/kube-stack/managed_otlp/values.yaml, deploy/helm/edot-collector/kube-stack/values.yaml, deploy/helm/elastic-agent/Chart.yaml, deploy/helm/elastic-agent/examples/eck/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/fleet-managed-certificates/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/fleet-managed-ksm-sharding/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/fleet-managed/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/kubernetes-custom-output/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/kubernetes-default/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/kubernetes-hints-autodiscover/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/kubernetes-ksm-sharding/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/kubernetes-only-logs/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/multiple-integrations/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/netflow-service/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/nginx-custom-integration/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/priority-class/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/system-custom-auth-paths/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/user-cluster-role/rendered/manifest.yaml, deploy/helm/elastic-agent/examples/user-service-account/rendered/manifest.yaml, deploy/helm/elastic-agent/values.yaml, deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml, deploy/kubernetes/elastic-agent-kustomize/default/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml, deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/base/elastic-agent-managed-daemonset.yaml, deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-managed/extra/elastic-agent-managed-statefulset.yaml, deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/base/elastic-agent-standalone-daemonset.yaml, deploy/kubernetes/elastic-agent-kustomize/ksm-autosharding/elastic-agent-standalone/extra/elastic-agent-standalone-statefulset.yaml, deploy/kubernetes/elastic-agent-kustomize/ksm-hints/elastic-agent-standalone/kustomization.yaml, deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml, version/version.go
Updates references to the new release 9.0.4.
Merge after the release 9.0.3.
=> [Release] Bump version to 9.0.4

deploy/helm/elastic-agent/examples/kubernetes-onboarding/rendered/manifest.yaml
This PR re-renders the Helm chart elastic-agent examples that were introduced by this PR https://github.com/elastic/elastic-agent/pull/8692. The issue was that this PR opened before the version bump on main but it got merged afterwards. As a result the Helm chart examples had the old agent version that `main` now points to.
Because CI needs to be green
None this PR affects only the version in a single Helm chart example
```
mage helm:renderExamples
make check-ci
```
N/A
=> chore: fix elastic-agent helm chart examples

.buildkite/bk.integration.pipeline.yml, .buildkite/integration.pipeline.yml, testing/integration/ess/upgrade_broken_package_test.go
This reverts the elastic-agent version pinning in the CI introduced by [this PR](https://github.com/elastic/elastic-agent/pull/8749) 
Because we need to run our CI with the latest and greatest 🙂 
None this regards solely the elastic-agent CI
Open a draft PR 🙂 
N/A
=> ci: unpin agent version

dev-tools/packaging/templates/ironbank/Dockerfile.tmpl, dev-tools/packaging/templates/ironbank/hardening_manifest.yaml.tmpl
=> [8.18] Bump ironbank 9.6

.github/workflows/serverless-project.yml
Set a different username and unset ephemeral
Avoid the hard requirement to destroy all the ephemeral clusters on Saturdays or all the obltmachine clusters regardless
-
- ...
=> github-actions: change default username for serverless oblt-cli and non-ephemeral

.buildkite/integration.pipeline.yml, .ci/updatecli/updatecli-bump-vm-images.yml
This PR updates the VM image definitions used in `.buildkite/integration.pipeline.yml` to rely on versioned Elastic Agent-specific images for both `x86_64` and `arm64` platforms. It also adjusts the `updatecli` configuration to automate updates to this new pipeline file.
- Aligns all packaging-related jobs with consistent, tested Elastic Agent VM images.
- Ensures full control over image versioning and simplifies upgrades through `updatecli`.
- Reduces build flakiness and inconsistencies by decoupling from less predictable image prefixes or default settings.
None expected. All changes are internal to the CI packaging pipelines and do not affect end users directly.
Open a draft PR 🙂 
- N/A
=> ci: use elastic-agent VM images for packaging

internal/pkg/agent/cmd/logs_test.go
This PR reworks the `waitUntilMatch` function used in TestPrintLogs test to improve reliability and eliminate flakiness. 
Specifically:
- Converts `waitUntilMatch` from using `require.FailNow` to returning an error, making it easier to incorporate in other tests.
- Applies a timeout mechanism based on **data idleness**, meaning the timeout resets every time new data is received. This ensures we don’t prematurely exit while output is still progressing.
- Replaces test-level context creation with `t.Context()` to ensure test cancellation propagates correctly and avoids goroutine leaks.
- Refactors all uses of `waitUntilMatch` to check the returned error explicitly using `require.NoError`.
- Introduces a common timeout constant (higher than original timeouts to accommodate for slower CI …
=> flaky: increase time constraints in TestPrintLogs

deploy/helm/edot-collector/kube-stack/managed_otlp/values.yaml, deploy/helm/edot-collector/kube-stack/values.yaml
Updates the docker image referenced for EDOT .NET.
Customers should be using the latest EDOT which includes a fixes for version mismatches that may occur due to upstream OpenTelemetry releases.
N/A
N/A
=> Bump EDOT .NET image tag

.package-version, dev-tools/packaging/templates/linux/preinstall.sh.tmpl, testing/integration/testdata/.upgrade-test-agent-versions.yml
Reverts elastic/elastic-agent#9450
See https://github.com/elastic/elastic-agent/pull/9450#issuecomment-3201905011
=> Revert "[main][Automation] Update versions"

dev-tools/packaging/templates/linux/preinstall.sh.tmpl, testing/integration/testdata/.upgrade-test-agent-versions.yml
Reverts elastic/elastic-agent#9447
See https://github.com/elastic/elastic-agent/pull/9447#issuecomment-3201901400
=> Revert "[8.19][Automation] Update versions"

.buildkite/pipeline.yml
This PR updates the trigger for the extended tests to include changes to the FIPS integration testing pipeline.
So any changes to the FIPS integration testing pipeline runs that pipeline as part of the extended tests pipeline.
=> Trigger extended tests if FIPS integration tests pipeline changes

.buildkite/pipeline.yml
Add back auto publishing from main.
=> Add back publish to serverless
